### ISSUE TITLE
Add Translation of Module Names

### ISSUE THREAD

**Issue by sweisgerber-dev** [EDCD/coriolis#100]
Hi there,

I noticed there are quite a few players out there, that are not capable of understanding English.
I've seen, that there are translations available for all the menu and buttons, but the Module names are never translated.

Would it be possible to put the i18n mechanics in place for all the module names?

I could provide translations for all the German stuff.

**Comment by cmdrmcdonald** [comment]
Any help in translating Coriolis to German would be much appreciated.

The file `src/app/i18n/de.js` contains the German translations.  If you look at `src/app/i18n/en.js` then this contains the English versions, so you just need to add the same key with the German translation in the `de.js` file.  For example, `en.js` contains:

    am: 'Auto Field-Maintenance Unit'

So you can add this key to `de.js` with the German translation for "Auto Field-Maintenance Unit" and it should work.  If you want to set up a local development environment to test your changes then there are details of how to do so at https://github.com/EDCD/coriolis/wiki/Developing-for-Coriolis

**Comment by sweisgerber-dev** [comment]
thx, I didn't see the new module placehold strings, because I checked the **old** coriolis github account for it -.-

Already forked (https://github.com/sweisgerber-dev/coriolis) and added the placeholder strings to the `de.js` file, translation follows.

**Comment by sweisgerber-dev** [comment]
Added pull request for first batch of translation, more to come.

**Comment by cmdrmcdonald** [comment]
I don't see a pull request...

**Comment by sweisgerber-dev** [comment]
Sorry, I accidentally submitted it to the original and outdated coriolis -.-

**Comment by sweisgerber-dev** [comment]
Added a batch of new german translations:

https://github.com/EDCD/coriolis/pull/107

**Comment by cmdrmcdonald** [comment]
Thank you for these updates.  I've merged the PR in to the development branch and you should see the results at http://beta.coriolis.edcd.io/  It looks like there are some phrases that aren't in the i18n file; I'll take a look at adding these so that they are also available for translation.

**Comment by sweisgerber-dev** [comment]
I'll keep an eye on it. Link me in comments or ping me on the the discord if you want to :)
