### ISSUE TITLE
Compare not working in Firefox or Edge, W10

### ISSUE THREAD

**Issue by ansorg** [EDCD/coriolis#101]
both give similar errors

FF:
`TypeError: e is null[Weitere Informationen]  app.dd0d2b.js:17:18745
TypeError: e is undefined[Weitere Informationen]  app.dd0d2b.js:72:1054
Arguments { 0: "TypeError: e is undefined", 1: "https://coriolis.edcd.io/app.dd0d2b…", 2: 72, 3: 1054, 4: TypeError, 3 weitere… }  app.dd0d2b.js:71:14747
Arguments { 0: "TypeError: p.findDOMNode(...) is nu…", 1: "https://coriolis.edcd.io/app.dd0d2b…", 2: 78, 3: 25349, 4: TypeError, 3 weitere… }  app.dd0d2b.js:71:14747`

Edge:
`Aktuelles Fenster: coriolis.edcd.io/outfit/viper_mk_iv
SCRIPT5007: Unable to get property 'id' of undefined or null reference
app.dd0d2b.js (72,1045)
[object Arguments]
app.dd0d2b.js (71,14723)
   {
      [functions]: ,
      0: "Unable to get property 'id' of undefined or null reference",
      1: "https://coriolis.edcd.io/compare/all",
      2: 72,
      3: 1045,
      4: { },
      __proto__: { },
      callee: <Permission denied>,
      caller: <Permission denied>,
      length: 5
   }

SCRIPT5007: Unable to get property 'getHostNode' of undefined or null reference
app.dd0d2b.js (17,18745)
`

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  The issue has been addressed and will be available in the next release of Coriolis.

**Comment by cmdrmcdonald** [comment]
This is now fixed with the release of Coriolis 2.3.4.
