### ISSUE TITLE
WEAPONS upgrade info varation

### ISSUE THREAD

**Issue by angusmadmac** [EDCD/coriolis#103]
https://eddp.co/u/8Jj5Xv3S
Use the site to see whats best but have the same mods on the above ship but they are all diferent dps etc 
thanks

**Comment by cmdrmcdonald** [comment]
Although the modifications are the same the rolls are not.  If you hover over the engineering icon for each module you will see that the rolls (damage, distributor draw etc) are differing values and this is what causes the final results to be different for each weapon.
