### ISSUE TITLE
Uncaught TypeError: r.clearModuelSpecial is not a function

### ISSUE THREAD

**Issue by bam13302** [EDCD/coriolis#104]
Removing any of the secondary weapon effects from my FAS (https://eddp.co/u/5pgDzEuw
) generates this error

(Looks like "Module" was misspelt moduel)

**Comment by cmdrmcdonald** [comment]
This should be addressed at http://beta.coriolis.edcd.io/ and will be rolled out in the next release.

**Comment by cmdrmcdonald** [comment]
This is now fixed with the release of Coriolis 2.3.4.
