### ISSUE TITLE
Can't access one of my saved build

### ISSUE THREAD

**Issue by ForbiddenTek** [EDCD/coriolis#106]
Hi, Every time i try to access one of the builds i have saved the error message appears or i get a blank screen save for the menu bar at the top and i have to refresh. Not exactly experience breaking but i thought you'd like to know... Great tool by the way.

Error message : 
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Path: /outfit/diamondback?code=A4pataFal5das5f4ihih2020020003032929m56b.Iw1%2FkA%3D%3D.CwBhwZjECYYRntZwg%3D%3D%3D.H4sIAAAAAAAAA42QO24CQRBEC3aB%2FWB2AYMW5MQGg8icOtsjWJbIfQQfwAcg5AiEHIGQkJAjEBI65NtFt6WRnIBInkqq19PqgQQAziVFnJ%2FI%2Bo%2Biv2kBLEhulacIvn7JxlZje34mWZTMTSXLPflYFbIVVIAsLwO96VYlTzpOKiw3ZPJxJDN7pLdWkyV5d334rfNRWgOeLb1YerU0sMRAxs48hQqkQ8A3NCZN3bmIgadZomb4z%2BzeNCP5NNM3s6rwVoqRnfCnd2w743ukVEZu54NVtbedflb%2FoFX9esULIVGLNHoBAAA%3D.EweloBhBGA2EoFMCGBzANokMK6A%3D&bn=rail%20stealth
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.d05c13.js
line: 31
col: 14942
error: {}

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this issue.  It has been fixed in release 2.3.4 of Coriolis, which is now available.
