### ISSUE TITLE
Point Defence Engineering Mixed Up

### ISSUE THREAD

**Issue by andrewgoz** [EDCD/coriolis#108]
When you click on the wrench to engineer point defense, the pop-up window shows no options under "Ammo Count", only "3" under "Shielded", "Lightweight" has 1 through 5, and "Reinforced" shows two rows of 1 through 5!

The "3" under "Shielded" is actually for "Ammo Count", and the second row of 1 through 5 under "Reinforced" is actually the "Shielded" options.

This is in the current 2.3.4, but I did notice it a while (weeks) ago.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  It has been fixed in beta at http://beta.coriolis.edcd.io/ and will be part of the next release.
