### ISSUE TITLE
Engineering not loading when clicking on E:D Market Connector

### ISSUE THREAD

**Issue by ddrake1984** [EDCD/coriolis#109]
in a previous version, engineering stats were auto added to the ship, however in recent version, this does not seem to be the case.

**Comment by Athanasius** [comment]
See this Frontier forum thread, and add your voice:

https://forums.frontier.co.uk/showthread.php/342408-Companion-API-stopped-having-Engineering-Data

**Comment by cmdrmcdonald** [comment]
We are waiting on Frontier to provide information about their plans on reinstating ship information for engineered ships as well as ships that are owned but not currently active (i.e. not the ship you are flying).

**Comment by strideynet** [comment]
Several months later and Frontier show no signs of giving in.
