### ISSUE TITLE
https://coriolis.edcd.io/ Initial Ship Table highlights

### ISSUE THREAD

**Issue by BeckyYork** [EDCD/coriolis#112]
Please add highlights to the ship-rows when mouse over so you can see where you are on the page.

It would be nice also to have bars separating the sort order as well.
For example if you sort by Frame Shift Drive; then have alternating background colour differences between class 7, 6, 5, 4, etc so that you can visibly see which ships on the far left have the same size modules.

**Comment by Blackth0rn** [comment]
I've got a potential fix for this but would appreciate some feedback on the color/styling.

![coriolis edcd edition - shipyard - no sort](https://user-images.githubusercontent.com/4995427/32693628-f84dee2e-c6e2-11e7-9516-e1b928c0ad51.png)
![coriolis edcd edition - shipyard - sort by fsd](https://user-images.githubusercontent.com/4995427/32693629-f86289b0-c6e2-11e7-92e6-e98cfb6e0186.png)

First image is with no sorting applied, second is sorted by FSD value.

**Comment by willyb321** [comment]
Looks pretty good to me, one thing though I would say - I'm not sure if its just the screenshot but the font looks slightly off? May just be me. Other than that, LGTM 👍

**Comment by strideynet** [comment]
Fixed.
