### ISSUE TITLE
Rq: Add compiled list of needed materials for upgrades.

### ISSUE THREAD

**Issue by cypheir** [EDCD/coriolis#113]
Request: 
Look forward to seeing a tab at the bottom that will show you a full list of micro-materials for the upgrades of the ship, as configured.

As well, to see them either as a homogeneous list, or sorted under the engineer(s) that require them.

If this is in the wrong place, sorry, feel free to remove.
Just a suggestion from an avid user, and fan. Thx bro.

**Comment by willyb321** [comment]
apparently i added this without seeing this issue, its now added.
