### ISSUE TITLE
Rendering issue in safari on macOS 10.13 High Sierra

### ISSUE THREAD

**Issue by asweet** [EDCD/coriolis#118]
![screen shot 2017-06-19 at 11 56 48 am](https://user-images.githubusercontent.com/6052871/27294208-c38035da-54e6-11e7-8dfa-842bbf269d78.png)

It looks like module specification text ends up being grossly inflated in safari on 10.13, making it unusable.

The above issue occurs with the safari technology preview as well as the regular app. Also occurs with the Coriolis beta.

Opening the same page in Chrome on the same computer does not display the issue.

**Comment by strideynet** [comment]
Issue confirmed on several other clients. Will investigate.

**Comment by kamenlitchev** [comment]
![screen shot 2017-08-19 at 13 36 41](https://user-images.githubusercontent.com/1465314/29485919-914fdeda-84e3-11e7-8c47-a57c34f79309.png)
Not really into web-dev, but experimenting I saw there is some `stroke-width: 20` coming from `div.slot` which - when disabled - fixes the issue for most of the text.

**Comment by Athanasius** [comment]
Huh, I should have looked more closely into this then.  I too looked at the CSS and found stroke-width, but research on that suggested it's only relevant to SVG, which coriolis uses for the icons I think.

From https://css-tricks.com/almanac/properties/s/stroke-width/ "The stroke-width property in CSS is for setting the width of a border on SVG shapes.".  There's similar documentation on mozilla and w3c sites.

So perhaps a CSS tweak to only apply that to the icons will solve this.  Still feels like an iOS/MacOS bug though.

**Comment by kamenlitchev** [comment]
Reported to Apple, too :)

**Comment by strideynet** [comment]
Closed #138
