### ISSUE TITLE
Request: Raw module stat input for engineering instead of only percentages

### ISSUE THREAD

**Issue by HittingSmoke** [EDCD/coriolis#119]
**Current situation:**

I am rolling on an already engineered FSD. The engineering screen does not give me absolute (from stock) percentages on the new roll, instead giving relative percentages from the old roll rounded to the nearest whole integer. It does, however, give the absolute new stats of the module. Based on those stats a roll can be better or worse due to variables like max fuel effects, extra power output, etc.

I have to either A) add and subtract the rounded percentages to my existing module saved on Coriolis or B) continually change the percent until the actual statistics of the module match up with the engineering menu in game.

This makes it extremely tiresome to find how a new engineering roll will affect your ship stats when rolling on an already engineered module. The rounded numbers displayed are not accurate and making slight adjustments to try to match stats is incredibly tedious.

**Solution:**

Have a toggle in the engineering stats popup on Coriolis to, instead of inputting the percentages of the roll, just manually changing the statistics of the module to match what is showed on the engineering screen. That would make it much easier to compare an engineer roll that's on top of an existing roll.

**Comment by rmblstrp** [comment]
I forked the project because I am encountering the same frustration.  I can very quickly make it work with absolute values rather than percentages.  I will also work on a more generalized improvement, but that will take a little bit longer.

**Comment by felixlinker** [comment]
This has been implemented by now.
