### ISSUE TITLE
Coordinate with EDMarketConnector to get engineer mods

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#13]
EDMarketConnector is already exporting the engineer modifications to ship loadouts for EDShipyard. Coriolis now supporting engineer modifications should coordinate with the EDMarketConnector team to also get those modifications in ship loadouts.

**Comment by cmdrmcdonald** [comment]
This will be available in the 2.2.2 release of coriolis and the next release of EDMC.
