### ISSUE TITLE
Long Range (1-5) Frag cannon mod

### ISSUE THREAD

**Issue by Bigity** [EDCD/coriolis#135]
Coriolis shows Long Range (1-5) Frag cannon mod - no such mod exists in game

See attached build
[fas.txt](https://github.com/EDCD/coriolis/files/1239945/fas.txt)

**Comment by strideynet** [comment]
Many thanks for reporting

**Comment by strideynet** [comment]
https://forums.frontier.co.uk/showthread.php/331721-Engineering-frag-cannon-for-range-!

**Comment by strideynet** [comment]
fixed in develop
