### ISSUE TITLE
Module power usage calculation inaccurate after module drag and drop

### ISSUE THREAD

**Issue by deadlypliers** [EDCD/coriolis#137]
Moving a module that is disabled seems to re-enable it in the power usage calculation, even though it is still visibly inactive in the module and power priority lists. Toggling the module on and back off resets the calculation.

Steps to replicate:
Example 1: In anaconda, put a 5A AFMU in one of the class 5 slots, and disable it. Then move that module to another class 5 slot.

**Comment by strideynet** [comment]
Can replicate.

**Comment by willyb321** [comment]
This should be fixed.
