### ISSUE TITLE
Feature: add an engineered marker to modules that have modifications applied

### ISSUE THREAD

**Issue by Charybdis** [EDCD/coriolis#14]
The marker would help find items that have had engineer stats applied. The attached image shows thrusters and power distributor as being modified.

Using something similar to the game "hollow hexagon" would help with familiarity. The hexagon might also be a "tooltip" for the modifications applied?

![engineered](https://cloud.githubusercontent.com/assets/23155785/20037041/8afade22-a410-11e6-8fda-4af90b7e9408.jpg)

**Comment by Charybdis** [comment]
Thanks!

**Comment by cmdrmcdonald** [comment]
Notification for modifications on a module will be available in the 2.2.2 release.
