### ISSUE TITLE
Support importing SLEF json

### ISSUE THREAD

**Issue by HittingSmoke** [EDCD/coriolis#142]
https://github.com/cmmcleod/coriolis/issues/72

It seems this was implemented by the previous devs but is not currently working. Copy/pasting an EDShipyard export into the Coriolis import field gives a "Cannot Parse The Data" error.

**Comment by strideynet** [comment]
#71 Turns out this was a hidden bug. Thanks for reporting.

**Comment by bionicvapourboy** [comment]
In the last days we are working to share a common public repo for EDShipyard

https://github.com/bionicvapourboy/EDSHIPYARD

There is a lot of work to do, but in order to keep the application alive we need users to contribute by opening issues and sending pull request.

**Comment by felixlinker** [comment]
Most concise way to export builds in edsy currently is via a [SLEF](https://inara.cz/inara-impexp-slef/) json that was recently added to inara. coriolis should support this event.

**Comment by FX-Wood** [comment]
I came upon this while trying to import a build from Inara.cz via a SLEF export. The error message I got was:

 `Build Name Missing!`

After chit-chatting for a bit in the coriolis-orbis discord channel, I was enlightened with a workaround:

**Comment by clinkingdog** [comment]
Does this also cover _exporting_ in SLEF format? I'd really like to get my target builds into Inara's "Target Loadout" section, and that only supports SLEF import.

(If this issue is only for import, is it ok if I raise a separate issue for export?)
