### ISSUE TITLE
False part values for shipparts between the game and Coriolis fitting page

### ISSUE THREAD

**Issue by ToBeFree** [EDCD/coriolis#143]
Copied from here https://forums.frontier.co.uk/showthread.php/374505-False-part-values-for-shipparts-between-the-game-and-Coriolis-fitting-page?p=5876130#post5876130

-----

Severity
Severe

Frequency
All of the time (100%)

Time of occurrence
18:54 GMT+1

Date of occurrence
31/08/17

VR?
None / N/A

Location
Nu Tauri

Ship/SRV?
Ship

Ship Type
Viper MK IV

Commander Name
Chaoschaot234

Description
I have made and gotten some ship fitting made at the coriolis page and found out, that some slots are not at there correct position but the most horrible ones is that the Alloy has false values either shown on coriolis or ingame.

Here is the fitting: https://eddp.co/u/LXAjyDu8

You can see that it is marked as "8" and has the same resistence values like the reinforced and it has no weight (0T).

Ingame it has a weight of 10T and 0 resistences which can also be seen in the ship stats.
So what is going wrong here? Who has the false values because I can for now either trust ingame values nor the ones from coriolis because I have no other fitting tool(s) to compare with.

Means that I now going to state this as a bug and yes, each bug is in my eyes a critical bug (I don't divide into categories like minor or smth. else, because a bug is a bug to me as long as a Dev can approof that it isn't a bug).

Hopefully, if it is a bug, it gets fixed or if this isn't a bug what should I do then?

Images from ingame are atteched.

Also pls get ride of this recaptcha!!! Another datacollector which I am going to block!

Steps to Reproduce
Simply dock on a station with the possibility to edit the ships fitting and then look between the Alloys. Also take a look on the Statspanel on the right side ... it will show 0% resistences.

Additional files?
https://puu.sh/xobQN.jpg
https://puu.sh/xobUN.png
https://puu.sh/xobVD.png

**Comment by strideynet** [comment]
Many thanks for bringing this post to my attention.

**Comment by strideynet** [comment]
Issue with game.
