### ISSUE TITLE
"Export" textarea text unselectable in Chrome

### ISSUE THREAD

**Issue by elomatreb** [EDCD/coriolis#146]
The textarea in the modal shown when using the "Export" functionality of a saved build is not selectable.

This may be caused by Chrome treating inheritance of the `user-select: none` set on `.modal-bg` differently than e.g. Firefox, causing the elements in the modal to inherit the property.

![coriolis_bug](https://user-images.githubusercontent.com/3387265/29999506-943f96b2-904b-11e7-8256-7a4e3fa84959.png)

#### Browser versions

- Chrome (confirmed not working correctly): `62.0.3198.0`
- Firefox (confirmed working correctly): `56.0b8`

**Comment by strideynet** [comment]
Many thanks. Will fix for next update.

**Comment by willyb321** [comment]
Fixed in c2a0dad9a811dbfa5d09b20d6978e311ce0bd547
