### ISSUE TITLE
Script Error Unless I Set Browser to Allow All Cookies

### ISSUE THREAD

**Issue by tententacles** [EDCD/coriolis#148]
I've tried every other permutation for allowing cookies, but the only one that allows the site to run without the below error is to Always Allow All Cookies. Not acceptable. I should note that I was able to connect to and use the site fine yesterday (09/28/2017).

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Safari/604.1.38
Path: /
Error: Unknown
Details:
scriptUrl: 
line: 0
col: 0
error: null

**Comment by strideynet** [comment]
Odd considering nothing has changed since yesterday. I'll take a look but without being able to repeat this I'm not sure there is much I can do.

**Comment by tententacles** [comment]
I just went in and cleared my history and this seems to have resolved the issue.
