### ISSUE TITLE
Uncaught TypeError: Cannot read property 'features' of undefined

### ISSUE THREAD

**Issue by Jorerlol** [EDCD/coriolis#149]
The following error (which I copied from console) was generated by the following link: https://eddp.co/u/GGX9Gx23

Uncaught TypeError: Cannot read property 'features' of undefined
    at r (app.a2bd2c.js:31)
    at t.value (app.a2bd2c.js:37)
    at t.value (app.a2bd2c.js:31)
    at d._renderValidatedComponentWithoutOwnerOrContext (app.a2bd2c.js:31)
    at d._renderValidatedComponent (app.a2bd2c.js:31)
    at d.performInitialMount (app.a2bd2c.js:31)
    at d.mountComponent (app.a2bd2c.js:31)
    at Object.mountComponent (app.a2bd2c.js:11)
    at mountChildren (app.a2bd2c.js:31)
    at m._createInitialChildren (app.a2bd2c.js:31)

The error generates a black screen, and thus the normal error message could not be obtained.

Path for the build (or closest I could get): /outfit/fer_de_lance?code=A2pktfFalidpsif31q1g1g1b1b0404040802025ip35d2725.Iw18cAMVA%3D%3D%3D.CwBgjCkEwgzPCGVlWkg%3D.H4sIAAAAAAAAA2P8Z8%2FAwPCXEUiIvWBmYPjP9E8MJMAKJPgVgAIiPP%2F%2B%2FxcN4WZgkABxlW34gYqY%2F0nBFdl8%2B%2F9faIogUOUFdqCiI5xAedZ%2FljB5zgKgfi4BPgYGRRBLCcRSBbHUQKz%2FvP9c4SZtYGFgEDIohRoi%2F8IUKM9HQJ6fgLzAP3eYPDfIf%2FwGP%2F7%2FFwSxJBYAfaIC9rPgP1WQIiCTgaFDGGiIgDoDgwyI9V8It5TwP0%2BQFNBSBkaQWewJH%2F7%2FV49gYmBQ8Pjy%2F%2F9%2FkX9%2BcKeB5AUf%2FPn%2FXwWsVZSA1v8Adm7i%2F5cBAAA%3D&bn=Shattered%20Sword

**Comment by Jorerlol** [comment]
(I already reported this on the Discord, so you can probably ignore this one.)

**Comment by strideynet** [comment]
Rapid Charge G4

**Comment by strideynet** [comment]
Grade doesn't exist but is being used by the file. TODO: Implement check condition that resets engineering for component.
[Shattered_Sword.txt](https://github.com/EDCD/coriolis/files/1347025/Shattered_Sword.txt)
