### ISSUE TITLE
Change modifications interface to allow manual input

### ISSUE THREAD

**Issue by jfurtner** [EDCD/coriolis#15]
Currently the modifications interface uses the mouse to set percentage change. That doesn't work well on tablets, and makes setting values a very slow and painful process with a mouse (I only get around a 5-8% change for every drag with the mouse. Change it to allow manual direct input of the percentage change in addition to using a mouse.

**Comment by cmdrmcdonald** [comment]
You can double-click on the modifier value to input it directly.
