### ISSUE TITLE
{ "references": [ "code":  appears to be required for import

### ISSUE THREAD

**Issue by alski** [EDCD/coriolis#150]
_Not sure if this is related to_ #142 

Hi, trying to develop an ED tool and thought it would be useful to offer export to Coriolis (your import). Unfortunately I cannot find a way to get past "Invalid data" without appending a references/code section from a previous export.

See the following attachments for example (only diff the code section)

[Coriolis-Fail-json.txt](https://github.com/EDCD/coriolis/files/1349739/Coriolis-Fail-json.txt)
[Coriolis-Success-json.txt](https://github.com/EDCD/coriolis/files/1349740/Coriolis-Success-json.txt)

**Comment by strideynet** [comment]
https://github.com/EDCD/coriolis/blob/master/src/schemas/ship-loadout/4.json
  
Please use internal references relevant to your application. I'll consider making this not required but to circumvent just fill it with random crap or actual relevant data.

**Comment by alski** [comment]
Sorry it looks like the value is being used. For example if I strip it down to 
  "references": [ 
    {
      "code": "fake"
     } ],

Then on import I get _: Invalid data_

but if I take the known good value and delete it down to the shortest string that doesn't show as invalid data i.e.
  "references": [ 
    {
      "code": "A0p5tzF8l3d1"
     } ],

Then I get

Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16281
Path: /outfit/imperial_courier?code=A0p5tzF8l3d1---------------.Iw18UA%3D%3D.Aw18UA%3D%3D.&bn=Didn't%20see%20that%20coming
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.a2bd2c.js
line: 11
col: 356652
error: {}

**Comment by strideynet** [comment]
Huh OK thanks. I wasn't aware it was being validated. That's quite odd.

**Comment by Marginal** [comment]
@alski Consider generating in the Frontier cAPI format -it's more portable, more stable(!) and easier to generate than Coriolis' internal format.
Schema here: https://edcd.github.io/schemas/ship-2.json
