### ISSUE TITLE
Import from EDDI - 414 Request-URI Too Large (2.4.02 API Online)

### ISSUE THREAD

**Issue by SwissSkynet** [EDCD/coriolis#151]
Here is the Export Link (Think now with the engineers Data from API):

https://coriolis.edcd.io/import?data=H4sIAAAAAAAEAO1dbW%2Fctpb%2BK4KB3e4C9kB8EUl1P8V20qQ36fXavg2KxcKQZ2iPbjTSVC9OfIv7bffX7Z%2Fac0hpRtJII81L0nxwULTpiKIOD8nnvPLwj5NwdvIjUacncbDQJz%2BevNEznQZ5mMR3F0n6pPNcn5yePAVRAU%2F%2FOJkXUQTthUsp8Yl7erJIZkWkM%2FiNEV9yxtjpyTRIH5OTH%2BFpnuQBtKc%2BtBaUw7MijpIg1jP80VOS%2BeKfpycPqYbeH4Io06cn2Txc%2FmKJuXi%2B1%2BnsOdbOpc7yNHnW6Ylt8O4SH%2F92%2BdvZJf6SG4qRQDMcqoQQUtDVqH6G%2F2RJ7HzQiyQNgaR%2FmpfS7DnL9aJ6T%2FhUrDlxMw%2FjNEjzAD7%2Bj3ka4HdM82A2S3UGQ2Y%2Bo1RKLhVxcRhBFD7Bm3lawDDmOojyeY1nrvljyNfRbOOHYlm9Gca5fkzD%2FPnkR08wcnqyDOCnz0n6yf4AX5om00%2FLMD9PdTCdIzNL3iVfnh91fA00hnEYP578yD37jdU0%2FXHytnjUb4N0tkygV4K%2F2Id17ini%2B3zFibfL%2FO5cB4v3QabTu5%2FCxX0Q3WE3wJIomZaThS0c08T%2BDFM2TcOlnZiTiyTOw7hIiuzsIUy1E2FD57MOljAt8M%2Bj6TXSM2eRFHF%2B6nwO87mThY9xkBfQPk%2BD6ScYkhNkWZjlk%2FWilAJmwBOtVVSxf8VlpMLyd5mGiWUvslLHj2GsgWgYfvX3akRpkji3Qfp7EcYn65bvgEkM%2BmTQa6qn4VKX7T%2Ba0dy9fngIp6GO85Pq%2BfsVk1bPHNu43qTJsHcxLNAowiHn8zCrWHUPY4YBQAczPYXpz3TmGIbCptXOQ5I6qZ4VU%2BBjPtfpIogc2G8zJ4hnzjL5DCyfpcHnyfqz%2BknD4vSAER9hgb2Lr9LkEVf3HSyKEGg1G8usm78W%2BUOYwyQ%2BvsH1evu81He39hvv4RPYpJwRd8KJK13qc6ZcomBLvYce32U%2FJcmsmoT1urmt0Ql0zcJsGQXPv9quTjw18dm%2FmN9hik7%2B739w63aRchksgkd9pdMbPU3iOjlkQlyPE8EJV5z6TWrK5bImx%2FbjLIFVme1pgybiTjw%2BnqYDSTng%2B1c445cw4Y3JkZQyIj2XuMqjbPvkXK3WzCYZVE6kHMUG2LBpeF%2FkySYxHiwSX3hCUsCdAWJq%2FfSQxKFDMYakd2uMrRGjFOVAj6tgkrg3MDvrLjbIOCNkIr0aHf%2FbR8eHIMsaJPge9X0pKUgWItUACebtza%2FziXSbH0dxt4QNH0Qfmtv6v%2F4bHjUkAn2RCC8S4fgSAfQkKgnzfaVceohAkBT6OkwgwC4D6eRR2OSukvJwgXBGoccx231DIOxDygHf7xYIypOu5zIQTD7l%2B8sDwifUP1QecCkYaO5SgOLgk0PlgUcnbG95QCawoZkACQU08f2lAZu4LWm9HY7fg%2Fk0pKG7IKcEaeDxhyLKw4sgjgFwSkQ2PTUg2TQ6s626QPk6WIYzAx%2BnTgabMDqbglVzD2iyTJO%2F62keRvooGO250pP%2BV4Do22Tm%2FAAQ4pyDQMl1%2BoPzYfqfANcdeE1FD17%2F9Umn0zkyb9aB2LWng5h9WwPqOn4CuCFOB9NpASx6NmgcxhV8r3HZyZPV787MIlFS5MsiPxpib1OcwXpEjYgqyb2hHTACJz134tI9FefdSTnk%2B70IBYQwzojw0LKRA2g5DFBnHptwNga6Xy0WyUUULm%2FCfzQFiCJCCpCrknHeJmiDM9iLM4VuYJP%2Bo0uSEDVhdAw9PYjJFWEA38Rj4gDI5DCqMfPUUp%2Fh%2ByDCPO65SpBBBb5beyYb9mYvWv9R%2FX4HW1THszBIn%2B9SAMIZPIyLKMJXP%2BhZWCzGwLk7BOe2q%2B8Vz130Ir7A%2BXcN50z5YNoqpTwytDvGwDmbqHEKXwec70zKId%2FfBudSgq3NfZf6h%2Fsfzjw5kYfBuVSAnZJzBrYSZ4fCOSWg3e%2FniKBCMRexVEjpb2dMN5LKpiQ5NpJ2OypekPQFSb8BknLBfUoE9wQ5gkOZiwnfF0h3puSQz2%2FBUU6EgpXDXMnbgL4HjnIyEepAHHUVd10BUsZDX%2BDBOOofoBYTl1JGmecz7g85ebaoxcSd0FH2y6ZezF3lY0BGgljZSy%2FmE9c%2FJprfIIYOq8VMqQaYXxVArXU73xZpqvM701EDyk2bfsfzDbAq0mdL06rtdc5Npw3QDmChLmBs0w74ruE2pQoX%2Fu647X4Vn%2FP7JH68DmKz39tAjc8c83AQp0v0ArCuvMuzU2cBK8Qg86y1k1eQPLOs6%2FZT16E7RSo2IJvsCdkfgi%2FholjYcTc2oPIlla4v5fAGLDuxpHVsQtV0tu6wCX0pBOi9nPqe3EejOvObEbdd%2FbwSvi2ET6RH%2BEBUdqujl04I2RkLYFUFi%2FtI3%2BEP8LlFHxb0KnYvWPCCBcfAAqF8xSmzyUoHQYGY%2BO5%2BUCAFJUx5YHaS%2FaBATsQohWSbFutSqSgnUnB5DPcuBaVrTy12d0rGfH4EKi3nQQbE3WX690KDtrIGpdswfh7WTzxKm5gEILIIrvCdS%2F2APVbYhP01oQkbOWWrLnD6EIJtCFblzDaZOK8q9AGUe7a4Y%2FcemqWZUxhjyr5kf4e9uNSzBP4vjO0idj7PdWztKD2rIRYRVH4NxLoOFgBY802wIqQNVg2mvQ8f5%2FlHjf%2FeBC2coj6UajyzCML2RpCWT4RTEJ8Ko4EuF3ttW09OvFHpTN0JKkIy4TKmmGCE7m9HnDE6EbyJHttjko3N0JMiIpTHRGMz3JjMxvMkQX%2FDHZpo7t0FbJDMa2wE28wp23WK6TyF5ZPD0s0wi8EJpnn4pB2bOemED6sF7Rg3zhI2zb3tLXOyHLYJrn%2F98KDNezGwrS6sufDkXh6XgbV%2FGc5C59cgx3SGLjeL6bexBZoMe6uDp%2BfLwsxgW2ybZw4%2BdDbY1yO%2BcUWi8F7L5ftnK5UbDhiUyItlmqz5a1hpfFUxurNw3p1Vkurx3C1259vVB%2BLKfLucztDydyUuGBHcR%2F8kRnsG9sFNbRAdwXkyEd4eIpxNBpwcPWKbYgzSPcCTwIkSYMUQsCIOCLARPiGjXD5dlgSZUB%2B90z7jSrgHZIycUX%2FCRzHjIomiMIPlc63RXRoYSd3IolFCUQVKnfTJQNqclRCbKTRklOP%2BL7CDQQIfgY6TsisnXfe1P10ma%2Bo4dFUJWEeh6%2FWXZZRkgLrHoGzV2a607SDd2It0%2BybSrVz9HbKt2hfVislHizgTVdDxHNfFAnMqswCewnTrbJX9iEJMd6wjkyp5jwdeUufTxs48mpjbjh%2BSMfiHUE9hDvB2ZB0DH1RMxCh9cxt8oHnmgt4LNjPz2%2FK2L3tzYIO6o%2FxY28ED6SLcowRztr2BrNLx0DEqXtqT%2FuIS5BLYsb57QP64OyF7ehgx4CF8Kl1z%2BmkPN7%2FbnJkd9QJXUVBOCAMThQxpJ9sUAzUyx3dQLRDADJ%2BA1cblUD5Qt1rAQNfcW5TwF6%2FBi9dgwgmgOYVNqSRrazgjvQYKOjnAa0CEBHwUSgBcHmA0nDE1YfsrVt6LYjUqUeNQxcpiIR5F3VSt1jgJsPCIKpKejdau1ohdpmWUK8UJUu1ME3QaAI5UfgXdcCucOvdFXgUCYCZmT6DXmaSNh5pDInnSKaBUldDxFdSvbrnFieuDvkV8MEQG7Pqt9izHUP%2FhVqTiHsgr5XsAd%2BQIWiDxJnyUk2O7EbkLWWPUwNFkDdmQuxA2Tg8cTVrPQULiCdf1XaI4PchRSwD5%2BVEcJIIL4oPiwblLB9Jh%2BjQhb3%2BXsXjB%2Fm9iVL9g%2Fx7Y7ymfeESojYMlu2K%2F5x8D%2BxlAh1A%2BJtMdB%2FvFqMPiA9jvSUqRLuW5Q%2BnAo7CfT%2BioYPEg9u9A2EjsH0ta3yFy5XqESypcTg9I9sND5GTUghrGft8H3V9QzPwZkEZ92N%2BOWeyA%2FfIF%2B7%2BJ3v8SLuwNF3qMUF8RgtGzw8KFXtMfND5cqKRymeC%2BD7A%2BIGb6QodKTtRBoUMPD3OAgCGDOcDbQ4feKNW4J3TIPMKYpxSDyTgkdAj6KDlc3AIyUlgaUhDhtl2m%2B4hbd0LGJiFtIqV6QcoXpPyTEyt8isVvKGFtQ3r3xAp%2Fn7MKbCJ8PMziulwwtV9uJBX%2BhIsDkJJxTihXlCn3EKRkTeN9R6RkzAWoJsTzmTwEKVmrAMUBeiRzJawMF0%2FWDPiR%2B%2FRIcQQTaRc6xiVZjKVrIMliF7pGxUnH0jWYZLELZSMjpZu0bZd0r9JFUqS9uf3S3VaD8s6%2BffdTGsw0aQg5E%2FP5bGI%2BzqsoSp675RxALIhZPKyZo7ACPA4egzDOcgedDjlwMUN%2FRJCjVKsJMfcryK8bHYGsdH7WQdfhy40QVzn2kVKr5PP2HInANHLujbSqJ0zkyODMmQM7AVFMcj%2FmRaxF29rzk%2Bowhmf2xa8lrd4adndKKzrhhLvMBY16Ixt3Y1G%2FBTzqE1WgiDbT0HqBehsuodiQngsUEamGih6OQiWQH%2BOqyA2lSTA8lcmES4hkx0mTQJkyKoNjI0WBSYyCooCXQ1KtR7qzsWfsB9Dac8EsJMAX32v76PfxaHHocRfN%2Fwqruv6c3HciIswTw%2FO8JSJWbe%2B6oPEWlfZpEN19nId5o9yTFcJtMLS%2FHgZvSD%2FqHFdREOfdmC64W6vAC2qSVXOW%2BIYxWWSXyWI1Gdttd9HArFhghbtCR6hR2xPhCOFYFrhUoutGCFbAFcT%2FGtUA38JUOLdBHHZYIP5mnkLFrjtrUAydoG9yYmzCmz0%2B37YlbFpHvfwfsg5MkXCma9humfkIssmuseN63i%2BCZTBtq9oIllwJSf0hc8PyY1p10mVwjDt%2B1O22lXhEWypBXbZReG4nty31m3T0whOItryq%2FjhtcoVSgbntzFeinbDRhibsBS3wqpsOgmgzB3BQU%2FsAaPParOesd2vXioHi1rbN69uanjQBNC2M16BrU%2F%2BS4Lo8y2BmTTUNPI2JCpott91INxJ4du8rxN1gOT8Ak0HTuQqirrOVlLY3dDnkyzDt1MjM785liqL0tjDVuHt38cfV%2BcjVwchTJwB7Dl7%2BIVtv49NtJTxNJG6V7zprqW1LnT4gm48ZT7Mc%2BOsyv1p33tI7QMYqWC9MiiG%2FK3QT4sgWa1Vvc4u3fH79QSNDGW6N6yBv0gQqmucRDwwhf%2BgM9PZCpGfSm7ijnAzd5j1xPQH7m4HCzwbcHFvNe6wGPUoV6wlX%2BQQwj3hU%2BG7bIbtbuApjl6O01WrZ4Hxv1h0iWBMKtB%2BXKHdIq18tmm5NUTXPqY9XUlGAU%2Bop4g%2FlSvSn0Y6tlmEg900Kvd3Mw4fcIEYf7BIMKNZg9y1QnxqYMNArujSqNzeXXaB7qZ8AJgBQAmMBJ58zJyugt2lahJk51A7YYCBmjh%2Bx4Pz3YrHMMEn%2Bs9YxOoDTEqTrGheYU7702F7FPQdg%2Bo2OQpT%2BzpsgzbSBiHaC6IbrF8a%2F9QD8uxVGQktno1WTa9gRbEWbFGu5gbBrGNg46L6Z%2FwB8Rg%2F7FHQ%2FdDR0qmg1s%2FtoKL2xuDksbp%2FAnoe%2F7JWOesbdkWluPaoWrA7lYhlNXw3WON%2BqatGRbt4eBObKA2vdZ9LnByEwH1lkDRZYN%2BzBpEipFHWVxApKY1DPJNt04x4HA3nU4b4PwZc3YEeB%2BP4ZlnITATnxPCzSJ4frSkE31h7D4gC4KbqMYyJ2wcP34YO%2BKZbLJO21LonnN7Cw9ooBQ69LD8VGTtVxV5U3%2FVhEoDJkzjy4D%2FPgPtLWsAzyRZItYXNqq3ZZ2wlsr4UGaw0Ub%2FQN6PQpCVOjeS3DKMlBd7vWC%2FjIp01dVvgSIyxHh8j30Mwp77vpUGM3SoQ02GYiOp2WafXIaXGwt1Z9VbKtTAaD6Wtqsh2QuMRaeKAubylLv28xkO44jxRUEcnQRTC4yLfgkBQjE4Z64jye8iSjgnLPPyQBjXkTJXax8yw567ItfTvNlChp%2B3Fq75ntpvq9OfVPdGki1eO1zWe20Otffjp1bn67MRvu4%2BuryvZP0kaQmfmEMNRcj76VsFji5WcdRZ2Khur08NTZ8hak%2BZvUFhbpMhEvjKfHeW3dN5XHp8mtbX6fdRWdcAGcybNVDuWy4SvpDC87n%2Bd4SsgCmYlBOw%2BmLuSqE%2BuIMtdIHE0ZsSWGsmttO2%2FuA1%2F5Ht5L49F23HdjN5b9AOiWHW3aiv7I2jylp%2BNgksp%2BjkHSjdWpDyap7OcYJJUM7%2FDhgcmGRXuE7%2FkuIaNnrt%2BRd%2BZN6Liwh%2BV4J02gTCkwsCUee2pXWOqdui004Y0%2Bo%2BotlTw%2FnKhq8o5BVM9pTTDSqMu5y6Q3pIZvkzweLMpdlLvrYBb0Cxuv6Vm80XEGiF%2BXMU2VrmywNeqbFWFex7r7IAunzkyXoeBTB3S5OF%2Bn6hh3Oe4Yk52DM3AfRmEeNiILxGMuo3sFFoZ0OB06F3NdGJ9hW%2B5sOCItA0pGHfUI5JFMTqxaKilnCnNZvL3qpkh5UE426Aim%2BKMklLZt3p0sTgGbeFTs0c7GrVlDN9MgfoV1BptWMJWEE%2FSQunLw3gbbkYM9ObarDmtYNu%2FfGdT%2F0Pa7DeJPfVsRaGtsxap93bxiTV8TWoGmy87dmKR4smOaxHkAS9oaSsZwLMqkOTS1fqjKPJtIYW2%2FgZa8740xMNgbsMdcYiMU3WmWeG69qehao%2BcnGw8r9dwyvMHu3gRZ3hj8eXgGwg3sF%2FtaFwteAbREoGPFQT3N8rH6gPXG1WpWVKpY2TArszUN4wJnUUznldJWifiVulYyzdzzx76KobkbSLVYWcbmO7Tiyuverv6R9WvDr5bL6Hl1L9paLf4cRlF5%2B1lHSY9GbfFVZOXbl%2FwgHucIBIKAaneEkh%2Bq6RTb88CPAMWAoGmFd%2B4c4cAPaJrjrmYcymXj0ucuVYwonzNxjGwWjzYDOTveEsYUF8QVHvVpm56drgkbO2%2FDtbDgjzAuXta%2BQaLFoM4sTbpRZHy7GDHISrcgK4oSRjuQ9QJs6%2FNKoHSmg5Q5xtjQOe%2BRK%2FVIRmFuCUj1WZVFMYU3M8x2SPH%2BhgjddMsgTJuJ7tnE%2BSUp09ix8O8UOBwsUSZVz%2BtSiPlS7FX0YiCd5HX0FKaB8yFI86L41AGqG7cytLhorqjoQFR7dUXpbejg6Egfw8qld58kwOmlk4cLC6I26WRWpKtEd0ytrERTtoS%2Fl80zW0kE5f3RfHtlbj%2BM5Qa%2B9LdlczMQIsEuZdTDeN52tLipEbq5P9VEjcpnX5NzWTKkvTs9k40nuHKH4q2rHjq0vZFG8pqc63q%2BZtMQJHj7JJPKHb5BrFw%2FjeTPTfLIyIIl57CUbpHdTbtUETzPicVWByQPvt8zX2dec8IG1WGDY2wAx3jTOr3Aq%2B6vg2kDwpr5yaaJg222magmnJOVGjKW6DE6HuwTPGBTVh1HODOd5WkQZw867ciQAch38ea1Q7RkboPJPYeRhJBswyy4mSbJsh6D5pt2gWnTxYM3AMtTxBBEDgwIZEVclluPK6A2ZkKGPWAjBGjEavy1HlNhZP%2FLc6rRe1tGDzabz0hz9Ghp6%2FQ8eK4Pv7kEyjbO2yB%2BDDp94K8q%2F%2BxMY2F5bRL05gnOvwk%2FRUERT%2Bfw85Oeh9NmhiMRHGZ9zwTHatTCGnV9lhFlzWDbZZrEGm9wTpPIKCTWkVK3DFu7wLbpjgCUHWVOFC6WOs%2FqUwwWb2jPm6GkMRIlAWk2nRcxlrGq17aqZ31Kpr6GjN6hMNWaK%2B%2FNqL7T4lTUpSAZQTr6g6X9ekta%2Bwe4ZgDi8U4MlD3Dh3O3FqciG8ecRuC93LrugSvN3X5ePD4%2BV3udd7kjMWFX50H67Pxqt%2Bp%2Bu%2F7R3JdzZg9odGx6iTJynwVOV1te2UH0wDzao02VPQeVMUjPk9nzZQhI%2FKTTZ%2FRHgUV%2F9wpLekz1rMGJS%2BfMKRt0Sj77yPp%2BQHdE%2B93U5VznHlcAxzwP9vNhAOdvHS1AXAvWby5xsYFgnlaen87pxpyhWsOugf4tsxO7xCMo1quc4V1lGPKupVw1cgMAz%2FcU4lvhCzAJcBsU%2FxRU%2B0v96VNnZJN3pFCFNWaAVQ1Y3JkmUD1yWnxxLoKluSzlVdrw%2BXRYHM0zs%2FY4Uj3LFaSATb8yTrC4luM6Lb8RpNMN44LvCZjNdfAmmMJTwPOwrkBjNVMC5r%2BC%2FwzmC9ouUNKFXXqzK5sFSHfMJcB8JsZAgfYOueDnzHM3yl72ZjTV2NO%2BawUvLKAoWTA%2BaM5gbGXNdfctK3hbQTujfhjZiWs2bXc1ZyzByVsaTWIu8blIFsvCHKovFfMmpNlGTtWqE9RtMuVaZ5%2BVL1VXjDg249KkT2IWjdVs8PLCJMvrGM98vpe%2F20D8pQadqPvaEoEF5Nc6vGkJStziPsjvXkff8gyR%2BXTPdRKwcrhoEXkVfLlKrbX3DQnsqQj%2BXRC4UjdeLZdpEkznNxjq7COYtTN5zNvNV7uVmaqNU2vUBm%2F0sv5ehCms%2Beq8RwPNs1PYAxgWc5Zg4KKha1T6J3gUTo3Sb%2FJoncDaPPD%2FD2AZrqpLwN%2FBFraGIhDzBRH02QhWQ2Xj0NcB2sJ5cn8fabdn64AFKNa3kNm2d7f6S34VFdk3m%2FWSxp56IbAwFW%2FTeDEHmZ8vguwWP%2FltCSXu98xMm5GCqlHP8XTJKFFraVG2h%2FWNJe%2FsYcxzpOFbEWzTVbYRzF1ZqzBdtv%2FzCP6AyROAIn2bSqCvr3mwAT7c8Ff2p%2FSak93XLXfkBjo1E1LLOPMcX21m4NfCg4AsthZhUySr%2FSpeH7ckwCZ%2FRlYH6OTW%2BGNptiJAvdZNq7jjPYwCtES0bcq7FL52wYCBcoqUUV8SnxN%2F8H73UeUUJei0RyinyBjhXBEFKsTQ6a9R5RRFsxrH%2FuUUdyBsZDnFsaRtlgpQQIny0UG1ZyEgjKmOipJ0Vp14NZuFrfgNWFiCKO4BaWowZ87stYFAiSd2LBi2wtJutVky9FE3sPSDaTMSTW3jYTy9snVUqqPm2aqayucyvxMvF7Ax2SVAQp6aQxWIEAi6E8eY%2Bk86NQd9ASzWxwSceZA5qAaWhWBXWcyIM3hAygnuQYe8z8s3KxeahWrn3QT%2BFRq%2FcdkQ9MnIhD7xaDHYW13vORp1WxPQRMeWUUGhKZ5oCZMZQBkwA5Z5EeNB3sp50yLwSGIC7VcQTzgf3WqT9JRfU0ew4RLPrNxdpWUlCJeAfF8FnL6BgK8I7pbv3ynB7y77%2BStJB7n2pbvLpAA99T0e%2Fv4ziO7n8XdL9F%2FC%2FDYIoz5d1a0BVleBE%2BziU5iTO%2BykGVbCXxzSaY5WT441gptlEka6V%2BF2pRo3iLKfZoC0%2FNHhnZ7y2sNjjeYj4Fh3dQccixLjxmJ6aY7E%2FNQ9jvWjY43ivFgst00JHzcM201zHPa37oHUnh08EpMe8DbIp%2FPmMDode%2FXv1T4xWefpGvkdpKbX8%2BD5MklS0CjgOzaCDD%2BZWW%2FHvm6Ke%2FMT%2Fr3sCeR1fo%2FhruZCvf4VgzppcG%2F09%2FsixMzMHwm2CWYgGKENOjYr56j5rXq3%2FB3nz36PfJvvdYT2Owb8sF4iDzZg34z0COZcJPGsPJZVUaLqlCSx3qDi366Tx0L%2F6y%2FnN1f%2F8ebfewb%2Fjb4Nf%2F4fljiInvKhAAA%3D&bn=Cyberdyne%20Destroyer

**Comment by strideynet** [comment]
Wow.

**Comment by strideynet** [comment]
URL Length issue sorted. ZBUF issue unrelated but an issue.

**Comment by SwissSkynet** [comment]
The "414 Request-URI Too Large" i now gone but got only a Black Empty Site with the Long Link.

https://i.imgur.com/9BV7CLx.gifv

**Comment by JR113** [comment]
Why did you close it? It's still not working.

Displays black empty pages in Chrome and FF in Win 10. In Chrome on Android too.

**Comment by strideynet** [comment]
Issue was closed because URL length issue was resolved as I said when I
closed it. I also said I'm aware of the other issue and thus implied I was
working to fix it. Why shouldn't I close an issue that had been resolved?

On 4 Oct 2017 11:39 am, "JR113" <notifications@github.com> wrote:

Why did you close it? It's still not working.

Displays black empty pages in Chrome and FF in Win 10. In Chrome on Android
too.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/EDCD/coriolis/issues/151#issuecomment-334116632>, or mute
the thread

**Comment by JR113** [comment]
I don't know how this works exactly, but

https://coriolis.edcd.io/import?data=

displays for me 

error: {"errno":-5,"code":"Z_BUF_ERROR"}

every single time. And advises me to create an issue.

When I put the data into

https://coriolis.edcd.io/outfit/federal_corvette?code=

(as it was before 2.4) it displays empty black pages.
