### ISSUE TITLE
Import from ED Market Connector (EDMC) is failing

### ISSUE THREAD

**Issue by NoWan2500** [EDCD/coriolis#152]
I'm using Windows 7 and Internet Explorer 11 is my default browser.  This used to work prior to the ED 2.4 update.  Awesome website by the way!!!  Thank you so much for the work you all put into this.

Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Path: 

Error: Unknown

Details:

scriptUrl: `/import?data=H4sIAG1611kC_-1a23LbOBL9FZeqtuYlw8L94jdf4jhZe-O1XJtHFiLBEssUqeXFGW3K_74NUpYFShQpJpndh0nVZGxFbDSBc7rPAfB99JhZOzp9NHFu342i6ehUvBvFpkwm83Ozyken30fjOC2QDMfRfyytfi-_Vh-5n-PUTNOyGJ2O8sJkhc1G714_-4dZQODRePN5Un9Q2Lz4Ws5mq9HLy8u70SKdlrGtBjrLFmmZuZ--pNnTx-QuS2eZzfMQvhM9RhNTRGlSffNzWTxGRREls6vIxtOH1dKGl_bRJhN7W33XZtfWxMX8toyLaBnD7-6xaZQvY7P6l4lLlwmmOOD0b5Dac_0JCSjmRGjKhRYCkts3zvs_lnGaR8_23uYRvDWMuSf275QEjG3FxgEljFFCBMIK05bgf48SW0STw6ExDaQfGlPJEJWcYM1US-hbk-d7ExWB1H6iQmrGpUZEo7ZoD3ObLToSZYFGW4FRoDnSgkjGBIeJcKtvkxm8cb06rz9_BBBShAhGb__-CiYb28SefLImgbiZnURLe2OfbTw65a-_r79agykEGDyvLssC0PaKNTfWDuoxUYhpytAGp3erYp4m4TrOh8xMLYZB02R0WmQlPLbMojSLIPIpfntH91Lvq6Qv0niN5sPDwspJQjbDrh8u8yJdRHkF-fDcxe419FUGUcbz6LG4zACiQ7l0Nb6EiSvuTbF_XSnyAIMY0ZxxzIXgbYCBkJ-XRbQwcQsQGQ2o8sIySqViihGmMW4J-zEp7Kyeil1oExQQ5iFQask1VZQrKiU5kikMBaiRIUKKYK4FVQy3RvvjqrTxnc0-lYvlnrgkwNyfToIZZMelokS3RL1Lv9nsMjPf9hYIFWjhFwilBVNIYK2R7CAeRrvEu7JxNIFZPrkyWW6rcn6QfbDa4U2azO5NMrM9qCcY3uIALGp4DW-ZTR2Iq87Dw4sYloW30ABt3hVAo6jAFRlg2h9M8tTNQRifcuSN__rw9ui0k4SKIl0R8cZkM3ttsukyjZICDyXi2WKRXsTR0iWxF-HMBw8gnCuOBRNIcInbEH5pFmZm95NQ6wYJteKKISEVORwOED62kzSZ_ry40Fuy6GtZpK1Qp3SnzVLGsBaIQy8cQB4sAkJ97gjiyhvQHIrHoXZo4huQPvtiSp-PKFAEaiYnjGDFue7qhGKXkA_p9OQ3GPXkHIAJ-uq3k9vJP8so6eyLX6xZQkv5_GyzydyBdNqrMzKBN_S4XhZhJawuTJJArA_R4quJwwry3fzUWEhXK_MlpAXdoEmD9efhJM2ySmeF-dzG8CZJGce71CK_jFo0QNKnFihDhIngTLYruFov3IFMKbIqgT2xBUgsv-ILKqDwciKhfhzNWdIMxwhUQIYlFFUphnN2WNxuzkJgRhqBgbJOwWrM6HFdGXq8aFRAkHGCueoHilgMIyz3pSsUAa4RQlRhBWv0F1_38NXAkofO-7k52c9VOpirPUj1Ows4btgNpriABaGcHSn1AFXShyhBEnMOzZUo3a70okW5qDXPHj7pgEkf9ppJijWiSAoyROhBxIZ01IxpIiRVkupB0AeRK4g3jSCYpaAEw38cdbk2rPZgH2B_-Q1q-K5upPvRfox0hEmk0sP6uTWLG5PbLHwos8wWPZEOqglUskA9sF7UUxi6yllGxRbeo0c7LpfLNCt6qU7Mmac6t56vhCerhSfpTB4KKFYug1sTJbWHzIeyrX78gAEUgVY-0yh4FrCyiDD4oW3jpAoLJhCazmMK87d_1wBMlld6u6IdsJQkQLjhrBCGpiCFUIwNcJRENT0qUVVPwBxTfOzOiwiEasgAAb4U4Mw4GmL8QLE0ygEFGQxmUivC1C-wfbhB33pRwnsbJbDCk169SjCkfeu3juLwL_raPres0Her8nRrp1G5-HHz1aq4eEAbuOIUY4KQ0hLs9VDBNSxsp94i4GgaCgkQBmSVGvqOoAN4QAOMmkDTSklCEdXiOBpgf48GYoFwc61bu52VIQ5ONxWhAgWAJHFIk3SYIoTmjX0LxxFQHzEMFO
`line: 0
col: 0
error: {"description":"buffer error: ","errno":-5,"code":"Z_BUF_ERROR","stack":"Error: buffer error: \n   at p.prototype._processChunk (https://coriolis.edcd.io/app.a2bd2c.js:31:379531)\n   at i (https://coriolis.edcd.io/app.a2bd2c.js:31:373142)\n   at t.gunzipSync (https://coriolis.edcd.io/app.a2bd2c.js:31:377274)\n   at value (https://coriolis.edcd.io/app.a2bd2c.js:37:7457)\n   at Anonymous function (https://coriolis.edcd.io/app.a2bd2c.js:37:6712)\n   at Anonymous function (https://coriolis.edcd.io/app.a2bd2c.js:31:29610)\n   at t (https://coriolis.edcd.io/app.a2bd2c.js:31:29495)\n   at Anonymous function (https://coriolis.edcd.io/app.a2bd2c.js:31:29624)\n   at t (https://coriolis.edcd.io/app.a2bd2c.js:31:29495)\n   at a.dispatch (https://coriolis.edcd.io/app.a2bd2c.js:31:29510)"}

**Comment by strideynet** [comment]
It's on my urgent to do list.

On 6 Oct 2017 13:46, "NoWan2500" <notifications@github.com> wrote:

I'm using Windows 7 and Internet Explorer 11 is my default browser. This
used to work prior to the ED 2.4 update. Awesome website by the way!!!
Thank you so much for the work you all put into this.

Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR
2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0;
InfoPath.2; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Path:

Error: Unknown

Details:

scriptUrl: /import?data=H4sIAG1611kC_-1a23LbOBL9FZeqtuYlw8L94jdf4jhZ
e-O1XJtHFiLBEssUqeXFGW3K_74NUpYFShQpJpndh0nVZGxFbDSBc7r
PAfB99JhZOzp9NHFu342i6ehUvBvFpkwm83Ozyken30fjOC2QDMfRfyytfi-
*Vh-5n-PUTNOyGJ2O8sJkhc1G714*-4dZQODRePN5Un9Q2Lz4Ws5mq9HLy8u
70SKdlrGtBjrLFmmZuZ--pNnTx-QuS2eZzfMQvhM9RhNTRGlSffNzWTxGRREls6vIxtOH1dKGl_
bRJhN7W33XZtfWxMX8toyLaBnD7-6xaZQvY7P6l4lLlwmmOOD0b5Dac_
0JCSjmRGjKhRYCkts3zvs_lnGaR8_23uYRvDWMuSf275QEjG3FxgEljFFCB
MIK05bgf48SW0STw6ExDaQfGlPJEJWcYM1US-hbk-d7ExWB1H6iQmrGpUZEo7ZoD3ObLToS
ZYFGW4FRoDnSgkjGBIeJcKtvkxm8cb06rz9_BBBShAhGb__-
CiYb28SefLImgbiZnURLe2OfbTw65a-
*r79agykEGDyvLssC0PaKNTfWDuoxUYhpytAGp3erYp4m4TrOh8xMLYZB02R0WmQlPLbMojSLIPIpfntH91Lvq6Qv0niN5sPDwspJQjbDrh8u8yJdRHkF-fDcxe419FUGUcbz6LG4zACiQ7l0Nb6EiSvuTbF_XSnyAIMY0ZxxzIXgbYCBkJ-XRbQwcQsQGQ2o8sIySqViihGmMW4J-zEp7Kyeil1oExQQ5iFQask1VZQrKiU5kikMBaiRIUKKYK4FVQy3RvvjqrTxnc0-lYvlnrgkwNyfToIZZMelokS3RL1Lv9nsMjPf9hYIFWjhFwilBVNIYK2R7CAeRrvEu7JxNIFZPrkyWW6rcn6QfbDa4U2azO5NMrM9qCcY3uIALGp4DW-ZTR2Iq87Dw4sYloW30ABt3hVAo6jAFRlg2h9M8tTNQRifcuSN__rw9ui0k4SKIl0R8cZkM3ttsukyjZICDyXi2WKRXsTR0iWxF-HMBw8gnCuOBRNIcInbEH5pFmZm95NQ6wYJteKKISEVORwOED62kzSZ_ry40Fuy6GtZpK1Qp3SnzVLGsBaIQy8cQB4sAkJ97gjiyhvQHIrHoXZo4huQPvtiSp-PKFAEaiYnjGDFue7qhGKXkA_p9OQ3GPXkHIAJ-uq3k9vJP8so6eyLX6xZQkv5_GyzydyBdNqrMzKBN_S4XhZhJawuTJJArA_R4quJwwry3fzUWEhXK_MlpAXdoEmD9efhJM2ySmeF-dzG8CZJGce71CK_jFo0QNKnFihDhIngTLYruFov3IFMKbIqgT2xBUgsv-ILKqDwciKhfhzNWdIMxwhUQIYlFFUphnN2WNxuzkJgRhqBgbJOwWrM6HFdGXq8aFRAkHGCueoHilgMIyz3pSsUAa4RQlRhBWv0F1_38NXAkofO-7k52c9VOpirPUj1Ows4btgNpriABaGcHSn1AFXShyhBEnMOzZUo3a70okW5qDXPHj7pgEkf9ppJijWiSAoyROhBxIZ01IxpIiRVkupB0AeRK4g3jSCYpaAEw38cdbk2rPZgH2B*
-Q1q-K5upPvRfox0hEmk0sP6uTWLG5PbLHwos8wWPZEOqglUskA9sF7UUxi6yllGx
Rbeo0c7LpfLNCt6qU7Mmac6t56vhCerhSfpTB4KKFYug1sTJbWHzIeyrX78gAEUgVY-
0yh4FrCyiDD4oW3jpAoLJhCazmMK87d_1wBMlld6u6IdsJQkQLjhrBCGpiCFUI
wNcJRENT0qUVVPwBxTfOzOiwiEasgAAb4U4Mw4GmL8QLE0ygEFGQxmUivC1C-
wfbhB33pRwnsbJbDCk169SjCkfeu3juLwL_raPres0Her8nRrp1G5-
HHz1aq4eEAbuOIUY4KQ0hLs9VDBNSxsp94i4GgaCgkQBmSVGvqOoAN4QAOMm
kDTSklCEdXiOBpgf48GYoFwc61bu52VIQ5ONxWhAgWAJHFIk3SYIoTmjX0LxxFQHzEMFO
line: 0
col: 0
error: {"description":"buffer error:
","errno":-5,"code":"Z_BUF_ERROR","stack":"Error:
buffer error: \n at p.prototype._processChunk (https://coriolis.edcd.io/app.
a2bd2c.js:31:379531)\n at i (https://coriolis.edcd.io/app.
a2bd2c.js:31:373142)\n at t.gunzipSync (https://coriolis.edcd.io/app.
a2bd2c.js:31:377274)\n at value (https://coriolis.edcd.io/app.
a2bd2c.js:37:7457)\n at Anonymous function (https://coriolis.edcd.io/app.
a2bd2c.js:37:6712)\n at Anonymous function (https://coriolis.edcd.io/app.
a2bd2c.js:31:29610)\n at t (https://coriolis.edcd.io/app.
a2bd2c.js:31:29495)\n at Anonymous function (https://coriolis.edcd.io/app.
a2bd2c.js:31:29624)\n at t (https://coriolis.edcd.io/app.
a2bd2c.js:31:29495)\n at a.dispatch (https://coriolis.edcd.io/app.
a2bd2c.js:31:29510)"}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EDCD/coriolis/issues/152>, or mute the thread

**Comment by Marginal** [comment]
> error: {"description":"buffer error: ","errno":-5,"code":"Z_BUF_ERROR","stack":"Error: buffer error: \n

This suggests that you’re running into an IE limitation. Change your default browser.
https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#import-failed-no-ship-loadout-found

**Comment by strideynet** [comment]
@Marginal This issue is different. Affects all browsers.

**Comment by strideynet** [comment]
![image](https://user-images.githubusercontent.com/16336790/31290526-b1676a56-aac4-11e7-9969-e7ad0a43bb29.png)  
Issue appears to be caused or correlates with the release of 2.4

**Comment by NoWan2500** [comment]
@strideynet @Marginal  Export started working some time today. No changes on my end at all. Didn't even restart computer.

A couple things I noticed in Coriolis. Far from a complaint. I greatly appreciate both EDMC and Coriolis.  And as I'm relatively new to both I'm not sure if this is something new or not.
-Export of my Anaconda (didn't try others). I have my Advanced Scanner, Docking Computer, and Surface Scanner in the bottom 2 and 4 slots. When exported to Coriolis they showed up in 4 slot spots (that were empty) further up the list. I can reproduce with more exact results if someone wants them.
-The export in Coriolis is not showing engineering modifications

Thanks again for taking the time to make both of these solutions. I, and I'm sure everyone, really appreciate EDMC and Coriolis.

**Comment by strideynet** [comment]
Did anything in your ship configuration change in that time?

**Comment by NoWan2500** [comment]
@strideynet   I did make changes on my anaconda today but I'm sorry I cannot be sure if I noticed the export was working before or after the change.

**Comment by sharkismyname** [comment]
Great Site!
But I am also having the issue but in Chrome

Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAEFC2FkC_-Vc227bSBL9FUPAYl4cou-XvCX25DLjbLy2sXkUOlLbIkKRAkVl1jPIv-9pUXbclChSdJzJIBggEztidZGsU3VOVbf-Gl2X3o-eX7ts6Y9H6XT03ByP5sV0lfnl6PlfoxflvFiV4W8fivLT2_y8LG5Kv1yO8Zn0Op24Ki3y9Sffr6rrtKrS_OZV6rPp1e3Cj0_9tc8n_t36s758411Wzd6tsipdZPg5XDZNl4vM3f7XZSv4MaKEJYz_a3Q8-lz_hiWEMaY5YcJaor4c71zo1_8tsmKZfvYXfpkuK4dFdxh_xk2i9QPjNOFGK0Wl5FQL3mL89zT3VTrZb5qaxIrINDVWMEGNEVzSFtPv3HK5y5pMVGyMSAVXpRFKKtli7Grmy3mHnyQx5oFhklhLqVGGcWWl_QLLPr_B_dYv5-7vbxEXnBBiyNd__7ebB4Nn6Z9HF7dTfP54VPpJuvBn_rPP4PPdz5sP1pE0Rgx8vj1dVbejL3eBFlbaCkPKDBGWK3E8yjcGcjcp8qkbbyy9Lt3UUyxb5KPnVbnChYsyLcoUtsPqd7cYbupl8fFj5gkNS-1fVGmGP-4XrS8cn6dZUb1zuKzXcqd-4rI-iymtBbtfbH3Z-KSYf3QVsOOm2e0B67HvvB7_fuu9KmHgcpZeV6clQD40Hb0siuoqne_ChY7RC1wwIjUjVihqmW5B3KvLU8RzdeGqXTZ5IklsU0nCYVRwJlm7yfeLKp27rCU3SJIQEuWGtnzwNq_8Tf08d-QrnQgdeWfglNUU98uVVgcmLC4Ty-PMKi1TmmpJbau18-IPX56W7o9dJhlLeJwEGePcEKu01UJ35CpKtnPVK5-lEzyPo1euXPrtlCUbKQvvYnxW5DcXLr_xPfKVEpTp-2jH4x-_wV2W0xCz48v0T6_GJxkeoGyJevL1XhXVFkVpHfwrn125_FM33OAAlyRy4O7i9fKyXp53gs5qLUVY-83qxr9x5XRRpHlFh-LuxXxenGTpIviw801zlKEoFrUiRAsUAMYFty3Rc-rm7maXQQHkxZGD58INp5QybuRec-e-vPShznw7u6jGZfpxVRXtoa4T3Qh1JE5htaWcSDsAPZQl2sZ0hGkrTAAG07QDPExtg-eqmB79Aopx9BIxVPnyl6N3k_-s0jzvQtEH7xZFPn7_2ZeTmStv_LQbSspQa79W4TeLarymjScuz2HrdYoSko1DdHZCSXEdoglLLhdwC3m1GbKb34-rwJ_gxqyYAGz5KsvCYzoLLj89BqhKRIwBAywbRbkO3E8eigEutqiu0JoSQw2RjA_GwEC73RjgNqEqNmyptGC8gEAruH7DL3YKiWdMNTk0U3iOBnw3cN4BmIIUid9QwCezgnPFqd1Hyl12VrjpztfOYpIQcCoJBXFC3rPiKXEqvgFOkaFBkLpwuoZQJ1ClhlJSPXDqEEbjDA80PJPdMGVPBlPIPBbDNMQ-2KJRjFpzMEwR9aIZ9YKEikK0VcNhOsxuN0wleGNM9KQOfJYAqEbxg2HKSVM3c5BuyGYOe4YNIY46MXEiIdoowuCnVlIPwqlNVIPKE24hbziDcv4pYboFOf5kkLMJix--QQgbYyRjih1eGA3Y5VYPCNkWdcY-ghwOtNuNOAFpFRsW0kqliSYgyXyA-FMJiSFMFEGRFYHLKjsEwqRx5wTiWRGLzNiqnVuUJEsEjX1jUFWMGiq5MEPSgUq0bNwt1E1oJqqnJcL_2AI7Kcpy3U0dL2c-yx4U2fTaX64Wi6KseqlR8LdIjT64_qEgZZ2uQ7qIdZZ959L81_X7WA7NN_Xle_o2z6xJpIlCBgDWUnLGFbVtUK7tvl9UyBLXBYrJ7g4s58145FxLoE9IwjjvMr6nMxTIJGmQEyRKwQ1V-I-qIX0iaHPa1OaGILNpAiZB2GHo5okwzZYYyK7B_-CkHAJvCCceP0-qOFKZNloqyboAzrYBjnC6RjQV5dG5y9JOfVu_GmTysldTWwli4ybRxkAAhO7bIJIwBRWzvr13fpqu5t9BotpENMILyowJvDlU4lZSWbfrz33uq3LtwM6sbxs5mlkpqEIZaZVq7RUeFLVBKYOaMppy5NNHSN9hdntwagnVF3NqCZVKADPLNTu8IIMB24ajxmhhkcQUlYMYsIaAaJBqbiQUhWBay39EGSVdZbQGUo86CuK1A3jsCYGnVAN4nEurVZBJVBzcH93qrAvGhSAadJrR4aJzoN1ugCiWyDj6YNFYQ5jmzA4pa42Ga5j3MGkV03LdRT8ccmKL_UNthgkmEcDxodOUhDYnRxCcRlLC4ab-OdF2DupX_VZ87DXD5Q9I892F4_sJ8pWbVGmYRX6YpVXPme555lDBXHn7YrEoCzeZXa7Smj52O0Pjgl-biu10-SA3D2FNhb4i5nEkeHniFm7SNiEUccpH1kH1IEF72hDZe5nq8sLX4bLTMmm2U4wVa50nLJXiQE75jG6RSiBFWpBKTtuz4-UtcDDf_wRk07IREhxdUwHK2polNpb3PQGJDB67LBgRYeaHaNdtj7bG4j6XBU8IbUyoCCVaGCul1vvt7nEYFYg0xkmWWKGR3PDGuso_sdsJ6Y0v3dGVy9NmAuKNBNSM-PH5Bh0br3tRbtZEYNNoKL2mL_lmGoHKLb0HZAB0NRSKQYn-eo2PpT6f7IxDzmINhuLCqA1jEc0s1YNknUloPP7X1DAdSDcC2xwKwV0dJWZBUWBK71N1e2KZhy0JjbaSgV6TcNQK-i1jTuyKufVLDXtGgOZpP2Gn2HaULdZmeog7ulPcXbipG5zl94aA4s2JI1eSaCQ3wZE17GEhoHXCYnHImIY4RC4GT7NDZthyiwWJ0HaH3DDatA7cLn0O6X4VEll1OXH5i_wm8y0QaOz50ZSooDkZlaGx2sGy5HaA_bYq06O3y9ncuU9dbYPaz42747P0ZlZ98OHPfglNxgmtNrMcnscus6IitI7TblKjkSqYioMdS-JxBEh_TPOH21269-gp1Gly7wWrL-7VYYQr8XOYhUB47XNA_S6vD9p1s_aE9_XkSZ-H-CG8kHXHtqcXrMsL0dcLCuoi7r1QP4QX-ofwwtQX_81e2B_BC0r6ehHUvaCRFyeoFcWFm3w6zAEUSWbuHahTRa89uFyq2IHLymeZK18W01tw0kkBrX0bSheS2PjF9HMYJEy7n4cUcqOUL-cuy75DP5gnLC6gELuKCZBSEzZ-DtiyRBqTEUGE4oobcF39mC1LQ-z2aEttNX2UwAPQkPyEKTpoMtvYYEiUhNyExNLcmIO7UhISPt6sJQVXxmiNzG7soZNZ1ZzMokIYoRiDuBy4_Yk0jYKCgeGvW8vsSRtd_Bs1uh6MOFsaXWs4dpMPcLod6H26pnI4oRKj15gwi9MCUdzaNukzzdnaCRHmhZxqwgTjh49zGIh5Q_1qYiUThCPnDU8Lw-z2GOc0GlJAHRUglsYGsj1gnEObW644FXicSnMhhB62RaqREYmG7JGGI3u39t86sMxlokzjCIDSYbTNjSXip8TyVZrfPr4QN47R1Rpn7zE6mcgGAqUEqg2KiaJDBia7k7_VFkJZHHq6zbKEx-5ZxhWjyDoodUO25tJ4B1JoAYeOKrOhOnWOJ4ecFWkeb6tfSt0tOuiUGzKu5PFW99hWSOCkt6Q3dEMCo9DrwUsR_6i7kR8nM3d9feZW-QTIHweDnesbuWP1wVsD-x3rFAml8cuXBkw0RLrRfMgGuWccKbsxgBOWhJ4346y1NvY5KMqao1wLF6UiiAPazpn3JvMtFkpEaJGBQFEl7CMOi3b5-r1RVTsbDgD-GKgS_VD1QPQGP86x5tydBwObxD6-WpWlr_ohjIIaqy1X5NNCjMdnMwIewl5CCAmjLR10ABE1oNHd1ZqAfxiiQ-PpERAb5uz-TWbNAQwJp6a55uHEnXkExLp8_dkhpp5k9BHGpLH2kcoyISwLxyNaB7stfIbGu60C-aBhUkWlhZRtnVPUDZ76bOkufMjmSRNk9KC2w-Ego9h-s-GY81URfthVMCVKRHz7YW-YplRZFbbUf9vJB989-fg9zbIPrixdXt01u16B5q997hF8TPIGWylxz3eWHsSe6Iw9rvD6zVbs6b-VNJnvvXotmk6KbPOFHx3d3DCC_trG3Fy8WlbFPF2uoTl-jcvyPptrvmx9xwOuWs7SxdvToAJ_f0al3vxmE0InDldD-qTFavk1jv8azVZhuzoN37phBWcPvsqEERL2iwkkrKqoXAhLgTCywNLxaJVnhct9-PYTpvHBL1_-D62djpsZRQAA
line: 0
col: 0
error: {"errno":-5,"code":"Z_BUF_ERROR"}

**Comment by NoWan2500** [comment]
@strideynet   I was able to reproduce the issue when I switched back to my Python.  I took a screenshot of everything on my python. https://imgur.com/a/7OMLP  Let me know if you need more info.

**Comment by strideynet** [comment]
Thanks NoWan

**Comment by sharkismyname** [comment]
No more error in Chrome today but I'm not getting eng stats

**Comment by willyb321** [comment]
Turns out the fix is fairly simple - basically the zlib library was bugged in some way. Now using pako which was already being used just indirectly lol.

(See #154 )

**Comment by strideynet** [comment]
Not sure if still fixed? @willyb321 . Merged change to beta server and now it throws a different error. Hmmm

**Comment by willyb321** [comment]
@strideynet what data are you trying it with? and what error?

**Comment by willyb321** [comment]
If its the data that was in this issue, that unfortunately has been wrangled by the markdown parser on github. (note how some of it is in italics)

**Comment by strideynet** [comment]
Ah didn't notice that. Damnit Github. I'll test with some examples tonight from Bugsnag.

**Comment by willyb321** [comment]
Ok cool. I DMed you a link that was not working before the changes too on discord.

(https://pastebin.com/fRJHdFRW for reference)

**Comment by strideynet** [comment]
Does that link work for you now? Fails for me.

**Comment by willyb321** [comment]
Seems to be. 
<img width="1680" alt="screen shot 2017-10-10 at 22 17 15" src="https://user-images.githubusercontent.com/9222609/31383998-df57cf0e-ae08-11e7-8208-c8bcd9d9d91b.png">
(assuming you mean the pastebin i posted)

**Comment by willyb321** [comment]
The scripturl in the OP still appears to be incomplete - this is the decoded data in its entirety:
https://pastebin.com/thHZEaH5

**Comment by NoWan2500** [comment]
Export of all my ships works.. except my main ship (Python).  Still getting the following.  I am using Internet Explorer 11.

Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; InfoPath.2; .NET CLR 1.1.4322; .NET4.0C; .NET4.0E; rv:11.0) like Gecko

Path: 

Error: Unknown

Details:

scriptUrl: /import?data=H4sIAB_w31kC_-1bbW_byBH-K4aA4r7kiH1_8bfYPp-TOo1rGb2PxEZaS0QoUrckface8t87S8q2lhJFir60BdoEcGxGHA53n2fmmdnxH5NHZ-3k_NGkhX03SeaTc_Fukpoqmy0vzKaYnP8xmaZ5iWQ8Tf5paf1z9aW-5L9PczPPq3JyPilK40rrJu-er_3NrMDwZPpyPWsulLYov1SLxWby7du3d5NVPq9SWz_ovVvllfPf_ZK7rx-yO5cvnC2KGD6TPCYzUyZ5Vn_yc1U-JmWZZIvrxKbzh83axlf20WYz-6n-rHU31qTl8lOVlsk6hZ_9bfOkWKdm8w-TVt4TTHHE6V_AtafmCoko5kRoyoUWApw79Jyffl-neZE82XtbJPDW8MwDtn-kJGJsxzaOKGGMEiIQVph2GP9rktkymR03jWkkQ9OYSoao5ARrpjpMfzJFcdBREUkdOiqkZlxqRDTqsvawtG7V4yiLNNoxjCLNkRZEMiY4LITffZst4I2b3Xn-_gOAkCJEMHr9_2cw2dRm9uyjNRnYdXaWrO2tfbLp5Jw__7z9aAOmGGDwtLmqSkDbM9b8s_ZQj4lCTFOGXnB6tymXeRZv7fzszNxieGieTc5LV8Fta5fkLgHL5_j1Hf1L_VQ7fZmnWzQffyzsnCTk5bHbm6uizFdJUUM-vvC2Bz362oGV6TJ5LK8cQHQsl66nV7Bw5b0pD-8rRQFgECOaM465ELwLMGDy87pMVibtACKjEVWBWUapVEwxwjTGHWY_ZKVdNEuxD22CIsICBEotuaaKckWlJCcyhaEItTxESBHMtaCK4U5rv19XNr2z7mO1Wh-wSyLMw-UkmIF3XCpKdIfVu_w3666c-e1ggFCRFmGAUFowhQTWGske4mG0T7xrmyYzWOWza-MKW4fzo-yD3Y5v82xxb7KFHUA9wfAOB2BT4xt4Szf3IK4zD48vU9gW3kED9PKuABpFBa7JAMv-YLKv_RyE51OOguc_37z7dNpLQkWRrol4a9zC3hg3X-dJVuKxRHy_WuWXabL2ThxEOAvBAwjnimPBBBJc4i6EX5mVWdjDJNS6RUKtuGJISEWOmwOET-0sz-Z_nl3ILS75UpV5J9Qp3UuzlDGsBeKQC0eQB4uI0JA7gvjwBjSH4HEsHZr0FqTPIZsy5COKFIGYyQkjWHGu-zKh2CfkQz4_-wGeenYBwAR99cPZp9nfqyTrzYu_WLOGlPL5ybrZ0oN0PigzMoFf6HGzLuNaWF2aLANbPyerLyaNa8j381NjIX2sLNbgFmSDNg221-NZ7lyts-JiaVN4k6xK031qke9GLRohGVILlCHCRHAmuxVcoxfuQKaUrnbggG0BEiuM-IIKCLycSIgfJ3OWtM0xAhGQYQlBVYrxnB1nt5-zYJiRlmGgrFewGjN6WlaGHC9aERBknGA--oEiFuMIy0PpCkGAa4QQVVjBHv2frwf4amDLY1_7-TU5zFU6lqvHVB4LaerVKJKYKYw56MdTiyEgPW6lE4S4JhJxWNZuiZesqlUjdvatKgLxPjCqCCQASgniiJIxCo_sSXBCESEYwkijfY7AE9F9eF64PD97MO5XgORARJ4i7wCPVAZ4vLBmdWsK6-KHyjlbDkQjKBtQsgINwGPZMDz20a1Kyh1MJo92Wq3XuSsHKUPMWaAMd-6vxSFrxCHpdR6CHFbeg08myZo6rxjLiOb2I0WaiLQKi28AiC83EWHwTVdzozYLhRokhscc1u9wZQ-FUAC_PmtHyj7SJhwiCEPglkIoxkZUfUS160ii6riNOab41O6IiIRqpWoBtSPAmXE0pjiDANOq9ihIVSj4tCJMfYfSDLfo22xKfG-TDHZ4NiifCIZ0WJ5trXj8i6Glmd9WyI114-eTnSfV6u0FUqcqwrgtMmCRCYHwpzlH4yuZkXZ7VRGFGoEEhBUESa8KoZYjchTURMR0aJJyDPzS1P8dV8sIGaHQKPVtQiVBKMAi_JuSz0-PgIzEZuWw5IN4kHzuKvhAnX0uKleUz4KowWS_IsKE8AEJqJg5s_
line: 0
col: 0
error: {"description":"Unterminated string constant","number":-2146827273,"stack":"SyntaxError: Unterminated string constant\n   at value (https://coriolis.edcd.io/app.30f6ff.js:37:7519)\n   at Anonymous function (https://coriolis.edcd.io/app.30f6ff.js:37:6713)\n   at Anonymous function (https://coriolis.edcd.io/app.30f6ff.js:31:29610)\n   at t (https://coriolis.edcd.io/app.30f6ff.js:31:29495)\n   at Anonymous function (https://coriolis.edcd.io/app.30f6ff.js:31:29624)\n   at t (https://coriolis.edcd.io/app.30f6ff.js:31:29495)\n   at a.dispatch (https://coriolis.edcd.io/app.30f6ff.js:31:29510)\n   at a.replace (https://coriolis.edcd.io/app.30f6ff.js:31:29168)\n   at a.start (https://coriolis.edcd.io/app.30f6ff.js:31:28788)\n   at value (https://coriolis.edcd.io/app.30f6ff.js:37:11019)"}

**Comment by willyb321** [comment]
@NoWan2500 that is because you hit the URL length limitation which is not an issue we can fix.

**Comment by NoWan2500** [comment]
@willyb321  So if I temporarily remove some components it might work?

**Comment by willyb321** [comment]
@NoWan2500 well the best solution would be to download chrome or firefox, but in theory yes.

**Comment by NoWan2500** [comment]
@willyb321  Oh.. It's an IE limitation.   I set Firefox as default and it did work.. Thank you.
