### ISSUE TITLE
Crash when adding a repair limpet controller 

### ISSUE THREAD

**Issue by richardbuckle** [EDCD/coriolis#156]
Steps to repro:

1. Start configuring a new ship (I've tried Conda, Cobra Mk4 and Sidey).
2. Add any size of repair limpet controller to any slot.

Sample diagnostic output:

Browser: Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1
Path: /outfit/cobra_mk_iv
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.30f6ff.js
line: 37
col: 90711
error: {"line":37,"column":90711,"sourceURL":"https://coriolis.edcd.io/app.30f6ff.js"}

**Comment by Raven144** [comment]
I just had the same problem here are the lines:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Path: /outfit/anaconda
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.30f6ff.js
line: 37
col: 90712
error: {}
