### ISSUE TITLE
Undersized Engineered Shield Generators Modules

### ISSUE THREAD

**Issue by Mav359** [EDCD/coriolis#159]
Hi i dont know if this has been covered already 

The smallest shield generator you can put in a cutter is a size 6 by defualt and you can't buy a size 5 or below in game nor add one in Coriolos

There is however an engineering trick that allows you to buy a Size 5A Shield generator in say an Anaconda which you can Grade 1 Heavy Duty Roll on until you get a Optimised Mass Bonus of 12%, this bonus puts it inside the math of being able store the module then transfer it to use it in a Cutter. 

Its not a cheat simply a question of math but there is no way to represent it on Coriolis and as a result my Cutter Trader build is incomplete as i imagine many peoples would be. Is there a way to be able to use & add the modules 

Top Site, im a big fan and it allows me to keep on top of my builds and plan ahead, keep up the good work.

Cheers
Mav359

**Comment by strideynet** [comment]
#145 Duplicate.
