### ISSUE TITLE
Power Plant shown in red even though it has enough power

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#16]
The 6A power plant on my Imperial Clipper delivers usually 25.2MW. But I overcharged mine to 28.7MW. It has enough power to deploy my hardpoints. But it shows in red in the core internals as if it didn't have enough power:

http://beta.coriolis.edcd.io/outfit/imperial_clipper/0pktkFflndpsnf47l7l0s0s04040404p005f432v6586b2f.Iw18aQ==.IwBj4z2VSA==.H4sIAAAAAAAAA2Pkf-f3-3+xFFYGBo6-jAwM-5mFagQYGPgnfP--X+IJOwODiIAwUJRHMOz---8q54AquJOBrP+8-Af+AVWkMgMFTJkYGARBhAqI+M8nmAdUpvIcqIr7F0gtP78FkJSQAUrKT+QDaqgHyguCCBUQ8f8-AFcUg2uFAAAA?bn=Kantos%20Kan%20Clipper

**Comment by cmdrmcdonald** [comment]
This should now be working on the beta site; please let me know if it does indeed fix your issue.

**Comment by nemesyssoft** [comment]
That did fix it, thanks!
