### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'y.Modifications.modules[e.grp].modifications')

### ISSUE THREAD

**Issue by silverjoe** [EDCD/coriolis#163]
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.1.2 Safari/603.3.8
Path: /outfit/anaconda?code=A0pstnFklndxsxf5--------02020202020202023h431111-----v42f2i.Iw18ZVA%3D.Aw18ZVA%3D..EweloBhBmSQUwIYHMA28QgIwV0A%3D&bn=Anaconda%20Explorer%20std
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.30f6ff.js
line: 37
col: 90711
error: {"line":37,"column":90711,"sourceURL":"https://coriolis.edcd.io/app.30f6ff.js"}

**Comment by Blackth0rn** [comment]
@silverjoe could you please add some information on which actions you were doing when the error occurred? Thanks!
