### ISSUE TITLE
Repair Limpet Controllers cause an error

### ISSUE THREAD

**Issue by ZoZoAizyhr** [EDCD/coriolis#164]
"Jameson, we have a problem..

Uncaught TypeError: Cannot read property 'modifications' of undefined"

Experienced when trying to equip a Repair Limpet Controller of any class and any rating

Browser: Chrome 61.0.3163.100
Path: outfit/python
Error: Unknown
Details:
scriptUrl: https://coriolis.io/app.30f6ff.js
line: 37
col: 90712
error: {}

**Comment by mendocinotim** [comment]
Yes - I just had the same thing happen to me...

Jameson, we have a problem..

Uncaught TypeError: Cannot read property 'modifications' of undefined



Please note that this site uses Google Analytics to track performance and usage. If you are blocking cookies, for example using Ghostery, please disable blocking for this site and try again.

Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Path: /outfit/beluga?code=A0pktsFplDdpsnf7-----0e-02-0303fm3c05--2dv4290i2f2i.Iw18ZJA%3D.MwBjCYQRjXqmZG1LIA%3D%3D.H4sIAAAAAAAAA2P858DAwPCXEUj8Z%2FonAWIzAwl%2BlV%2F%2F%2F4us%2BPv%2Fv%2BgGFgYGiQpWBgblhA%2F%2F%2F%2F9n%2FicFUsQKUhTw%2B%2F9%2FoQvsDAwiHcJARS%2BAOv%2Bz%2FDMEybOA5EEahFY8Aepi%2B5cA11XxBih64MH%2F%2F3o234BS%2FP%2FUYLb%2Bl%2F7HDGfL%2FouFsYUKxBkYJB%2FoAUX%2FM0ABACwZD%2Fe5AAAA.EweloBhBGYA4RQKYEMDmAbJIYT0A&bn=My%20Exploration%20Beluga%20Liner
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.30f6ff.js
line: 37
col: 90712
error: {}

**Comment by JBrace1990** [comment]
+1. This happens at all sizes/quality.

**Comment by strideynet** [comment]
Fixed on beta branch.
