### ISSUE TITLE
Uncaught TypeError: Cannot read property 'modifications' of undefined

### ISSUE THREAD

**Issue by DHARVED** [EDCD/coriolis#166]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Path: /outfit/anaconda?code=A0p0tiFklndnsxf5--------02020202020202023h1105-----43v42f2i.AwRj4zmnRPLiA%3D%3D%3D.Aw18ZVA%3D.H4sIAAAAAAAAA2Pk%2BCTEwMAf9P7%2Ff7E8fgaG%2F0xCCv%2F%2B%2F%2Bfv%2Bfb%2Fv0QdJwODSAGQK%2FqFjYFBOefl%2F%2F%2F%2FmUUmCTMwCH0AquUP%2BP3%2FP6MMEwODhAE7UCuLkBVQBb%2FcR6BWN6DUf1YhNiDJ2QRUy3WKGaiBCUhImADtUuwByiuBFKlGAQm1oj9AhWz8257%2B%2Fy%2B06MH%2F%2F3os3EADBYQuPQIaqPEGKCkoFPIYyH4CtEHiE9BJ%2F4WEwh4CBQxAjhIW6gCxpV4D2SIQhWBNokIsIHYJSFxMKA9k2DGQenGwJfwyIMNegAz7z4ACABmFBogWAQAA.EweloBhBmSQEwPYBsAOALAlgOxCAjBEUA%3D%3D%3D&bn=ANEXP
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.30f6ff.js
line: 37
col: 90712
error: {}

**Comment by Blackth0rn** [comment]
@DHARVED could you please provide some more info on which actions caused this error? Thanks!

**Comment by DHARVED** [comment]
I installed repair limpet controller, but but the bug has already been fixed.
