### ISSUE TITLE
Repair limpets problem

### ISSUE THREAD

**Issue by Ribbon46** [EDCD/coriolis#168]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Path: /outfit/diamondback_explorer?code=A0p0tdFfldddsdf5---020202-320n432f2if2.AwRj4yVUg%3D%3D%3D.EwBj4hGb0lSA..EwegLCAMUgzK0CmBDA5gG0SEBGS%2Bg%3D%3D%3D
Error: Unknown
Details:
scriptUrl: https://coriolis.io/app.30f6ff.js
line: 37
col: 90712
error: {}

**Comment by ThomasWJames** [comment]
Same problem here. No matter what size or ship get the same error really:

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Path: /outfit/asp?code=A0patiFflidfsnf5------020202023d0s4302v62f2i.AwRj49mtROg%3D.CwBjIRgZnWvqAmREShEA.H4sIAAAAAAAAA2P858DAwPCXEUhw3Prx%2Fz9%2FHQsDg9i7v%2F%2F%2FC3kwMzD8Z%2FonAZPnV2NiYBCaBWSKTPr%2F%2F7%2FoPyBLQgdIKPP8BPKZ%2F0nBVWr9A%2BoPATKF9wG5IgeAJkm0gVTWAIn%2F%2F4FiADBWxiB4AAAA.CwegTCAMUgzB0CmBDA5gG0SEBGS%2Bg%3D%3D%3D&bn=Stargazer
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.30f6ff.js
line: 37
col: 90712
error: {}

**Comment by ThomasWJames** [comment]
Awesome thanks!

Don't know what or where "beta branch" is but I'm guessing it's where you developers test stuff out. In any case it's much appreciated for all the fixes you guys do. I love the coriolis!

**Comment by strideynet** [comment]
https://beta.coriolis.edcd.io is the Url and has the currently tested
changes live on it.
