### ISSUE TITLE
Import of loadouts broken

### ISSUE THREAD

**Issue by Marginal** [EDCD/coriolis#17]
c88e436 changed the way that Countermeasures are imported/exported in a way that:
- Breaks import of loadouts from EDMC
- Breaks import of loadouts from Coriolis 2.2.0
- Breaks import of loadouts from coriolis.io

See your [failing tests](https://travis-ci.org/EDCD/coriolis/builds/173504733#L237) for details.

BTW, since 97fc4ce Coriolis exports in a new schema 4 that isn't documented anywhere.

**Comment by cmdrmcdonald** [comment]
Fixed in latest beta (except edshipyard import, will take a look at that separately)

**Comment by Marginal** [comment]
With the current beta importing an older save no longer gives an error, but Countermeasures are silently dropped. See [Here's](https://github.com/EDCD/coriolis/files/585717/Asp.Explorer.2016-11-02T16.05.txt) an example older save.

Also, exporting a build that contains countermeasures creates a file that doesn't validate against your [schema](http://coriolis.io/schemas/ship-loadout/3.json).

**Comment by cmdrmcdonald** [comment]
I don't see that countermeasures are dropped.  Importing the file gives the following:

<img width="1112" alt="screen shot 2016-11-11 at 12 08 50" src="https://cloud.githubusercontent.com/assets/16817420/20214702/a7de3c96-a807-11e6-91ff-a1bdb52c23bc.png">

What do you see when you do this?

**Comment by Marginal** [comment]
Refreshed and tried again and now it works. Odd.
