### ISSUE TITLE
Microsoft Edge continually has an issue with looking at Blueprints

### ISSUE THREAD

**Issue by carlockdvzo** [EDCD/coriolis#178]
I am unable to preview or set up blueprints in Microsoft Edge.  It works fine in Google Chrome.
Thank you,

Information from the website:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063
Path: /outfit/imperial_cutter?code=A2putuFplxdusCf62cApAp1g1gihih04040404040402026161p1fm5o2d2dm9m92b6b.Iw18ZFA%3D.CwBjGYEYwJjtKTsmjiPmMwg%3D.H4sIAAAAAAAAA3WTTWgTURDHX9Lu2nxudvO1aVPSmG3AUoKUKggSofgBBU9KlRykh%2BJZVDCHHkREguQkWESkJ0%2B1R%2FHgoUjx4EUUD1JEBAt60FoUNEpb3%2Fj%2FC7uugnv4M%2FvmN%2FPmzZsX0YeUUj8NiDX%2FSaSwZCk1QJGoLviu3MUtEff6LqVqzb0g53oi%2BXQGUJ8eDOK3sOrMY9VtxJTKXmHg3TwgQx%2FwoVh7WyTuAqrS2k1rlFadltsfUcqhiKlnGdPPxBsfRRr7vyN7852IDOgTfjpzAnu69U2RWg9QcTGqlLECj8RC0NQ3QPe%2FAGK8MYukEv%2Fj3xmCGBtYNa9%2BBbn%2BGeQkSCuTBpnQJ%2F8mj7KmNeDOB1RaeukpNdxAXcVHDvBkCKcUV9ECY5Xk5gjIZY3s71G2pPSpgGQXx%2BYgThNJ3MNodalbQ%2BALrJU7WXT%2BYBzZ06GYWBDzgDGLjCnUseMK1moMFMtqAXXMS%2FB3wFcmT2M1o48El%2FaE%2FtYF%2BO%2FQ30HxHhPblARF7BC%2BRHyB%2BHNsV5kCbk8QcvQxH0o8g9ptkzXZSMdf69UPnDgbgm7Bb81gruw9JG%2FgiB4tyYW263K79fP%2BdtdmkPgpHB4lQZG8HiXeB1Hsk9OZRsfGcSlS%2BNd1dh9cDm5BinqaLoyLiozv4KpbmEG3zcbxgqSkjwfjwzMnbgO1K0iVv5xUaqgL3Gui3GgPw2WdwfXmTM5VWY8FR3wLPL1QQiAtp5BC4bRSayx8OETeg6YfuyBpOW28P4%2BWjISgm8ifflMEROv3S%2FNopZaZrqrL%2Fo
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/outfit/imperial_cutter?code=A2putuFplxdusCf62cApAp1g1gihih04040404040402026161p1fm5o2d2dm9m92b6b.Iw18ZFA%3D.CwBjGYEYwJjtKTsmjiPmMwg%3D.H4sIAAAAAAAAA3WTTWgTURDHX9Lu2nxudvO1aVPSmG3AUoKUKggSofgBBU9KlRykh%2BJZVDCHHkREguQkWESkJ0%2B1R%2FHgoUjx4EUUD1JEBAt60FoUNEpb3%2Fj%2FC7uugnv4M%2FvmN%2FPmzZsX0YeUUj8NiDX%2FSaSwZCk1QJGoLviu3MUtEff6LqVqzb0g53oi%2BXQGUJ8eDOK3sOrMY9VtxJTKXmHg3TwgQx%2FwoVh7WyTuAqrS2k1rlFadltsfUcqhiKlnGdPPxBsfRRr7vyN7852IDOgTfjpzAnu69U2RWg9QcTGqlLECj8RC0NQ3QPe%2FAGK8MYukEv%2Fj3xmCGBtYNa9%2BBbn%2BGeQkSCuTBpnQJ%2F8mj7KmNeDOB1RaeukpNdxAXcVHDvBkCKcUV9ECY5Xk5gjIZY3s71G2pPSpgGQXx%2BYgThNJ3MNodalbQ%2BALrJU7WXT%2BYBzZ06GYWBDzgDGLjCnUseMK1moMFMtqAXXMS%2FB3wFcmT2M1o48El%2FaE%2FtYF%2BO%2FQ30HxHhPblARF7BC%2BRHyB%2BHNsV5kCbk8QcvQxH0o8g9ptkzXZSMdf69UPnDgbgm7Bb81gruw9JG%2FgiB4tyYW263K79fP%2BdtdmkPgpHB4lQZG8HiXeB1Hsk9OZRsfGcSlS%2BNd1dh9cDm5BinqaLoyLiozv4KpbmEG3zcbxgqSkjwfjwzMnbgO1K0iVv5xUaqgL3Gui3GgPw2WdwfXmTM5VWY8FR3wLPL1QQiAtp5BC4bRSayx8OETeg6YfuyBpOW28P4%2BWjISgm8ifflMEROv3S%2FNopZaZrqrL%2Fo
line: 1
col: 1
error: {}

**Comment by willyb321** [comment]
That would be the URL length limitation. Not much we can do about it apart from use another browser.
