### ISSUE TITLE
Type 10 Missing?

### ISSUE THREAD

**Issue by Rindula** [EDCD/coriolis#181]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAOnRPloC_81aW2_bOBb-KwsBu5gBEoF3UtmnJmmaziSdwM5M901gbdohIksCRXXqKfrf90hKZMuxLDW70yQPgUKb3_l47ofK12DhjAlOFjopzFFg58EJQUdBost0dneq10Vw8jWYJplHNJ7av4yo_y4_1UvVc5LpeVb64CRYZKULjh4XPugVwAY_vTOJnf_rw-n05t_vfoaP02Z9YebGaW-zNF7Y5Z03Lvh29AiM_wdgm85NbuBX6jfIFXRFWNRnYP1nKLx21Y5dadN2_UGMN4X_VC6X637az8GqmK6yeZmYWvFv3Ko6Ozw1i9XTE3thoqTiguAW8Hadmyi-tokFUeu4QYnfOT03GMRmaXDiXQnbc2czZ_0aQI6CzzopYTeqOJybmU7wsGAhpGRRK7jeFt9WguK3qXeVJUxtvLEyyQvIpD9W5oUDkOmdXfhzZz_XIj9m7v59euOypTNFEQMXu7CzOjxqP_it9AvrvU2XF9Yk88q-8cX0_NJoP9G-hpjbIk_0-o9GUCBCrP4ZtIJxiASWkkuCBYoEsOiB_C33dqWTa10Ue1AJCRHpwBKCCGYRpZjLHtT3qTfLRhNPAI8xDiO8hYhCpVBEiKCIkYj0YfbwO8ZRyHmHII44i8CAVHCOe9G-XJQmuTHul3KV78GlIYq62qRIQdQJpBBTPag32Z_GnTv9516iNFS0S5QqojADEyHKKz8x6dKmxtTh__j8HtyRIgRG3Hz-kFbeJp-t0_-4huRSlveA7MzM5ubKfDYJbHr8--HbYOr4KkuXE50uTdBmnT7_R4Jhilr_B5PGl3BGN688uE6qMj5LwCi0JwZQe1IuIiWjJhJA6bc6vR-OP5BPOe7If9zclKXD0jcRSCJEWS38SruludRunmc29SNynYwoEhsdXOY-fnN7XSbenuk0hUJ2WzpnfFwDD6qBEqao2MOEvBom9NUwYS_JxC7MtMzzzPlRfopFN0629teuyscGChZKkZrCtbbp2zrai-dWi2b7gYJxzEOxUzG4kNBVRCqShPTkuAYWigbkzkXmVjqd7QPHKKRdcIyowpJSoXAkh8APVKRj0kVGYSQFmABLQiV4xDNqEg_JTrLnUIkElxJLQZ-T7FnIu1UTMU4QgnIsFKH_91xPdnJ9o8f43Dq_HpXqUcQ7LvwA8Nw0f23mtlx9T6pF0FGoqBPMNyV84UoXxj1GcgM7HEaAp_bxIK-EB30xHg8DAhrV6CvOul5xWSbJxNgU4n5mVtW8tZXehucMzBH8dHiQl-Vxk-jUVETe5LnL9OxuWtomVw5wglyDZYdTA9XFGSLCSN32NZnEFt7ZT6XP3KiiQ1BXJ7sgY5qkrdjlAmPUkqkOM672ISGe0sir7TUB1RBgg6rgrG7ba31M9FyPVALtKmFq0iJzRTPzjz27RBEl9YXBnc3fn6MRnQevKmQruUq6cGQP-bJGiM-z8lNirqoM-vFujCOgjXj8kuIrqJHn3yoYGwI3Ts88NCYJos8RjV9AdHUjhBtffW6ndeqye5NOzBJ-9bRahIcUdZoWySTMuwSSG2a9PcZZliS2ANkTU0Bo9_RaKuSi2xBhRiMhMQyXjPU3csYt19DF1cT3wLIQoZ0RGFRPaZWSo77B-u2XPMkKGBEPMua8i41CBjmZMCYxisC3e8B_BZcGGx-EZjzErAPNmRJU1fO7EPw7rxdkGO0oQYIDVr0hFZT1gB10BRWyaMdaHHHMKYN2M-o7OoQIPL4z6dQ7aA393b6eW4VUdntuRSXCXDIFyu1Bvr0zbjWg1OMolN27CwRWkqK-YqL0b7-7aE9f3SBDbWuL_3y4u4U4oFR1y8QO3FalovGFLvxgzSBQNCSotU0hpOmVx91rMNahcwYDajbRs_vtfntEG1NplsuWwtZ1_UAOJTA671ytNPfmp3q93Tfg4daSKxXRqOXAmk5spBrIATWM7-Yw5kK0DPjmwn-orxRCRk8umKazLMu3Gwg-fMPEKEUY7XvnMNhGkqh7d3BavRV4NAMbqwOBCdrIl_VmOtII6IAR6Hhf5IK2BNSPJwAdURuMuKnn46Y9zro-cJ7N7iE_nmWrvISIiKeQE6EdnQ838_zBBCudJN85-jKlOqPeRNtkWaYQll_MPK4RhztoSLN7CJAfT-DWpuvvVADH3Vm3uraa2vT-qn4ruZl4K-jh5BxJ_oQHeSU86LiJl4oOj6ZinWZZUfskeDc6nJ3YhoXCaI9d2CvhwX8MDzrEQ7wSHvKV8FAvx-Oj0XmWwuwz7k04JXjrpuxhc1n4bGWL5v8NTisBI8bBbz3v02FvUY_W8Ml_juXk918fVj603842zfHX4K6EdAk1kRIqEEdbL_gxTGSEowiO7TOvq6tbLIWAZVgp0yTTqamOpWj19u3bt_8CXAOfhq0hAAA%3D
line: 0
col: 0
error: "No such ship found: \"Type9_Military\""

**Comment by strideynet** [comment]
Ah looks like a case of FDev not naming the ship the same way I expected
them to.
