### ISSUE TITLE
Anti-Xeno Weapons missing

### ISSUE THREAD

**Issue by NikolaiVChr** [EDCD/coriolis#182]
I dont seem able to select AX weapons.

Thanks for great website. Use it all the time.

**Comment by Kurgol** [comment]
http://elite-dangerous.wikia.com/wiki/AX_Multi-cannon
http://elite-dangerous.wikia.com/wiki/AX_Missile_Rack

**Comment by willyb321** [comment]
Fixed in #196 

@strideynet pls close
