### ISSUE TITLE
Hull Ratings

### ISSUE THREAD

**Issue by strideynet** [EDCD/coriolis#183]
All hull ratings show as 8

**Comment by pnellesen** [comment]
This may not be a bug? I believe every ship can equip any available armor type? That column appears to be the "Max Hull Rating" - maybe we could add a tooltip with wording to that effect, or suppress the display for that cell only? There don't seem to be any rating values ("1", "2", etc.) associated with the hull types in the data files, unlike every other module.

**Comment by pnellesen** [comment]
Maybe use the first letter of the Hull type instead of a number? Similar to the Utility mounts? I could work up something like this:

![image](https://user-images.githubusercontent.com/6032970/38534662-cfcc2312-3c44-11e8-90bb-b9355311995c.png)

**Comment by willyb321** [comment]
Fixed in 51d29aee38ecedbf4ec0f56c49ca31f77165e653
