### ISSUE TITLE
Inconsistant units

### ISSUE THREAD

**Issue by strideynet** [EDCD/coriolis#184]
![](https://media.discordapp.net/attachments/164411501166198784/396005900965380096/unknown.png)
![](https://media.discordapp.net/attachments/164411501166198784/396022167269146634/unknown.png)
![](https://media.discordapp.net/attachments/164411501166198784/396022280435793921/unknown.png)

**Comment by Blackth0rn** [comment]
I'll look into this issue tonight hopefully

**Comment by Greg-Navarik** [comment]
Sounded like something was being done on Fdev's end regarding these units. Might be prudent to wait until that's sorted out before we start changing units in Coriolis.

**Comment by Blackth0rn** [comment]
Sounded like something was being looked into at Fdev's end for this issue. Probably best to wait until that's sorted out before working on this issue.

**Comment by willyb321** [comment]
Per EDCD Discord
Fdev Rhevian - Yesterday at 11:03 PM
The "MW/s" in game will be changed to "MJ/s"
