### ISSUE TITLE
Anaconda retracted power doesn't match outfitting

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#19]
Retracted, the outfitting screen reports I'm using 26.95MW. After carefully reviewing power requirements from all modules, I didn't find any discrepencies even though coriolis reports 23.63MW in this build: http://beta.coriolis.edcd.io/outfit/anaconda/0pptnFklndusxf57o0v0v0v28281919040404040405--3c0505054af50s5dv62i2f.Iw18ZIAxkA==.IzAM-MOmJFQPkA==.H4sIAAAAAAAAAxVPPQ8BURDcO+Ijr3jeOaIQJ1yhUosoLn6ESqGVKFQKrV6lvk4nKvEb-AgR8ROEIBFrppm3O7Mzb9ezyVe1OsmKFFqeiPr2pqq1g4iEXVSVXUakfUKrmeBXErHJC-oYrJcrYih10Jc-jJbsGk9t44u4K7Jignky1dkeU-uQzBSEI8QfSoE90rWga06WYC6UynZI1x51NMJf5kwrISZoaO+0zmjdkiWYDlqt+-W3qkuxd3tAdsULIo8rNR84OV+BtcEzVf9lNlFABQEAAA==?bn=Kantos%20Kan%20Anaconda

**Comment by cmdrmcdonald** [comment]
This will be fixed in the 2.2.2 release.
