### ISSUE TITLE
Equipment placed in wrong slot on import

### ISSUE THREAD

**Issue by Kamiakze** [EDCD/coriolis#191]
Importing an Anaconda-build with EDMC placed an Advanced Discovery Scanner in the top size 6 slot rather the size 2 one it actally was in. Other equipment installed was a 5A Shield Cell Bank in the Military Compartment and a 5D Shield Gen in the size 7 slot, all other optional slots empty. Was reproducable by different People on Different PC's.
I am actually not sure wether this is an EDCD od EDMC issue, so, tell me if im on the wrong path here :)

**Comment by awdwyn** [comment]
I'll also test this later tonight and post results.

**Comment by awdwyn** [comment]
When the slots are all used it's getting it right, so it looks like it has something to do with the handling of unused slots.

**Comment by strideynet** [comment]
This will be fixed by the upcoming journal change.
