### ISSUE TITLE
Ship table highlighting issue when sorting by certain headings

### ISSUE THREAD

**Issue by bananastalktome** [EDCD/coriolis#193]
When clicking to sort any column except "SHIP" or "COST", the alternating row highlighting (which is a great addition, by the way) no longer alternates color row-by-row. The attached image is an example when sorted by "SIZE":
<img width="1545" alt="screen shot 2018-01-17 at 12 36 53 pm" src="https://user-images.githubusercontent.com/60870/35057502-20c3f23e-fb83-11e7-9547-2d028c55ecd5.png">

**Comment by strideynet** [comment]
Please pay more attention. They are grouped by identical value.

**Comment by bananastalktome** [comment]
> Please pay more attention. They are grouped by identical value.

I was not aware that was what the highlighting was for, since the default view when the page is loaded as well as when "COST" is sorted by is alternating rows (which I realize would contain no identical values, so grouping wouldn't be possible). The design of alternating row highlighting for a table is common enough that I mistakenly assumed it was what was happening here as well.

**Comment by strideynet** [comment]
Sorry if that sounded a bit rude, I was in a rush.

I've considered ensuring it's always alternating but have grown to like the
way it makes grouping appear more obvious

**Comment by bananastalktome** [comment]
> Sorry if that sounded a bit rude, I was in a rush. I've considered ensuring it's always alternating but have grown to like the way it makes grouping appear more obvious

Not a problem. I personally would prefer alternating row coloring, but I completely understand where you're coming from with the grouping.

**Comment by Noobilite** [comment]
What about a setting to let people choose between the two. The best of both worlds? 8)

**Comment by Blackth0rn** [comment]
The initial enhancement request was this one: #112 
It should be possible to add a checkbox in the settings drop down possibly?
