### ISSUE TITLE
Incorrect calculation on armor and shield will hold times in defense screen.

### ISSUE THREAD

**Issue by Noobilite** [EDCD/coriolis#194]
There seems to be an error in the calculations for the shield will hold and armor will hold in the defense section for ships. It can be seen by making a single ship setup and using the best power distributor then changing to any weak one. The weaker ones will always have better times and last longer. There is some sort of error possibly related to the power distributor or some other factor for the calculation of these two fields..

This thread on the elite dangerous forums has links to specific ship builds set up to demonstrate the time and the logic error.

https://forums.frontier.co.uk/showthread.php/400353-Weird-shield-anomoly-Coriolis-!

**Comment by willyb321** [comment]
I believe this may be related to the shield / armour exports being bugged from the CAPI export => coriolis. We will get this fixed for the new format when we have it.

**Comment by felixlinker** [comment]
Can't reproduce on live. Seems to have been fixed.
