### ISSUE TITLE
Importing engineered ships using EDMC fails with unknown error

### ISSUE THREAD

**Issue by compro01** [EDCD/coriolis#195]
Attempting to import certain engineered ships fails with an unknown error.  Corvette fails, Cutter fails, Anaconda fails, Python fails, [Imperial Eagle](https://eddp.co/u/26RECSAc) succeeds.  Unengineered ships seem to always import fine (tested with Beluga, Type 10, Cobra MkIII, and Hauler).

Error from Corvette : 

> Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0.3 Waterfox/56.0.3
> Path:
> Error: Unknown
> Details:
> 
> scriptUrl: /import?data=H4sIAK4kZFoC_-Vca2_bRhb9K4aA3e4CDjHvR_ZTbMdJuk7jtYz2o8BIY5sIRaoUmdYt8t_3DOXXUKJIUXG326BIIcvWnTsz99x77oP6fXRVODd6eRWnS3c4Smajl1QdjtK4yqY3R_HtcvTy99E4zUvCJuPkN6frn6uP9Vv-dZrHs7wqRy9HeeZGh_c__xDPIXX0jzcuTWZ__-FofP6v03_i19nqfTdfJIWbXCXXN6UrRl8O72XSryfzC6TO81mVunoTr4p5XhX-1epN_2p978wQYbkmD1JP3cwVcZnk2eQ4Lz67snSTlajJmyKeOQoF8mz0siwqyFgUSV4k5S0kHY4-x2kFEcQrcuKmcUq7V1dKa0EfVq8_hoXnH-NychJn167Iq-UOS7J-S8rmkpd-b5PXaVK6HVbjPVezjdVe_7pI88IVuyx4WkDC-Ca5Kk-K5HO93k958elddl7k14VbLidQJLlKpvXl1SbwoSqvkrJMsuvTxKWzy9uFm5yOT966uLyIy1rELFku0vj2x9VCIxNJ-7fRw8I0IkYaaTUxwhgo0SLxw6JM5nH6Pl4uNwgVJuImkCoMh0CmuZaCtoh9l5XuenUSaxJfMBqpp4qSSBtOlCREUa6MbZHZouALyiImAg0pY4JzwZkWolXYr6eVS89d8X01X2zad8QahymYZdZIwVqFnue_uOKkiH_ZuGuO-wgkMk40EGwYBDNvJS67TjLnatzfv34HS-SEUEIef__DPdrTZIozPjiNi6X_2OGocNNk4c7cZ5eOXsr7n-__fnwyOcuz6wsPzdGDw2n1LUpQph-MH1c6eYtdFjNvwbV_VZPjFJciWzBAHvcqqNWS2xoKOPbLOPvUw7kpwSUJFLj_cL28XC3POyFoJM7Zr_22unZv42K2yJNs5b2HoPDVfJ4fp8nC67DxpklEVGjf1nIlhSJGMyVbrOcknsfXmwQKGJ8OIUiJUoZyAbTwreJg4GM3zbPZ15ObLMsi-ViVeaupCxJRFQomVHFNLQ6BmAE-Q0aMhWiUjCoiNWOKqBaBlzeugGM7Q0DeIBJug4vgloxWUjL4DiotEx2AxLprgLzMZwffYdWDI9glwvp3B--n_6mSLOtC5k8uXiBmf_jsiulNXFy7WTc8cU_Wqgd0vF2Uk_dVWibHcZZB1psEYTideIvvhKeUVnEh1hDCng0hLJImRAiIhGYUu5J0d4CIiPDQ3gThnOE_jpMaDpBhcrsBwjUkBYK5FtxwKSVk6wEAoSSMqQiCRBljOBOEMT4gYEGiYA2JgiqGm7KG0G8THmd-9f0jSLslR7rh54SmhgscOG21ix6GPETsNnPTESehQI1LJ9Jo2WpsbfyNg2qF0YILJhWh0ggrTDuBS-bVfMVl1qUqeHcZCFWMC8m1lZZYO4TAUbnGMyViBUGKILDp7XggfB0PR0WeH1zGxc_AQE8I7ELfcHgkBMB5hT84i5euOKqKZXkPgtqoO1EAMo1LqUGQXLlxtVjkRTkUAFvzA64iwoLooLgFnAVsjBlqdrMvWAIN2RhHuqFwONyClXT5sQ33doazOfger5f52r3xxr09OavJmU_2f3L-__3Yt2IB-X0q6wn_7UG_ibFMar_V93GSva63sxx6d6uPb8lDXxgQ4BB8hhCAj4O1CdEW3ldykY3Ck13lYG7ZdJN0ZkHUwjzKGvBKinAnBOsSviXVfWEiRgNLsVRbyFRUEtjKoFxXgdqETAcRXjDN4BKoFrvZsmxSVitAWQnz9kLkIKdmIxJ6cmqslVrD8BmYWAc62Do6YExXsKW8ODiP027HtroYkKYCB9gHFcSGOemdgLre1xcQoq412Br8790sqebPGNPhf0IS6e8LiYYRUujh5HSQ2DbLB9NVTaarmCVccGutHRaDNQPPCITC6rkBlJgXPdRcQ_BTS5TUUvpkcFAeaCMeBhsINBT7VhyZsPlTxnXOg7h-5OJ5HdbvI_rKprthYAwxcgMI2HPEdRYJ0zBYoZVCZAfX0zsaLAMZa0QByTQVVsFu1TB7NTDQMIcyVBvLFRO83b
> line: 0
> col: 0
> error: {}

**Comment by willyb321** [comment]
Internet Explorer / Edge?

**Comment by compro01** [comment]
No, Waterfox, which is a modified Firefox.

Though upon testing, import does succeed using Chrome.

[this](https://eddp.co/u/i31Rcfyw) is the Corvette build.

**Comment by strideynet** [comment]
Most likely URL length limitation.
