### ISSUE TITLE
AX weapons/ items corrupting saves.

### ISSUE THREAD

**Issue by Noobilite** [EDCD/coriolis#197]
This: https://eddp.co/u/JAlmuRmb
Ignore the differences in priority values.

Turns into this after saving and loading: https://eddp.co/u/e16Vu4pY

And nvm it messes it up even on linking... It was modified from this: https://eddp.co/u/g3QPXc9Q
Again, ignore the differences in priority in the energy screen.

I only changed the two top utilities to a zeno scanner and a shutdown field neutralizer. 
The weapons were change to: Large: 2xTurret AX missiles, 2xFixed AX multicannon; Mediums: 3x Remote Release Flak Cannon

Hope this isn't covered in another post. I wasn't certain. I'm using firefox if it matters.

The problem occurs both after reloading after a save and from linking even to an unsaved link. BTW, it also happened on a cutter build I tried to save. So it's not just one ship or anything.

https://eddp.co/u/66ihnhNP

**Comment by willyb321** [comment]
@strideynet should be on this fairly soon, per EDCD discord
Strideynet (EDStats/Coriolis) - Today at 9:00 AM
I thought i had tested them all but looks like the one I missed was broken :smile:
Yeah he used 3 digit ids

**Comment by strideynet** [comment]
Will resolve this tonight or tomorrow depending on how busy I am.

**Comment by Noobilite** [comment]
The behavior hasn't changed for this.

**Comment by willyb321** [comment]
@Noobilite is that on live?

**Comment by Noobilite** [comment]
I don't know if it's live or not. I googled the site and opened it and it's still not saving for me. I use firefox on linux. Is it possibly from this?

**Comment by Noobilite** [comment]
^found the problem. It's the 0F shutdown field neutraliser. It is still causing an issue. it also removes itself from the build which is why it doesn't show in the above links. I was clumping it with AX.

**Comment by strideynet** [comment]
It's fixed on the beta branch, hence why I closed the issue...
