### ISSUE TITLE
Incorrect DPS comparison for some hardpoints

### ISSUE THREAD

**Issue by alecz20** [EDCD/coriolis#198]
Whenever changing a module, some comparison stats are displayed in the form of new_value (+/- difference).

For example when comparing pulse lasers **1G** with **1F**, where the latter deals **1.65** more DPS (7.9 vs 6.2), the following text is shown:

    Damage per Second: 7.89 ( +1.65)

However, when comparing **burst lasers** the numbers do not make sense. For example, comparing **1G** to **1F** burst lasers, where the latter deals **1.6** more DPS (8.1 vs 6.5), the following line is shown:

    Damage per Second: 3.44 ( -3.03)

The reverse comparison shows:

    Damage per Second: 2.72 ( -5.43)

These numbers make no sense, the difference should always be +/- 1.6
![image](https://user-images.githubusercontent.com/5096883/35458247-9cf4b32a-02a9-11e8-80dc-2754b8d148d5.png)

This seems to affect fragment cannons as well.

**Comment by strideynet** [comment]
#185 possible link
