### ISSUE TITLE
Enhanced Performance Thrusters are not exported correctly

### ISSUE THREAD

**Issue by atfrase** [EDCD/coriolis#2]
When a build with Enhanced Performance Thrusters is exported (either individually or by the bulk Detailed Export), the thrusters are converted to their regular A-rated counterpart:

> ```
>     "thrusters": {
>       "class": 3,
>       "rating": "A",
>       "enabled": true,
>       "priority": 1
>     },
> ```

**Comment by cmdrmcdonald** [comment]
Thanks for reporting this.

The export is missing the name from the exported item (the other exported stats are the same).  I'll fix this prior to the 2.2 release.

**Comment by cmdrmcdonald** [comment]
Fixed
