### ISSUE TITLE
Mismatch between outfitting and coriolis for Corvette speed and boost

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#20]
The outfitting screen shows a speed of 228M/s and boost of 296M/s while coriolis reports 211M/s and 274M/s respectively:

http://beta.coriolis.edcd.io/outfit/federal_corvette/2putsFklndzsxf50x0x7l28281919040404040402020l06p05sf63c5ifrv66g2f.Iw18QDFZA===.EwRgDBHpO8bROJSg.H4sIAAAAAAAAAy1RvU7CUBj9Wmj5Kclta9Ei8qMWB0YdND6AMU4+AIODcSDG0dmBwYmZB2BwJAzGyTgYF+NiMCHqYzAYUD-PQTqcfP3Ozz251zIDxZd3RLKnIrLMSe14aIsUn12RzSgSiZq-qqY6Uw27KfCpsBeKmPZUNfZz4C8gUsfsw9VIeyJbD5Dl+t9IHkO0-gjYOEOIZsO+JRIfgXIPISpdZmDNO23EuH6MA89bWKCKVFjC38O0MmZJz9wiwbnPQ3lVhnIGf2WQXoi0EKKFmG1hPg5xrpkZUjkX7VJkTBch8QFm7w2igJAQ1DcjUj+YvSEpQkLQwPgoEE84d7LgX8gTEkKNOw1Nh-53tA4E4I3IE3Tp399EYe+DPCEhaBydoFyxhYRyD3678QXlJ-oF8yY3AJe-yZRXX7Ke4MrwQaqv2NaneBVds3ZAZti-moahfof71VpoYxsf40lLrdTiVlc5FSbk9Q+6fbbO-gEAAA==?bn=Kantos%20Kan%20Federal%20Corvette

I have verified the speed in game and I can indeed reach 228M/s and boost to 296M/s.

**Comment by cmdrmcdonald** [comment]
For items like this and #19 please could you provide details of the ship from the raw data obtained by the companion API?  I believe that EDMC can provide this, or other tools that can obtain the companion API data.  Otherwise it isn't possible to work out what the problem might be.

**Comment by nemesyssoft** [comment]
I'm attaching the JSON file.
[Corvette Raw Data.zip](https://github.com/EDCD/coriolis/files/585201/Corvette.Raw.Data.zip)

**Comment by cmdrmcdonald** [comment]
When adding in the modifications that are in the raw data but not the URL it gives the correct numbers.  However, the fact that some of the modifications are missing from the URL is concerning.  This has already been raised in #21 so I'll continue the conversation there.
