### ISSUE TITLE
Cannot import from anywhere

### ISSUE THREAD

**Issue by triccaj** [EDCD/coriolis#201]
I have a heavily engineered anaconda and when clicking the ship name in EDMC it loads Coriolis with the following error report..:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAARze1oC_-VcXW_bxhL9K4GAi74kxH5_5C2x6zpt3Phaxs2jsJXWNhGKFCgqjRvkv9-zlPyxlChSdJwWaB8C2xVnZ3fnzJwzu9TX0VXp_ej1lcuW_uUonY1e65ejeTFbZX45ev119KacF6sy_PSxKD-9y8_L4rr0y-UEn0mv0qmr0iKvP_lhVV2lVZXm1yepz2aXtws_OfZXPp_6s_qzvjz1LqtuzlZZlS4y_B4em6XLReZu_-eyFfwYUS4Twv8zejn6vP4LS7gkTFFjrGHs28ud4_z8ZZEVy_Szv_DLdFk5jLnD9ivOE_bYNk04Z5xIrahgSrcY_y3NfZVO95umImEkMk0FtVpxpSzXbX6fueVylzVmEmYia8wwQ4k2zMLdFmuXN76cdzgqEiMeGSaJlVQJZTUTAt5-g2mfX2PG6925-_kdAoMTwih5-P-_u3mwOPaZz_2LX73LYbf003Th3_vPPhu9lne_bz66DqYJwuDz7fGquh19u4u1MNZWJFJmiLBciZejfGMgd9Min7nJxtIvpZt5imGLfPS6Kld4cFGmRZnC9mv6MMswrWM_dRkNA-0fUktLDLkfsn5scuTyvMgPGIh1D6SU1tI0BqojufTlZFy58o_M_YV96D8q7zeq2JpeMf_DVSEcq77jnZQwML5Jr6rjEsAbmiHeFkV1mc53hSpjCZUxCBgVSjIqiVG2BQQn4-MPiyqdu6wFXFwlNEYqV8RqwSRjTLRYfZdX_nq9DjuwbxJJIlAZuMiE1Bq5i4sDwc9JQmzsICGWCiM40lW7tS8nK5-d-_LX1Xyxa96JjqdNuCaEGkG0Jm0J6rz405fHpftzh0G4aeJUYi1DllKaM2S-jlRCyXYqOfFZOsUivzhx5dLXkRjlE9HIJ9jryfsiv75w-bXvkUyUoEzfhz72dHKKSZazEMCTcfqXV5OjDLsiWyBAHlaPa8kUli0gAct-6fJP3diDAwiIyIG7h-vh5Xp43olAw4mtUXi6uvanrpwtijSv6FAQrrPpOdJ4Vdaf3LnbjYqEaqC1MpqjbLRVpGM3d9e7sG0TSmNrlhLJsUKADd9rDRE-9qEKfDezqJZl-seqKtoiHQBnsV1qUApBG5iwRB2Kb5bIBr6ZtNRgIYWQph3f6Xw1X4f6tlWlEhXvj0Kml5oLSa1VA-D9irKtWYcEDHRTTSjtogpqG9-XxezFT2ApL95mdaX56cXZ9L-rNM-7gP7Ru0WRH4J1ZcK076F2ukB1C7xzXcgnv6QoeNkkwKcT6whvrUgNt_eu_B54a4WFSHQjfoUm0hqQIGLoYFgMM9sJCy6QBKIKoCQWXXKrOWnn0_uCDjRa6biUSs4UQ63iwAjbx3xd9r5wu6YvSTx_kgjLjATnpQF1pqtSmR2RjCA-_tNnWXeR2sTuz1cIi9TnVT_Sa3QUu-crfOC9W4IYbkK3DsWW2GUPWy3IztBl3z10ZaJ1HGOgP8QKwrho3bfu0B1mtjN0WUjhUUhoA3kpDUSQsUoNpIG6SQOZNRBtEqCwB2pAxuOEDg8VR_6VgC7RckhGZySW1jAJuCpuCQVjI2IYuBpVAuDSGvCCq1hPLf6F4OLPycN0nHMBiJrFSyuhN-ihPAwhGzdECAidwAIJEPnhPGyY2W7U2oQ3ApgoZYwOjQklzBDU8rhvAxWjDOQW6oNixhxI7WhMkmHM6FC7KNQllUNEFtNbU0ZlJTRMXGijB2FWqETEk5ZgAlCqdZEl_N-B2fTKj1eLRVFWQ_G6P7AMBHHMjqB5raISxQARcVhoSZtIGadZIiTkNgc5Mq09hr1cKyGsEaxWy6Dhoeyk7QgCsqMV-DbNsheXqzLfDgLeCIJHqz95n17fVB99-LefiJc20tCPbT2S0ayT2WsrRF2gzlya_1zPZTk0FtaPn3pXXbhqZ4tYi6bu05B7Gv9JDjHZ1tqu7X5YVMi3VwVAvbuvSy0EXyzWQmnnEKiStabce-N7-mWvTJPlW0YQe4RJJVRrH24_VdIJi2PPMG0gLKGEwR4OhEaiY2RYEWQ5dIPFT3qQ9KWJiFuPlEKbCykZ9oo9Q2uriY_1zqAmlr3a5EoQG3e2NgYCHnTfrpaEKUvX8zvzs3Q1_zG9pVcK5DbeQgQu08xyokAkD2U1VMWpDdunCAzCHAF_HkxrhtndhwTbjDNIG2G4lIIDvIfhgEPDNBu82nLBqG5vfnW0lcJJlI3pvabEKC1CTdZ6mGYwcQce202hQawkFCTO8ufsLLHdZGR8g-LRt40sLLyM2MiFS7PrVT45Sb_42WQNnU4qIoItsgNr31-cI3AbhDx06bmREoyEmKcAYojdTqL_yiamoXIgpIkxoYGvDlTSOlHN-sWt1Nyi1nCuBgKD2yYwVJANDCZlO9z24yK0EJqnyAbFVmMtDXvelus_ExhpllauvCX0x91AYAmLiRRhTEpJhWHMPun-gQjiLZZdFrTHGjA0pP2n3T8IhK_BWIJRUCpJWvv_fW4MBNON9jEN8hO2OVgRfd4rA6erLLvwaQ7qO_VzH4jN3Vr3OARQRgoVH_ht2euhGB4O3rhhch2a55nDtiA23ywWZeGmN-NVuub9HT5pLFtM1damYjtdjggmay9qFvuQT5-mXpZHbuGmbZxdNruHRkDHgqVpJbTcr1-WF356Uwv03XdnGko0NOcVhV5WTFN9WLqnCacNWasscqMJxxK8jUuOb5Ed510LQBtnEyLIFkMhmFWrBN9Y3rcAIhG8cSlHKsDWaEm5aKsl6wy9z2WuE9M4aYS7WlAIfd7K3TZ29zgMsSkaGcEKAp8t5Yp-55ZvUxk1Q35yvoHHxu9eaok1Idg0GrKC2a-bHsAIRCtqDb9HZEB01es-AFE7HFmExw9zgSomDdhzfe3iws1c-SxNLaUSGSs1zoWg4YKeUEwd2NTSoDtxiwz7AjRJRBGhrWccY58vi_IyBGc1nrr8TX6d7RYvKuHxbTfNFTZfU8Op7NTxB7a4mqVr7ebG24ObXEyKKDDWZpaPo6K7wRVIC1c6zHOcFRWh637Ac4QGiH8i44ubSksmsaGhqTyoDaNpImJJq6mA6KTIM9qq5-1Qhps542lRLMCBg7t-1odwKEjjrQs-GzMPrRjRsnP8YapQ1xK5-n7r2PqCUq-kwkycVNYT-AWcq3R3yU31ziyPrjrVnvC-nmAtVOO-1YVfuLS-3vjgwt1ibB5-8EE8akyhanBx74I4YDFQQCMXjpA3igs3_fTYh-47pFyFSzr3Hsg1b-zpAdvjgezrAQi9VOreA_W3e6AfPBjEOftd2kZaaVxe0bLmhURJZp6gmfgW7VKBwnCO1EsIl4fSTmMbtDN4iMynFaH8KQKscfQTmiF1I1qEfgP70fprs7R_h_oS0F5r9VXHn6mfFj_w5YTEingjwHu5ssKg2IinvZtAWcIbBzgo3fVpgjDyqb0B2xTwNjSsjbGi9c5A62mLamiVsAJgayRINvOUVxNIIpvtEaEtEQwE08gfHecbl3vGuegR56JvnIdW-EOc03XB7fVGAZeKxqW_gqhy5dtidgt5My0--_I2cGZQgcmb2eewFbNuf6S4d2jusuw7nArN58VRli7CxHanvOaZHmGSsHDsyGVrz7a1_x0ujsTgYjawUoN8D6U9uP890G53_1tvvQCkDdMALIxz02b4V_xhZ-J6pVX83g_shYYI1pRDuqlB3WoKm42GEAfbN1Jqi6T1NzSrPyC6102LWb9utbRdN4TreO-hs7CS2_BgzwePxi1ZG_ZRax64uuYD4NFgGMxKFDXoeuyUego8htjtBQ-qGvCgUjNpSFiCAQexPFGN0s5DMtVgz9ocDDclExE33pQMd5gM1eG8eNjhEFaz8eISs8Qazmm4bin_lXi7TPPbp1ejM_eltYfEt3pUKrQ0jIaoIu3vYu7ta0gZX-qjgAm2USOA93CoTdluO5GUOlHx5YRgTHMjQCc4f95myabJ9dF98nfs4pCXNaCtmYlC4ygrVrM7UyENkr6dE65QfM1WcLDnaHrx-N5KfeVCAouheW8P1Y-yceINSs3DexSE2z2H1O2BqxIWcygF5winiAnGLBsYuI2GnAwygoWzCsKHBq5KSJx7pQLpB9fRIZ3_kMD9DU98dGXp8mpg_HIWx2-Zzv2O-OXdnT9GjbVb8dvr1V4Dbhy5se78vS2KkN4f-9F9GSy8b062k6zo0XAKdw7j5TjHmHN3HgxsZPcE-1N6yCwY7873oZOw5Yr857iieu4O77c73Z39QKC2N0f_c1bE9FwR1m9FaLcbd72hNTk5KrLNF1d0vO7PGerjvRObh1fLqpiny7oyTC56SGSM_G3rawrw1PImXbw7xt_O3nzY_HrXcXDlqr4Ms7HwdXSzAvWBT0SRcK3w0fdwoAxwHnohL0dVUblwqR4pXBBD8alVnhUu9-GrO1g4L_727f_FCi7y1kMAAA%3D%3D
line: 0
col: 0
error: {}

I will attach the Loadout event of this same ship.
I will attach the EDMC loadout file written when docking.

Where is your document stating the JSON object I need to provide in order to get my build in Coriolis?
[Anaconda.2018-02-07T20.55.42.txt](https://github.com/EDCD/coriolis/files/1704865/Anaconda.2018-02-07T20.55.42.txt)

[Anacona loadout event.txt](https://github.com/EDCD/coriolis/files/1704866/Anacona.loadout.event.txt)

**Comment by compro01** [comment]
I think this is probably related to #195, except I was able to get mine to work using Chrome.

**Comment by willyb321** [comment]
```JSON.parse: unexpected character at line 1 column 1 of the JSON data```
Something is wrong with the JSON.

**Comment by triccaj** [comment]
I see - do you have a reference model so I can amend the one I am attempting to import?

I am using Chrome and updated it yesterday before attempting all this.

**Comment by willyb321** [comment]
Yeah, you can click on your ship name in EDMC and it should import it.

**Comment by triccaj** [comment]
When I do that it fails with the above error? That's literally what I put in my first post :D

**Comment by willyb321** [comment]
Ah. Not sure. I'm fairly busy at the moment (just started at TAFE) so don't have a lot of time atm.

**Comment by triccaj** [comment]
No worries - are you the sole dev on this project :(?

As I say if you, or someone, can provide an example JSON body I will manually amend mine to match?

**Comment by willyb321** [comment]
@strideynet is the official maintainer, I just help out when I can.

**Comment by strideynet** [comment]
Is this on the beta?

**Comment by triccaj** [comment]
Okie dokie that makes sense.

So, I have run my JSON object through a [validator](https://jsonformatter.curiousconcept.com/) and it says my object is valid JSON.

So I did an export of another build, and provided this validator with the schema URL (https://coriolis.edcd.io/schemas/ship-loadout/4.json#) - and it says that the scheme requires invalid JSON:

![image](https://user-images.githubusercontent.com/19332692/35964917-106d3ff0-0cb1-11e8-8946-b03d67bf2f86.png)

@strideynet This is not on the Beta, this is on the current Production version

**Comment by strideynet** [comment]
Ok, I'll take a look at this when I can.

**Comment by triccaj** [comment]
@strideynet many thanks.

If there is anything I can give you to help let me know (I am a Software Test Engineer for a living so should be able to help)

**Comment by strideynet** [comment]
Ultimately we are changing the import system with the beta, so I can't promise I'll spend a lot of time on something that will soon be resolved.

**Comment by triccaj** [comment]
Oh I see - well if that's the case totally don't bother!

Leave this open for now. ONce 3.0 drops, I will retry. If I encounter the same issue I will update, else I'll close.

**Comment by triccaj** [comment]
@strideynet ETA on 3.0 build to prod?

**Comment by triccaj** [comment]
@strideynet I can now import from EDMC. Loving the new look and feel too. I'm closing this bug and responding to other import bugs to see if they're fixed too.
