### ISSUE TITLE
links broken to eddb

### ISSUE THREAD

**Issue by Kurgol** [EDCD/coriolis#202]
Now that the EDCD services have moved to *.edcd.io the "stations that sell this build" link points to the old coriolis.io domain instead of coriolis.edcd.io.

**Comment by AnthorNet** [comment]
Both domain are valid and use the same version now.

**Comment by Kurgol** [comment]
eddb.edcd.io is not serving pages currently
eddb.io is 404 currently

So which is supposed to be working/default - because neither work currently (when you click stations that sell this build).

**Comment by AnthorNet** [comment]
EDDB is under maintenance, and eddb.edcd.io never existed.
