### ISSUE TITLE
I cant import my ship build 

### ISSUE THREAD

**Issue by scotty113** [EDCD/coriolis#203]
Hi, This has been working fine recently.  I'm engineering a Corvette and like to keep checking where I'm up to.  But last night it started giving me the error page. I'll attach the details here.  Im using Chrome and its up to date.

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAKZ8hVoC_-1ba2_bRhb9K4aA3e4CCTHvR_aTH1Xc1G69ltF8FMbSSB6EIrV8OPEW-e97h5RlDSWKlFK3Xew6gWHL4p0z5D3nvka_DmaZtYN3MxPn9s3ATQfvOH0ziE2ZTB7OzFM-ePfrYBSnBWLjkfu3FdXv5X31kv85Ts00LYvBu0HxOR28ef79J7MAq4O_ndq5y__609no5h_Dv8Ofk_r1mZ3azBQuTcYzN38obDb4-ubZLg7tztIy2zb83sZuWht-v2HYJVO7tPAtKV4se9Mer662wNq3kBcm81c0VxutX18tU9i8uC_n86d22MfY8kgX6bSMbXXfT7OF3zv89DHNPv2Q3GTpPLN5Pob3uJmbVDeweufPZTFzReGS-dDZeHr3tLTjCzuzycReV--12aU1cfFwXcaFW8bwu79s6vJlbJ5-MXHpkRAqIib-AtAe61doRAXjSiuOhGQAbtc6339ZxmnuHu2tzR3sGtbcZZtFim6YRpHkWCKmlOaU6xbbP7rEFm6y1zJFEcaBZaHBKuaIEslli-Vrk-c7jDER6dAYp0hJzDHiiAvVYu3uwWaLDpxvKY4437CNI4o5U5RzIZRU_uHbZA47rh_O888_ACcpQgSjl78_-5KNbWJPPliTgNnMTtzSXtlHGwOLn39fvbX2pfHp9NHDmw7WnuaX2tIATBRimkq29tLhC2PP0-zRFoUdr2zeWjMp4PkDhDQZvCuyEqwsM5dmrngCWy_upJSUGCPpt3qW3t_HFlcM3I9EUsIQXiOpLxwDj57RuDR2eefqyK_6fXUDz9N4RayOlRmShKxXXl1c5kW6cHm9_Jm33WvpYQZWRg9uVlxk_m4dSevh6AKoXNyaYpeTNViGI2AYUQScGHPV5r1g8udl4RYmbmMFjxgKzDJOtURYUyVIG3l_SAo7r2_FNhkwj5QIiKYYphxrIANmGB9G27eURSLcOGWCSIWIErrd2JdhaeMbm30oF8tdohUxHN5NwgAcERxJ3aaHN-lnm11k5vMunIRGKMRJKGDEAgmKhejQAIy2NWAIgXACN_lkaLLcVoFlrxDAwx5fpcn81iRz20MGBOxXrikAz3R8CbvMpt6H65RgfB7DU-EtLEAve2VYS_Cbigxw3-9M8qmbgwCAchQAeL64Wp7Xy9NOEiouZbX2ZTm3lyabLlOX1FF7PwKhsNYvSni5LMZn1iyuTG6z8Xu3uDfx2NvsvAESgqjkYgsD-WMwXJmseSOOEaTTxSI9j93SP4ydLo8jgcLIr6gGphNKOMa8hUYXZmHmdrcYyaYYQSKhGYQJjMhec0D1kZ2kyfS3swsBP3P3ZZG2cp6pSOrQMIR7Kfx_TlhX3BfbnL9LpyffQc5xcgauD8nkdyfXk3-WLunMAj5as4Sg9fOjzSYP_vH3SwSYwIHrVVnkuUkSsLVyvsqZOr0PdJNLHy_yJcCCeNN0sNXr40maZVVSOc4fbAw7Sco4rpzWzeyoXC7TrOilHZjrQDs2rt-UD9IJXWiJqUdwbVxSZwJ5LwRIh_JZX1stLvtKJ-MICawr2l7bqSsXvwNvSUQavIV4ipHCnCpyMGt1JGRIAi2E0JDWEoLY8aw9zm43azmJuAgMc8Ih2aFeQVvlYF_Og2kkQ4sYjAG7MMCl_L9CB1CXDtTe2UMIEFbfogMNFpBXYwGLuG7UrQwphgSHuo3TFj-oS6MbqM6Kumra5Q8RDz0XcnQhBSIaHvbhYZFBdhoSAdyUSq6wJFofT7Dj7PYIiyKijXgL9OKICVBNyg4rADCOFA_LCdApoqGWoMBZ9n9yHUQuF7vCZE8I96nOJZFhjL2uLri1Lpml2cQufDOuR6zdaBRoyJB4gORogkOtH7sc3rG3OQP1Im9wEQpIpCTy3Z82J9_VYTudTl0L4SGkCNYIKVDdQFnCoSz6tv6ajmTYXgMRkYxjin1tyb6hv3ac5dZCnUa0UajDF3iQhHuBxDf017pwvmp77RKYEzo8eMPj00VZPHWTX0AdwERYY2_ZO5JAN5CtFh_S-15tNvi3RvF84XhX5-8Xd58ZAHVTZsu4Z__rJjbgbMDl0-UyS83kYVS6uofVcXckoThMoWtToZ0uDIxWHda6O_MSnY6VlVUFcG6WZtLW4sKQKzRiElS8HPJTpQlp5Xtt-dbWwWN3x7vZSEYcilXuG6VcHcZIDqhC2jCMJaQ2jIPVtjx39AQhcfEa219Z_s23X0fl10C8srwPsYpk2EikEFnALhTDUAJ0df3UjuQE8pKLzxC0uxt-TY8fX7r5wzCz_yoheD316gCSJv-aJr04qb7FLKEaQ3TFazp6OhfHEtE3w7-fwdtctZ3diSbmjUTTD3SwwozIY5rXDDeb15ANQx6kGGUSM3HgzClSMmQgh9vOKaMCUux9XeY9zgxxlolGnIVtQzBkXPOuaIj0tstdQhQ4uTOJ6-Vw1TMdn6UpsHnay8mQ2OFky8pMD_fCG21mAvU_5FV-j7dmao7W-L0-IFSkwkkh3FuNJYbyUByswrKhaSgimnFIQjlnhOC2MnNkkzzN7rzsFKOJSU6Teby7jFURCT1WYkm11ERBLadJV3Ykd0iQM4k5GaZZUSa2yydqoCu84ys_mf9o_fd--sND16jN5MfLTjX7x3UPrk8GgiltIHjwz-A9pIeQGq0EcNXNo-Mh1IvdjXh4uojSNRrSF40fiFCyA805hIOz57FI79ai8pM8wdc46J8Ex8Z5k468FYoHisMBUX3y48w8bU6ocPeEClQIVHKNgffFIIQUlAcYbu3SuMxmB87IQPURrw8DVBBEnfj3gQBZyvacbDRJ0-Vm8dCNQWpBsJBrCLIvBO8RLPSIc5Cm9NZMglkd7tRwECaE1gDUy7mdIyfmXsmzqZsAVYcQMZP5lVu4YqdQygiF0VgSTQmoMcLwJdpH6Btr1LPVHUG50Uz0U2qu4L5B_cc0PbCUxjISYWcOSz8kYApJ3RqA9o6nKQ5374-oQFzmkF9LpcRvHSXo9mzavdzFQ8bU4Pxyo3itvD94JLUL9aYhqArlBO06OtZZrRIdqtGZP9z1rEWs77zJN1jXSoRRdTHtoYZSUhr2Ei6y1B95SYosjVeyVFvrLQhrKAsTx4eMzn1bU5NwbG1yN7l2ee5iWwnD0H2x03FlunsIR2V9eihEQv5AJHcueTrwlnBMAyDnD2Y2u6qOXEK88Aa7Hwlk8Vurk9dIdFmzS48Y0RIxIAgSB1Y6KEKh_PlKA_IyhjUV7fL3pTWt5SSSLFBrwCUo83UY2MbHaKDUkQq7tFIryhHjkAS2ngD02Tckg23KD0a1bhjVSmsskBK_V_b9o4vjjybznbsV3MMklkBNGjpu5hb22ZSXFNRXUiDFkIhseTB9DQ-mEW-ciaOwEQyuxyDjPLBOaxb-GoozARWKnw23noTb58JMNo_HcMIQwRwJikAqjnFhzUKYONJMcUWZolAZH-fBikBJGthUhChNOBOCU_U7ufBH88ke6buEh74bp-V0h-_2qBLwKhUKXJf1lH4doPDdq5FLPr2of5lltugXBCiS2xTifxIcoh8OEsbkG3gEC3PjDaymawchwSArfAuKPLrJ32v09pZFBDdDJMgL1sAOoo5oMG41uBHiHBOpKEX0W87Kv-VNYUBcQQiiUDpSjQ-N5oQ0UBKCOMaUktZjfX0meYRGrHHmwp-4hbqGMdJ9Yg7tOCV74abu5BcD5cDCdE_w6z5G3bzMniH3m-Nt5N7en0NLB4VIwsSqERA4s3rdQfhb2gxHUFAiDCmQJL4t_U1D6rc4Eo0EEAvI_hRU16o1mezl2ARMNY5qQ8EuNXhNe2W9N4iKLVYLghRjEPbaSdjLvWWEGwfrIJAqCakr9nnE_5p71_Oz3p_JAHHZOAm9ujj4TEb_qfTXfZ9veXlCvw4eSn8-BrJ1Aqv7owLrj2n5RoHCEsONKdLCwLuUoqCmgsArZRKnJrGAXCNGJf369T9Ulq5ocTcAAA%3D%3D
line: 0
col: 0
error: {}

**Comment by scotty113** [comment]
I just tried changing to ED Shipyard and it seems to have worked but this error was showing as soon as the page opened.  I wonder if this helps?

API ship(s) imported with errors:

* Utility #2: Unknown blueprint "Sensor_KillWarrantScanner_LongRange 5"

**Comment by triccaj** [comment]
Hi - I already raised this [here](https://github.com/EDCD/coriolis/issues/201)

**Comment by scotty113** [comment]
I did notice that, but I had no idea what the result was.  I just reported as was requested by the error.
