### ISSUE TITLE
Import of New CRCR Failure

### ISSUE THREAD

**Issue by reticenti** [EDCD/coriolis#206]
I'm reti on discord @reti if you want journal, I've already provided a picture to discord channel :]

Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIALhGl1oC_-VaXU_jOBT9K1Wk1bwwVfyd8AYUFiTYYWmX2bfKJG5rkdpZx2GmO-K_r5PQjzQtCR2hQdo-QAn19bF97r3nXveHNzFCeMcTnmTiyJOxd4zRkZfwXEWzU77IvOMf3jDR1g_GQ_mvQOXf-UP5qHifaB7r3HrHXma5scJ4R8tnf_C5s-wNV89V9cCKzD7k0-nCe35-PvLmOs4TUU50YuY6N8W76mHxroEPwMDHIcJ4ZfB2YWdajavR4zvBIyufhJtQK-_YmtwNTI3URtqFG37kPfEkd-MAADAMgR8WKAYi4glon5pSxghYTV0OG48Mj8X4PJG2fVa_mO3CuOHDmZzYgSmgusm-avN4pW6NnhqRZWOHQk5kxK3UqtybL7mdSGulml5IkcSjRSrGF8PBl9TKOU9ueFZ-KpZZmvDFfTWXR0jf93_z1kvuE-Km32XrSlkxrcA2zHwGW3b8frDPzh4kn5G_DQXtsXCrvwkzMPxbFySgD0ixo0JNpRKiJM_y_ZU7MuT7wPfX_38h5YVIZOQW27vgJhMlO42IZCquxZNIvGOy_Hv5-eFgfK3V9I6rqfBWrN1LUIoBhCuWuL0dX7qlmbg47dKRyPgscTtF9vDFXy0QYxYw6Lsps9Qhcke9zYyX5-NJFo9ngj-54SpPkpJnuUhGXD12cCmKEfFriJeDN_GiVn4HhLHSo665mYpLbuJUS2XBoRwfyMwa-ZBbvY8TCPT9sEZOGoTgEJpTf5vm-G0sZ0E_ADUDEIAg3HgFB5AewX6I6gtkPvPXL9DiAZA2PWCk496n0Uz0Tt25uvj8qXcT_ZlLpdpc4avgqYu213I6s19F8bODP-AQ03XUvEzt-CZPrDzjSjlbv8v5gyNwyZhWhyA-I45h7f4QaWN0VjhcNhNJsvaKOjPhuzITBVvMpPDXMJP1Ma0zExK8wSEfH8ZMn2wxMyT_QzY2WIXekVUNLrBDKEUaZt6Y0llDFEByCId2LOcdCYQ_LoHkRAzzNNXGdsrXgLBavt4YX6Zs3FVioCD0ISwg3HCpzsuNzQ7lbzX8UnB7x63oEstAn-6hTWXLSdxbYSbazLmKdlnEDYO4zeArmvkzgH2yJXbZe6vm1zUvbGhe2OYisOki7hwn7hi16d3yRLZG1mqvXDwybnVdFK8f1hXvi4GCirQrFQEGISOo9IcbEct8XleQ7X6JUM0vTwWfX_NMmKVXVlbbZTcKIWM7YMBfBOM24Uq4UnpxkqZG82g2zGXlXy0FK4MI1ANFZapup03WYxSUKEqerlPUz0WJ7IynPNrnPbCPybYbEkRDEDiugdddPLsT0ayMvzsSDu0jWq9EKaI-IsAlliKqsgOcFLs6tGbTWcIkRO4HdIb3mRwuXLKav8c-vFh-ZR8w6aM6ZkwQpqGTgsQnGO3dhyplvgfoF8s_d3gt3YBgh3hwumHwzdUI7Y2AbQcYXzrJcGHEP7lQUbc4CUE9TjZMFhGTdY2YgYuWjJKVcxbObQ91yyJtn0_cx2S5mub2b6cid67BAakRwK2UDfvwjf0k2Ej68DW3fYWsB6RXP2yS6FIY3htxJTtRqDyml5aliLvlV7qDN2lppwNjNkI58X0KQtqhhE7XU0RaJw7oqoi-4zE_OPy_KptwoyCgb-MGbegutE93DYVygmhUBBs7jLg6UdNEdKGbI35boNkhwa6F7J3NRK6mbWVJBeyNZYmLLbie6isz2dtEGHICJgRlIC37_KAa3q41AoTCjb58AeCsasLogiB6cuY2Wt_x6HGzQAGtjGUBYGQFB34sOOhjwcFVu_ajwCEfCw6tBn8UOGx9qdZ27UQpCxrt-aGLymllo6tzsxAijFYIgs4IGIRBWENwWlzinfJFaQJWAGB7icfCqmFdzh9Wg7vsACIbPZcyuFkn2bg51fHCyadIPwmzKIK4cmXWSfxUdAvi9ltARAiripuRVIs3lpsEhLU6rxBQQ6ker8sLVIdjlBsj7Lgw3SHuMtjAcXB7-oZ_35vNurcQX21MkIYG25tnq2Oprs92SDBA-2FY04OAhmFbk4PtkPKSK9670MbmSrQpsWWS7X6xRykksH7kZ4nO4yXtCjL7XV0xpG4FzRPv4IzMFZaA1GD8LZReojjlmYw6cg76L-5Yw9AhQjIGggDXMJwoK_9Sj0p_U8NZbmP3uxsKQmBQxqR7R2-R3GsZdWhtBBC7cnWFoBx1W0Tke1FO0OEq_nnrSwRuTDaT6dWguPMd3d2cvDxYSveyc9I7_54Wfrim6w9vlhc3TDjAwEkwf-NbDSBEhSqj9Miz2nL3IYhBgBhE7kmuEu0sFnTGBBbe_x9Uz-jJkSEAAA%3D%3D
line: 0
col: 0
error: {}

**Comment by Geleybear** [comment]
Having the exact same issue! Although it seems that E:D Shipyard is working
