### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by awdwyn** [EDCD/coriolis#208]
Using coriolis in a windowed chrome-app (via add to desktop link) I occasionally receive an error when the window is resized. Usually this is when the window is snapped to 1/2 the screen and then affected by another window (pinned on the other 1/2 screen) or by my oculus rift coming online (adding a second virtual display?). Refreshing the website reloads correctly.

Screenshot: [https://imgur.com/a/nn2Ro](https://imgur.com/a/nn2Ro)

Details:

`Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Path: /outfit/fer_de_lance?code=A4pktfFalidpsif37o27270s0s0j0404040404B25d2bm32j.Iw18aQ%3D%3D.CwRgDAzATG5f9oKiUIRA.H4sIAAAAAAAAA42SvUoDURCFJybZZJOY%2FcmPq6BGsxqwkFhamcY%2FEAnYWMbCPqWFpYWlhQ9gmUewkhQ%2BgA9gsYhFCosIFopxxjPCXkEUs8VwLt%2B5w9mZS5wloo80Sr41EvFOUcKoQiQJ3lCURMkOUJ0AqNqxgSa4Gt9yakDlAotUrvNEgR7rVw5MSZ4xpva7iH%2BXgfO8BJO2kxSvKU8p7wzBe48ikub1%2BJbdRdecWyRaULWoaknVsiqx%2BCh2%2Bm6DaHXnRWR6bxYoy4cxGmn%2BVP8NnS89IutW89vf%2FCfK%2FY3yfGC6zqGkz9DbGj6LBJq%2FfjFA%2FsI4pkk%2BNqM5eULq5qtIsx8BFXnToHtUv4e%2FDHR08%2B0thHD%2B4S5vm4U%2BYLZOpFtVFbQsolCVeOOY%2FHFMJd43cXTrXg37CbtTQGXejd9PQhee0ffT0HHUdFNS4RXT%2Fwa1qLc8VV8vJVQlQr99nwRqwpy2AgAA.IwelBYQBhAOaQEMB2iDGB7ZATRIxSFA%3D&bn=Bounty%20Hunter%20(MCs%2B%20Beams)
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/outfit/fer_de_lance?code=A4pktfFalidpsif37o27270s0s0j0404040404B25d2bm32j.Iw18aQ%3D%3D.CwRgDAzATG5f9oKiUIRA.H4sIAAAAAAAAA42SvUoDURCFJybZZJOY%2FcmPq6BGsxqwkFhamcY%2FEAnYWMbCPqWFpYWlhQ9gmUewkhQ%2BgA9gsYhFCosIFopxxjPCXkEUs8VwLt%2B5w9mZS5wloo80Sr41EvFOUcKoQiQJ3lCURMkOUJ0AqNqxgSa4Gt9yakDlAotUrvNEgR7rVw5MSZ4xpva7iH%2BXgfO8BJO2kxSvKU8p7wzBe48ikub1%2BJbdRdecWyRaULWoaknVsiqx%2BCh2%2Bm6DaHXnRWR6bxYoy4cxGmn%2BVP8NnS89IutW89vf%2FCfK%2FY3yfGC6zqGkz9DbGj6LBJq%2FfjFA%2FsI4pkk%2BNqM5eULq5qtIsx8BFXnToHtUv4e%2FDHR08%2B0thHD%2B4S5vm4U%2BYLZOpFtVFbQsolCVeOOY%2FHFMJd43cXTrXg37CbtTQGXejd9PQhee0ffT0HHUdFNS4RXT%2Fwa1qLc8VV8vJVQlQr99nwRqwpy2AgAA.EweloBhAOEoQwHbwMYHtEBN4hARgkKA%3D&bn=Bounty%20Hunter%20(MCs%2B%20Beams)
line: 0
col: 0
error: null`

**Comment by Reaver01** [comment]
Also experiencing this issue on Chrome desktop:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Path: /outfit/type_10_defender?code=A4putpFplndusif61f1f1f1f0t0t0t1313040404040404040jB7fh3cm9m72b2929245i5i.Iw18ZVA%3D.Aw18ZVA%3D.H4sIAAAAAAAAA42TOy9EURDHZ%2B2DtWuve%2Ffhrngsez2yCVn9JiqRiIhEQUmhEYWCZAsSEhKJRkhUCoUPoFAoFAofwAdQiEohohARjxnz33BCQc4t%2Fpmc%2BZ05M3NniOuJ6COq8r6nkjivI2paTxK5M2p5Zwmi4ClEJCEeBhkCuabSgFMnySK5k4j66zhnIi2rOJNvIhn%2FXSR75BD5d2Gi4nZayTC3GrIKMngVqb2UWc0qea0eifAQoAj8s4%2FqP70VkShXzNUNlTiuNkK6IN1Ip2ephai37GqQGM99415zH9Fg5VkkP96urgaehiuMSDsqpX5AV9oNf1MP8wgicRuo0QZK2EBJnjLVdahEZ%2BNEscUHER9S3L3TFjTZQCkbyPmRU%2B6vnJptEnd51Dx3iCk6jn0NgAvLv9TXA1jiWZNpazLDI79IBwPklVe%2BoM6bBYWyNlDOBmqxgXye%2F4ac6r0OHSavfHGjbc%2FzhLm%2FAD%2FWw0VhQa2ZHVwy%2FgMUfqpmqtCmECwPeABLOq3JAg8Ych8k9jKFxF1YQUVJ6eYx86u3VEJHmnNtOX38774CNvjlRUsoWpNC%2F36fett57n8EAAA%3D.EweloBhA2AWEoFMCGBzANokICMF9A%3D%3D%3D&bn=UFE%20BIG%20MAMA%20(Biweaves)
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/outfit/type_10_defender?code=A4putpFplndusif61f1f1f1f0t0t0t1313040404040404040jB7fh3cm9m72b2929245i5i.Iw18ZVA%3D.Aw18ZVA%3D.H4sIAAAAAAAAA42TOy9EURDHZ%2B2DtWuve%2Ffhrngsez2yCVn9JiqRiIhEQUmhEYWCZAsSEhKJRkhUCoUPoFAoFAofwAdQiEohohARjxnz33BCQc4t%2Fpmc%2BZ05M3NniOuJ6COq8r6nkjivI2paTxK5M2p5Zwmi4ClEJCEeBhkCuabSgFMnySK5k4j66zhnIi2rOJNvIhn%2FXSR75BD5d2Gi4nZayTC3GrIKMngVqb2UWc0qea0eifAQoAj8s4%2FqP70VkShXzNUNlTiuNkK6IN1Ip2ephai37GqQGM99415zH9Fg5VkkP96urgaehiuMSDsqpX5AV9oNf1MP8wgicRuo0QZK2EBJnjLVdahEZ%2BNEscUHER9S3L3TFjTZQCkbyPmRU%2B6vnJptEnd51Dx3iCk6jn0NgAvLv9TXA1jiWZNpazLDI79IBwPklVe%2BoM6bBYWyNlDOBmqxgXye%2F4ac6r0OHSavfHGjbc%2FzhLm%2FAD%2FWw0VhQa2ZHVwy%2FgMUfqpmqtCmECwPeABLOq3JAg8Ych8k9jKFxF1YQUVJ6eYx86u3VEJHmnNtOX38774CNvjlRUsoWpNC%2F36fett57n8EAAA%3D.EweloBhA2AWEoBcCeAHApgfQIwUwE3QDN0A7QgJxAFUAxAUQAIAhASQHFGBZAQV8YAUABQoBLAM4BbAIaJRAY3EBKELggQgA&bn=UFE%20BIG%20MAMA%20(Biweaves)
line: 0
col: 0
error: null

**Comment by willyb321** [comment]
I will have to keep an eye on souporserious/react-measure#104 as that seems to be the cause.

**Comment by felixlinker** [comment]
To enhance on this: If we remove the callback `onMeasure` passed to the `Measure` component or set it to an "empty" function the error goes away.

**Comment by felixlinker** [comment]
I opened a new branch https://github.com/EDCD/coriolis/tree/feature/resize-observer where I update the `react-measure` dependency and tried to debug the problem not to much success though.

If we update the dependency the error is thrown right away when loading the page 🙄
