### ISSUE TITLE
Losing some engineer modifications?

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#21]
Is it normal that after an update is available (as displayed at the top of the browser window), I lose some of the engineer modifications? For example, after clicking on the udpate, my Corvette power plant now shows no power increase and no integrity.

**Comment by cmdrmcdonald** [comment]
One of the URLs you provided previously showed incorrect information.  Did this URL come from EDDI or did you build it yourself manually?  If the latter, is it possible that the URL was built more than a week ago?  If so then it could have used the older binary format, which never made it out of beta but if overlaid with the final format could cause this issue.

**Comment by nemesyssoft** [comment]
Could have been an old URL as I store them to share across my multiple Apple devices.
