### ISSUE TITLE
Shutdown Neutralizer Corrupts Build

### ISSUE THREAD

**Issue by Esync7** [EDCD/coriolis#210]
Inclusion of the OF Shutdown Neutralizer in a utility slot and saving a build results in a corrupted build once that build is re-opened. Optional internals will be missing or scrambled, placing modules in slots they cannot otherwise exist. (i.e. 1E Fragment Cannon in a utility slot, or an 7E Fuel Tank in a C4 slot.)

E.g. https://snag.gy/cb6A8u.jpg -> https://snag.gy/AKrYVd.jpg

**Comment by strideynet** [comment]
Fixed in beta.
