### ISSUE TITLE
Import from EDMC fail on all browsers (new engineers modded modules)

### ISSUE THREAD

**Issue by floc82** [EDCD/coriolis#211]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAPkRm1oC_-1cWW_bSBL-K4aAXewCCdFH9eV9iu1cM86sYRnJo8BIbathitTycMY7mP--1aRsqamDlDTJBkj04EgKWV2s_rrqq-pq_TG4za0dnN7GSWFfDNxkcKpfDJK4SsfTs_ixGJz-MRgmWUn4aOj-a1X9ufpcf-XfJ1k8yapycDrIUjt48fT5t3iGQgf_eGsTN_n7b2fDq3-9-Sf-d9p879KJnVv8k5ajW3c3LW0--PPFk2D6Fwv-E0XPskmV2PpxXuWzrMr9u09Zfv8-vcqzu9wWxQivcbduHJcuS-sr_12Vt64sXXr3xtlkcvM4t6MLe2vTsf1QX2vzdzZOyumHKindPMHP_raJK-ZJ_PgxTiqvExcy0vxvqORD8w1EQmpOOOcGgAopUb9NQ73-fZ5khXuw17ZwRRnjsBvEMx4ZtiKdREoSzQihnGnAgfgW8b-61JZuvFu4jqQKhaNYqZVkIIAbIrYI_xAXxQZ5L7mMzKotaMSl4UQIQYlgxGwRdzO1-axD15ecRUKHsplQmhlQimgqQXok2PQOH7yZqaf37xH2nBBGyfL_F0gb2sSm9uQXG6coObdjN7eX9sEmg1Px9HlxaQOsEULi4fGiKh8Hz7jzY62tM8o0AcMVPKP3jZ3YvIbf6DzLH2xZ2tFC6LWNxyVCAXXI0sFpmVcoZZ67LHc40CldgotTI5U29bO-rp_lPEsWgN-tjQKimHrWZnFzVZTZzBWNWldVPk-6lSB-8Dc5yhlO3W15kXvND1xwb4YX_56XbhYnWzAlIAIZTLsA2Lam3qelvWvUXQcQFREhAdr13vgmoQjE4BYJV9kXm1_k8Zc-mtCIig7wUrkO3tfJg8vjkw9xXlbVfRd-0dKjyyy9u47TO9sDvBLoClzQsqN3-GD5xM92HS3k6DxBO4kteCHLxwNqlOB-9RdzVAnnug2Nxfej22IymvoVNjhNqySpgVbZ5CZO77sRjipzQQKVn26uFRaNwrwT4FooZfzY76o7-y7OJ_PMpU3gOgTj29DE1mDAtgPydzerZs3crYvSa7jUB-GSreGSdeCS8HVcnuVZdnIT5_-p3JpXhRYqP9l4jp5nD2BKTY1ZetV383J0ZuPZZVzYfPTWzT4jjPy8dc6yYqC5pj1QWfr4hP8-IPFYAjMAB_sJjp_gWAHHZZz_dB3fGzqQkAHvQEc9cZ3woEYLTfXh8HC3dljN51le9oprVJggrq3cvxraWKfi0iDF9xp8iF3acMDiUHA2tyMhLq_jciNnlyYiEKBCGsIlKKqBK7otH2gEIy-8svlthubbkr6YSLFwEeDTKQGScm8x2iV-B-18qSMjArJoMIWhoIBRLjGZOIiBkgh0yECNYFQRjrweBOUHsUmDiVBgBWI4VYCES9SMqCstYuvLEHFwizDI8pOrOHGdqVFj0NGFy3ulRRKICZnlQkBdg-jLKgV6EKl1_Xgf7MRVs5_u9jt0t3y3u21mrjvvpaAVP9jdtvDxk6z9xEeID5e4Ms4fCf1LC4evJhPn79pU1jCRoGFZwwiK8UVIg5bBKHlU2ZDKiJow0nBNFGVUaIPJrTmianio7K1FFRqBCIsqFEBoMFJofMv1EWXDbmW_atHwHQLs2roUWczYznzdeo_6oZQauUxYglmTtxf7Q1sqQQLEH-wLz7MkcQVesdP-JFJh0ZYQpalivhYpNaPbeNS-60nydplQcpBEAIAUnCuijltPPDIt5iaROWnl6-RcUiqOWVCHCt-6olQEIe3mCg2hBVeaoTnMMYX4Htr-mEvqCjOq8pfsc49SPGecLhO6pxtHm3YIbvzOwBgj1qepK3vW5q-SGFGHq_vVfJ5n8Xg6rFyToHVYR6FeITNvRIVyepik1qImKAik3H2uyiw_Ls0szuN5PD6-tL-Qdm3H0zrTP07a8LEo7eyv0m0hbZdua8LMNmENH9ulGnIQyVocRLLd4nboBjziIedEf9C1raHXfQE6oZOLLzZJ8I4OX9CG2OhqAceFtr2SUdaGfFuo9we6b1rKuKG-_NCDi879QJOVgW7jYoWU1nr49VceunJ8aeb1LV7mMJY-Hpm47KxssDVcKrErb9mBSm4ipcLghUStK3kx6zh6h74Uk5fU9UJRbejRWZbhEpz0K2LIDbiZ12J6IGbpLo1UgJSoN2KaIabubvq0FJ8Qcx1P4rxXPZGJUPehTYssLw6Eum_umLr5-wvSI_Z53i2eB_dTgA-Ega6RMHqb28d-Ua65gX7rIX915Vk1m9t-W-6kowHAS7x3JR01MmEvPYbzzCW9FdH9FFkI3U-Tm9gl_dTQrJ8aXuJ-OnxCN1P0VEL2U6IWuYcWHlo914DcBMgrh6pYwvaEpBdAv_GwvkWMLrvGDglPZ3l2bzF9vMM_WzYQKCCJaJEnoTjXTFMmJeHboky_7JSySIcNUFqhoQypNxJgO4e0-d3jlc1r3TfLbe17UIa6IjEGqrnWhB6VjQoZ5ncEjSQkgKCY42nFjklGQYWbKiQSjCmFbl5pTmBbGr17FpFWtFJGtLOU0nAMRnIrHZ76t29t2tEhFLHQ1kQwAKUpUdIQTbukD8scmUM53cRFWHuHiTNFhcKXIH4v8ZjS1EuIRFj3IiCE7-kTiGwDXdR5w77NpXUn51NbpXddnOf56b3zy3wH2iID7sF9pO8SDPcj2-JWd3JGaOCs1mg3nZAcHZRS-tm9sCPdS5aVN262cecQ1ujq124p21muZ2tVf7YTtWdxeu_J_SbXo9dUYmT1RTslB9WQTXsUbWWJ7ir5bNhbuEQAnPyC74tsrebDN6L1HHPCs7qZq6HDrujJ1DlnG9C6FNe97ciWvWHE1xOhB1kv6lHGOMooe7B5gaNMlly93XbdEbqZMq2HeNM0QJ_Fj6sPQDvDN-MUCZB61gGaZr4e1SF8abrWXjccZ9m8T0MgX6qgCQYrtiQSoq8OfjKBBzqcYw6UXcfj-1Udus3ABRdsaQXZVP0O9TU7vYQg7SW5Z0FXQ9j6TCIqoHM_DzaXVoaLBped4eGDK8ajS4-wT9b_7RUUWGtmLtDt2_MsRfef1ITMjmuevVJf7c6OkdYAl8_zpL73eWLteVJm5QU_5KTp-m44okfcz1s-cWPkFm_iMf7vpZu5jeEPMwa5uhHEIgpIpxiV6PSI33TaMqfhKNv2518Ci7gMQaLwcRkRgAmWkQe18ICOWLgbDJpRAM2ZpLQzvNINqPHHAlKbnJzlrji5sPf369VUWO8Qd0sL-FwkTie9CKH0OwdhZAis2cx_7_BANPGlpWf8mCV-uhRB7hyGqGGJATjOz7LJ4wWuDx-JH4fjOEWmOno1efDcfNLd7ieIZ6dPClFSK8R7xCswAkKqfJGN7xEZ59lsXqGBUEG0cpxPOs2C2WPDjTEVSn72On2HvSxsdy9LPXE9Oo-VhoM7WUJw_Gx0-m7AQVQAjqsKL6jRcVblRTm6qfLclj0hAj5T7pOBjPN49jmxI_8FipstcXLj0sfjfUirS6PJq3Yfl9SRbDX7aEyoFDeSYvZPDT8gD2c0kmEJCMM9JgpCKDS9AaH2PudFwwIeRIRiTCKaUk0UFwdhlUFEwx4V5tuUtVK-C5d3tSLhaw23F27iTj7GpXcFadqv6NPsceX7tk1wGQA4lOXDIenLDhnHhNasoZB9QxTKiMnWOVUmkWxxLZQ223fBd6HQ16pbrgi40Z5yEoS2PqZDqH0I2CAKBTESGbxRWu4Jb2YgYqt1bx4ZYBLjjqCCb62YdoEb2uAGSbXBta04lT8MuNGVNUwxADf_huDmEWsVrTn6QyXQgyFmKDeHgJtHMjzZTXHJKCEJJnqK7Y1AycOj5148ZhG4UAxs3WTYzQQkPmeooeSILMGk0cZnBj-4f4VvB0FmwkKIP5kjqO_79EmtOcy5UtpyrhQhSBkojNb0COeKRDQsrhljqAKOyCZSEEX39q4MRYTelRlDBFWS4po50Lu2WrUYSL_LhSaQsPV3Gnr1c0ai1VGmwR_XBh8NlaE_uOMWX7c_-uVm8xOJ4OZcw3Ftyy-hHQoIMAYEOadG3k3IMaQEhdPWPhBgiOEGqKc8UG-S7I10FfGw-4vU_IFxhDo6DwpHQB2zVxl2EygfvZTymwqcGPatwb5Q-juBujy4Q7cfGHlYOcWp9f3iQJhGyzNxVNsCCqetLgCECwVDCYYeztVxsGHQgo3C3BJhIxiRhsEPDRv1lWEDkaItN4O-ADAZF4QB48ehpnX0iHAAg0ZDQDLFtDgONty0YCMJ4kYwdL6Y8P_Y3kZ_9cDaOvhltKZMaSWJjyc9Dx71ILukXdEiRIJGrwbCdxqq43q9KFvrnVKKMWGoMAKE1uqgxhUVaWh1iVD0xUz7s-hEHHdA8FCVdxIDrtZqNorhasKUgkO9O3MEB-7W-Nsu1UZb_7ta_7fc8SMuSJt8zNy4x8kh7Ys9y32u-q4r35Px0dYj9OopbQrrvX_PDH30yk-9LG4-8PfM_tzVD4wCirpT3E_qx_PFx8W8TWxcTk-KaTzJviwB9MdgWiU4y9QfjaPGn3h7_o1C5VuQjfId6WVWxniVASW5oP5IWJUmWZz6RiGJaa0GXzj7H53_pYbGUQAA
line: 0
col: 0
error: {}

**Comment by willyb321** [comment]
*checks emails*
We are aware of this issue. If you need a shipyard service immediately please consult EDShipyard. You can import from edmc using it. There is no ETA currently for the update. Pull requests are gladly welcomed.

**Comment by strideynet** [comment]
#205 

DUPLICATE.
