### ISSUE TITLE
Cheiftain not added yet?

### ISSUE THREAD

**Issue by Rindula** [EDCD/coriolis#212]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIADUEn1oC_81Xy27bOBT9F6694FOSvWviaVMgHQRRkHYnMBJtE6FJgSLbegL_-5BSKltpCrHdpDuF8b3n8D4Pn8DGCgFWG646sQCyASuCFkBxr-vdBT90YPUESmUcpFUp_xO4_9s_9EfxWxneGO_ACnSOWycsWPw4-5fvg2dQjud6OHCicw9-uz2A4_G4AHvTeCV6oHd2b7yNX8Nh_PqJH8JFgTKWZ6PDu0MrvlSDcfXB8kaggGY0WDnrg1VrpbHSHYLtAnzlygcjGKH_0VupxaVRSag5hTnGI-qzse-c2cuOO2l0dRF9J0G_t8FLuZMbt7byq5hHhxlFGI3oH7WrrsK9bRPN-9yw6lLxrqO_IABHAiiHiKCip-GFuuP6MQmf0OUE_4dxj04HdDJ7fUxzQiP2NbdbccVt0xqpHUqgQJekOIXgqnXVjQ8_uOadsNV7-V00VbnnSs1GAGPYZ-FabkTp29ZYl5YBVkwicGZ_ngI0S4CgPO8T8IlLPVRSl8QAFlMGg20PnqWCo-Uyp3mPLhrp92-bg09SyTAiDjABPcsKRum0CbxSt0LqjbG12AvtzqsRz1YjWjI48LhRXItI5F3bWsPrXemlS2jMLMchmxNOg6upnzki7JmF-SbsWnbOygfvjE0qCgzJFP-Fk98rj6JYDrXZu4l3SWsOyF5h0Zun4J-lJAvjqS_PW97wxAiQKXYpdGdsd14LCX2BwoSLuGEutx_XMGElsBCr00qIG69V3IV-7D1Ua-MflLiOHfp5l1IF8ASP3hI-ukq8_5K9QuDG8trJmitI_gQavQF0VDRoqNS0kivYtOR2Uqjmg9DC8hc9RxJW8jLPcTYSwcM6SVzLeELkMuxVc8vrx5SVdNZ2CLHsxIAMvZMyk7OMsZ-EQVkb06bM4lMQKM0xHQmcCc7ZAYyLqTK5iPIyyNfBRSo-DpPnVAssFT-sRPZCGa1N_Sj19tLsWx-0bxU0sA6jrJkPwfMauJP68DtrOS5Gkk3W8lCPF8Z0PYNwFzgEgs0HokDwFR74L-FB_hIe9O143IuuE-reyDpBoRQ4dBYcSfRWN3E-3Ms6Soyk-fhZ8Nbo5LcSweisJ5-N_-itdJy-88D4vyewC9ov_LrIEKLxPTg-JRkL6pIFUeaM4yq-ORAhLGoEr8PrVIvAkoV2x-R4_B_KmDw1Aw8AAA%3D%3D
line: 0
col: 0
error: "No such ship found: \"TypeX\""

**Comment by strideynet** [comment]
Use beta site.

**Comment by harakiwi** [comment]
link for anyone not knowing about the site: https://beta.coriolis.edcd.io/
