### ISSUE TITLE
translation problem in coriolis/src/app/components/StandardSlot.jsx 

### ISSUE THREAD

**Issue by Sk93** [EDCD/coriolis#215]
The render() method in coriolis/src/app/components/StandardSlot.jsx does not use corresponding values in the translation files.

An example is line 106:
`{ m.getOptMass() ? <div className='l'>{translate('optimal mass')}: {formats.int(m.getOptMass())}{units.T}</div> : null }`

It is trying to translate "optimal mass", whereas the language files have "optmass".
This results in the correctly translated terms not being displayed outside of English.

Quick list of the translation issues found on this page:

line 105: "minimum mass" should be "minmass"
line 106: "optimal mass" should be "optmass"
line 107: "max mass" does not have a translation (suggest "maxmass" to align with existing standard)
line 108: "optimal multiplier" should be "optmul"

**Comment by strideynet** [comment]
Many thanks, pull requests are accepted but if you don't want to, I'll get
around to this in the near future

**Comment by joelgarboden** [comment]
I'm working on this, at the very least finding what things like `"minimum mass" should be "minmass"` exist.

**Comment by joelgarboden** [comment]
[Initial stab at scoping](https://gist.github.com/joelgarboden/129f2ad59b9757650664b042d5203b64#file-translation_audit-js), looks like about [2200 missing/mismatched keys for various languages](https://gist.github.com/joelgarboden/129f2ad59b9757650664b042d5203b64#file-missing_translations-csv).

**Comment by alex-williams** [comment]
Fix pushed to develop. There are missing translations, which those who speak the languages will need to contribute to, in order to avoid mis-translations
