### ISSUE TITLE
Ship import from Market Connector Fails after engineering

### ISSUE THREAD

**Issue by PrometheusII** [EDCD/coriolis#216]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAI0BpFoC_-VbW2_bOBb-K4GBfWsNXkUyb7n0OsnWGwftw2AgMDZtC5ElgZLSyRT973soOXZ0sSQ7mWIWm4cgVs1zjsjvfOfG_hgtrDGj04UOU_NmFMxHp4S_GYU6j2arc_2Yjk5_jKZhnCHhT4O_DC8-53fFI_d3GOt5nGej01GaaZsZO3rz9Ozfeg2SR9Pt86h8kJk0u8uXy8fRzzdPsvDLZf0Eaet4noemMPrMruPcur--xfb-UzSx8dKaNPXhO8EimOksiKPim1_ybBFkWRAt3wcmnN8-Jsa_NAsTzcx18V1jPxodZqvrPMyCJITPbtk8SJNQP37VYe4swUSOpfoXmPZQPiFjIqVCCitPcupRwsDANl3v_kzCOA0ezI1JA3hz0Nsi_y3FY8WeycdjihXDioN0xRgje8T_FkQmC2bdwjEbY1kRjhmWRDLMPSaZ4GKP9Gudpm0CCRsTXBFIGMFYEM4V8TDdI-52Zey6x1g2lvyZZDRWHHNCPaEEEgg22iHBREt47_Kknv7-BOimCBGMdv_-BCwTmsicfDY6AsnWzILEXJkHE45O-dPnzVdLYPkAiYfHyzwrUFzizulquBPgAjFFPbbF7FmkZ3E01_5G0ger5waD2jganWY2h4WJDWIbgOxTvHtP91rn8d1daFDhLt1KhfA4FVul5UJ_kq-T-yA6RBlGA5QBuhGuKwNvdU7mX4D4OAzSYVovzUyHeJBOTslWZ7HMnwBOjP1g4zzxp-8mkwNUkl-vkv5Sle8KyF_E4YYXexQzJFwo2CjeLM7TLF4HaXmuX6yOlmaY8vcW5ExXwSK7tEB1x_Ly--nllyQL1jrcQzycjxGq8A7ne7jmU5SZZWlsCyHW5CAgnQMpkKK6KftYbxJ_N_bS6u9DLAFq5j0Mh70mw70LHwKrT64hgOb5fR_JwT77V3G0vClOuJ_hPIbJjmxgZ_2P8GJ27s66SBw8_yKEfeJ70IJ2rwchTUBEA51pAibBSdeBsXnuL9K5v3I0PDqN8jAsYJab8FZH9_34BpMpRxWTnxaXmU5pMO2Ft8QIwhnovgoWZponSWyzY-HdCUmG6pD0DkOkgJhMKgIIFxI9-6F9oZM2gXUFO3LyGf5O40bsZDVYXQfpzL8Klqvsm3G_hyGLq8oxPdvn5ydFeqHlcckKMrrWQVQSWnrsSZXLIQnIbnTWlqV4jdPam_8VooDWJsYuYrvek_ZAflnjASL7JHYQ5VvcMFAdRZRegyjZUTTnNWjO60MjaaIRTnEBhxjbk4kOg95krtwp_zaPzHwQGJGsgnEj4BnF9eMQYAgp8ACCK9_ND52rfC8dZst0E8Bw9jm-GxbJudxa_bTQ3-ah1ybTYRjMiP8hDufD4jmkIFBWaPt4liQ21rPVNA9KP-g2xhOE4mqkKEVV5fTZwDArrCgQBaWCDe7yLLYv8-b0Qid61o5z1gjm3e6c3pjZSttlmycPTwymj2lm1l12vVUNL8bdwjoMO0DYN6MT2NDXsWwjrMsy2hAm-tgBNdkBsp9ZfPKf7ybK6sxAa8xQh5Y_2cDwKXAMYQuCWBXqdaEH8QbBnpR0i3vnN0dnGi5yvVvA1wITzdqOj0OZLavxi2Osnv3QA_PhVobviBRd2MKkEXXk6-KBteGh2HKoa4t20LB4wUkTAUkpZpe78H7CU8KjRSnTFzSSnYbWwHGj59r-MxNUr1F00X1F19REEORvHV1k05mOzqJl2EocpGFUL1B4Eyifc0hyP6Wrtdb3fUgpTTs4zSW8yhWlmLSAiRxKEZgxTlHxhlBsJ58uhzRvuARwbXW7t4AdzGCPCwn-eahn98OygnIF_uU6fwuy83ydGDusocJbmnFOzH2QYb8URA5SPk3iIBysXXZo30g6TP2tDsJhuj3SoduJOUzxN_DJdKBm0aG5kEOHq3Z4GYhsplpQVrTcrbGIHIo0J2Mgvhnr0owP0uzGLbigAjEgx4YfSRqtjeksjpNSRnfUYbvehlQIg8StDaTMWIa0nwWlsmLDpY1d-zHKbBz6NybRgW2r3zdy2sxRTIjdftChtrhWD6MVWy4gcMQ3sP_PM7D-HjzllBOxtYANtcDzXPSuWFBugLFt3bHGFpBnBK8IyGNbG_huLveLGl6KU4y3-r2d_mMSiosYKs8UvtE58kFjTqvZP0CBECUlc_MpIV40WuNkTKt9MSY8wZHnKc5dYD6mg0xIdUyFx3BuTHpAhILCrxdM64iqztbQWCAhpefmTMgjXHgvmK4RPBY14RLcmQhFhevLEtXXfG7pylyZ4ORiZfJo2deQAY4Faz-YyFjtCqSNycMyKFHLoGqyHFBZdyaFnzVpMKNblIuhXuY5WOKKGeduPn2uH9v0d5CdZITtyE6Wq4cYgAmn-4m38Hmro3Sx4R7cwz3P6Jd6O4PUYIMc95H93EcH63epk1BbEzDamXDUjH869V3z1o3127rlakyrE2xwAXxozYtq5Qc5pjfKGw0j_sqNet5ew7zXaVFd9bufyzlo1f0uTQYJpZlPc7vQM-PkgCf6t0H02Ot9hFEg4O1Jl6GeDAEbcGvV_aBaD0Ntz-P542WQzuIHYx-fbDmbPzga7O95YogGYFFhUGbh5IrqbkjqKyt8kBaLy8I89WfFLNYMbLm6jfuo7RwqhKi8MPPqFTwAjdSaPkoQyN4ZwgpjTg7EvxBjz6tOnAhlTCDCYF_IMYMCOfZEratIieCMC4UhL2J90anl8seNXp_c6lWfT1ys9GJxVdyMMoeW90xxvCPljwlkoBVpHU6xK-4hDssGEAY4hdNOSEX7BCh3rSdOwOaqk3-bW2uyYZZgicpGZMUU-s8x5eigMCxjlPUcSWGiXOIFvAU04dGjJmmQItZ7mtINuRCHwIfwCzJGMca1_BmoUnlcMBeexVFBiYB9tRteSCLYCK4g_njqBTlor7mvmYHS1gz0PI7TDByztNPdWBkQAt09vwq2q7JcDEPdpTfdRUBBVRlwKsDmfy-wRfUaYLHzWAnkHJcocSyusajjmkiACFQThJOX4foYc_dma2NFK4iGqEcJcTkF4vuTv243geKS1epAyjAWkgJfIKRe6Cjd7___6yje3-0oXi0CECoVVF8USUWQOMpRUMNRlKQAQNfkEOplAYDUzXXVDJMQrBA5MgCwxoUUWk4GmRtVyRfhusfcblyjllHfZTAPTr5Cuecu2ET_29iWx2L7bL2Or_WfwTpft_XBWsrMAwkU2I7R6iV4lxJ5VHIBhO9umLVLvDHupv9tsG4d4nE-5qp2qxPSDOBP1_ni_PWS_joQ3Jx8GkT320z96cF2Oj0s-VcVSDSkHpLxQvQoiP0rHLsJv8bBbMC9G0kY83ZGFKsmrv_91RTyB1Wg5T2NwTeIKcFq1_TeLK7cIL4ZVvv-bIyOYFVaTApdTW2SZPN5c2i_u0d_nFi9Q8yP0SoP4Xwh8AJwpJs9bv-zCKaYeNzz4OyzONOhaz9IyT1OYcPyCIDpboeduv9dgABq_wUbvp5sNDMAAA%3D%3D
line: 0
col: 0
error: {}

**Comment by LFS96** [comment]
I have the same error, 

Import from EDMC 3.0

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAA8fpFoC_72YbU_jOBDHv8op0r2Dyk95KO-ALhwndhcRBC8jk7itRbAjx2Gvt-K779ihaUMParjTvalSNzPzs2fmb7s_o7kRIjqa87oVB5GsoiNMD6Kad6pcnvBVGx39jPJaW5QVufxbMP-9u_dD7rnWvNKdjY6i1nJjhYkO1mPf-CN4jvJhXPUDVrT2vlssVtHzwdoX_ve-nsHbo666WnjoY_OoO-Oe-kH3tDtXkiE2pQkbHB4rXmpV8aK3L84NrwSGgFpFR9Z0YNgYqY20KzA_iJ543YEdctFnouQ13h8ySdI0ToeQ3qz48ldTayNMcc3Vwk8xNCIJi8iyVxFv3NSKE6MfPhSOhoWj01fhTvXjPbdunsLYsHhf1EIqcarroEymDKWEDFFfjLvW6kfZciu1Kk6c76DQZwa85Es5tzMjn3zMO20eLtSV0Qsj2rYAGDmXpXfsK-57Z-fSWqkWZ1LU1c2qEcVZPvveWPnI66-89W9Vsm1qvrrtY0UxnrDs92gIjicxZhkA_JO3C2XFosfdcXSI4wlCW57QJIvf8PMGyyFFYxd4Qt_wcKV_CDMz_EcICZ7g2K2p8BkRPpXr5wvIHUUII7T5_aXZz0QtS5jsb2fctMLXqBGlbMSleBJ1dBSvv6_fz2fFpVYL30DRoAZvNn7CMNl0Iaxt8QdMzVQu317skuK0hpWK36gYtJlggtNpTDHEbBtAgmy_Lo6X8WLeVsVS8CewV11d-1LrRH3D1UOAViWMxmiEvDb2wHEPTPeWeEbR1Jf5pZyLvGsaDS0ZEh7H01H4LfttArJ3ydIpY8wRfOVS9a3aBhGgjI0IetuQ4GQrXyjJ_Pyvaq4EbCqr46YxmpfLvJNWBChcSigeF0_vauxnXx4Y8Y3Rd5NsrZH3ndUmaCEIHi_Eayd-SbLQfIDoEJqkA42bTVhJIEZ2ORpn7gno-020SQpkForbAVzzipvPKu67Gvla4NAk_ZhExjsO3tLYXKhWmxtuFsLmJVfHatEvY5Bu__dqSV-pZc8HDbxY2jvhPoMkk8TjquvdtJ8uNn-QxN48DRNANgY4hRXW17zsFTDtEfYf2DBOM0bQgEB6xQ8528Dphu5ocF5q3WzvGmy_BOIpqDAdEGgogktDOtZhOKlA4Z0LJQxf9_4n5NBzsA9wUEbfyUYSmg2KMoLIQBD3_IEE5B2COLwecJwkA0Hy_xNMWQYniDVAGgoA1Zjg8ZngWjRcuqvEh6qAgKNsOgBs3ff2boVkikcAJ-5GBrfH3kUoQAqtvanCaXD8hMbJOH5uRV1zc6KrFWyIpX4SZuU0GLqjOK6euCpFtb8iYhYjNABhFA4ESGORmsEZQ9aiyjsz56VYs9xItdrLQRzFBqNXCRJ0sY3ZWCVmunyATQpuYk1nXX1YDlddU-2VKrcSjuAWtmFR32pZBpyRMsJYsgHwVleuLW6F9x90D7sTvNEq-ApICd6qxRfj0RXwHMxUSOznnf8EwKpdyuZiBmOXZ_nhn_nLyLed917c_IyWcMh3aAg0FhG29RcFxSiBjRBuMVZb7l6KMTRzjGDJOlVrOE3CpAhFSZzBVvkL2Wu-n6oRAAA%3D
line: 0
col: 0
error: {}

**Comment by strideynet** [comment]
Dupe #205
