### ISSUE TITLE
Issue loading my AnaConda

### ISSUE THREAD

**Issue by bjornthv** [EDCD/coriolis#219]
I tried to laod my Anaconda loadout from ED:MC and I got an error. I'm not sure if this is due to using ED:MC or a general issue...

Details below:

`Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.146 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAD6yp1oC_8VZ23LaSBD9lZSq9g2r5j6S3-wQx87aG5dxOY-qsRhg1kJSjSQnbMr_vi3JXCTAEuTGA8bAnO6ZPqcvw3dnYrV2TicqyvTAMWPnlIiBM0_GRaQz5_S7c2bnSWHLV_Wb5autNZh4iPlUsIETqzl85pzFKkzisQrq9cFHq8YaOwMniZ3T3BawMLUmsSZfwPKB86yiAtahl5eBc548PkYa4W6jQhJ4WhmtFwa3JkryGwXLepkb6lBFfYwJKblcGauWBR--pVFitQ3uVDzV9gCL5LdbpL_T4oUFiNHMTPKhNc-VwS-JfbqKb20ytTrLAvDETEyocpPEFdU-F_nE5LmJpxdGR-P7RaqDi9Hwc5qbuYpuVFZ9a2yyNFKLh9qWw6Tro7-clXHsMukjIjnyhedTCq7swr2Kcz2tHd-CPMGeS-QGJnI9LAlHjFLuU4TIHtA9Lp4w5CLS9BFAqOdh7Atfir1w3y4KHd1q-6mYpzuAiStkAxYRIXxCfYaFxB7fg3ubfNV2aNXXXb4S5vKmr4Rx7BEqOIaDFQiX0dXx1MRaV3lh-foKKASHgxFaf_5PzaMLHZkQDvvdhbKZrihkdWhSfa2fdeSc8uX_y--PhsF1Ek8rwjkvg67cIxgma9ZCbINL2Kgdl8wLRuY_LYL3EQSH7-EuWm-XMuRJT1YUhsO_V_FTj-QnGOWo4cBycWWe1-Zpp3Q8jDAtbV-biR4VaZrY_FjpvElx6ruSNyguUBloYBCjvpAQ5oM4LpjrNfEox0wyzBEo0ZNSsg7eAHG2eHNuoujdfWHjbcrQFmU2Diy4NtNZ_kWXz_3II5qx28Q6KHxYMIGq9HejTPyh2kx2bPzq5Zda5Xcq1zvzCnNJK_cxgihoFFNJMBB5TxBraEiskFsmiZ2rONxlgAAgb-YCzJjHPIEp1F7GOvHfSNwnspkUkesTH5THBYa_DMujMjcHlGbmZkgCLBCRef6hiVu6gjUTrBQgdCbL1gPwjkmwGHyiDVAIFCVlyCQR9Fek17ZW6vAEQ2PhFPsIBHm8IZBXgB7aWGdWJnzfr7RxC9rIPyWPvfo76ZGV6eXCYNVdnkcqfLqwZqwWAerZXt5GKta5souzNLWJCmejwtT66nSG4maVqaGaOF0-MFxlwpojJsuteSzyxPYqMgTTpv0WSBURr47IvtMgK0-49DAhK2fKzeS93ECtWlctT8vlh6XLNSXu1FjZX1Loyt4LNQvdwZWNi1ZlgxK58WB7AEc6zhJ7r-xU56NQxWfxNNqZx8mWj15XFiDbWeBam3fvZ7qIp239s5b-a8cOLpOEs0bYa5hsk3Sku8FijFNU7Q-mg_RqiLopJ7kHFWFlu9wFnF8OJ1whBF9mfYSH1jbxb7dZru-5U3-X1VurwhyEECFyjGn8B0zDEI5wRQ75K5QN9dIV_oZqiEul8BmCAYggSQXmhwkdubzZ7CBU9QxUQL_DIPsfU-095qJmCwENCZVlqyMp7az2P9gUl0PIKEyStGQt-KvH3UIX8NiouctZ5hWmjGbfWUpyLrgv1mwg9Sx2dENc3kNkMNLd6Qxq3p6mlW8lU35MJ0l4G0buw_kbogMCedOrHy5DzHd93NwWQsc0oDD5ebI1-eF91yQ1bT7quKOXF-3d7S-KS8RRboHY-WyXtFtnDy3yvrO_n2k77zj7rfoKc8xPra_t64vVHrVVZVdWHZ7J-qivLLOyqb42Wqkh2leDMA_Wl2BZCh5CANtCe30_yCorQZ4U0xmYAm_iIopW0qVr6XbeIAra7BPudKpMeX-40Rz2yB4I2kNg-NIDv1rOet1Ec-Y3PBgm4RPQ5n0yT4u8dASoAg3nuNMJKukqfWHU1wMBQ6LAzSDmOoqUPU_GC-jXw-RZ20XZE0JQg7Pxc8nccff1Qrk5vDoSXAeFHJtPh6NRUF4t3BRRvivjsPagCrM_PXCCFlvSE8eUUboFQ3-qgunuDvlCZVXn3q9qtmg_hCHTRHo8KuxEhXoZ7XsTLzojDQ0M9qomufz6JVA1TWD2pf3Yj9fsv0zzoLxCGpn46VoVcTgrXSis1flbnqwVQPz6xrfhB_tzfjwAvXX0kJiwx8juEQZJZOVEtepWhU_Bg67wezSyL1s_acGqrJoByhuJy5Oru5vXd165cz8DXqu5-tdM14T97swgnQI2ltxHntz8kQ0jjJmPBZSRPMkVfItgTzIEWh84RRwlqsrHsB-OiXx5-R-jhW8-tRsAAA%3D%3D
line: 0
col: 0
error: {}`

**Comment by willyb321** [comment]
We know. Please. Stop. Opening. New. Issues.

I am a student and have very little free time. @strideynet is an incredibly busy man.
Duplicate of #217 #218 #213 #201 #216 #203 #211 #207 and probably more
