### ISSUE TITLE
When trying to load my Orca, I get a blank or locked screen

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#22]
Tried to load my Orca build from a bookmark. Got a black screen. I then accessed beta.coriolis.edcd.io and tried to load my build there. Screen would stay at all the ships but would not respond to any click.

Using this loadout:
http://beta.coriolis.edcd.io/outfit/orca/0pftnFflsdksif50v272700040404mlmmp237mg02v62f.Iw18SQ==.IzAM-MIlReg=?bn=Kantos%20Kan%20Orca

**Comment by cmdrmcdonald** [comment]
This will be fixed in the 2.2.2 release.
