### ISSUE TITLE
Jameson, we have a problem

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#23]
After changing module power priority, tried to save and got this:

Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Path: /outfit/federal_corvette/2putsFklndzsxf50x0x7l28281919040404040402020l06p05sf63c5ifrv66g2f.Iw18QDFZA===.EwRgDBHpO8bROJSg.H4sIAAAAAAAAAy1RvU7CUBj9Wmj5Kclta9Ei8qMWB0YdND6AMU4+AIODcSDG0dmBwYmZB2BwJAzGyTgYF+NiMCHqYzAYUD-PQTqcfP3Ozz251zIDxZd3RLKnIrLMSe14aIsUn12RzSgSiZq-qqY6Uw27KfCpsBeKmPZUNfZz4C8gUsfsw9VIeyJbD5Dl+t9IHkO0-gjYOEOIZsO+JRIfgXIPISpdZmDNO23EuH6MA89bWKCKVFjC38O0MmZJz9wiwbnPQ3lVhnIGf2WQXoi0EKKFmG1hPg5xrpkZUjkX7VJkTBch8QFm7w2igJAQ1DcjUj+YvSEpQkLQwPgoEE84d7LgX8gTEkKNOw1Nh-53tA4E4I3IE3Tp399EYe+DPCEhaBydoFyxhYRyD3678QXlJ-oF8yY3AJe-yZRXX7Ke4MrwQaqv2NaneBVds3ZAZti-moahfof71VpoYxsf40lLrdTiVlc5FSbk9Q+6fbbO-gEAAA==?bn=Kantos%20Kan%20Federal%20Corvette
Error: Unknown
Details:
scriptUrl: http://beta.coriolis.edcd.io/lib.0ab234.js
line: 951
col: 16607
error: {}
Save

Now, my Corvette build will not load anymore. Same as the Orca. After selecting the build, the screen stays on the default screen and no options work anymore.

**Comment by cmdrmcdonald** [comment]
This will be fixed in the 2.2.2 release.
