### ISSUE TITLE
Viper Mk4 fails to import

### ISSUE THREAD

**Issue by robbyxp1** [EDCD/coriolis#231]
scriptUrl: 
line: 0
col: 0
error: "Unknown bulkheads \"viper_mkiv_Armour_grade1\""

FDDev id "viper_mkiv_armour_grade1"

**Comment by robbyxp1** [comment]
EDId is 128672257 as given in corolis-data
import json is
{{  "id": 128672257,  "name": "viper_mkiv_Armour_grade1",  "on": true,  "priority": 1}}

think it might be case.. checking

**Comment by robbyxp1** [comment]
No failed with _armour as well.

**Comment by willyb321** [comment]
@robbyxp1 do you have a `/import` url for a mkiv? I don't have one in-game to test.

**Comment by robbyxp1** [comment]
I've sent an email back..

https://coriolis.edcd.io/import?data=H4sIAAAAAAAEANWXXU%2FbMBSG7yftP6Bec9F8tNDdIboJpjGhFfU2cuLTxqtjR7ZTyBD%2FfcduC0FqWF2ZTbvph%2B0cP3p9fM6bx48fTk4GglQw%2BHQymLMaVHazup4PTt1EJWnDQePco%2F2PIxeqko16GXhe1B3CQUZxIIrPx2dxPDo77czsNlu7zaoVW2fEBc2WilCIBt3FUuBSoxroDtaKScVMa3fYDT9tfjxt1w0uiVrKK2KK8s%2BsOyI3SVRhH81JS6VUXjBxH8wXhTvMSrYwU8XWcLh6w3EaReN96l0Lk5UtKkhtxEyzX5BmBSdap17Mw17mBvgdESsv2CSd9MEuMJ7BeF3UJMxZf2MLmDV1LZXxkzZN%2Bmg5htSbkA443gD7JWdvPtwQJj6LJRPdq3UA8PA87gMGF64r7ihMHtwAZU11RRStJRMm8gBOJ2m8Nx%2BuapPlQCrExBKwYA9As8rt8y7M8f%2FAfMuJAENUe1HXSpKinDXMeJQKLLRJtLfQ2vSoN9G3obULHeTu3cp7UFOmjWJ5Y6RHZ7AXcNKbz7WNS1%2FiusxOgma2Q7ey%2B1WNYdpbkB20ldocX5B7lf5BKPGTFxOij1SD0FLprqqB%2Bga2ufpSFquaHSDrHi9QbJ8NotmMSzOMspk9DD%2FpznoPWZcMOF2CAEV2iRm29Trq2JfaOq3JsI86b5bLFk1NF9evm72Nmzpcn0qLbiE578N1HkyRYmMXomN4306KseP16GbjcTxKRr1JYYCjdcwlbbFoFXINqtUFEZgkOEcEXl0ahn4OWgOfS1Yc0Bye75ddXls5EcxuEE7IxAmZeNrE3jx9ffBJ2IOvCOfHOpn9rcq5AqJZUTGtGQdHvjEH2u4W6Ia9Ave0M%2F8S%2FI6J9kjBR9Fec265i5IsFpw0oijxehnc4x1o%2FVQexb0qox9ARV1MCgsQBWSmUQpMQPIpFIQfoO%2BOi9r12GqrnJiMErEEJRsdyBHiy435KvPDaWr7xE%2BZZx0bkHNMyIViFFvWMNT9R2tyPR0eDma%2F8fgM2KZfM5pR2eQcuH3Tui%2BDeegNl8fx%2FUWu77jVUYrBQ82lAoX2a6kgVMfZEh2lVVAi%2B4UfT78BiRNeUUETAAA%3D&bn=Vengence

Try that, hopefully it will paste.

I can get the raw output from EDD if required.

**Comment by willyb321** [comment]
https://github.com/EDCD/coriolis-data/blob/master/ships/viper_mk_iv.json#L2 seems to list the viper mk 4 as `viper_mk_iv` rather than `viper_mkiv`. If that's different to how it is in the journal, let me know.

**Comment by robbyxp1** [comment]
Below is the JSON I send..

The journal calls it either Viper_MkIV or viper_mkiv (its a bit random on its cases) but that's the FDEV ID.

Your coriolis data has it as viper_mk_iv (which does not match the journal).

Giving coriolis the viper_mk_iv does not work..  error: "No such ship found: \"viper_mk_iv\""

Giving coriolis viper_mkiv without armour gives : 
scriptUrl: .. edited out line: 0
col: 0
error: {}

Giving coriolis with armour gives:

error: "Unknown bulkheads \"viper_mkiv_Armour_grade1\""
error: "Unknown bulkheads \"viper_mk_iv_Armour_grade1\""
error: "Unknown bulkheads \"Viper_MkIV_Armour_grade1\""
error: "Unknown bulkheads \"viper_mkiv_armour_grade1\""

Checked EDID vs your coriolis data for viper armour - its right 128672257.

is it case sensitivity? Because its called Viper_mk_iv?  

Rob

Here is the export JSON
Export {
  "name": "Viper_MkIV",
  "modules": {
    "Armour": {
      "module": {
        "id": 128672257,
        "name": "viper_mkiv_Armour_grade1",
        "on": true,
        "priority": 1
      }
    },
    "CargoHatch": {
      "module": {
        "name": "ModularCargoBayDoor",
        "on": true,
        "priority": 2
      }
    },
    "FrameShiftDrive": {
      "module": {
        "id": 128064116,
        "name": "Int_hyperdrive_size4_class4",
        "on": true,
        "priority": 0
      }
    },
    "FuelTank": {
      "module": {
        "id": 128064349,
        "name": "Int_fueltank_size4_class3",
        "on": true,
        "priority": 1
      }
    },
    "LifeSupport": {
      "module": {
        "id": 128064143,
        "name": "Int_lifesupport_size2_class1",
        "on": true,
        "priority": 2
      }
    },
    "MainEngines": {
      "module": {
        "id": 128064082,
        "name": "Int_engine_size4_class5",
        "on": true,
        "priority": 0
      }
    },
    "MediumHardpoint1": {
      "module": {
        "id": 128049429,
        "name": "Hpt_beamlaser_fixed_medium",
        "on": true,
        "priority": 0
      }
    },
    "MediumHardpoint2": {
      "module": {
        "id": 128049429,
        "name": "Hpt_beamlaser_fixed_medium",
        "on": true,
        "priority": 0
      }
    },
    "PlanetaryApproachSuite": {
      "module": {
        "id": 128672317,
        "name": "Int_planetapproachsuite",
        "on": true,
        "priority": 1
      }
    },
    "PowerDistributor": {
      "module": {
        "id": 128064192,
        "name": "Int_powerdistributor_size3_class5",
        "on": true,
        "priority": 0
      }
    },
    "PowerPlant": {
      "module": {
        "id": 128064046,
        "name": "Int_powerplant_size4_class4",
        "on": true,
        "priority": 1
      }
    },
    "Radar": {
      "module": {
        "id": 128064231,
        "name": "Int_sensors_size3_class4",
        "on": true,
        "priority": 0
      }
    },
    "ShipCockpit": {
      "module": {
        "name": "viper_mkiv_cockpit",
        "on": true,
        "priority": 1
      }
    },
    "Slot01_Size4": {
      "module": {
        "id": 128064276,
        "name": "Int_shieldgenerator_size4_class4",
        "on": true,
        "priority": 0
      }
    },
    "Slot02_Size4": {
      "module": {
        "id": 128672290,
        "name": "Int_buggybay_size4_class1",
        "on": true,
        "priority": 0
      }
    },
    "Slot04_Size2": {
      "module": {
        "id": 128064338,
        "name": "Int_cargorack_size1_class1",
        "on": true,
        "priority": 1
      }
    },
    "VesselVoice": {
      "module": {
        "name": "voicepack_verity",
        "on": true,
        "priority": 1
      }
    },
    "Slot03_Size3": {
      "module": {
        "id": 128064340,
        "name": "Int_cargorack_size3_class1",
        "on": true,
        "priority": 1
      }
    },
    "SmallHardpoint1": {
      "module": {
        "id": 128049492,
        "name": "Hpt_basicmissilerack_fixed_small",
        "on": true,
        "priority": 0
      }
    },
    "SmallHardpoint2": {
      "module": {
        "id": 128049492,
        "name": "Hpt_basicmissilerack_fixed_small",
        "on": true,
        "priority": 0
      }
    },
    "TinyHardpoint1": {
      "module": {
        "id": 128049513,
        "name": "Hpt_chafflauncher_tiny",
        "on": true,
        "priority": 0
      }
    },
    "TinyHardpoint2": {
      "module": {
        "id": 128049522,
        "name": "Hpt_plasmapointdefence_turret_tiny",
        "on": true,
        "priority": 0
      }
    },
    "Decal1": {
      "module": {
        "name": "decal_combat_dangerous",
        "on": true,
        "priority": 1
      }
    },
    "PaintJob": {
      "module": {
        "name": "paintjob_viper_mkiv_blackfriday_01",
        "on": true,
        "priority": 1
      }
    },
    "ShipID0": {
      "module": {
        "name": "nameplate_shipid_doubleline_white",
        "on": true,
        "priority": 1
      }
    },
    "ShipID1": {
      "module": {
        "name": "nameplate_shipid_doubleline_white",
        "on": true,
        "priority": 1
      }
    },
    "ShipName0": {
      "module": {
        "name": "nameplate_explorer01_grey",
        "on": true,
        "priority": 1
      }
    },
    "ShipName1": {
      "module": {
        "name": "nameplate_explorer01_grey",
        "on": true,
        "priority": 1
      }
    },
    "Slot06_Size1": {
      "module": {
        "id": 128662535,
        "name": "Int_stellarbodydiscoveryscanner_standard",
        "on": true,
        "priority": 1
      }
    }
  }
}

**Comment by robbyxp1** [comment]
Also
error: "Unknown bulkheads \"viper_mk_iv_armour_grade1\""

**Comment by willyb321** [comment]
Looks like it was an issue with [this](https://github.com/EDCD/coriolis/blob/fac71feea76bb26266c18f930ab1d6962f4dd68b/src/app/utils/CompanionApiUtils.js#L151). Have changed it to lowercase the bulkhead check, and the URL provided imports not. Will close when this hits live.
