### ISSUE TITLE
Import doesn't work on Safari

### ISSUE THREAD

**Issue by xtoudi** [EDCD/coriolis#232]
Settings->Import.

When I try type something in import window I get this error:

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15
Path: /
Error: Unknown
Details:
scriptUrl: 
line: 0
col: 0
error: null

(content blocking and other blocking stuff disabled)

**Comment by felixlinker** [comment]
Hi, is this still an issue?

**Comment by xtoudi** [comment]
It works now :)
