### ISSUE TITLE
Where is Dev Support Needed

### ISSUE THREAD

**Issue by mcdonnelldean** [EDCD/coriolis#237]
I have the next few weekends free and heard there is need for some dev support. I'm fairly handy with JS on frontend and back and I use this app a lot so I'd like to pay back.

Is there a priority list of what needs to be tackled that is also viable for someone new to the project to tackle. The work doesn't need to be technically simple, I just need some time to kick around before attempting anything too involved.

**Comment by strideynet** [comment]
#190 

Closed.

**Comment by mcdonnelldean** [comment]
@strideynet Ah I didn't search hard enough. Ta! I'll pick something off the list on Friday when I actually start to work on it and call it out.
