### ISSUE TITLE
Engineered ship data repository

### ISSUE THREAD

**Issue by willyb321** [EDCD/coriolis#243]
Please put any data you want to put towards helping Coriolis get engineering back on track in here (See first comment for format).

**Comment by willyb321** [comment]
Choose one (or more) of the following:
```
`/import URL`
https://pastebin.com/sFnzGQtz
```

```
`Loadout journal event`
https://pastebin.com/sFnzGQtz
```

```
`CAPI raw data`
https://pastebin.com/sFnzGQtz
```

**Comment by joelgarboden** [comment]
## Vulture

[`/import URL`](https://gist.github.com/joelgarboden/e218882277c24975f6d8f3971bdeea59#file-edmc_import)

[`Loadout journal event`](https://gist.github.com/joelgarboden/e218882277c24975f6d8f3971bdeea59#file-artemis-2018-04-12t20-47-26-txt)

[`CAPI raw data`](https://gist.github.com/joelgarboden/e218882277c24975f6d8f3971bdeea59#file-journal-180412204532-01-log_loadout_event)

## Python

[`/import URL`](https://gist.github.com/joelgarboden/1ea0ce73015eb15d517767efe9450c14#file-edmc_import)

[`Loadout journal event`](https://gist.github.com/joelgarboden/1ea0ce73015eb15d517767efe9450c14#file-athena-2018-04-12t20-46-45-txt)

[`CAPI raw data`](https://gist.github.com/joelgarboden/1ea0ce73015eb15d517767efe9450c14#file-journal-180412204532-01-log_loadout_event)

**Comment by felixlinker** [comment]
@willyb321 What is the purpose of this issue? To gather test data?

**Comment by willyb321** [comment]
Yea, probably not needed but we can keep it open for now.

**Comment by felixlinker** [comment]
@willyb321 Will close this finally for being outdated. Feel free to reopen it if you think it helps with something.
