### ISSUE TITLE
New experimental effects override manually entered numbers

### ISSUE THREAD

**Issue by TezcatlipocaXBL** [EDCD/coriolis#249]
I love that the new experimental effects have been added, but I don't seem to be able to use them along with my own values.

Previously, when applying an experimental effect to a weapon, you could still enter your own values afterward.

The new version does not appear to allow that though, at least not for the new experimental effects I've tried just now on the power plant and shield generator.

**Comment by pnellesen** [comment]
@TezcatlipocaXBL could you check this again? - there was an update today that fixed one issue with the manually entered values in the experimentals, it may also have fixed this issue, though I can't say for sure (I'm still a bit of a noob to most of the Coriolis code ;) )

**Comment by LivewareCascade** [comment]
Hi, I think I'm seeing something similar to what the OP is seeing.

Example, Military Grade composites applied to a Viper IV, with G5 Lightweight mod and the Deep Plating experimental.

If you then try to edit the percentage values manually, so 17.40% bonus to explosive resistance, Coriolis forcibly resets it to 14.43 - sometimes this happens as soon as the number is typed in and the enter key is pressed/focus is switched away; other times the number appears to update to the user value, but if you close the engineering pop-up and open it again, you can see it's defaulted back to the old value - which is about what it would be if the experimental mod was forcibly added to the user changes.

**Comment by felixlinker** [comment]
Fixed in #385
