### ISSUE TITLE
Grade 3 engineered dirty drives show wrong worst optimal mass.

### ISSUE THREAD

**Issue by es-kan** [EDCD/coriolis#258]
This might be a database error, I am pretty certain the worst optimal mass for this grade is 5, instead of 50.

Found on the Type 10 Defender, but also present on other ships. Apologies if this is not the right place to post this, I could not find a feedback/contact button.

![image](https://user-images.githubusercontent.com/19603425/39228632-60d1cc60-485f-11e8-9806-389f37e51166.png)

**Comment by willyb321** [comment]
Yeah, this should be fixed soon:tm:
