### ISSUE TITLE
Unknown items found in users logs which are not on corolis

### ISSUE THREAD

**Issue by robbyxp1** [EDCD/coriolis#260]
in EDDiscovery format, but its FDID (lower cased), then its ID, mass, name, type..

These are in FDID stuff:
            { "int_dronecontrol_recon_size1_class1", new ShipModule(128837858, 2, "Drone Controller Recon Class 1 Rating E" , "Limpet Controller" ) },
            { "int_dronecontrol_recon_size3_class1", new ShipModule(128841592, 5, "Drone Controller Recon Class 3 Rating E" , "Limpet Controller" ) },
            { "int_dronecontrol_recon_size5_class1", new ShipModule(128841593, 8, "Drone Controller Recon Class 5 Rating E" , "Limpet Controller" ) },
            { "int_dronecontrol_recon_size7_class1", new ShipModule(128841594, 16, "Drone Controller Recon Class 7 Rating E" , "Limpet Controller" ) },

I found one of these..
            { "hpt_shipdatalinkscanner", new ShipModule(-1,0, "Ship Data Link Scanner" , "Sensors" ) },

In a  user log:

Int_dronecontrol_unkvesselresearch 

Int_corrosionproofcargorack_size4_class1 

Just to keep you up to date with what i'm seeing ;-)

Rob

**Comment by willyb321** [comment]
Yeah, will add either tomorrow or day after.

**Comment by willyb321** [comment]
Recon limpets added.

**Comment by willyb321** [comment]
CRCR added. Will close this now.
