### ISSUE TITLE
Module mass changes from engineering do not import

### ISSUE THREAD

**Issue by compro01** [EDCD/coriolis#262]
Importing [this ship build](https://eddp.co/u/iXKSsZMD) via EDMC does not input the sensor mass.  It should be -48.95% (16.34T), but instead there is no mass reduction.

Mass increase is also missing on the FSD (should be +30%) and power plant (should be +10%)

Masses are correct in the JSON (attached).

[Azrael.Rafferty's Mobius.2018-04-29T17.20.25.zip](https://github.com/EDCD/coriolis/files/1959320/Azrael.Rafferty.s.Mobius.2018-04-29T17.20.25.zip)

**Comment by willyb321** [comment]
Is your EDMC up to date? (help => check for updates)

**Comment by compro01** [comment]
Yes.  Using version 3.0.4.0.

**Comment by willyb321** [comment]
I have found the issue, will push to beta soon:tm:
