### ISSUE TITLE
Add module comparison chart similar to shipyard

### ISSUE THREAD

**Issue by pnellesen** [EDCD/coriolis#263]
From @Wyvern on Discord:

"If you're taking feature suggestions, I have an idea for Coriolis
So, the ship info overview page or whatever it's called (pictured) is pretty rad. 10/10
WHAT IF there was one for all the weapons as well? That way we could easily compare things like DPS, DPE, damage per shot, Thermal load, EPS, ammo count, all that good stuff.
I think that'd be neato tbh"

**Comment by felixlinker** [comment]
Closed in favour of https://github.com/EDCD/coriolis/projects/4#card-53925092
