### ISSUE TITLE
Enhancement: improve keyboard navigation on outfitting screen

### ISSUE THREAD

**Issue by pnellesen** [EDCD/coriolis#271]
While working on mobile keyboard for the sliders, I noticed that there was no way to navigate through the slots using the tab key. Will try to add some markup/event handlers to allow improved tab key navigation, and to open slot editor when Enter key is selected.

**Comment by pnellesen** [comment]
Initial work started - https://github.com/pnellesen/coriolis/tree/feature/%23271_keyboard_nav

Need to add keyUp handlers next - comments/suggestions welcomed :)

**Comment by pnellesen** [comment]
Should have this done in the next day or so - got it working well on the modules sections, now finishing up on the modifications sections.

**Comment by pnellesen** [comment]
Have some final testing to do, but should be submitting PR for this shortly.

**Comment by pnellesen** [comment]
Pull request #288 submitted for this enhancement, along with fix for #284

**Comment by willyb321** [comment]
Added in in 752d9f0c680e9193229f40a73d262534cfe99cf2
