### ISSUE TITLE
Engineering shouldn't be possible on Guardian power plants

### ISSUE THREAD

**Issue by burtonsimmons** [EDCD/coriolis#273]
Currently, when selecting Guardian power plants, it shows engineering options, yet those aren't engineer-able.

**Comment by willyb321** [comment]
Yep, that's because they are (in Coriolis) considered the same as regular powerplants. Will take a bit of refactoring to change that. I'll get it done when I have a chance.

**Comment by willyb321** [comment]
Fixed in 2255e3bfc4a1d255f9bff464c3169458078291b3

**Comment by burtonsimmons** [comment]
You're a rock star.  I take back everything I said about you. :+1:
