### ISSUE TITLE
blueprintFunction.getPercent() returns incorrect value for some blueprints

### ISSUE THREAD

**Issue by raorn** [EDCD/coriolis#274]
This may be two separate bugs, but Coriolis fails to properly calculate some blueprints, for example Resistance augmented Shield boosters. "Roll" is forced to "Random". In EDCD/coriolis-data for these blueprints "worst" and "best" values are same for all features (and this may also be wrong). This leads to this code:

```javascript
export function getPercent(m) {
  let result = null;
  const features = m.blueprint.grades[m.blueprint.grade].features;
  for (const featureName in features) {
    
	if (features[featureName][0] === features[featureName][1]) {
		continue;
	}
	
	let value = _getValue(m, featureName);
	let mult;
```

to always return `null`.

**Comment by willyb321** [comment]
Hmm, will take a look.
