### ISSUE TITLE
Wrong Shield booster mods

### ISSUE THREAD

**Issue by raorn** [EDCD/coriolis#275]
Alliance Chieftain, 6C Bi-Weave shields, G5 Thermal, Fast charge. 2x A-class Shield booster, G5 Resistance augmented, Super capacitors, 1x A-class Shield booster, G5 Heavy duty, Super capacitors. Raw shield strength calculated - 405 MJ, in-game displayed as 512, EDSY calculations - 512.4.

[Coriolis build](https://eddp.co/u/TUywV7Vb)
[EDSY build](http://www.edshipyard.com/new/#/L=C90H4C0S0,,DBwG9Ib6phX8u00IrSAMrSAQrSADBwG9Ib6phX8u00IrSAMrSAQrSADBwG5Ia16004qpD8u00Cw58,9p30AAo0AQQ0AeU0Au60B9I0BLo0Bb60,,7UeG9H34wPcasPcgy00)

**Comment by willyb321** [comment]
Ah, looks like I missed a bit when fixing super cap.

**Comment by raorn** [comment]
Now it works as expected, thank you!
