### ISSUE TITLE
Pricing Wrong on Guardian Modules

### ISSUE THREAD

**Issue by Lynk9999** [EDCD/coriolis#277]
The prices on the guardian modules seem to all be off. 8A Guardian Hybrid Power Plant is reportedly 5 mil while the actual cost is something around 140 mil in game. These really need and update because boy was I suprised when I thought I could get the power plant for 5 mil and came up 135 mil short. Whether the weapons are correctly priced or not I could not tell you but the power plants prices are incorrect.

**Comment by Turbolalka9000** [comment]
Guardian PP prices:
2A 187.360cr
3A 468.401cr
4A 1.686.243cr
5A 5.058.729cr
6A 15.176.184cr
7A 45.528.551cr
2018-06-29, Station Bernoulli Vision in system Caeritis.

**Comment by Turbolalka9000** [comment]
8A 136.585.652
2018-06-29, Station Meredith City in system LFT 926
