### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by Felix7R** [EDCD/coriolis#278]
Coriolis used to work fine on my windows laptopb(and works fine on Android), but since a few days I keep having this error whenever selecting any build I made :

Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Path: /outfit/diamondback_explorer?code=%5Bobject%20Object%5D&bn=Test1
Error: Unknown
Details:
scriptUrl: https://coriolis.io/app.a2acc7.js
line: 11
col: 467851
error: {}

Hope this helps.
Best regards

**Comment by Felix7R** [comment]
I've been changing my build pretty often, can't remember if it started to
bug right after a change, if that's what you're asking ?

I'm unfamiliar with informatic, I've tried to type what you said but it I
must have done that in the wrong place.
Anyway, I've copied what the console tab shows : Arguments(5)
console.(anonymous function) @ config.js:15
Ship.js:1135 Uncaught TypeError: Cannot read property 'getPowerGeneration'
of null
    at t.value (Ship.js:1135)
    at t.value (Ship.js:704)
    at t.value (Ship.js:784)
    at t.value (OutfittingPage.jsx:81)
    at t.value (OutfittingPage.jsx:469)
    at d.updateComponent (ReactCompositeComponent.js:613)
    at d.receiveComponent (ReactCompositeComponent.js:546)
    at Object.receiveComponent (ReactReconciler.js:124)
    at Object.updateChildren (ReactChildReconciler.js:109)
    at m._reconcilerUpdateChildren (ReactMultiChild.js:211)
copy(localStorage)
undefined
Feel free to ask me things to help clarify
Félix Ceytaire

**Comment by willyb321** [comment]
Ok, so when you type `copy(localStorage)`, it copies the builds to the clipboard so if you can paste into pastebin.com and link it here that would make my debugging easier.

**Comment by Felix7R** [comment]
{
  "builds": "{\"fer_de_lance\":{\"Pride of Neptune
PvP\":{\"code\":\"A0pktfFdlidpsif32c2a2a1g1g000204---4am72b6e4u.Iw18aQ==.CwBjCYEZJc7gzEsIYmAoA===..EweloBhAOEoUwIYHMA28QgIwV0A=\",\"useName\":\"Pride
of Neptune PvP\"}},\"imperial_eagle\":{\"White Sparrow
3000\":{\"code\":\"A0p5tzF8l3d5s8f11g1717004027m32525.Iw18kA==.CwBjCYEYGYXepjEA.H4sIAAAAAAAAA2P8Z8/AwPCXBUhw3GFlYOBX+fX/v9gTHgaG/6z/bEBSzEDiTyOQ4Kz58/8/F4hQBBFKV/79/6+6gJ+BQW0HN1A5579guPIuIMHqwMbAwLbg2///EiBC2eHtf6D2fxGoijqEgYousDMwKEcwAQ35DxRjAAAf5j6MlAAAAA==.EweloBjEoUwQwOYBtYhARgtoA===\",\"useName\":\"White
Sparrow
3000\"}},\"vulture\":{\"Backstabber-4000\":{\"code\":\"A0patfFalddksif31d2b04040m0h4a2d032o692h.Iw1/kA==.CwBjCYEZJdwZkcGZRA==.H4sIAAAAAAAAA2P8Z8/AwPCXBUhw3GFlYOBX+fX/v9gTHgaG/8z/pGBS/AG///8XOsLJwCAyRZCBQWIDUPD/fwYGAH75W5Q+AAAA.EweloBhAWEoUwIYHMA28QgIwV0A=\",\"useName\":\"Backstabber-4000\"}},\"asp\":{\"PolyFlex-1988\":{\"code\":\"A1pftfFflidfsnf52727121212120006020h05mk40f32tv62f.Iw18WQ==.CwBjCYEZJc/gzE0IbFEA.H4sIAAAAAAAAA2P+J8XAwPCXBUj8qQAS/AG///8XOsLJwCAyRZCBQWIDUOY/x79gkCJmkCIgZmB1YGNgYFvw7f9/CRCh7PD2////nMQo4voXAlLECCTEF/AzMEgK8DEwKKcAuf+5cUvx4JbixS3F/88DJsU9B2i3IIhQ2cMElPrPAAUAlqyrq/8AAAA=.EweloBhBmVoDhAUwIYHMA2SQgIwQKA==\",\"useName\":\"PolyFlex-1988\"}},\"type_9_heavy\":{\"CargoBob-5000\":{\"code\":\"A0pntsFklndssif6-----02000304070706054a0303020224.Iw18RQ==.Aw4JgRg1TOxtUBmIA===.H4sIAAAAAAAAA2P+J8XAwPCXBUj8qQAS/AG///8XOsLJwCAyRZCBQWIDUOb/fwYA/JAA9CcAAAA=.EweloBhA2AWEoFMCGBzANokICMF9A===\",\"useName\":\"CargoBob-5000\"}},\"type_6_transporter\":{\"Drill-Fiesta\":{\"code\":\"A0p5tdFal8das8f42l2l03030004041vP740C52h.Iw1/kA==.Aw4JgRg4GYbBI4RsIA==..EweloBhBGA2ECsUCmBDA5gG2SGF9A===\",\"useName\":\"Drill-Fiesta\"}},\"imperial_courier\":{\"Erithacus
Rubecula\":{\"code\":\"A0patzF8l3das8f21a1a1g02040404402953m3692h.Iw18UA==.CwBjCYEZJc4ZkfG8SiA=.H4sIAAAAAAAAA2P8Z8/AwPCXBUhw3GFlYOBX+fX/v9gTHgYGIUag2H/Wf5YgeaAMAyfPv///uaYIMjAoglhKIJYqiKUGYv3n+BcCUskMJMQd5BkYJCdIMTDIBogwMCjrAI36z0lA/j9QggEAjxXLW48AAAA=.EweloBhAWEoUwIYHMA28QgIwV0A=\",\"useName\":\"Erithacus
Rubecula\"}},\"federal_dropship\":{\"Test\":\"A1pktkFflndpsif42b1g1g1a1a0404040205mk4a32m72b69v62g.Iw18eQ==.Aw18eQ==.H4sIAAAAAAAAA2P8Z8/AwPCXBUhw3GFlYOBX+fX/v9gTHgaG/8z/pGBSfyqABH/A7///hY5wMjCITBFkYJDYAJT5/5+BAQDv4yGSQwAAAA==.EweloBhBGA2ECs8CmBDA5gG2SGF9A===\"},\"diamondback_explorer\":{\"Test1\":{\"code\":\"A0pataFilddfsdf22b1a1a04040402452bm5582h69.Iw18UA==.CwBhEYCZ3FPgzEhsQJMIA===.H4sIAAAAAAAAA2P8Z8/AwPCXBUhwXGBnYOA3+PH/v9gTHgaG//8ZABF6MmcdAAAA.EweloBhAWEoUwIYHMA28QgIwV0A=\",\"useName\":\"Test1\"}},\"federal_assault_ship\":{\"Test\":\"A1pktkFflndpsif42b2b1a1a040404024a04mj2bm72t692g.Iw18aQ==.Aw18aQ==.H4sIAAAAAAAAA2P8Z8/AwPCXGUhw3GFlYOBX+fX/v1gOOwPDf+Z/UiApFiDxpwJI8Af8/v9f6AgnA4PIFEEGBokNQJn//xkYAOCAMnZDAAAA.EweloBhBGA2EDMoCmBDA5gG2SGF9A===\"},\"federal_gunship\":{\"Test\":\"A1pktkFflndusnf42b1a1a1a1a--04040402054j032b2bm7692h.Iw18RQ==.Aw18RQ==.H4sIAAAAAAAAA2P8Z8/AwPCXGUhw3GFlYOBX+fX/v1gOOwPDf+Z/UiApFiDxpwJI8Af8/v9f6AgnA4PIFEEGBokNQJn//xkYAOCAMnZDAAAA.EweloBhBGA2H4FMCGBzANokMK6A=\"},\"orca\":{\"Test\":\"A0pftkFilsdksif42b1a1a040404022d2d5i4am7m5692h.Iw18SQ==.Aw18SQ==.H4sIAAAAAAAAA2P8Z8/AwPCXBUhwXGBnYOA3+PH/v9gTHgaG//8ZABF6MmcdAAAA.EweloBhBGA2EoFMCGBzANokMK6A=\"}}",
  "comparisons": "{}",
  "insurance": "standard",
  "moduleDiscount": "null",
  "outfittingTab": "power",
  "shipDiscount": "0"
}

Done !

2018-05-12 9:39 GMT+02:00 William <notifications@github.com>:

**Comment by willyb321** [comment]
Thanks, will take a look!

**Comment by chartercook** [comment]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Path: /outfit/fer_de_lance?code=%5Bobject%20Object%5D&bn=USS%20Castle%20Rock%20V2
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.34c16f.js
line: 11
col: 510100
error: {}

i also got this error.

**Comment by felixlinker** [comment]
We haven't seen this error in a while and we weren't able to properly debug it. I hope that the ones reporting don't face this issue anymore. I'll close this issue due to inactivity but I'm happy to reopen it at any time.

**Comment by ShadowLegion** [comment]
Just got this error just now. I see the thread is closed but I figured it would be best to mention it.
