### ISSUE TITLE
TypeError on modifications

### ISSUE THREAD

**Issue by ZyKyook** [EDCD/coriolis#280]
Firefox: TypeError: b.Modifications.modules[i.grp].blueprints[i.blueprint.fdname] is undefined
Chrome: Uncaught TypeError: Cannot read property 'grades' of undefined

https://pastebin.com/3t65Nfat

It systematically happens when I click on modification/engineering of the detailed surface scanner.
Build link is generated by EDSM
If I replace that module with something else, put back a detailed surface scanner, I can now enter modifications.

**Comment by willyb321** [comment]
Temp fixed in 157c1148fb0b49b78325efde165722493c5359f2

**Comment by willyb321** [comment]
Releasing now
