### ISSUE TITLE
Empty window when no Experimental Effect is available.

### ISSUE THREAD

**Issue by victorleblais** [EDCD/coriolis#284]
How to reproduce:
- Click to engineer the Life Support
- Choose any tier of Lightweight modification
- Upon clicking, you'll have an empty window where Experimental Effects normally are

What should happen:
- If the modification/module doesn't offer any experimental effects, this step should be skipped and show the final result (values and stats modified by the chosen modification and possibility to change the "completion" rate of the modification)

**Comment by pnellesen** [comment]
I noticed this while working on the keyboard handler (enhancement #271) - fix will be part of that enhancemen.

**Comment by willyb321** [comment]
Fixed in 752d9f0c680e9193229f40a73d262534cfe99cf2
