### ISSUE TITLE
UI behaviour when changing modules

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDCD/coriolis#289]
I have noticed a usability issue in the latest version 2.9.14 for optional modules, hardpoints, and utility mounts.  I'll describe this using a fuel scoop, but this happens with any non-core module.

Old behaviour (2.9.13 and earlier): If you click on the fuel scoop, the module list will open, and the list is positioned at the fuel scoops, allowing you to quickly change to a different fuel scoop.

New behaviour (2.9.14): If you click on the fuel scoop, the module list will open, but it is now positioned at the very top of the list.

Noticed with Firefox 60.0.1 on MacOS and Windows as well as Chrome 65 and 66 on MacOS.

**Comment by pnellesen** [comment]
PR #291 will fix this issue as well.

**Comment by willyb321** [comment]
Fixed in 507ea9e09e03673a1f6737b97b1835edee0117ad
