### ISSUE TITLE
Mismatched EDMC import data

### ISSUE THREAD

**Issue by Noshtzy** [EDCD/coriolis#29]
I imported my latest outfitting from EDMC into the updated Coriolis EDCD and found a couple oddities in my not-very-impressive Anaconda. The differences are compared from the EDMC export (attached) to the Outfitting modification stats in-game.

Lightweight Alloy bulkhead: Game shows 29.2% hull boost, Coriolis shows 12.98%
5D Fighter hangar installed in class 5 internal slot. Coriolis shows a 7D hangar in that same slot
4A Pulse Laser: Game shows +50% thermal load, Coriolis shows 0%
3C Multicannon #2: Game shows damage -8.7%, Coriolis shows -14.37%
3C Multicannon #3: Game shows damage -8.6%, Coriolis shows -14.29%

All other modules appear to be reporting correctly, engineered or otherwise. These errors affect the stats on Coriolis such as Armour, Speed and Jump Range.

[Anaconda.2016-11-22T18.41.38.txt](https://github.com/EDCD/coriolis/files/607851/Anaconda.2016-11-22T18.41.38.txt)

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  Please could you provides screenshots of the modification information for the bulkheads and multicannons to allow us to investigate these?

**Comment by Noshtzy** [comment]
o7

![elite dangerous 11 22 2016 - 19 21 53 01](https://cloud.githubusercontent.com/assets/23667836/20547303/1fe0fd16-b0e9-11e6-84bb-8d12ed3c2c0c.png)
![elite dangerous 11 22 2016 - 19 22 14 02](https://cloud.githubusercontent.com/assets/23667836/20547304/1fe63d80-b0e9-11e6-9049-945ad8dd323c.png)
![elite dangerous 11 22 2016 - 19 22 27 03](https://cloud.githubusercontent.com/assets/23667836/20547302/1fe0db92-b0e9-11e6-8543-7c411cb9a241.png)

**Comment by cmdrmcdonald** [comment]
Thank you for the screenshots.

Fixes have been put in place for this on the beta server.  If you would be so kind, please import the outfitting file to http://beta.coriolis.edcd.io/ and see if it now matches up with your expectations.

**Comment by Noshtzy** [comment]
Yes, everything seems to be lining up correctly now, including the stat summaries. Cheers.

**Comment by cmdrmcdonald** [comment]
Fixed as part of 2.2.3 release.
