### ISSUE TITLE
error when changing stock fuel tank on Sidewinder: 

### ISSUE THREAD

**Issue by Tomparkes93** [EDCD/coriolis#290]
to recreate, [build a sidewinder](https://beta.coriolis.edcd.io/outfit/sidewinder), then click on the fuel tank as if you were going to increase its size. 

scriptUrl: https://beta.coriolis.edcd.io/app.07f937.js
line: 31
col: 334911
error: {}

![image](https://cdn.discordapp.com/attachments/357165142430973952/450966709126299659/unknown.png)

**Comment by pnellesen** [comment]
Gah - I'll look into this one.

**Comment by pnellesen** [comment]
PR #291 submitted to fix this issue

**Comment by willyb321** [comment]
Fixed in 507ea9e09e03673a1f6737b97b1835edee0117ad
