### ISSUE TITLE
Problems noted with your Modification data while plundering it 

### ISSUE THREAD

**Issue by robbyxp1** [EDCD/coriolis#292]
Just importing/double checking data between EDD and Corolis.

Unidentfied Scan Archives **** Not found - you've misspelt it.  "unidentified"

Strange Wake Solution **** Not found in FSDinterdictor_LongRange 4 - I think its "solutions" as I have it and Inara has it

Atypical Encryption Archive **** Not found in FSDinterdictor_LongRange 4 - I think its "Archives" as I have it and Inara has it

**** No engineer for LifeSupport_Reinforced,5 - meaning your modules.json does not have the engineer listed for this blueprint.

Ta.

**Comment by robbyxp1** [comment]
I see Inara does not have an engineer for Life Support Reinforced 5.

**Comment by AnthorNet** [comment]
Nope there is none, even if we have a recipe
=> https://github.com/EDSM-NET/Alias/blob/master/Station/Engineer/Blueprint/Available.php#L368

**Comment by robbyxp1** [comment]
As also noted on discord, the receipes do not match Inara.

**Comment by robbyxp1** [comment]
Also, the Inara is showing special values for the holiday event.
