### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hstracker90** [EDCD/coriolis#295]
Trying to modify a heavily modded sidewinder. Displays just fine. But whenever I click on the wrench icon, this happens:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Path: /outfit/sidewinder?code=A2p0t0F0l0d0s0f1e0e00000m3272566.Iw1%2FEA%3D%3D.IwBjdYtCg%3D%3D%3D.H4sIAAAAAAAAA32QsVLCUBBFFwkaSCAkKBMYMoOAWug4Y2lHaWFhYw9%2FQOknUPgRlnyCn%2BFHWFha2Khhr3vf%2BDJaaIqd%2B965e99mRUMR2TasRKt3IF18ALOHRAQ1nRPVrYSLVyB7MdnfbAHsaN93JWO73Y8VOHiMRHIep66%2FrsPKdPNp%2FU975lz3zMQkBHpBHpC7%2FM2zRTf00nc1V5ba6nZEDqkmVEdUx1TY1aV3Zt0TkfOrN2BwXRgK9dajkvMLecCSufc56cgN2fzhjP91tjT26xAi9%2BbI%2FUn0N2rrabXfO4tJJ6XtlwUdPatQYRfpvfEZFRItfGCcl9%2Brz7m%2FoZsF8uv7ArGRMt7FAQAA.HIQ2HpQrwBksCIFMQHMA2zxKA%3D%3D%3D
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.1960d2.js
line: 31
col: 221576
error: {}

**Comment by pnellesen** [comment]
I can reproduce when I use the code above. As a test, I set up a new Sidey with every module engineered:

https://coriolis.edcd.io/outfit/sidewinder?code=A1p0t0F0l3d0s3f117240m00B527P42i.AwRj4yg%3D.CwBjIRjAmbgqYg%3D%3D.H4sIAAAAAAAAA22QsUoDURBFR7NZN9lsNhuTmIgi6qpoERKxEUT0BySFIFamsbGyELQQbFJYWIlYWeQDLCwsLP0ACz9AJFiIiIVYiGic8c5CHiy4xWXemzN37j5im4h%2Bk5DuKcRdcIi8DIsEzgBRvvUqEj6gLX28bMgjiNP4EfE7VaLSlQXyHrj0c8lAexBfoUK5K1Js%2B0TllwTR5PEgyAQPG3JfyfBbJH%2FjEhUOiyCjnRbXFbK033xH%2F%2FpJRJK8aEZbkJTGTZ8FRONaTWg1pdW0VmJzs4f7B28wue2IVJc%2B4eTwhnE6gcw1IFGIaH8lN4P5FG8aCPEpqdb2%2BodIbh7HkYtnkdFLD2Sat2ObKrqkpuvEZS8e4u4RtxleM9Y72tJHCvTNwt0hGHo8a%2FrnEK%2BZIsrWvjDf1vxZXv3H1eet3m1e%2F6C%2BMgYvofj3Bx3a2376AQAA.EweloBjEoUwQwOYBtYhARgtoA%3D%3D%3D&bn=Engineering%20test

This code seems to work ok when I paste into FireFox - not getting any errors when opening the engineering sections. Seems to work ok in Chrome/IE as well.

screenshot: 
![image](https://user-images.githubusercontent.com/6032970/40869584-65bf147a-65e3-11e8-9f9a-5e9286996ba6.png)

**Comment by Josemaloco** [comment]
Same stack size error, different script. It happened on both Chrome and Microsoft Edge:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Path: /outfit/federal_corvette?code=A1putpFklndzsuf50x0x7l1b1b2020040404040404030jB00606-11Cd042dm9-6n2f.Iw18ZlA%3D.EwBj4zIRm9gMyjNUQ%3D%3D%3D.H4sIAAAAAAAAA42SPUsDcQzGo23Pvun1rm%2Bn1FrtqeBQKggiiJu4iSDuXVxEwUHBQQfBQZwcxMHJwQ%2Fg0MHRwdHBDyBSnIqIODloTcwj7Wmh4t3w8EB%2ByeWfhNggos%2BQSmwqTNQbZxEr3ENkHzyJuPcakS6ea0GNPZXw0oeIWSsRZS6DSt4pLt2c8aAtFRNQymmIpM9NIqceICoeJpUM8IBH7oB030XsqxhRajet5Pc%2FgzwJKIh45VXj1UcRCfGMl7qvEkG70ROLaBhuBG4UbgxODK60cHPnWYtc10RKs29aKczLXqUjlVAlQmSsv4g4kOJxXaHILyj%2FFxTllRZEiXGiIMTezOpLMJjBgj5cYj%2BVOhaJ%2FxM3ecHr5AzLujCaI7bgnBvNceEk4Zu0fJO2bzLpm0zxfBtpYu12ebsJDdXWFErzNKAAZovbsTHbHE5JMrzattt%2BrLWMBUuWF73SG4jjAC004WItkuNE%2B1ncPmhWnie8rFO0XlXbV8hpKpyNIi6cCHX%2BvgBip%2B9STQMAAA%3D%3D.EweloBhBmSQMwKYBNECcCGAbA%2BgYwHs0A3RAFzMRAGEjSLEACAGQwGd0QBlACwLIDmAVwB2IAJziAjEA&bn=Corvette%20Laser%2FShotgun
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.52b101.js
line: 11
col: 412158
error: {}

**Comment by willyb321** [comment]
Will take a look soon:tm:

Thanks for reporting

**Comment by pnellesen** [comment]
This seems to be related to the keyup/keydown handlers I added for the sliders - if I have them in focus and hit the Enter key I see this happen. It doesn't seem to happen once the text input is visible, only when the focus is on the svg element. I'll remove the keyup/down handler for now (it doesn't seem to happen using the click or touch handlers) and see if I can do this another way.

**Comment by felixlinker** [comment]
I was able to narrow this error down even more. In https://github.com/EDCD/coriolis/blob/master/src/app/pages/OutfittingPage.jsx#L224 `engagementRange` is `NaN` which cascades all the way down. This is the case for all broken builds provided in this issue and in #294. This likely has something to do with serialization which is hard to debug as we only have already broken builds at our hands.

Might reference to #339 

@willyb321 Would be great to have a second guess from you on how to proceed.
