### ISSUE TITLE
Corolis engineers vs recipes does not match Inaras list.

### ISSUE THREAD

**Issue by robbyxp1** [EDCD/coriolis#296]
The list of engineers and their recipes on Inara does not match the data in modules.json in modifications folder.

Now, i'm not sure which one is right, Inara or Corolis, but they don't match !

There are a lot which is wrong.  It needs a manual check I'm guessing against the game.

**Comment by willyb321** [comment]
Yeah, tbh I'm not sure how many people actually use the recipe and mat checks - not sure how to proceed.

**Comment by neilser** [comment]
Perhaps I'm one of the few people who does use Coriolis to check which engineers do which upgrades...

If it's not considered worth the grief to keep this up to date (this isn't meant to sound provocative!), probably best to strip out what's already there (on the basis that wrong is worth than useless). For example, I now realise I was misleading myself about a few things.

**Comment by alex-williams** [comment]
Resolved
