### ISSUE TITLE
Ranks link

### ISSUE THREAD

**Issue by RapidfireCRH** [EDCD/coriolis#298]
a very small feature request, but can i have the ranks link to some page that has all the ranks listed.  Like the gunship, having it link to the federal ranks, so i can see where my rank stacks up with the rank required

**Comment by pnellesen** [comment]
Would adding a simple link to the Elite Wiki Ranks page on the rank label be sufficient?

http://elite-dangerous.wikia.com/wiki/Federation/Ranks
