### ISSUE TITLE
Armor/shield resistance calculation and cap

### ISSUE THREAD

**Issue by ctrl-shift** [EDCD/coriolis#305]
Armor and shield resistances do not seem to have a cap, and in general calculations do not line up with what is in game if high resistances are present.
For example 
https://eddp.co/u/ZapMwyig - sidewinder with 99% thermal resist on hull.
https://eddp.co/u/4ukEGw2B - fdl with 91% kinetic shield resist.

**Comment by MartindForlon** [comment]
Can confirm that for shield boosters are wrongly imported (EDMC) shield values.

Export: https://coriolis.edcd.io/import?data=H4sIAJt1VVsC_-1b0W7jNhb9FcNYoC-pQFIkJWWfJpOmmTbZSeNgCuxiIdASbXMjS15KyjQt5t_3UlISSrYj2dGgO4vNPEziiEcUee65514qf0yvs7hMZD49_ccf03frdfYhfZ-ozfSUoJPm58tss5F6euoi-OiHdKlSKbVKl9PTP6ZnSSk38EPx4Xx6ionPPZeR4OTl87-JtZyeTn-VYpOl4UUWlbmMpy848LszlSSTu1Kn8NPLLwwg3BFhc9PfYAJqLdNCJD8sFjIqYFi-kZESSZhk0X0411Lc1-O3rg2vskgkytz3dHon9FIWE_jofnL2POhKPshkespOzHKohZK6XpArMTefT69FnleX5fmH_McsAyR8Mv2oFcxVJJ8EPO301Hdgqs333PFdFnD-5eQF5FysxVLeSD2TUZbGHTy0hUd8h5sv_xnVRQ7mlPJgG7YXzaUOheVE5AXNcxjy3Q6aygut5mWR6XMtPvc-NHOY9dA0cAPGbLy7ldRrkVxlIu7FwthaQc_xEPGwjfVOr7NS38hUFloUKkt7HxojZEFi5psZYtp64mvxm1qX61uRDllF1kLkPmMOxpzg1kRnq6yYbaTs32PfY_YEPew6nhcg5tpwt6KQHxcXSvfPDwHvzNczJHyAKEE7iHghkiRbLIY9N0Gt53YD7DkEBYQEX_55Mv2lhPgqHs3d0JeT6YdCruE2q00RbhKRr4WIIplI2LNMhwv1m4zDxIRhKOIHkUbVMn1Mp6eFLuXJ9EarTNdoJ9NZkplYvzKXXwodbzLQFDw1T_NNilWs4Dudw3cgMkncr1fnTwMmF82APq26yT7LYbGLncB73lLiuB7ivj-6YjFGO-HxJsVivk_JWIrFHA8zTshIikWRx7A_qmRR6iBKkeuNJlkex7BLPmXeKJLFA-RQEC5MR5QsDJMmI0uWz10ARox6f4JkkW9XsuaJSmOYTpivZJIMUCzx---JnMyaq_vk6kNayGW1eH0byqlNY-543IVcOa5eEbAdnAYBHUURfAcH1Gsn8zcrAoSvj70xPQwlTkARdUeyMMgBkmLkjWlhPEzI6BYGOYRhD_0ZFsbd0gO3KweEDpIDjuleObjK0uXT4liCcJfFk--A1JMzeLRC6u8m19EvpUrTbXkgvE8eFsCRuYASLBJ5JGIZRlmWyAHO5i97EVJ4iL-OVZXZosGcFokOcUr8hY8Qfx5lb9EdCGGXm3_PmDRwUAD__CN8Em7FHzH8HUG7uMOPV5h2qLEAc4cFAUfBG2MY7wdux7DPcTuKtVDJskyb2F3LWJXrcF7qvNgTueQ5cq-rizvVx4A87fmHBuaZzrLJndD_hmDckardvliUa5Xn6kGG6zJVJrfk_WH4QzNmcm2NaSKPjhZ51OGUBgQfF37I4VY24L7n-96xJIeChLesJkaEjsZ0FxFww4wR741MZ3txX09WZZJLUHWpW0zfw3G8j-NkIMc9f0fyma1MpXqWZSa3hJdSPDyel5W_s6h-rmI1-QSuADZuV-JBqI_seXWbeXObexhcqKif7xeZjkzmy6L7sVKMa1WUmLb1d7i9pXb_kFHHQ4wF3rH5iljpqp2r5EKCYXl63HqzrsukUJtENc3Q122UU-0OfckUpgBkvO1If67341bmUJ4bhzTA91lZzAnMl98hO_NM0WrzvU2CXP0uURgB_3PWK-t3Kn08WNT_T_ivR3hQYorwN0B4BkWi5wMfvjrhCXXdr0P4wQof9BK-fmSwEN8k4Y_kK9TMxK127L-fr9iHChq-xhRo36GM4sDdsmHHQ3LH82FFWykPtjrJjD19M2g7sIKvFFbbdT3eavP1VvWeiznn22EHmaWYqfT-SpRptKpTTfXBe7ERkepmnFuxhmJitR152PT8mrhw35QIoI59aag4Hgs6Am6evPHT_by1mzPtnHIrE7D2dxDy_TNq7X4AQeqhoMc0r2AZc1jG5Gldi1JrWYQF7GxvX6e1_bTa_gb6HmrOIlzfKxVGoEUbVfTacAj2zfvmWgtpbc7ohY6EXmZz8Rhnmd4DRZ-h3puLL0URrQYqPWc7lL7uVoZNZLf5NZOJTOXkJyl2NY56-8qihpZPEd4v7FfiUWoZT24SUZjn6Bf3jpZCvCTF6hAtZTadQPDbUn24hpJWr4bVWZ-_TUS_h2nVODYyDdgIWoobaN9q8EIB7cFHXUWlxg_t4H6zz1qKqDEJr8dATbmh9oR726St0jCQJC3C2qN0DkQupRagjKnaYUqCAdI43DJUx3dWb440J5pbpsFS8L6Ggy2TYESxEXQbzyQFCB4VKaD-44B-CLXaIZR3t5XZ2wprHG7MfDfV6po86b2eJ1_29WVXBgvSjoOuelh4rnQ33d3obAFPmunJDcx-lySR3v5ZDZ49SG0SzpAuNri95eRcA7HzUc0mJi3mILaPOYPspmc3vcC6ca8FVC_Ux02h1iLZkfh3EruVaAlH7ZT9DHkj9SIzJUAkjzj75j712yfLNbAhuTlTOsihgGX3uxWW71G3ze-GBIbbfCi3r4VK64nlQ8m9q666mJ3vaw1fyEQZgZhcCJ3LXSe5uLeeWuRxWGTlcgVpewi1s3KeQCGlRSTjsVoHpJVQ-bG9A0za9PPaifno1nKrRILtOCgmEGuXHiD3wGF_u_gwrTKbcqtH2IjYiEhFO_Y67V6854UG3oBnXBSVAg2hHtQWjJFt6l2rPIJKXqULUz0f_AZBww3ytmqiU7kdyY2A2xQDUBd5BLHuJvjmDM_ehURB_ig3m0zXmY0Ojf4rGDirBw61LW6wx7ZYbzOFl2q5utDy32WTyO0j3JWcnH-WSbJTCfw-JahyeGzdKrIqyNdV4X1Smhp50jiWTA_Je_WxVz7Y5fDWSSRxwIR0cl-DeCujlTlY70d0sJUAGWfE87fTyvAZUtxuBiHenWGDOHiG7YNqjjnzWoXB7BHWfT3mDBvEt82wk06RH-ywizbVBphG1DaNVkwMkjiKsLujfTKTKbjDvS9FKJGKyQXEcJnKHebRQ2O9kGCrnN-xTfUc65fUZ5FI36XLRB5WFBDcaZ4MOm8EhWxnVEoCx-XIZaS7xeb1S3uH82rO-RDH9LKxtyIW2u5xGKRFKROoS-_tLOj2yu8FjIJq7n6g9vp0b0f7RzBG9Ss-OxseV1JN3q9kWbUeuppLhnWzoQ5e1ncZ1PK4EHkB93wOz9HKC-x2XozHQbf3emtmusNk7-Cf1c12wbPbKGc6uweYwVh2kz1ov69zeLtluzMCljPAI_RctrvsrnmFp3sicEzPpeUiKaxB27pgu31ZxV9FrOUzd604dMOFGPCGi_kP4XBmBvY3sOmOu0dgReZPkTtYBKr7Euu-thaA-QGfMRePthrg_haqwXQrTNbFXJYCUpFI6znrJ7dros--CRk2cfr6Taqmrdy-CX39Jp0nYdVN6FBfiXf4yssySW5b09hzRN3f0P0Kb-TxV86-6n7tuzhWg16UrZoQL5FDqRO4PsJvPPbCDq00xK5McNUCfZuEDMM9qmm7H7lTAxGvUwOtgCvblHUPoiyvKOseGheH3cSzbvI_Ehf2ARhx_PHiAgetpjGkQHMc3P5DlWOOg4MOy8xf02A38N56JjwE97iD4b3I3aa36w6JC3IQZf2KssSOi3k2nycyjFYanmENqVrL_gOSs2oQwjuAYCEMI8IIBmXgIQdiYWRjxRL8J0Cs56IIJaxJ_5TOzZDWhDYClu1f2Ty0ToKWWsQK1o6ACY77zwsMwk_ZvKsj5uhBFmKz0ZmIVnk5ZH439Rj9-K4ZNquGWcjmnXNALqQxNBsVh3HV_UxMK3ieiOpVkv6z2w_n6GuA4j3Hygb1XhU4nJdrsGZkENzPqjirLu8DzTeZAqGmQ1Fn9fV9sIVQyWDMO7i4D_Az6H4-GPFXc_WeTbqHKM_BPA7fG5NK0Khorb1-yFQkN-ZvIx5kU9e9jvIJBFAmn8ywqRE1g9patulJwymotPzm-xhi0iSpC6hqmt83KfJcPijzR1yQ3qpLzBvWWWkKigJqVlCbtUEnkEu-R973xL1D_JT4p9T9-_TLfwDVTtzXW0AAAA%3D%3D

Real numbers are close to this: https://s.orbis.zone/LTwNBV-x (SB are not completelly maxed on lvl 5).

**Comment by felixlinker** [comment]
@MartindForlon This seems to be a bug related to importing your builds from EDMC as resistances are generally in a good range and wouldn't have been capped per module anyways.

Please open a separate issue for this :)

**Comment by felixlinker** [comment]
@willyb321 This can be closed as well afaik
