### ISSUE TITLE
Retrofit costs broken

### ISSUE THREAD

**Issue by andrewgoz** [EDCD/coriolis#31]
The retrofit costs are not calculated correctly unless I adjust the module discount percentage setting, which appears to force the module costs to be recalcuated. I've typically got my module and ship discounts set to the 15% LYR discount. I suspect the retrofit somehow defaults to only applying the discount to one of the loadouts and not both.

I also remember the old coriolis hiding modules that didn't change in the retrofit list.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  I tried to reproduce this problem at https://coriolis.edcd.io/ and couldn't.  Please could you describe exactly what you are doing, what you expect to see and what you are seeing differently?

**Comment by andrewgoz** [comment]
Sorry, I've figured out I was using 2.2.1 on http://coriolis.edcd.io/ (the non-secure one) v2.2.2 looks good.
