### ISSUE TITLE
Links from EDDiscovery and EDSM.net do not work

### ISSUE THREAD

**Issue by nsgallup** [EDCD/coriolis#310]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAAA7WWUW%2BbMBDHv4ufoyohJWnzOHWbIrVrp0p7mSbk2AdYMTY6m3as6nffYZKFQpMydcsL8Z35%2BXz%2B35knBg9gPFuxa8ulrTybsPtclWTYIlc%2BKbZKke3GykqDY6vvT2ztoSB%2FXvqk1NwVnAsBGpB7i0mqfoJMNMcMGpS2DTsMc46ytMr4GTluDVt5rGDC7lBZVL5mq%2Bnz5P3w6H%2FC5%2B%2BEFyBVVRzo7fifJeYN%2FNjUCFQFOMGNAUyc%2BgXTRNCKLj6QvTL1m2HP%2BlxtK%2FkX3GPx9rkuV6DlxlrnX4LnR8BjjvGg%2FoRjYStMMuQSOsjWPCJGWjEp7SMgnRv9bQJcDnZ%2BmDCSCCZTBgJtMaAVnHxhghux1waX1yWgRPXQIuMBMkVOqshV6sOsY9gJ%2BxjWBVQmY6sn9kFXUNLAr69oE9HFYjlfXM4nB%2FsX4jZ8R8VnDWXZhAK8psak2ep8wr5WXLcpCH1IpQqw7UTXfNPMYTcUKr3yjROTraKYYkNFUXC9N00boHNr99lauUvm%2Fu218ZCF8P8gZtP4LL6k38UANeuzpl3WXXOMV8gfD6zp2WIZDTBkPRHSp%2Fur29KrguuXW5vFUXQ23B6FOwjqx3PvhLVKwVVlabHV4Hl7xFGn2R1mjFRNUK1UzqPaVE0jOiHuzrSRdAfGWXRHNE7lyMeS0gq052bb1XanlPfuscVMZQqelyVaLnJXKd%2B5MXZOrPv%2BMeS2lWVgdn399Z07ekxnrXNkAgTdYxa52HaRsx4yOonsx5pXWiMok1oUUMCus8UDVQX0vHWORKcqy6mXb3jdZfbDPT%2FJ7GdgU2VZvScOtR%2BIces8Qpz3iBKtAWGNR6sTYbUG4ZU1gTF%2F%2FdAWrXOsap2kR1M5Yi%2BGI9zlSW7UV5kHTR82GytrKkphHwDr%2Fb3M5QM3AmRvgYuwwJgbuWi%2BFDkGwVG6pQ3lvmMFa869yI%2Fm%2BMfzbxxjPc%2BUCgAA
line: 0
col: 0
error: "No such ship found: \"krait_mkii\""

**Comment by willyb321** [comment]
beta.coriolis.edcd.io
