### ISSUE TITLE
Missing modules vs Frontier data

### ISSUE THREAD

**Issue by robbyxp1** [EDCD/coriolis#313]
From my autoscanning corolis vs excel frontier data, i've scanned the corolis data vs the excel from frontier.

This is the report.  Some of them of course could not be in-game, some could be errors in the frontier excel. Just reporting

Rob

Missing Weapon Hpt_ATMulticannon_Fixed_Indie_Fighter
Missing Weapon Hpt_BeamLaser_Fixed_Empire_Fighter
Missing Weapon Hpt_BeamLaser_Fixed_Fed_Fighter
Missing Weapon Hpt_BeamLaser_Fixed_Indie_Fighter
Missing Weapon Hpt_BeamLaser_Gimbal_Empire_Fighter
Missing Weapon Hpt_BeamLaser_Gimbal_Fed_Fighter
Missing Weapon Hpt_BeamLaser_Gimbal_Indie_Fighter
Missing Weapon Hpt_Cannon_Turret_Huge
Missing Weapon Hpt_CausticMissile_Fixed_Medium
Missing Weapon Hpt_FlechetteLauncher_Fixed_Medium
Missing Weapon Hpt_FlechetteLauncher_Turret_Medium
Missing Weapon Hpt_MultiCannon_Fixed_Small_Strong
Missing Weapon Hpt_Multicannon_Fixed_Empire_Fighter
Missing Weapon Hpt_Multicannon_Fixed_Fed_Fighter
Missing Weapon Hpt_Multicannon_Fixed_Indie_Fighter
Missing Weapon Hpt_PlasmaBurstCannon_Fixed_Medium
Missing Weapon Hpt_PlasmaRepeater_Fixed_Empire_Fighter
Missing Weapon Hpt_PlasmaRepeater_Fixed_Fed_Fighter
Missing Weapon Hpt_PlasmaRepeater_Fixed_Indie_Fighter
Missing Weapon Hpt_PlasmaShockCannon_Fixed_Medium
Missing Weapon Hpt_PlasmaShockCannon_Gimbal_Medium
Missing Weapon Hpt_PlasmaShockCannon_Turret_Medium
Missing Weapon Hpt_PulseLaserStealth_Fixed_Small
Missing Weapon Hpt_PulseLaser_Fixed_Medium_Disruptor
Missing Weapon Hpt_PulseLaser_Fixed_SmallFree
Missing Weapon Hpt_Pulselaser_Fixed_Empire_Fighter
Missing Weapon Hpt_Pulselaser_Fixed_Fed_Fighter
Missing Weapon Hpt_Pulselaser_Fixed_Indie_Fighter
Missing Weapon Hpt_Pulselaser_Gimbal_Empire_Fighter
Missing Weapon Hpt_Pulselaser_Gimbal_Fed_Fighter
Missing Weapon Hpt_Pulselaser_Gimbal_Indie_Fighter
Missing Weapon Hpt_Guardian_ShardCannon_Fixed_Large
Missing Weapon Hpt_Guardian_ShardCannon_Fixed_Medium
Missing Weapon Hpt_Guardian_ShardCannon_Turret_Large
Missing Weapon Hpt_Guardian_ShardCannon_Turret_medium
Missing Weapon Hpt_Guardian_PlasmaLauncher_Turret_Large
Missing Weapon Hpt_Guardian_PlasmaLauncher_Fixed_Large
Missing Weapon Hpt_PlasmaShockCannon_Fixed_Large
Missing Weapon Hpt_PlasmaShockCannon_Gimbal_Large
Missing Weapon Hpt_PlasmaShockCannon_Turret_Large

Modules:

Missing Module Int_DroneControl_Decontamination_Size1_Class1
Missing Module Int_DroneControl_Decontamination_Size3_Class1
Missing Module Int_DroneControl_Decontamination_Size5_Class1
Missing Module Int_DroneControl_Decontamination_Size7_Class1
Module Int_DroneControl_ResourceSiphon_Size7_Class5 incorrect mass 90 vs 80
** Fighter so corolis won't be worried Missing Module Int_Engine_Fighter_Class1
Module Int_Hyperdrive_Size8_Class1 incorrect power draw 0 vs 0.56
Module Int_Hyperdrive_Size8_Class2 incorrect power draw 0 vs 0.63
Module Int_Hyperdrive_Size8_Class3 incorrect power draw 0 vs 0.7
Module Int_Hyperdrive_Size8_Class4 incorrect power draw 0 vs 0.88
Module Int_Hyperdrive_Size8_Class5 incorrect power draw 0 vs 1.05
Missing Module Int_MetaAlloyHullReinforcement_Size1_Class1
Missing Module Int_MetaAlloyHullReinforcement_Size1_Class2
Missing Module Int_MetaAlloyHullReinforcement_Size2_Class1
Missing Module Int_MetaAlloyHullReinforcement_Size2_Class2
Missing Module Int_MetaAlloyHullReinforcement_Size3_Class1
Missing Module Int_MetaAlloyHullReinforcement_Size3_Class2
Missing Module Int_MetaAlloyHullReinforcement_Size4_Class1
Missing Module Int_MetaAlloyHullReinforcement_Size4_Class2
Missing Module Int_MetaAlloyHullReinforcement_Size5_Class1
Missing Module Int_MetaAlloyHullReinforcement_Size5_Class2
Missing Module Int_PassengerCabin_Size2_Class0
Missing Module Int_PassengerCabin_Size3_Class0
Missing Module Int_PassengerCabin_Size4_Class0
Missing Module Int_PassengerCabin_Size5_Class0
Missing Module Int_PassengerCabin_Size6_Class0
Missing Module Int_ShieldGenerator_Size1_Class1
Missing Module Int_ShieldGenerator_Size1_Class2
Missing Module Int_ShieldGenerator_Size1_Class3
Missing Module Int_ShieldGenerator_Size1_Class4
Module Int_ShieldGenerator_Size1_Class5_Strong incorrect mass 2.5 vs 2.6
Module Int_GuardianShieldReinforcement_Size4_Class2 incorrect power draw 0.949999988079071 vs 1.05
Module Int_GuardianFSDBooster_Size1 incorrect power draw 0.349999994039536 vs 0.75
Module Int_GuardianFSDBooster_Size2 incorrect power draw 0.349999994039536 vs 0.98
Module Int_GuardianFSDBooster_Size3 incorrect power draw 0.349999994039536 vs 1.27
Module Int_GuardianFSDBooster_Size4 incorrect power draw 0.349999994039536 vs 1.65
Module Int_GuardianFSDBooster_Size5 incorrect power draw 0.349999994039536 vs 2.14
Missing Module Int_GuardianHullReinforcement_Size1_Class1
Missing Module Int_GuardianHullReinforcement_Size1_Class2
Missing Module Int_GuardianHullReinforcement_Size2_Class1
Missing Module Int_GuardianHullReinforcement_Size2_Class2
Missing Module Int_GuardianHullReinforcement_Size3_Class1
Missing Module Int_GuardianHullReinforcement_Size3_Class2
Missing Module Int_GuardianHullReinforcement_Size4_Class1
Missing Module Int_GuardianHullReinforcement_Size4_Class2
Missing Module Int_GuardianHullReinforcement_Size5_Class1
Missing Module Int_GuardianHullReinforcement_Size5_Class2
Missing Module Int_GuardianModuleReinforcement_Size1_Class1
Missing Module Int_GuardianModuleReinforcement_Size1_Class2
Missing Module Int_GuardianModuleReinforcement_Size2_Class1
Missing Module Int_GuardianModuleReinforcement_Size2_Class2
Missing Module Int_GuardianModuleReinforcement_Size3_Class1
Missing Module Int_GuardianModuleReinforcement_Size3_Class2
Missing Module Int_GuardianModuleReinforcement_Size4_Class1
Missing Module Int_GuardianModuleReinforcement_Size4_Class2
Missing Module Int_GuardianModuleReinforcement_Size5_Class1
Missing Module Int_GuardianModuleReinforcement_Size5_Class2
Module Int_GuardianPowerDistributor_Size2 incorrect power draw 0.620000004768372 vs 0.73
Module Int_GuardianPowerDistributor_Size3 incorrect power draw 0.620000004768372 vs 0.78
Module Int_GuardianPowerDistributor_Size4 incorrect power draw 0.620000004768372 vs 0.87
Module Int_GuardianPowerDistributor_Size5 incorrect power draw 0.620000004768372 vs 0.96
Module Int_GuardianPowerDistributor_Size6 incorrect power draw 0.620000004768372 vs 1.07
Module Int_GuardianPowerDistributor_Size7 incorrect power draw 0.620000004768372 vs 1.16

**Comment by rlsg** [comment]
According to http://coriolis.io as of time of writing.

- Guardian Shard Cannon (Fixed M/Fixed L) are available
- Guardian Plasma Charger (Fixed M/Turreted M) are available

- [ ] Guardian Shard Cannon (Turreted M/Turreted L are not available.
- [ ] Guardian Plasma Charger (Fixed L/Turreted L) are not available.

**Comment by rlsg** [comment]
- [ ] Fixed M Shock Cannon is missing
- [ ] Fixed L Shock Cannon is missing
- [ ] Turreted M Shock Cannon is missing
- [ ] Turreted L Shock Cannon is missing
