### ISSUE TITLE
Guardian shield reinforcements not available in restricted military slots

### ISSUE THREAD

**Issue by faybs** [EDCD/coriolis#314]
This reproduces on beta 2.9.17 - 2018-07-03.

Repro steps:
1. Create a new ship that has restricted military optional slots (eg. Viper Mk.IV)
2. Select a restricted optional slot and look at the menu with available modules to add to that slot

Expect:
To see Guardian Shield Reinforcement modules

Actual:
Only see SCBs, module and hull reinforcements

**Comment by Thurion** [comment]
Guardian hull and guardian module reinforcements can also be put in those slots.
