### ISSUE TITLE
Send to EDEngineer sending wrong modules and no experimental

### ISSUE THREAD

**Issue by HWG90** [EDCD/coriolis#316]
Sending to ED Engineer [this build](https://beta.coriolis.edcd.io/outfit/krait_mkii?code=A4pptkFflidussf57l1e1e27270404040jB1fm2d2d2bm5m56b.Iw18WQ%3D%3D.Aw18WQ%3D%3D.H4sIAAAAAAAAA42SoU4DQRCGh%2Fau9Nqj17tey7WUBOgBSUUDkoRgMYTUUYEAgUEhEBUkBFdNCEEieABEBRLBA%2FAAiAaFQKBIgDLD%2FIRuEJDcismf%2FN%2FOzM4scZaIPm0Nw1MN%2Be03Eb%2F3LhJfekQyxmvGP9aQbX%2BIeIMWUeXaIgruxxVKccVAhxo8QGE0FCkjSfSUJmr0SkqmuWbILshYKwU3eaLwqKzkgzpi8TIgC%2F7Oi%2Fr9RxGxecVcPdHguCySO%2FOJZqHmoOahFqAkw7sjPCguErVWX0WqG9NqZbljMmlnZKFduzNFlEEnDTxMHN4yEF7XbCMT%2FO8mq8gpuSRQ%2Flc5%2Bq%2BcmwSa4HUDXWBZV5mfYftQ0Z1DFENJITHpJSaLvDcive6zDhMTXbod6G583jRJ9uFj7T6SxAeTerXETeOfo0hfZWGmrhBUADyGkjAxWU5MRlwHmdLgop0In7aGnydCf50vFaSnqxUDAAA%3D.CwegTCAMUgzB0CGA7RBjA9sgJokIBGSYoA%3D%3D&bn=Eh)

Results in no experimental effects being applied, and weapons and other modules being mismatched, IE it is adding Plasma Accelerators and Cannons - when the weapoons are MC's and Pulses.

**Comment by willyb321** [comment]
No experimentals is fixed in the next EDEngineer release

Weapon blueprints are generic in Coriolis so the second issue cannot be fixed without a lot of code changes. IIRC all the weapon blueprints have the same mats so the shopping list doesn't have the wrong mats on it

¯\_(ツ)_/¯
