### ISSUE TITLE
Missing and wrong mod exports (to EDEngineer)

### ISSUE THREAD

**Issue by MBGTBenjamin** [EDCD/coriolis#317]
o7, I have discovered that a few mods and/or experimental effects are not exported:

Missing experimental effects:
- All Hull Experimentals
- Shield: Stripped down; double braced; force block; thermo block

Missing modifications: 
- Hull: Lightweight
- Power Plant: Overcharged
- Life Support: Lightweight
- All drones: lighweight
- All Miscs: lightweight

I have tested almost all modules except the weapons for export errors, so there may be something wrong (with the weapons).

**Comment by willyb321** [comment]
Unfortunately this is a result of coriolis using generic weapon BPs and EDEngineer using per-weapon BPs. Will close this for now.
