### ISSUE TITLE
Thruster Blueprints Still Use Range for Negative Effects

### ISSUE THREAD

**Issue by LivewareCascade** [EDCD/coriolis#318]
Projected thruster modifications still have minimum and maximum allowable values for negative effects, whereas with Engineering post 3.0 update, the negative effects are fixed and only positive effects are used.

This seems to affect all thruster blueprints.

Tested with 3A Enhanced thrusters and 3A thrusters, most likely module size/class independent. Suspect this is a holdover with Coriolis attempting to use pre-3.0 calculation methods with updated 3.0 values.

**Comment by LivewareCascade** [comment]
Can confirm this applies across all ships/thruster types.

**Comment by felixlinker** [comment]
Same for rate of fire value in the high capacity blueprint for missile racks.
