### ISSUE TITLE
Security Error...

### ISSUE THREAD

**Issue by Dellonman** [EDCD/coriolis#32]
SecurityError (DOM Exception 18): Attempt to use history.pushState() more than 100 times per 30.000000 seconds

Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0.1 Safari/602.2.14
Path: /
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/lib.55de2b.js
line: 74
col: 4823
error: {"code":18,"name":"SecurityError","message":"Attempt to use history.pushState() more than 100 times per 30.000000 seconds","line":93,"column":1926,"sourceURL":"https://coriolis.edcd.io/app.716c60.js"}

**Comment by cmdrmcdonald** [comment]
Same issue as #34
