### ISSUE TITLE
[Suggestion] Add Shortened access links

### ISSUE THREAD

**Issue by Marenthyu** [EDCD/coriolis#33]
The current implementation generates VERY long links that sometimes don't even fit into one standard IRC message.

I would like to suggest adding a shortened link that may be generated and then used if the user wants to.

This could either be done by creating a link shortener, using services like [bit.ly's API](https://dev.bitly.com/api.html), [yourls](https://yourls.org/) or other means.

**Comment by cmdrmcdonald** [comment]
Bitly has a monthly limit; are you aware of any URL shorteners that have an API and don't have limits (and, preferably, an account)?

**Comment by Marenthyu** [comment]
As linked above, we set up our own linkshortener for the fuel rats. If php is enabled on the webserver, it has a very easy to use API. (As in, a simple HTTP GET which returns a json object)

An example (in python) how we use it can be seen here: [FuelRats/pipsqueak/blob](https://github.com/FuelRats/pipsqueak/blob/master/sopel-modules/rat-shortener.py)

Otherwise, the goo.gl shortener API has a default limit of 1,000,000 requests per day, which i assume should be enough for this application. (Unless someone decides to maliciously abuse it) [link](https://developers.google.com/url-shortener/v1/getting_started#quota)

**Comment by cmdrmcdonald** [comment]
I don't have access to the server on which coriolis runs so can't do anything internally.

I checked google and the public one is no longer available (it returns a quota exceeded message).  I may well just go down the authenticated route.

**Comment by cmdrmcdonald** [comment]
There should be a shortener set up on http://beta.coriolis.edcd.io/ - it's on the right-hand side next to the other icons.  Please could you give it a go and let me know if it works for you?

**Comment by Marenthyu** [comment]
Works as expected! Well done :)
