### ISSUE TITLE
Cannons - Experimental Effects -Force Shell

### ISSUE THREAD

**Issue by johnnavarra** [EDCD/coriolis#335]
Expected: 
Force Shell no longer adds jitter. It has a reduced shot speed (-17%).

Actual:
![image](https://user-images.githubusercontent.com/11891698/43263445-45967492-90b1-11e8-8308-26e78c7de6c4.png)

Steps to reproduce:
Add a Cannon (Class 1)
Add a Overcharge blueprint
Add Force Shell experimental effect
See that jitter is still being added and shot speed remains unchanged.

**Comment by felixlinker** [comment]
To enhance on this here is a C1 gimballed and modded cannon.

![image](https://user-images.githubusercontent.com/9728715/44301578-c89c5a80-a319-11e8-86a3-2c5bb4b5a116.png)

**Comment by felixlinker** [comment]
The fact that shot speed is reduced to 1000ms suggests that forcel shell reduces the shot speed actually by `16.6...%`.

**Comment by felixlinker** [comment]
@willyb321 Can be closed.
