### ISSUE TITLE
Guardian Power Distributor Serialization Issues

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#339]
When equipping a guardian power distributor of class >= 4, it will be stored badly.
When re-loading the build (by reloading the page or saving it and loading it again), a class 1 power distributor will be equipped.
The mapping corresponds to the following table:

Actually equipped | Equipped on reload
--- | ---
Guardian 4A | 1A
Guardian 5A | 1B
Guardian 6A | 1C
Guardian 7A | 1D
Guardian 8A | 1E

Steps to reproduce:
1. Create a new build with a ship that fits a PD of class >= 4
2. Equip any Guardian PD of class >= 4
3. Reload the page

**Comment by rlsg** [comment]
Already reported via #330 - this ticket provides better information though.

**Comment by felixlinker** [comment]
Fix works fine.

**Comment by felixlinker** [comment]
Hauler and sidewinder have 5A Guardian Power Distributor equipped by default.
