### ISSUE TITLE
Cannot enter engineer values using iOS with/without keyboard

### ISSUE THREAD

**Issue by woodbane** [EDCD/coriolis#34]
Firstly, FANTASTIC job on the incredible job you guys are doing with the new version of Coriolis, it simply is the best tool in my ED box.

OK, so when I try to adjust a value using the Modifications button on an iOS device, you cannot enter any numbers as the keyboard does not appear when clicking on the number. This is regardless of whether using the device with the built in software keyboard or with a Bluetooth keyboard attached.

If I try sliding the bar to make the adjustment, after a few "slides" I get the following error:

Jameson, we have a problem..

SecurityError (DOM Exception 18): Attempt to use history.replaceState() more than 100 times per 30.000000 seconds

Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (iPad; CPU OS 10_1_1 like Mac OS X) AppleWebKit/602.2.14 (KHTML, like Gecko) Version/10.0 Mobile/14B100 Safari/602.1
Path: /outfit/type_6_transporter?code=2p5tdFal8das8f42l2l030005040420C040P42f.Iw1%2FkA%3D%3D.AwiMIypI.&bn=Mining%20Build
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.716c60.js
line: 93
col: 2083
error: {"code":18,"name":"SecurityError","message":"Attempt to use history.replaceState() more than 100 times per 30.000000 seconds","line":93,"column":2083,"sourceURL":"https://coriolis.edcd.io/app.716c60.js"}
2.2.2 - 2016-11-22

Any ideas?

**Comment by cmdrmcdonald** [comment]
This is an issue with iOS and react.  The only way to work around it is to force a reload when this error occurs, which now happens in 2.2.15.
