### ISSUE TITLE
2.2.2 (and beta 2.2.3) still unable to load JSON from EDMC

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#35]
I'm not sure what is wrong. I read from the 2.2.2 release notes that it "Fix import and export of ships with modifications, bump schema version to 4" but it does not import, at least with the lastest EDMC version 2.2.4 that I just upgraded to, or I am supremely dumb. Or does it mean that it only imports backups that you did with it, which is kinda useful but if you can't import engineer mods from EDMC, that's almost useless. With all the changes through the various versions and the lost of countless engineer mods that I painstakingly entered, I just stopped wasting my time and just waited for when coriolis will finally accept the JSON from EDMC. I specifically chose Coriolis as my preferred shipyard but that doesn't seem to make any difference. 2.2.3 also barfs at the JSON file attached.

So, is coriolis 2.2.2 (and I would assume beta 2.2.3) supposed to be able to load those files from EDMC or not? It's currently broken. As in "Cannot Parse the data!"

[Beluga Liner.2016-11-23T22.28.09.zip](https://github.com/EDCD/coriolis/files/610433/Beluga.Liner.2016-11-23T22.28.09.zip)

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  It should be fixed in the latest beta.  Please could you give it a go and see if it works now?

**Comment by cmdrmcdonald** [comment]
Fixed as part of 2.2.3 release.
