### ISSUE TITLE
Failed to import ship

### ISSUE THREAD

**Issue by lordpoppington** [EDCD/coriolis#36]
With ED Market connectors latest update they added auto ship update, It has worked with my anaconda but with my diamond back explorer I am getting the Failed to import ship error

Browser: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIALtJNlgC_61YW2_rNgz-L37OCt1t9a1tTi9DNxRNsR3goDDUWGmE41iGbHfNivz3UXZuStIeJ9hTQlkkP5IfKdkf0Vi5Vxudf8CfUo1NPY_OsVgMoonTOjqfqLzSIDQ693tmyhThXkpgr9OVdm86fILOOFnAQ5NF50QMopnNmlxXftOFm9nGtQbbRf8v8Od1MElEjBNKBlGhZvAsGho1s0V2qcY_v9-nnZH0xqlM42gQWUBWuwa0S2es6yIZRE2RW1VoMIgG0ZvKG7CEPK5L-_KSa4Sj8x_Pa4kEEg0kFkg8kEQgxYGUBJLcljDqpKEeqxz3SIiIYy42CfFq6bf3MrdOu_RB1dOJKTLtTkhHa4v0qQkhbBfCg3p_cAYWTvRLe_qlu6HffD_B5bfi1RT6yuYtCX3-rx1YHU3NpB460xH5azRIMExIS2ozMdq1tNatXe3uhtAXCGGEuv1S0mDnj49VFLCYzlRVQRD1vNQt7BXSMxqTWGKeJBS80cUg0JpqldfTA3q_oTMsacwRZhRxjPmOYgnuIMS0tP-0PNn3iyVjSHCZQJQ02VGfVFlqy9rMTKW_wM5wTChoxzGRgvWCQLZDQBgLLqgUSCKZbBuofb-3jndzQLb8I8pkIkmcxIJyShfPq_nzpF59BbB49mNrbErtq9XyiwrJBlGV2_oOeujdT63Fmm93RZ3eghuXeYKkI_Ov5ulVDjD4JwxEKwf3-s1PT76S_-wsXo-G6b0tXh9V8eobp3v41zKCw_RllCZUYE_iaxjJT6r42YurlKMgkpXydhy0TycBF-UGTit5MPdwiOhb5bLSmqJejtR7M9Gjpiytq_s1FJMByC39FiftcJLP830oZYnAzEP8A46urvGrXmhQLHu2Nzj4or07rY6w4wZOyXTW5LUpc_NZ-yEkMCZAeyH32u_Ltoe5HEuZECEI2dFbogD1-rAyAV9cQtw8lggf1t7EcNgGYlIizoWnKEnI8YMHIk8E4glDBInjex7mBUYkoZglJJE9MhBoc1CM4ZRhAD7G-xMjPjQxRBxODB5OjI5wLXvZL9kbTAu6My2Wlp4aT-9-w4JDNmVLfZ2ZZrbbnjury5vPA7RJ_bt96XUgxwlbh7tSTMNb2mUOv9fOZGqeolOuaQ85LNfKzS_K0lk1no4aU-te8KCeQTU6U6GdHoAY4ZsBDBX2oDyHh6aqnXlpauv6zTfJQjg7RnrS5FCmCMM4WQPzcfYbuYjG-5BKr96CIV-fcJ-UDUP7y_aMelSZ6pcbQsLZP9JFZV31P8z9EXQnwl1u-1ywoaXl3lk5GltbbteHH1sfSuHAWOMhffH4s5vhAM-Vf2F7hK7axnNkZxGJY7lGQ7s09yuU2CnU1Og8u9GFdmrF4dMKhrnsWNNiYn0xwTsi4TTANHTWX--L2tm8u-o4VVQT3aHDJ1UQbqKb8vGuO_rQiXIRlm9U6zxX7tJmc-j9sX3Tbj4aqwISmF5kb6oYtwP-qH7DlPAW3ZMp5ttz_pcFZZLjTfJuS6DXVE0m96opxlNA5A0e2Xcc7UNZHi7BGj2wtnzF_lur0habF7TF4U8A0drpRzRt8tynIgESxVsfGxLGpfDfELbvsBzeihb_AfBwP4b7EAAA
line: 0
col: 0
error: {}

**Comment by Marenthyu** [comment]
Entering the url manually gives the following additional error code:
{"errno":-3,"code":"Z_DATA_ERROR"}

Hope it helps.

**Comment by cmdrmcdonald** [comment]
It sounds like the URL has been truncated.  Are you cutting and pasting the URL from somewhere, or is it going directly in to a browser?  IE and Edge are known to have issues with long URLs so it might be something to do with that.  Have you tried it with Chrome?

**Comment by lordpoppington** [comment]
I am using chrome, I am getting the URL from https://www.edsm.net/user/fleet/id/14696/cmdr/LordPoppington 
There is also an issue with my anaconda showing a 7d fighter bay in a 5 slot

**Comment by Marenthyu** [comment]
note that Markdown is screwing with the link in here a bit. Here is a direckt link to it. Same error as derscribed can be seen in chrome.

[LINK](https://coriolis.edcd.io/import?data=H4sIAOLHNlgC_61YW2_rNgz-L37OCt1t9a1tTi9DNxRNsR3goDDUWGmE41iGbHfNivz3UXZuStIeJ9hTQlkkP5IfKdkf0Vi5Vxudf8CfUo1NPY_OsVgMoonTOjqfqLzSIDQ693tmyhThXkpgr9OVdm86fILOOFnAQ5NF50QMopnNmlxXftOFm9nGtQbbRf8v8Od1MElEjBNKBlGhZvAsGho1s0V2qcY_v9-nnZH0xqlM42gQWUBWuwa0S2es6yIZRE2RW1VoMIgG0ZvKG7CEPK5L-_KSa4Sj8x_Pa4kEEg0kFkg8kEQgxYGUBJLcljDqpKEeqxz3SIiIYy42CfFq6bf3MrdOu_RB1dOJKTLtTkhHa4v0qQkhbBfCg3p_cAYWTvRLe_qlu6HffD_B5bfi1RT6yuYtCX3-rx1YHU3NpB460xH5azRIMExIS2ozMdq1tNatXe3uhtAXCGGEuv1S0mDnj49VFLCYzlRVQRD1vNQt7BXSMxqTWGKeJBS80cUg0JpqldfTA3q_oTMsacwRZhRxjPmOYgnuIMS0tP-0PNn3iyVjSHCZQJQ02VGfVFlqy9rMTKW_wM5wTChoxzGRgvWCQLZDQBgLLqgUSCKZbBuofb-3jndzQLb8I8pkIkmcxIJyShfPq_nzpF59BbB49mNrbErtq9XyiwrJBlGV2_oOeujdT63Fmm93RZ3eghuXeYKkI_Ov5ulVDjD4JwxEKwf3-s1PT76S_-wsXo-G6b0tXh9V8eobp3v41zKCw_RllCZUYE_iaxjJT6r42YurlKMgkpXydhy0TycBF-UGTit5MPdwiOhb5bLSmqJejtR7M9Gjpiytq_s1FJMByC39FiftcJLP830oZYnAzEP8A46urvGrXmhQLHu2Nzj4or07rY6w4wZOyXTW5LUpc_NZ-yEkMCZAeyH32u_Ltoe5HEuZECEI2dFbogD1-rAyAV9cQtw8lggf1t7EcNgGYlIizoWnKEnI8YMHIk8E4glDBInjex7mBUYkoZglJJE9MhBoc1CM4ZRhAD7G-xMjPjQxRBxODB5OjI5wLXvZL9kbTAu6My2Wlp4aT-9-w4JDNmVLfZ2ZZrbbnjury5vPA7RJ_bt96XUgxwlbh7tSTMNb2mUOv9fOZGqeolOuaQ85LNfKzS_K0lk1no4aU-te8KCeQTU6U6GdHoAY4ZsBDBX2oDyHh6aqnXlpauv6zTfJQjg7RnrS5FCmCMM4WQPzcfYbuYjG-5BKr96CIV-fcJ-UDUP7y_aMelSZ6pcbQsLZP9JFZV31P8z9EXQnwl1u-1ywoaXl3lk5GltbbteHH1sfSuHAWOMhffH4s5vhAM-Vf2F7hK7axnNkZxGJY7lGQ7s09yuU2CnU1Og8u9GFdmrF4dMKhrnsWNNiYn0xwTsi4TTANHTWX--L2tm8u-o4VVQT3aHDJ1UQbqKb8vGuO_rQiXIRlm9U6zxX7tJmc-j9sX3Tbj4aqwISmF5kb6oYtwP-qH7DlPAW3ZMp5ttz_pcFZZLjTfJuS6DXVE0m96opxlNA5A0e2Xcc7UNZHi7BGj2wtnzF_lur0habF7TF4U8A0drpRzRt8tynIgESxVsfGxLGpfDfELbvsBzeihb_AfBwP4b7EAAA)

**Comment by cmdrmcdonald** [comment]
Turns out that the issue was me mixing up the two Diamondback variants.  This should now be fixed in beta - please could you try the same URL but starting with 'http://beta.coriolis.edcd.io/' rather than 'https://coriolis.edcd.io/' (note that the beta site is not HTTPS) and let me know if this is fixed?  Thank you.

**Comment by lordpoppington** [comment]
It is now working on the beta site, thank you [(link)](http://beta.coriolis.edcd.io/outfit/diamondback_explorer?code=0p0tdFflddisdf5---00---320343F42f.AwRj4yKA.CwRgDBlV5iQ%3D.H4sIAAAAAAAAA2P6J8HAwPCXGUiIvgOS%2FAF%2F%2F%2F9XVvz2%2F78I77%2F%2F%2FyXeA8WEGBgZGP4z%2F5MCqWQFEkIB%2FECVHT%2BB8rzsDAwiPgJA%2Bf8AFTWjAksAAAA%3D)

**Comment by cmdrmcdonald** [comment]
Fixed as part of 2.2.3 release.
