### ISSUE TITLE
Large Fixed Plasma Charger power draw incorrect

### ISSUE THREAD

**Issue by tarogre** [EDCD/coriolis#360]
I was making a power crucial build for going out to the gnosis for the cone sector jump and because i have limit unlocks. When I went to make it in game however it was incorrect and found it to be the large fixed plasma chargers. In game the power draw is 3.10 MW however on coriolis it is 1.39MW.

**Comment by felixlinker** [comment]
Could you provide us with a screenshot of the plasma charger? Either in outfitting or on the right-havend side when clicking details in the modules section.

**Comment by tarogre** [comment]
![image](https://user-images.githubusercontent.com/23597369/44995677-d54fbe00-af69-11e8-880e-cbb3f60d5bd5.png)

**Comment by willyb321** [comment]
Fixed on beta.coriolis.io

Will close when hits live.
