### ISSUE TITLE
Wrong power consumption values on krait build

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#363]
[This](https://coriolis.io/outfit/krait_mkii?code=A4pptkFfliduspf50v0v7l1z1z04040b0gB10537Ce6l6v0M2f.Iw18WQ%3D%3D.IwBhtdmmZBmYAWaIg%3D%3D%3D.H4sIAAAAAAAAA42RrUsDcRjHH93dvG3n7mVv55SNbac2mVEwrIgmESwDFS4ZRMGgsLBiW9NgXDD4BxgMxgWjwWgQEYMsiBhEUOfz%2BDzD%2FWAwYRe%2BPNzzeb6%2F5wXQAIAfnaVzzBLb%2FCRyGl9E%2FpkFQCNYUfk6i9F8JnJvxwDSPkM0immVP2Cx1r6Jkl6HKCX1XjsEUGok2CmEWUXWhJR69yoGkKynmLznDGk4L5Am%2BeCN85dP%2FIiOC6r0iCViIlH01AEoSFSUaFqiGYkojEEPt2ovbNJ6JJpb%2FGAnA9eVU45FDyIA4d1XIk%2BkdNJmKDIMFMWqgnhG0GRwvTrJpMxUuuAZKIYbCipIO%2BVDANeeBcjsZxhaeWcncxhoHJcV1JQ7nYf%2Flu1I5F1zi75EFMelPtKSxbri2YXyd3GGLNzuW9GEbKcseyIb9%2F5LObiqrHckLyd2pAlfOqUE5tT1Wlv8YCXPf5No95%2Fj5oG9UjjVY02Z1ROvbPdIaSwOKCAY9P0C1L6vesACAAA%3D.EweloBhBmUDYAsICmBDA5gG2SEBGCQoA&bn=Scylla) has some issues:
* Power consumption of large gimballed beam is too high (should be `0.83MW`)
* Power consumption of drives is too low ( should be `8.47MW`)

**Comment by LesserHellspawn** [comment]
![beam](https://user-images.githubusercontent.com/37193224/45119455-d1838d80-b15b-11e8-9753-ab8f23180c7e.jpg)
![thrusters](https://user-images.githubusercontent.com/37193224/45119456-d1838d80-b15b-11e8-9c73-fb781f55c6c7.jpg)

**Comment by felixlinker** [comment]
Latter of the issue actually already was fixed in https://github.com/EDCD/coriolis-data/commit/da60bb4f2ebe519f263c67561add5c610ec925bb.
