### ISSUE TITLE
Suggest reduce the width of some columns on master table to aid navigation.

### ISSUE THREAD

**Issue by GraXXoR** [EDCD/coriolis#366]
Ship-screen real estate is at a premium, could be possible to abbreviate the ship manufacturers to fewer letters to fit on smaller screens and MFDs.
Here are examples of reducing the Manufacturer to 5 letters for example.

MANFAC
-------------
ＣｏｒｅＤ
ＦａｕｌＤ
Ｇｕｔａｍ
Ｌａｋｏｎ
ＳａｕｄＫ
ＺｏｒｇＰ

**Comment by felixlinker** [comment]
Another idea would be to move the manufacturer to the rightmost column? This would still make it readable and give even more space for the "important" stats.
