### ISSUE TITLE
Importing Beluga Liner leaves a class 5 internal slot empty

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#37]
All the internal slots on my Beluga Liner are filled with a module. After importing from EDMC (yay it's now working!), one of the restricted class 5 internal slot remains empty. It's currently equipped with a class 5 luxury cabins.

[Beluga Liner.2016-11-23T22.28.09.zip](https://github.com/EDCD/coriolis/files/612047/Beluga.Liner.2016-11-23T22.28.09.zip)

**Comment by cmdrmcdonald** [comment]
This should be fixed on beta.coriolis.edcd.io - please could you confirm?

**Comment by nemesyssoft** [comment]
Fixed, thanks!
