### ISSUE TITLE
Resistances calculation is not correct when adding multiple sources

### ISSUE THREAD

**Issue by Sheuzzo** [EDCD/coriolis#374]
as in topic, reference for resistance calculation is not correct, these are the damage resistance sources

https://forums.frontier.co.uk/showthread.php/266235-Kinetic-Resistance-Calculation?p=4230114&viewfull=1#post4230114
https://forums.frontier.co.uk/showthread.php/286097-Shield-Booster-Mod-Calculator?p=4998592&viewfull=1#post4998592

                var getEffectiveDamageResistance = function(baseres, extrares)
		var res = 1 - ((1 - baseres / 100) * (1 - extrares / 100));
		var softcap = 1 - ((1 - baseres / 100) * (1 - 0.3));
		return 100 * (res - max(0, (res - softcap) / 2));
	

source: edshipyard webpage code and forums, credit to Taleden for writing the formulae / code

**Comment by felixlinker** [comment]
Already fixed in #329
