### ISSUE TITLE
Catch missing modules when importing

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#378]
[This](https://coriolis.io/import?data=H4sIAAAAAAAAA8Va75ObuhX9X%2Fx5owGBEOy3997mvWaaNOlupv3QyXi0IIxm%2BVUBm7iZ%2FO%2B9Em6MkdBie9vmQxIjfJB0j8499%2BLvG%2F7M635zu3nfsKwZ%2Bs3N5qEQLVx4kkz02%2BpJCLj2ocmGkneb239837zreQXjRdtvWfbM6pRnfSPbdl829TYX33i2LZnccQVVNgpbfyyYzNpG1L0PAx%2FrzW0vB36z%2BSRFI0W%2F39wGN5u39U7UnEtR7za33ze%2FlgNv4UP%2F7m5z6%2BM4irEX05vj9b%2BwigP%2BV85aeHbXDzLbA%2Fp7WFS5ucU3m78OrNTgvl6DyAWX4yres0d1z%2BYD6zr4yt8YYMJtPoJvfZQC5sHKw8VYIXbdu%2B6Ppsngnh83x6%2B%2Fq3u%2B0%2FM%2FYkSeARGFpxjeFONzwWXFShWBI0oYIUoMHEIcc%2FlFVs0gP%2FGa95L1oqkncwo8z5yV7%2BmrixP7IOpfJWdp8VuhwjyBs4O5oNi3q6C%2BADm%2BtcCMCujKyrd5zlNFra7lqWDlNuO83aZDv20Z8BA28od6%2BoSqbcm6irE05SWH3WnkGqriy6lKA4LjRarmTTp0PDtyNZxw1UMRiZf4aiULxijyE%2FhjbCX2NY0u4kwSIOCy54Xnx1pUQ3XP6t0k0BFsCPLDJPHMExYQJ%2BBD0fQPLeeTFfskjpEX0JBG5nmdr%2FgE7I5VbMd%2FZ2XZ5PlsjkGEE0STJPbMo4ctZ%2BXLnGUXCWLw%2FxBED1E%2F%2BR%2BKIokQxB579DW0kaLABw76r6ePmPoxShQ5g3Uy%2BZIgSdhy%2BaikBmK3TVmXsowbqvTIWQXCxOV2J6pH%2BFrFMzFUR6aMn18hd9Ig8RJvkSo8z0UqlBVYkKSELqbQT81XLu8k%2B3rcT5Awi2o4YjOeyk9cPvC0qU8OOvJwaIu1jxHBroMuul6KxwHO4unkMMIhSSzCEaAwdMzRLr2IBD4mJhhBAZ6DvUSafnzCVnuya7lyefLSXPHP4Qo54QomIT2PLF5gie%2BFdPGjiGIzE15BFz8gcfJadAkxCeL4v0%2BXrhC8zB6bpuuBMp34F%2Fe2KfCnI0fGgDbtX8OX04Aq7zHny%2BkU9GxFaifNorjc8ZxDRv3P4IOG%2FDCUvWhL%2BDyJfIxiJdQWD%2BQhNeC58syfYX29SO95BzQ4dahvApUYEgsBXJ7l87haGyCOEehPkpgewwUITCibTjzzK%2Bf4EqnsQbuaXVdZaZoEL7FL6l2B7bEnsEV%2BWbxKCL5XbaZpVcLYESCLsvlaIeZChIyDfnMB37EZ6yuJDgqJqbWKuJDolwE6iX4G5HlET4uhftovlI2awdkYmS2Yasn7rWL3AteXDD1ekXmh4iIm1yvRpYcJT6vGWdrV5nU1zX2PgEsDppvJKHDFx5rBTZp7Js2NciktWJ6XbKjTQmnN8o6GCzvqTwCPDast005%2Fu5Pguf0j5Hh5CWqNEEXqPM%2BDc3hawdnzPhv6%2FVJ84sV6a3bo%2F8RZ2RfWJEcIohT7pluiyZgBXBbHleR8igghCTErvTdrZMWV7qBOj6hn1lVXZDuK%2FDCOsLkNb4LkZyY8Tw4OUbToAER62yrSgxjAf1Wyo0ayO95wDb8otfBr%2BuxeU2OJYUEQrivpQ%2FPMh54jK%2Bkz%2FxtrWXoiIZgg08Q4xQOo3b891A%2FpfqogYNstNaNWFoeKqNhwva06LpERl4rBmL6hWwiMt%2BrgE4u%2FPTw4E3Lp0J9jO5Qeh%2BqcmUfQx66zZxFkcJhQBJkigUjkiPK4DR%2FbXkBVMesBYUtX2w%2FnpPGscFCn5Q1UKqeZPIT0o5Zr%2Bhh3e3GEVUS6Z%2F2JzmBLXeWj4Nyy6hDW5plL1UrmmaEGxR6%2BnkmQJ806YrAul8AQyNd5r%2B%2B6KuUkFknIu2xbNjUkuLF%2FeQ71TgNrtZHn9faSAMWhvU88h3rZSEQWZ4dcpP394c7O2CiBil%2FZeBvByNl2UW25TvEGG0qR825o20aOySEc6YAn%2Fd7jHReLEFjDUGV3qzUsxa7ov3L193Xvv5AlMZzHBkLHY21RH8ObGFKuU1127MS4ku3ktov9tkq5gaWBbsyjgK3NJf%2FncEhbhy0O1mzx33XbrDPTJ0mQT61bFfmOc3PAu%2Bdgn%2BX09QVFNLT015ELbNwgy%2BTASFFLBbwCy5wYQd6LvDp947MHp1O9zqwOWJfOyuBox%2Buukd2C34CSg11eYtDQi6il8zo%2B037MV3FwJvpmLnfaP8sxjyOk63DT%2F7nNyoNeyWcVif4hZfUv9a6cJvF1jtIISj7wEqqEp2k%2BDib5%2BDC8oozUMgRmm%2FesbWXD0qIbRD95eXcYlPv5%2BBrkFBbeSJY%2BTekzKVE7%2BMfzx8GVkGNbYMfrw3vtCTCeAWMn8CojHNveas%2Bn0KiELBwvuBOq3tGuoWqCAs9m61yWwJaVwiVvHZ3d04MiLQ5MEcJo3h48mdTYyfuD11a3QnyzPiZOd%2F0T76GX4Fh1UXj0z5AJIttqE7ez5nK3B7d%2BzyGWU1dm%2BSmK25U5Wg2hPyqHafQWa%2Fd1jYY3fjQG2dzKVT0MZ8%2BB%2BBZhOt9Fjidl0q2eC9mpQBC7QATj4EqB2A0MvAyrwcFOG%2FZkBho6QQOL4HZp07RTyzuHJOPgAmQ4g3wcdrv9I9vrL2G7gkV6cKnBOkfMmvQJpCxtqnbQy4agQnrOZqD0LFDYwLJk8rHJ9uAQU1Um7jvIZHB4fv7%2BY%2FaAeFzSinhV6od2TGoWwFZkjTa3Byx9tWB9WixO9cuPfwMb31fP0ycAAA%3D%3D) import fails.

**Comment by felixlinker** [comment]
Link was generated by EDSM.

**Comment by willyb321** [comment]
That'd be it most likely. We should probably handle cases like this however.

**Comment by felixlinker** [comment]
Initial import does not fail anymore
