### ISSUE TITLE
Consistent script error when opening site with any loadout

### ISSUE THREAD

**Issue by cold-n-sour** [EDCD/coriolis#38]
This is the message I receive when I open the site with or without the loadout URL part:

> Jameson, we have a problem..
> Script error.
> Create an issue on Github if this keeps happening. Add these details:
> Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
> Path: /outfit/diamondback_explorer
> Error: Unknown
> Details:
> scriptUrl: 
> line: 0
> col: 0
> error: null

When I click on "Ships" link or the blue station icon, it works fine from there, but refreshing at any point brings the error message again.

I have to mention that a couple of weeks ago this started happening with the "classic" coriolis.io, and now edcd does this, too. I've tried: a) removing cookies and site data and b) completely reinstalling Chrome. No dice.

PS: Opening in Incognito works fine.

**Comment by Athanasius** [comment]
If Incognito continues to work then I'd check which Extensions you have set to NOT run in that mode.  It could well be one of them to blame.

**Comment by cold-n-sour** [comment]
It was Ghostery. Thanks!
