### ISSUE TITLE
Optimal strength for shield generators broken

### ISSUE THREAD

**Issue by Sheuzzo** [EDCD/coriolis#384]
as said in discord
Shea
there still is some imperfection on optimal strenght calculation maybe?
all the other numbers are ok for the shield generation
Fett_Li
Can you open an issue for this with the screenshot attached?
SheaOggi alle 19:13
sure thing!

Shield Optimal Strength

https://cdn.discordapp.com/attachments/164411501166198784/490190357288452096/unknown.png

Resistance values

https://cdn.discordapp.com/attachments/164411501166198784/490213073441914890/unknown.png

**Comment by felixlinker** [comment]
Could you provide me with the coriolis build that has this discrepancy?

**Comment by felixlinker** [comment]
The bug with the resistance values is already reported in #249. But the bug with optimal strength was previously unknown. I renamed the issue accordingly. Fix is on it's way.

**Comment by felixlinker** [comment]
Actually also for the optimal strength bug this is just an issue how percentage changes are displayed. So actually works as intended but will be changed with absolute moding.
