### ISSUE TITLE
In compare ships, the x axis on the Jump Range graph stops at about 37 Ly

### ISSUE THREAD

**Issue by thunktone** [EDCD/coriolis#387]
I guess it hasn't been updated since the boosters were introduced.

**Comment by felixlinker** [comment]
What exactly are you referring to? Could you provide me with a screenshot and name the bug/enhancement explicitly?

**Comment by thunktone** [comment]
![coriolis](https://user-images.githubusercontent.com/3865802/45586348-4043b200-b8e5-11e8-8d38-d99f744469b9.png)

**Comment by felixlinker** [comment]
Alright got it. I certainly would consider this as a bug.

**Comment by felixlinker** [comment]
It has been a long time; sorry that issue wasn't top priority. However, I just tried to reproduce this and had the axis scale very nicely. Can you still reproduce this?

![image](https://user-images.githubusercontent.com/9728715/63649757-02304e80-c742-11e9-8776-70cb68526e7d.png)
