### ISSUE TITLE
Meta Alloy Hull Reinforcement Package is not allowed in military slots on coriolis

### ISSUE THREAD

**Issue by slubman** [EDCD/coriolis#390]
Hello,

The Meta Alloy Hull Reinforcement Package is not allowed to be placed in a military reserved slot on Coriolis, but one can actually place such a module in these slots in the game.

**Comment by bionicvapourboy** [comment]
I've made a pull request that addresses the issue

https://github.com/EDCD/coriolis-data/pull/55
