### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#391]
Importing [this](https://gist.github.com/felixlinker/679367298b073311e8fc28a50712c8e7) build by clicking on the import button fails.

**Comment by felixlinker** [comment]
This issue probably boils down to us not handling journal-style imports when importing builds which is done in the following bits of code: https://github.com/EDCD/coriolis/blob/master/src/app/components/ModalImport.jsx#L339

**Comment by felixlinker** [comment]
So @willyb321 said that this is working as intended as the modal is not meant to import journal-style ship builds. Should we change this?

**Comment by felixlinker** [comment]
@willyb321 ping for your attention on this again

**Comment by willyb321** [comment]
We could, but I want to finish the rewrite before we make any feature changes.
