### ISSUE TITLE
Imported build from ED Market Connector shows wrong effect on railgun

### ISSUE THREAD

**Issue by Bigity** [EDCD/coriolis#40]
I used EDMC to export a build to Coriolis and it reflects the incorrect weapon effect (but does show correct weapon mod).

https://goo.gl/gf5LNd - is the imported build

Attached is the dump file from EDMC (renamed to .txt)

[Achenar.Fortune's Loss.2016-11-28T15.53.32.txt](https://github.com/EDCD/coriolis/files/617573/Achenar.Fortune.s.Loss.2016-11-28T15.53.32.txt)

**Comment by cmdrmcdonald** [comment]
Thank for reporting this, I'll take a look.

**Comment by cmdrmcdonald** [comment]
This should now be fixed, please try to re-import the build and let me know if it works.

**Comment by Bigity** [comment]
It is showing correctly without reimporting now, I will reimport though just to test.
