### ISSUE TITLE
Many prices are bad

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#406]
Some values reported by a user: https://media.discordapp.net/attachments/164411501166198784/498107370795302912/unknown.png

We should first find a way to get bad prices. Maybe by comparing them via API to Inara?

**Comment by neilser** [comment]
I just noticed a bunch of ship prices were wrong. Where are these actually fetched from? I checked the place that I thought might be the source (https://github.com/cmmcleod/coriolis-data/blob/master/dist/index.json) but the data I see there seems to be correct...

**Comment by willyb321** [comment]
They are manually inputted from user reports. Fixing this is on the todo.

**Comment by felixlinker** [comment]
Devil Ownpag compiled some useful data: https://docs.google.com/spreadsheets/d/1NMjVyOKCZkFzhcpGeV5EZjxPbbNiSDLzO5y_Spu6khU/edit?usp=sharing

**Comment by Arcitec** [comment]
2024 and every ship build is off by like 25% on Coriolis.

Would it be possible to collaborate with Inara to pull the base prices for all ships and parts from them?

**Comment by alex-williams** [comment]
> October 2024 and almost every ship build price is incorrect at Coriolis.
> 
> Take this example:
> 
> * 45.8 million: https://inara.cz/elite/ship/27/
> * 45.8 million: https://elite-dangerous.fandom.com/wiki/Krait_Mk_II
> * 44.2 million (that's the "Total" price stat for the whole stock build) at 0% discount: https://coriolis.io/outfit/krait_mkii
> 
> Coriolis could just import prices from an accurate source instead.
> 
> Would it be possible to collaborate with Inara to pull the base prices for all ships and parts from them?

I actually went through and updated all of the module prices, 1 by 1 a month or so ago. I hadn't realised however, that the build costs calculator, makes use of a value called 'hullCost' for each individual ship and that 'hullCost' needs to be the retail value of the ship, minus the cost of the stock modules, in order for the build calculator to actually be correct. I've now updated the 'hullCost' value for every ship in Coriolis and verified, that the build costs calculator, now displays the total cost of the 'build' for a standard ship, as the retail price for that ship and pushed this change to the https://beta.coriolis.io site. I will test this with a few builds and hopefully, the build cost calculator should now show the appropriate cost of a ship build. It's worth highlighting however, that both elite-dangerous.fandom.com and inara.cz, both have some prices which are inaccurate to the in-game prices of both ships and modules, so they are not good benchmarks for pricing. Please feel free to also test the build costs calculator on the beta site and let me know if you find errors in the pricing.

**Comment by alex-williams** [comment]
Closing this as resolved, as I'm happy the prices are now correct, or as close to correct as they can be, as FDev seem to move them around at times and with the new PP2.0 giving discounts galore everywhere and eliminating rebuys, it's becoming less important anyway.
