### ISSUE TITLE
UX editing engineering on iOS is counterintuitive

### ISSUE THREAD

**Issue by treyharris** [EDCD/coriolis#408]
This is related somewhat to #248 but is a different issue.

On iOS, if you wanted to modify engineering, it used to be sufficient to tap the wrench icon. But now  (behavior tested identically on iPad Pro with Chrome, Firefox and Safari), if you tap it, you get a "Modifications" pop-up:
![b7820212-3956-4fa3-8033-507c76ec3e4d](https://user-images.githubusercontent.com/97895/47243601-8eeedb00-d3c0-11e8-9237-752363b6e6b0.jpeg)

But, if you tap the "Modifications" pop-up, it just toggles the module selection:
![2f950257-6f71-477a-adfc-2dca109bb28d](https://user-images.githubusercontent.com/97895/47243602-8eeedb00-d3c0-11e8-95b2-bcc842b78d99.jpeg)
![1709b1ec-d364-45de-bf65-38cc0edb7c39](https://user-images.githubusercontent.com/97895/47243603-8f877180-d3c0-11e8-8092-f7e232794263.jpeg)
![3dfff736-6043-4c2d-8556-d60dd80c6fd9](https://user-images.githubusercontent.com/97895/47243604-8f877180-d3c0-11e8-823d-437bef35fb68.jpeg)

If you ignore the inviting "Modifications" pop-up and instead tap _again_ on _the wrench_, though, you get engineering:
![2c5ac0ba-1912-4216-bb21-fa94659b4248](https://user-images.githubusercontent.com/97895/47243605-8f877180-d3c0-11e8-9bfa-469398f80478.jpeg)

The same is true with the blueprint selections—one tap brings up the pop-up, a second tap actually selects it. In this case, you're less likely to tap on the pop-up I think—the values listed make it clearer the pop-up is informational and not a button.

So the minimum discoverability UX tweak would be either:
1. Change "Modifications" to "Modifications (tap wrench to edit)"
1. Make a tap of "Modifications" do the same thing as tapping the wrench so that if it's mistaken for a button it still works.

Overall, though, it would be best if tapping _any_ of these pop-ups had the same effect as tapping the wrench or blueprint rather than having the tap passed through to the thing behind it.

A counterargument could be that the user might tap on this pop-up simply to try to make it go away:
![aae9fad6-969f-4865-a6ad-3bfd1641c3aa](https://user-images.githubusercontent.com/97895/47244153-78498380-d3c2-11e8-809f-c04fc124b7fb.jpeg)

but it won't have that effect, either; instead it will toggle the module selection. So I think it would be best if the pop-ups—since they look like buttons when they're small—act like buttons.

Since I use my iPad as a second screen when full-screen gaming, this is a real issue for me. Thanks!

**Comment by felixlinker** [comment]
Unfortunately, I can't reproduce the wrench-click issue by simulating an iPad Pro in Chrome for Windows.

**Comment by felixlinker** [comment]
I still find the behaviour on my android tablet and in iOs simulation-mode to be consistent with my expectations. Can't reproduce the behaviour described here.
