### ISSUE TITLE
Multi-Cannon Modifications DPS

### ISSUE THREAD

**Issue by theFisher86** [EDCD/coriolis#41]
It is possible to get a Damage & Damage Per Second change with Rapid Fire Modification on Multi-Cannon, however that option is not available in the modifications menu in Coriolis.

**Comment by cmdrmcdonald** [comment]
Multicannons do have a damage modification:

<img width="392" alt="screen shot 2016-12-08 at 08 49 17" src="https://cloud.githubusercontent.com/assets/16817420/21003994/2c387096-bd26-11e6-8a7a-d12a4fd29d7a.png">

Damage per second is a composite value (from damage, rate of fire, rounds per shot etc.) so not directly modifiable.
