### ISSUE TITLE
Raw Data Values Misaligned on Bar Graph

### ISSUE THREAD

**Issue by bWildcard** [EDCD/coriolis#410]
Please See Attached Image;

https://cdn.discordapp.com/attachments/164411501166198784/504196671161499668/unknown.png

![coriolis raw data misaligned](https://user-images.githubusercontent.com/43270488/47348503-3a28ba00-d677-11e8-999f-d1660d72a489.PNG)

Tested on Three Separate Browsers, IE 11, Chrome 69.0.3, FireFox 62.0.3

Issue started after last update

**Comment by bWildcard** [comment]
Tested on Three Separate Browsers, IE 11, Chrome 69.0.3, FireFox 62.0.3

**Comment by felixlinker** [comment]
My guess is this is due to 06dc110025ea8de309009234dd0140145cbf1740, where `recharts` was updated.

**Comment by bWildcard** [comment]
Was that supposed to fix it on the current build?

**Comment by felixlinker** [comment]
No. This bug is currently fixed only on beta.

**Comment by willyb321** [comment]
I'll be merging it into live soon:tm:
