### ISSUE TITLE
Mining builds should be thorougly revised

### ISSUE THREAD

**Issue by Anarch157a** [EDCD/coriolis#420]
Mining builds currently are recommending 1D power distributors, which is insane. Mining lasers use a lot of power, even if the ship is equipped with only 2 of them, firing them constantly, to get the chunks out quickly, can deplete the PD in some ships, so it's recommended to use the largest A rated module as possible.

Another thing is the balance between cargo and number of collectors. In some ships, the code puts too many collectors and not enough cargo (ex. Krait). Having 10 collectors active is recommended only for Type-9 and above. For anything smaller than T-7, 6 should be enough, so there's more space for cargo.

The type of collectors are also wrong. D class is good only to collect materials and pirated cargo, for mining it should be A class, to maximize the time they're available.

**Comment by willyb321** [comment]
I think this bug stemmed from another bug. The suggested builds are actually dynamic and iirc they got changed slightly.

**Comment by Kurgol** [comment]
mining builds are also not including:

Utility Mount: Pulse Wave Analyser
Hardpoints: Seismic Charge Launcher, Sub-Surface Displacement Missile, Abrasion Blaster
Optional Internal: Detailed Surface Scanner

I agree with OP that coriolis currently advises too many collector limpets for builds in small/medium ships.

I think the initial post suggesting that the whole "mining" category be revised is a good one, and I disagree that this is an "enhancement" - as it currently stands the mining builds it suggests are not fit for purpose.

**Comment by alex-williams** [comment]
Coriolis no longer has suggested builds, so closing this issue. I do however think suggested builds could be a thing for the future, or shared builds, within the app... but that's a separate thing entirely.
