### ISSUE TITLE
"Shields will hold for" calculations strange

### ISSUE THREAD

**Issue by Shnyrik** [EDCD/coriolis#429]
According to "shields will hold for" calculations, my shield with 4 pips on SYS is going to be the stronger, the smaller PD I install.

For instance, 3A reinforced prismatic on DBX is calculated to hold against 4 overcharged frags for 22 seconds with 1D distributor.
https://s.orbis.zone/_fw

But if I change PD to 4A despite the drastic increase of SYS capacity and recharge rate on the very same ship against the very same opponent it is calculated to hold only for 5 seconds.
https://s.orbis.zone/_fx

Checked those calculations on multiple ships on both coriolis.io and beta.coriolis.io -- and I get the same result.

That is very strange, for the obvious assumption is that increased SYS capacity and recharge rate would increase the time shields holds, not decrease it.

**Comment by Shnyrik** [comment]
Sorry, forgot to add: that works both on coriolis.io and beta.coriolis.io.

**Comment by felixlinker** [comment]
I remember having fixed this issue - also, it has been a while.
