### ISSUE TITLE
Add account to store builds

### ISSUE THREAD

**Issue by TonyyStarkk** [EDCD/coriolis#43]
Hi, i was wondering if it was possible to add account creation. It would be far more easier than always having to import / export the backup JSON when we change devices, the builds we make / creates.

**Comment by cmdrmcdonald** [comment]
It's something that we are considering but at current coriolis is a pure client-side application and this would alter that.  If anything it would probably end up being an easier system for import/export rather than a remote account.

**Comment by harakiwi** [comment]
While an account solution will have it's PROs i guess some guys don't like to hand out email and personal infos ... etc etc etc.

Just bookmark your build and move the bookmark to a folder.

i bookmark my ship builds and save them in a folder called E:D\Builds\$shipname$

to compare specific builds - after cookies got cleared / a reinstall - i just type 'coriolis.io' and for example 'anaconda' and firefox will show you your bookmarked builds.

I name them "TRADE - max shields max cargo" or "PVE - Bounty hunting" or "EXPLORER +Shield +SRV xx LY Range'

So i find them very easily.

Sadly Chrome is missing an Awesomebar like Firefox. Instead open your bookmarks and type your croiolis and your shipname ...

Maybe offtopic and a little late to respond. But adding my thoughts might help some guys not as tech-savvy saving am comparing their builds

**Comment by th3fallen** [comment]
+1 nothing worse than losing your build

**Comment by DomDulley** [comment]
Have you considered using OAuth? I tend to work up builds on my laptop then have to export them to my NAS to import on my gaming rig. Using OAuth instead of local storage would mean we could access our builds anywhere (for example at work), and we wouldn't lose them if local storage gets wiped.

**Comment by gingters** [comment]
@DomDulley How would OAuth (which is a protocol to authorize users) help in actually *storing* data somewhere?

@cmdrmcdonald What you could do is, as an option, add support for authentication by leveraging the Auth0 authentication support - they have a free tier that should suffice. Also, builds could be, again optionally, stored in the Auth0 user_metadata (actually it's not really meant for data not required for authentication, but it would not require another data storage service). So the local storage would still be primary source, whether logged in or not, but when a user is signed in, a copy of the local storage could be synced to the Auth0 user_metadata whenever it is written to.

**Comment by dbackeus** [comment]
The remoteStorage protocol might be of interest for this: https://remotestorage.io

The users themselves need to chose (or host) a storage provider. So it should be implemented as an opt-in thing for those wanting the remote sync capabilities.

5apps.com for example currently offers 1GB free storage at: https://5apps.com

**Comment by strideynet** [comment]
https://github.com/EDCD/central-ship-repository
  
Soon (tm)
