### ISSUE TITLE
Research limpet controller corrupts the build

### ISSUE THREAD

**Issue by NecroBones** [EDCD/coriolis#431]
Adding a research limpet controller to a build, and then reloading from (or sharing) the URL results in the limpet controller being replaced with a cargo rack, and everything after it being reset to empty slots. 

I saw that there were previous closed issues pertaining to repair limpets, but this is the research limpet controller that is currently having issues.

**Comment by CMDR-Cometborne** [comment]
Having the same problem on beta.coriolis.io

**Comment by willyb321** [comment]
For some reason it had no ID. Will fix.
