### ISSUE TITLE
Engineering broken if builds are imported from EDSM

### ISSUE THREAD

**Issue by AtomicMegaNerd** [EDCD/coriolis#436]
I am not certain if this is an EDSM issue or Coriolis but it appears that engineering mods for builds imported from EDSM are broken.  There is a thread on the ED forums here:
https://forums.frontier.co.uk/showthread.php/462620-EDSM-export-broken

Here is an example EDSM import build for my FDS where the engineering is broken:
```https://coriolis.io/import?data=H4sIAAAAAAAAA81Z23LbNhD9Fz4rHOJCkPBbEidtpkmTWp32oZPRwCQoYcxbQTCJmsm%2Fd0HKFq8WFaVJ%2FeKRuFgCe3bP2YU%2BO%2FKDzI1z5bwuRFzUxlk5650q4YtExlILo4p8E%2BuirOy3K%2BdNEdeprJyrvz47r4zMwHBXms2tFFkqKqk3W5XdinSTCr2V1llaWO%2FNx53QcVmo3CB48DZ3royu5cp5p1Whldk7V97KeZFvVS6lVvnWufrsPEtrWcIH8%2BrauUI4DAj3OFodv%2F9VZBL8f5SihI3KJFGRsgdaOa%2FhZKlz5a%2Bc32qRtv5dznDQHEIlSur2GK%2FFrTV03hUfpb7W4iMs%2FkPAC%2ByCkIRe%2BGV1tLoWmdjKd1KvZVTk8dEW%2By6inLG%2BtaqMVre1KQaeieuFKCS0a%2Fz7TupMpBaJniHzCezhPQTnUwmRyeB8In2RJDKyoa1KGSmIuGlXbxo8v1i%2Fj%2BGTyVjV2RGg9vP%2FAaEgPAsgHyO%2BCB%2Fkgy1dhg5yQ879PpST6GAXjvx9ocE%2FCBp0Jiz%2FCSj4uyAiKhVlqqpUCgwY3W0S9UnGp3AhX40LCwi1WT%2BDy05td5EoRWTdPUBDB7yGyBw%2Bb0RVHePDuhGcgA65hC%2FEjrqU48DvcdiNMPJt8lJp2c0GwjDpl%2BnTLCuep6pcq386lggPbd6ITypron7Ph%2BQkuLEW201W58qKV%2FWN4KU%2FFl5OvxW8lCG2FF%2BOkUf5AnwD4mH2vfA9BA6aE1kAZ8FWhhBDsyLT%2BLYoKgO8WsEevE0EJFv5R3yNyvcn9Q4tQTfgeIxufwtaVkBr6oM8Iky6CM%2BB%2Byo3cqvbzDgEiGIXlCng4UmkfYQIQ12zX%2BAkRkU3zW5EHnWgCd2AB4j6I4Jdbg6gpUUFh3x0wfshWDspTKXyu1TUeQRv3Jhaa2k2FqAZuGY18NI8mCPx%2F2MeEJcj6pEFhO5xTsnCPAhc7E20pUuNH82Bg%2FkoA86G6SIyDsKJHqi%2FBUjJD%2Fu47hIyXtIK9bkYUr5XHxMg%2BjBhBJzz4DSIfVGWiYTQ3u9i3ez%2BTZ0aVabwuZMlnks9%2BBvU3cRwtxE6K2roQrWIJTkGvv36krpglI4DfnjbRKT9JQXRjzTCHtALQf5jQfpZitTspoJEfOySMPBCf2GRPEF2AfHGA8K0PXMD5vseWVwpTwjMfTBMYtzHDeK32dVpqqXKk0JH0kpkUzG0rRjcaWAUxFDovXeZuKGJ1mW8hW%2BEI7Q6hHke%2FSoYPRcFQchOrn0ax01r2ClDDHh6JAjwwgSA3siH6d1nCxMAAVkzSvByvTyuGCVA1tzBnJUCc4KJBq5LSz1lKg4e2YiGjwYXJRXzx0nVeXfLw%2FExl9AS9p3gV4QC1%2FIr90cE%2B%2FzYc9%2BPjqGLMbBlr2WClDEvDpNxtHd6Te%2FpObNzpqgoUjjSEEzZBGsm2pmAZ41BdYniMRaMw314sanzbqDJ%2BTJH8QmRQ1AtXggihE%2BoXOgiRsN%2B%2FNvTvS2Ngnl9wBbEJ65v1ZNNroCZBgokG9QVCl0riH3ubtdYrO2A00U5gF2fQvkQyhmEd3tYGmuo8wZlf4RyogERkODENFYXIc0npDap4k1a5CDs%2BVbO8LPL%2FYUTZn%2FOm4L7JM6ey3pD5cv19TTAoH8uC0AP6MB8jBSmLraFzk%2BiZcMxA1WqElnVZVlo08Wqw6gdiwUzyAOlxsdLrceItWN2UYdL%2BAy9dvdhLx4SLf%2BuD8T29bJNETQr0ETxU5lBsEsDGvbR%2F7MZ56sxH8OEE1K%2F3xsfjG9ktDv8wvDQYkEjDQo%2BruoJz5i7nIZANhPWY9eQWYRQ1uve1nsQqGzCNUEuhambT1k%2F4nok8pXMq0JXXWHvZAv06GI2RQaeklqm0FzcdV11%2Bvv7x0s7BBAzaURZ6kJEu6pWpvMzz%2BGh3g%2BfL%2FHcjmBbmdvJZLZOKvjnofbhJTUSTtXIcAsPPVZ8Zn20A9lPMl8bDepgdt0rb%2BIyRHuJeiPhnX0%2BQ6CFrN8IP9PFHZiNbSGLgCP7vSUcYbsHBWzMe9QbwlixsM2l3EU8pEu73CfIZR7xgl55P9rl%2BoHLmE%2FCiTHH5mUFPF3OqGaTCLh9uLASIii%2Borny7bhEA5fkUZfDpL2tt9v9rdjPNOCNR9o%2BPHhMRFr1XOKBSxjIc3sVa3SRglClKciXHdStEzIdBr99uDAM21qAEIgchLB750IGTtlZTmOoewWaWtU6EZGsIpHn9i6vd4nX%2BOWN39mJ5PTPWNRD%2FkSb0zLmJhGVsW8%2F84Zt0ORAieIA9Urqer3e2Lqzo2enREJoZjAZDurNjCZ0k3GQHnHRKPohDM23O2Gi3UwQrLN%2FAYIAEQebHwAA```

**Comment by AnthorNet** [comment]
I'm not sure without a precise thing to look what issue you have and what is broken?

**Comment by AtomicMegaNerd** [comment]
> 
> 
> I'm not sure without a precise thing to look what issue you have and what is broken?

It appears that most of the engineering for modules breaks for any builds I import from EDSM.net.  I am seeing similar reports from others on the ED forums at the link I posted above.  There is no issue if I am import the ship directly from the current ship link in EDMC.

For example in the FDS build I included above note how the current field shows 0% for most engineering mods?

I can provide an additional contrasting example.  Anaconda imported from EDSM (broken):
https://coriolis.io/import?data=H4sIAAAAAAAAA8VaW3ObRhT%2BLzw7zN4X%2FJbUTptp3LhWpn3oZDRrWAnG3LqAHTXj%2F94DyBaIi1CkTPyQDOzZj7PnO9e1v1n6USeFdWl9TJWfloV1YS2CMIMXKlFemvgK3tykfhnp3Lr855v1odAxrAZZsczKKNeRyrVZrsP4XkXLoFzrCiFKK8jqKVDGz9IwKTC8%2F5RYl4Up9YV1a8LUhMXGuiQX1nWyDhOtTZisrctv1ruo1Bk8FB%2BurEtMHCEpF%2FRi9%2F4PFWuAf9IqS5OlXq1CL6wOcWF9hNNE1iW7sP4sVVTjI1u4pD5CuAq1aQ7xUd1XctZt%2BqTNlVFPsPcvBfiVvItdIp8vdlJXKlZrfavNQlcW2ckSbjtMEkn70jsh16aII%2Bx0ZMK8MOF9WaR7X8c2EgSxjvDnQJtYRRVBbTWloJiT5y%2FPlewkK5EybVrqx3PxQo7hhXZ4cYU4iheJMHfJLGKwtDF1kOBTxHCbwilm0VI50b7wCC3MofwMtJCfRwsR8kheJHHFbF4IdvBkwAAvSEpBZjNDCJrJjHs6MfTnEeMcGy6sa5fpcEFCDkh3wwVxPJuVeYz0%2BYjLqAg9lSRgk6I0RsMr7YdlvGOkeT6cwk5GHo3Cw8g5nDfaAdeP50m6rHKEESeK0mRtVFLzNlQMxzzoRuV5q67ZiHJKWZvCQR8jUINIJ1Bv1NcwLuO7rQ5bSSE4CEvsdkvlIkiLRaZ1u6QKgWyMHMcZKMHvwYbpajUBPsebJpk5Ke8y1z2GGf49zHBOOREHmaHIJXMzKCKu43bIfmvitDS3OtGFUUWYJi0NQAXHYd0UPsy6lIjZWDiMywOsU%2BRgWwjJBjLQMOlt7B7peRDqyL9P07yArJ6H%2F2m09CDF53xHexEmm4PxiOawLh3UZ72rQqDV48YvAfKVfNzN7XCOeR7QMeWHpNDrWtXXdebajLrwc8BFsN31oiu90omnX1RY1PrfVNGTRfDc4grbnDGExBnsPhZt8%2BzuDgwFXRWMzsHtw8dj0%2BGQXQnEFOLksF0Zh1TUceTf4SSQhe5qbRRYuSUOpVJwiVmvXB4hf%2F01i9Icjjm943S%2BxpofOi9OBpqfg3Gy1wO586IEDs0PBAqvCOV8RqBQ57sChTm2g%2BBnoCodbXj20w0vKD2n6WHIgCj5gaaHsQAhfAbT8zHTnwosZgJnABKreovfGOClk6ngRsDljwR3ZoC%2FXB8tVd1LLKH58TXeATavR4DwHLcWjPXdevu1AX%2Be1W3tedhvWkVFMORhmLiVD%2FPZif4NZjZ1OWVzMz2zhUS82xFNJvo3VWVGEkFG63g9GGcZlFFkdJisUuPpGIbM2kF546CkNf%2BEYCBlNmisI5rFjEQDE0pfBeU%2FVifwT5pVcNUGIoHJRKKYoBGsXKWiqTTT7H7r%2B2G3E6awmUNl7d4yTbgAtQkHpxUzHWBIfNIBXjf06M%2Bq3AqhvuXd6SWmncBJvAve57317SY5tvhuN8H4iGYMc2FL3qsev6hMed2uDSahjmcAmcX19qbFawkim5G%2B3XR95NpmsmezWMFaLZCf0sYKPjA0bj%2Fsh%2BboFDZkLuTayGV798pDBRfZUrrdlFNr8ikrQpiT94ZRRKktYNogeHDHrTYQ7PFeOwqJk8P4wFl%2FT0XOnSpa0sRmCDv7g32d0TaZNr6BUKjpET16VgZMCUV5VdRSJ1Uad6DSrHL%2FTEM9ODNlhB1omjAS0P4iig%2BRCM0akrJDybs0LT6HcXcqIMLl3QvC94urYaKlgLEGUcgufSKicKXzMstSM1ZUWhJjgTKUr%2FzdjcVU1mqJnTRN0oEw7OkRhOtgZfS%2F5TZ7HEP63%2FVFUN5PUoLbiDAiO%2B3wVvpOe8H2OnrHHGJud3hvjjcAzSi4lsvxQEgPQAuIZtTtyhcbyNjxXOSt9Dhyz3tyneSpydsEtzwHekb1%2FT2iZAiIHRh96m%2BC466D4klX%2F54UvpjbElOM8IEAZrLqGAnuMLeodflcWatYeCp5m6yjdv4jNuKucHDfcqtSR9AAPLSDjrbS33Z5zHr7EQcFWhcqy0yqvCAvw6L1G5Dtotnsr89B9uBsqVHeQ7uMtgaBHP5DuFmcCdmMWmudaKNeskO%2FANTApFk8Jfs7dKCb3VfhtbMd62Ynfn3TzLG%2F6mRRGCj8RdD2Lccmcv86751JH3Ryp%2BHz3XLJbNkN32vQb72BQlwLt2uEEDO7VpilkaB7Gky0rW%2Bo7ch69p7bt1bNHGzYn9ZfnDz30jSb4phOczzpj2LYH9kJkHwYkjeL54QU54eUJ0CyYUinWTwnpHt2SIyOgvRT7wEyhpfGWVlf94BLQ6ny90Abzxy75W5fl8TVn9goU6t6rzZ%2BWnczW6z6baAKLxhF%2BvL8P44BqdDLIwAA

Same Anaconda imported from the current ship in EDMC (working great):
https://coriolis.io/import?data=H4sIAI7fClwC_-1ba2_bOBb9K4a_zBdH4JtSvqVJM-lssk3joAPsYmEwEmNrK0saPZJxi_73vZQdW_Qjkm1lFh3UKJLYlo5I3nPPfZD91r9JgjLSef_039_67-NxGGudhfG4f_qt_y4qdQpvig8X_VNMXCEpF3Sw-vyfaqr7p_3ftUqTePT-8TH0Qx0X_cESCb59lyVJ715lf5RhXPvGYFKEEEWD_rV-0lH_lA3MaMLHUGfz8VyrB_N5_zZ51tlFpp775to8_5D_miQBjGnQ_5iFgKeizwoGBZ84VA76izfI8bBH5PfBCulCTdVY3-psqP0kDtbw0AYewY4k8MJLUMIdl0ki6SZsI5p0XLIE8hyKOMKuhRPmRRY-lEXSdrpcLAGxgwRBzAK8n-hsqqLrRAX7gSFHCoo5-f6fQf9TqaKwmJkPhUe-D_ofCj0F8ElajNIyynWkcp2NxuH0QUWjSVmtxMe4f1pkpR70b7Mwyar7YfLDKCng1iu46EplQZoAjXDfDLkN-cjbkY8eTz7gG6kvIMLcLNfh7MPMkZJhj61sLB1MXST4AexjDneXQNyhsKjHcG9ttsJbB9yHe2tgzKV8g3ueEE3ci1TWgnzX5qq_P_sk8UT37CPYxbQD9iEpBemUf4SgDvnnbdCPCPkW_CN_W_Vjtj06Uj8kpNuF-iGOO6Vfd9RbJ577FrSjFe3OptPkQ3wehSkkJLBo8_dXSZoaAhGM0KANNTHfSc1hUWbBzOblfRL0foE16r2DaRQ6-6V3438Cjm4hKRErkuJdJL1Red64zsxBy2VmjkWhD3Ghx9VyNbGI4xoKRsRBh5sdeTWzI9di41k2TcrsVse6yFQRJnHjyKisz485DBwc2RqGzWjrTJqWURH6Ko7BTmCmTMNHOgjLaSOXbqrL1mLoTzIdRSaoXSj2EPmBGAXiJKn7RqQiHZKKee5OUl0n8fhOxZWCHs8rdhSvSG3J4W_KKWV1K-4Tjkm9miNQzRGLWjfqz3BaTl9m3hA9wfS1oQnBAVJizy6Dh5OkGKZat4jtwsIjQiAHI9d1t1TrlyqKksfHdgMluwdqE7dZCnNwvKiRtENz1ZsIIfO8v4izvEPOck45EZ1wliKPHFkiIFpXROK5HjtOFIk1W5iu6zK7HjrGr6REzMHCZVx24lcUgoAjhGRut25VH-df4VZtayTpbqmRhpNQR8G7JDEeMbrS6ml2URZrWcRFGIS9z6ow4XabuyDUolhq5S7U4bWg7_DDcgfm1szBiUPJYS6HHVJrIFKbJ_pRx75-met8HW-MRdMI3rcgjVMt3KqAY9JhQnoeX2MN-BCziZNXD3tYGC0Pv2o08kHUcr6DOmhJnfswnu3d3ZEebWLOnc5Bf8InfThzdiYHBxqegeER4sTrwviMQ5i0CPAPmAe473ziCqjQODpkZbQgPVxitpHQdgv5_s80SnKwy9Ggr0pZV4z8qWWNWoY497wfQs9cxzWfbLRsvCO5Q7dzh_7kTgN3iDDJ_g_CHeFBXoU3tjkofRv2sIo9bwDM3wpYbJRTmKyXU3jOyXqDFJ40VRVAMDfbS-5ZAPh-I5D_9xG49cVVsTK9czXyE_9LGhY7oPAqj56E6fni2hrO1Oz6q8xX2Th5ULMgSbLGUZ2bi69U4U9aqpBgbFOF5iXXLvkZ6giKsd5vWm0rWXGLknXNUeE5UTHZw1GlB-oNr5oUEM_ICj82NzrZ1IATzBzqcco6zJGYIyTidsV3SIp0QhcrsSrJTyh2OJIIwtvOVGnJUDU39DhTgcaNPJ3Tom14E1taxJXO30YqLkbzGBfY1LoBuie9T8_2LtkLtVCLznD7qIQFryeYXDiSb8Skc5Uqvw0aFXXzorVaDxhevOz_-bMWPRFW3216ZYcAlnaUmoGm1aIaFXdfV_GVOVfGaKsVfEuza37b6CLM1nXiNkseYZpJ1ruFoW_TCtJCK_YwKGNWxeA5yGNrZ23aJxqeg0k995HSs921msvHtAinKtqSTG07pySsfiqi1BGMegRvxb3V2WNiMrwWOoCtzo8RQ86g5mSbwIaJd5A6tjmlVesYMoTd19qzhod6zgTDQdm26rpRYTwfWN6WhN6WgHU5vNjVbr3UUWg8uHepslxXwWWNhhh11WVldSuAoFBG2GEpM2b2vpMAmUcUu4f2bCWvn7hDUlqcAy0u7sNpC1Ks1eREeNw-QACW2McnsGvvMUiBgWuUC_Y61yYzyOqCDKJlxTfRVvMuMyAM5FuPxYW5uZ5uGdgoBMUq0zTJ5lrK57ikkcfXcONwfmPb-Ei9HfGx1kEfXYXjyWWm_ygXcaO-jzDRvYtnHUVbOe224PR8nyJvHeNkva9uoidhRFp13ALxTvuTxXGHpsOWlsYi5tnbEgtpaD1Cu_FGwQE9jrfIdvsRMmd1IkWAXCO7cB3OIImZdjnABeJRA3zVdap0IahxrEXSgOykocbQNmyXDAHhtzQ7dAzZwWjx6xqoXvyuzU-b6Nc67J1PdAngmzwnXWm3sJIH7khMMcIHqjexkn1pShOI_paZq0nfGxMXQ1_FZ_E4ajY2RfbOFuKecPHr9s6rJ-V1M5NGnbxTgcrW1fGx1BHUJV_q0kibJRfuuoe71tGqujZT_pd6xtBchJhfCI-G5p6WUutSd1en7VeoZDNlvOBOhzHkW_56SdKWfTu3DZYPGhYZpEjFpB19zMutEdJ1iDSVnhW3s-SLju_0GH5s5nRbDrM4lNZqUGlr2XtYivEM0s4KsEVSUd8HFuK4wnuzkDVSKejajPcvu7dV9NRxZdXVO7L85mv5ngHd7BW6a_5Y8WG8JN5e-UvFflKxX2xzz9xPkvQASLod0vZRsZePsjaQfC9IXkHyLiFF95CyDSTbC9KtIFmXkF7nkBhthwwS_wuIs59M07JqNYNzQXQJGpuZFeicmaQOGmhfRaPCNK1GUN0VunF4F-YOvInxoAs1KrTpgLfDIB1g0DrGvGj2y7xIpmFenW8Z-bOqs_o61DwUnSfRHi05tCUOXpVRtIx9Uw32OguejPoFB3Z9jztch-t9NGwOsCCBySu7PHs3j5H9AGF2o9zGB5wFQdjuRKZnHe6BJ3DBpf2fgfYPj8RhJjquEgLqECiSmTguOLaCPSQy7gZ-vawHMmYWGVtU4SufuAkBV2UzZLl6qgD6v8nDaNn2fohA4B6zMFCzEWoWt1sD8FvysC5spucKzp-mWaL8SV62UaLb-T3Z7Gxx27C6rYYcg18CcqFNppCGweh50gbYbCJ9uECdIeHdSObdHlhGaFCnaNbYnpLQ16mJWE96UZ29jvIZmKujz-a2Os5z1bs4QInnTY8XJQZ-m2HWdln6g8WS9k_dxZ-B2eA47Wd-cIK8xfcLPVYPWfn1a9jL09JoGWhqdak5XZ6UpjIuwikEGzU1jyAIuyeYnCB5T_Apgn_kX_3v_wOiC7RVMTwAAA%3D%3D

**Comment by AnthorNet** [comment]
Ok can you load the game to refresh your current ship load out in EDSM and try again?

I think we removed some mandatory values for Coriolis that we normally calculate.

**Comment by AtomicMegaNerd** [comment]
Thank you, indeed this is fixed.  I am actually at home today so I fired up the game again and took the FDS and the Anaconda out for a quick spin.  When I import them from EDSM I now see the engineered stats properly.  I knew the jump range on my FDS wasn’t great but it’s not THAT bad :-)

**Comment by AnthorNet** [comment]
Thanks for testing.
@willyb321 can you confirm the use of original Value and lessisgood?
If I could at list delete again the second! The first one should be fairly easy to recalculate!

**Comment by AnthorNet** [comment]
Closing as it should be mainly fixed on our side ;)
