### ISSUE TITLE
Ship List UI Improvement:  Brighten highlight color or allow customization

### ISSUE THREAD

**Issue by sjmagy** [EDCD/coriolis#439]
Hello,
I’m opening several requests for UI improvements as individual issues since I suspect some may be easier to do than others and would be cleaner to track 1 issue per ticket.  (I’d help if I had any current coding skills.)

Request:  Brighten the row highlight color or give users the option to set the color(s); the current brown & black alternating row colors plus the hover highlight color (maroon?) just blend in and makes it extremely difficult to discern what row you're on.

**Comment by monopoint** [comment]
#448 should resolve this one.
