### ISSUE TITLE
Beam Weapons mistake

### ISSUE THREAD

**Issue by TheRealBix** [EDCD/coriolis#44]
Ingame values report 1.8 and 1.12 of power draw for C3 and C2 fix Beams, Coriolis reports 1.62 and 1.0

**Comment by cmdrmcdonald** [comment]
The beta version of coriolis  at http://beta.coriolis.edcd.io/ is tracking the current beta releases of Elite, to assist in testing out builds.  https://coriolis.edcd.io/ shows the current live values.
