### ISSUE TITLE
Ship List UI Improvement:  add extra blank space at the right to enhance horizontal scrolling

### ISSUE THREAD

**Issue by sjmagy** [EDCD/coriolis#440]
Hello,
I’m opening several requests for UI improvements as individual issues since I suspect some may be easier to do than others and would be cleaner to track 1 issue per ticket.  (I’d help if I had any current coding skills.)

Request:  Add extra blank space at the right of the page, so that horizontal scrolling (pulling the numbers to the left) allows you to line up an individual column's data to appear just to the right of the ship name(s) which are already locked to the left edge of the screen.  Think Excel > Freeze Panes on Column B, so that columns B, C, D, etc all scroll / disappear behind Column A (ship name).  Currently, on my laptop screen, I can only "lock" as far right as the "HULL" column (just to the left of the Base ship values column grouping).

**Comment by monopoint** [comment]
what problem does this solve?

**Comment by felixlinker** [comment]
I guess it helps you to relate numbers to ships. For the numbers on the very far right it is harder to maintain an overview.

**Comment by sjmagy** [comment]
Exactly right; because the alternating row color is not sufficiently different from the background color, and because there are so many rows, it's difficult to know / ensure the numbers I see in a column on the far right are actually for the ship I'm wanting to review.

Having extra space on the right would allow even the furthest right column to be pulled to the left on-screen so that each row of the column's data lines up directly next to its ship name.

**Comment by felixlinker** [comment]
@sjmagy Do you think #448 fixed this? I think it does. Since you now have the option to highlight single rows, relating numbers to ships is much more comfortable.
