### ISSUE TITLE
Jump Range >Full Tank shows as 'NaN ly' in Compare tool

### ISSUE THREAD

**Issue by Athanasius** [EDCD/coriolis#442]
This compare, using two of my builds, shows "NaN ly" for "Full Tank" jump range:

https://coriolis.io/comparison?code=N4IgdiBcIIJghgYwPZgCbwAQDcDOmAxAUzSICd4AbTAYWTOyIBcmiQAaEAIygG1RcUEPAQp08DuCEBJMIkwAlIoM6IhMAAwAHAK5MtBANaV0AL1wAPAGYBWAOzIAjADY7lN3YBWXgEwAWfw0AZmCNHw1HUL8NaL8AIQ0rAFsbMCCiGiIkgE4cnNCQoIBaADppAHdHAA4ALQA1GABeEppyhQBzABE4yh0I3DAaGFMAWQs7AhgSgAk%2FXGkYRaWlnwB1AGUABQBPC06AVQUAFQBxI4BqbEcARy5nHzqLbKYADT8kgHorI%2BQATTtWusAFLSAAyvyBmzsAFEAIowWGgmi%2FABydROw2h0iBWOkFngZAAliiCEkRkdYQoXodcNCkidYT4dh8LEFEITKDYrMgqpsXmg0EE7EFzlU%2FNk7DZpDogc4ANLYGgjBRoTxxEaUQwAC2cCn25XKRy0q1%2B7U2hmhfi0nVwKMo00ocuhcqS5xq53gyD8zmk%2B0cWsoR3WZDQ7SsH2cfk8uHaXHKlCclC1BDqniCVXKiBsSR051h2jqctB%2B3OuFBA32NSpfgIQJoAHlzlp4O0UR9pijpkwtcgLCjpFQaloaHF1oYrJquFqgVpoS9pmAtEcCFwjhYtIg7OtQfXNkRstNzjp9i9ED5nDpKNdPExsgpplp9kdHITkCNX9IyKCXoZVoYmMgsIvHUhiIOsRDQu0G5%2FIgKLZDQhhgNs1xBDYChykE6xJC8OibGgJxVDQaYvJ0BC4FqvzlCcNignYoJaO0po%2BGKhhHMWcg0NkNQaPszhgLgsLXB80IonIRwfLCYD0e02AnC8c7JlYMA1I4NBVIYOjbFq5TrDAVhyn45Q1DAXAjDUNCrLCBBoL8NjnEwFi%2FIYdjnBYRjrGgfgKPWEwvL8dSINcVRkEc2DNlZpjbLgfiEmABCrDAQQjPANR0dC1yGNM2rnNk1nZIYphJIYKLwNkQJMJ4XCCjAdRcLgNBgPebSOFYPj1j4VhoNIiA0MZRyEps%2FVoIYXR2J0PgqrCRwaJ4hhcF08AKM4RzbNIQS%2FH5hLwFqRDtEc5TZOc0w6NMdQ6KCrrtBohIWKC5wnKlhLQqYKLXISNRkDUmy4HKVjOPscqmdk9YfEEnTrGA2DrIg0ygjA7SLCAAC%2B7ACEIVgkOQVAAPooAwzCsJIEDQEEJQ%2BJgRSYJsZDIABTDbFobCqOo2h6AYxhmJYtgODzlAaEw%2FOOD4QuhOEsQxKLwQJDYuBBFqGhckkeTZD4aCqwUnFlJUtSUE0JQjG0XRxBa5R2Ps6wKDU0KEu0BCUOslDlO0zSzPMyzuwEWw%2BO0%2ByHJ01ERkwOhoDodg%2BNk2AonYqz7GFphgCMXDrOU10AUC7RauZ8LtNINC4DUZw4k9nQ0NCNAIVtQLsnEcS4HYOi8vWsIZ3SFjrHEBBxL8Jydyc0JaECCjlPEwmwpQnSeFY0w2EcdhAmQNB%2BGQXDvJ0VimEQHyNirNQEJ4UayOUcqUNCWp1AQHwjD4uDbtsEEvCcYAnOsJyeJyoLOOULw%2BHKaDCdMGg96mAUDAeAPhCTrHrGQSq6wPR8hrBYGA2RTB%2BGwIcIIfhOh%2BHWKYIEphsDlFhNsGo5R6xaDzMCF4ngB7YHaEQQwHwXiak7kQUwFgkj7CYEEMgOhpDnE4hJbY7RkBxCsMGWEVQ%2Fg%2BH2AQfqKDpC%2FlBOsCiaAmA%2BE8PsaQnh2h8SIDXT%2ByBNjXCODQOUKIdEwDGNgKw7QTjwDsAoVYWoYBaGyHKIg9Z9hkCIGAUcSRVjTHcYYIg5wIQWGfLta4hZfj7DsNgUEIxTDZBsKsIgoJ0xxHrMgbIzg0AEDEasbYYB9golwISRA9ZOghJgHYF4pgXhxBsNkGMVQKk%2BFki8UEjgtA1ETtIAKZAgSXn4lUKwPYE5gHpGKGgNgXjOHaOsTw2RYRMAUOcZAWgyQnAmiMaEYcgirAMpsDQ2A4g6AsDYesTBoSIE8AQbAzhthWGwJsMYWpziEmmC8KoWE5TnBsFqTwsJsAwE2DQSg8BfhVGoqYOwKITifH2FoTYOhKIvDlPAPwQI4jtHOAoUERBsA1BYJQEU9j%2BHbBRCiBp9ZT6RWyDoLQWg%2FA6FwLgbUYAiHwDqKCbAI1EiIDANkMgWptjnCIFYRAatTDUNMB8QkCgggWC1K0lg5yrBy2hE8SpBBTDtHKB8Rw9Y6h3jAISXwi06hME2FoD4%2Bx4DTGcHcJIBgPieHgPsPwvwwBECCPAPYhhsDZGyPpaY0hoRcGhDAToSxGjIwALqcCsHwRwQR2BC3TY4dg2R2DOHYH4dN7A00%2BETSALQQgEBJCZiANAUANBIyAA%3D%3D%3D

**Comment by willyb321** [comment]
Fix for this is on beta now.
