### ISSUE TITLE
Coriolis Home Page - Incorrect Jump Ranges

### ISSUE THREAD

**Issue by Apollo158** [EDCD/coriolis#443]
On the Home page of Coriolis.io, the table comparing all the current ships has an issue such that the listed Max Jump Ranges are (mostly, if not all) incorrect. (Sidewinder listing 3.9LY, Beluga surpassing Asp Explorer etc.)

I am not aware of whether this is only my personal issue, or a site-wide issue, however in the actual builds the range is calculated correctly.
![coriolis jump range](https://user-images.githubusercontent.com/45839403/49916073-01e07380-fe91-11e8-984c-f60cdda00466.PNG)

**Comment by felixlinker** [comment]
I had a look at the code and it calculates the jump ranges as for the explorer loadout with any internal, utility or hardpoint modules. When you use these builds, the jump range aligns. I think this is alright to go for. Feel free to disagree!

**Comment by Apollo158** [comment]
Hi CoriolisI appreciate the reply, however this was an old issue and has been fixed for a while, however I forgot to delete the error report.The initial error was that the jump ranges were vastly incorrect, however this appears to have been fixed since.Apologies for any time I may have wasted, however it was a 5-month-old bug report.SincerelyApollo158
-------- Original message --------From: Felix Linker <notifications@github.com> Date: 17/05/2019  18:54  (GMT+00:00) To: EDCD/coriolis <coriolis@noreply.github.com> Cc: Apollo158 <Aegisexcalibur1@gmail.com>, Author <author@noreply.github.com> Subject: Re: [EDCD/coriolis] Coriolis Home Page - Incorrect Jump Ranges (#443) I had a look at the code and it calculates the jump ranges as for the explorer loadout with any internal, utility or hardpoint modules. When you use these builds, the jump range aligns. I think this is alright to go for. Feel free to disagree!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/EDCD/coriolis/issues/443?email_source=notifications\u0026email_token=AK5XIK65U5IL35MHGJ5FCTLPV3WLRA5CNFSM4GKDVSM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVVNZKY#issuecomment-493542571",
"url": "https://github.com/EDCD/coriolis/issues/443?email_source=notifications\u0026email_token=AK5XIK65U5IL35MHGJ5FCTLPV3WLRA5CNFSM4GKDVSM2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVVNZKY#issuecomment-493542571",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
