### ISSUE TITLE
Detailed Surface Scanner no longer has mass and is class 1I

### ISSUE THREAD

**Issue by MarmiteScone** [EDCD/coriolis#444]
As of the Beyond 3.3 update, the Detailed Surface Scanner no longer has mass. The class/rating has also changed to 1I. See attached screen shot.

![screenshot_0094](https://user-images.githubusercontent.com/25859641/50056515-1a12f580-0112-11e9-9926-6d3a19238268.jpg)

**Comment by felixlinker** [comment]
This issue has been fixed by now.
