### ISSUE TITLE
Shield resistance to thermal weaponry wrong in offensive profile

### ISSUE THREAD

**Issue by DadInACactus** [EDCD/coriolis#449]
Stock shields show a 20% resistance to thermal weapons, when infact it should be a -20% resistance.
![xurmkot](https://user-images.githubusercontent.com/46005169/50238709-657d0c00-037d-11e9-991a-2c4d1701dacd.png)

**Comment by felixlinker** [comment]
This actually isn't a bug and works as expected. The percentage values shown don't show resistance but show the _effectiveness_ multipliers from different sources. As shields by default have -20% resistance to thermal weapons, the effectiveness of the weapon is 120% which means that it deals 20% more damage.
