### ISSUE TITLE
Suspicious Empty "Restricted" internal compartments?

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#45]
When loading my Corvette in beta.coriolis.edcd.io, I now find 3 class 5 internal compartments labeled "EMPTY [RESTRICTED]". As far as I know, there are no restricted internal compartments for the Federal Corvette. If I copy this load out and then import it in coriolis.edcd.io, I end up with my 3 smaller compartments empty, losing the modules there.

Is that part of the new ED beta? If so, need a way to be able to export from beta.coriolis.edcd.io to coriolis.edcd.io without losing the bottom internal compartments.

**Comment by cmdrmcdonald** [comment]
beta.coriolis.edcd.io is currently set up for testing the changes in 2.2.03.  You shouldn't attempt to export from beta to live because live has no knowledge of the new slots, modules etc.
