### ISSUE TITLE
Errors with Railgun and Plasma Accelerator experimental effects

### ISSUE THREAD

**Issue by SupraOptimo** [EDCD/coriolis#450]
Plasma Slug for the Plasma Accelerator is listed as having a 40% reduction in Thermal Load. The reduction in Thermal Load only occurs on Railguns.

Super Penetrator for Railguns does not show the 50% increase in reload time.

**Comment by starkline** [comment]
I can't speak to the super penetrator special effect for rails, but plasma slug on PA's does not appear to change thermal properties. In game heat is hard to quantify, but I cannot see a 40% benefit in thermal efficiency with plasma slug on 2 size 4 PA's on a Corvette.

**Comment by Noobilite** [comment]
I don't have the engineer to check. But woldn't the display for secondary show the change as a value. Can anyone check. It's mcquin or the sarge I beleive.

**Comment by felixlinker** [comment]
Furthermore, feedback cascade reduces damage by 20%.

**Comment by felixlinker** [comment]
The experimental effect for plasma accelerators is also called `special_plasma_slug`.
