### ISSUE TITLE
Multi-servos special effect reduces rate of fire, again.

### ISSUE THREAD

**Issue by swordurban** [EDCD/coriolis#452]
As title says, multiservos detracts about 5% from the actual rate of fire from any weapon that supports it

**Comment by felixlinker** [comment]
I tried to reproduce this issue but couldn't. Could you provide me with a build that reproduces this issue?

**Comment by Qwetek** [comment]
https://s.orbis.zone/214i

First laser with second without, first one having 4.5 second having 4.7 ROF. Even the tooltip on MultiServos says -4.2%.

**Comment by felixlinker** [comment]
Will be fixed by merging https://github.com/EDCD/coriolis/pull/495/commits/87effb612acfa3d973f3da1c5351a2775379057c and https://github.com/EDCD/coriolis-data/pull/69/commits/d3f9cb4294da12ff83d8ed2c5b768e07f51d85a8
