### ISSUE TITLE
Shield generator: increased Optimal Mass should also result in an increased Maximum Mass

### ISSUE THREAD

**Issue by MusTheBunneh** [EDCD/coriolis#453]
On legacy engineered (pre 3.0) Shield Generators with an increased Optimal Mass, the same percentage modifier should also apply to the Maximum Hull Mass, but Coriolis doesn't take this into account.

Example: https://s.orbis.zone/755 ; engineered Maximum Hull Mass is 1013 tons + 8.84% = 1102.55 tons, but Coriolis still shows 1013.

**Comment by felixlinker** [comment]
So this means that new modifications don't allow modifying the maximum mass?

**Comment by MusTheBunneh** [comment]
No, unfortunately not. A modified optimal (and thereby maximum) mass was a secondary effect in pre-3.0 engineering. With the intoduction of 3.0, secondary effects were done away with, including the changed optimal/maximum mass on the shield generator.

However, increased optimal/maximum mass is still persistent on legacy engineered shield gens that weren't changed over to the new engineering system.

A lot of people (including yours truly) are all for bring it back though: https://forums.frontier.co.uk/showthread.php/439592-Shield-engineering-bring-back-Increased-Optimal-Mass-as-an-experimental-effect

**Comment by felixlinker** [comment]
So, on legacy mods, the effect on maximal mass was tied to optimal mass?

**Comment by MusTheBunneh** [comment]
Yes. The same percentage modifier applied to the Optimal Mass *and* the Maximum Mass.

**Comment by felixlinker** [comment]
To couple these effects together could be quite hard. An easy solution for this (quite niche) use case could be to allow users to enter maximum mass modifiers by hand. What do you think about that?

**Comment by MusTheBunneh** [comment]
If the Optimal Mass is changed, so is the Maximum Mass. They use the same percentage modifier. This used to work fine, I wonder why it was changed.

**Comment by felixlinker** [comment]
Ah! So it hasn't changed that modifying optimal mass also changes maximum mass. What has changed is just that you're not able to do that anymore. Got it!

**Comment by MusTheBunneh** [comment]
Exactly :)

**Comment by felixlinker** [comment]
Btw: I guess this was changed because when optimal mass for thrusters is engineered, maximum mass does not change. This needed to be addressed in the past. Will investigate how to revert that change for shield generators.

**Comment by felixlinker** [comment]
@MusTheBunneh Could you check whether everything works as expected now?
