### ISSUE TITLE
Style sheets not loaded

### ISSUE THREAD

**Issue by Trotsky21** [EDCD/coriolis#456]
Each time I attempt to go to coriolis.io from my EDSM fleet list, a notice appears at the top of the screen - "refresh" or "view release changes." Clicking either of these renders the Coriolis.io site unusable. The screen is thereafter either black or has a much enlarged blue coriolis icon, and that's it.

**Comment by Stevax** [comment]
I get the same blue Coriolis symbol when opening from browser to Coriolis.io using iPad now.
![09458829-0bcc-4b1e-9618-c6e88ee19465](https://user-images.githubusercontent.com/27301376/51648704-7838c100-1f79-11e9-977c-0d7ea8e0fa7d.png)

**Comment by AnthorNet** [comment]
Again, link.... How are we supposed to fix anything or help you?

**Comment by Stevax** [comment]
I did type Coriolis.io in the report and say it was when opening from browser, is Coriolis.io not a link? I type that in my browser and it gives a list of links and I click on Coriolis.io and get that blue symbol.

**Comment by AnthorNet** [comment]
That issue is for link from the EDSM fleet ^^
Hence the question!

**Comment by Ryuonato** [comment]
This might be a non-issue, as I've logged into my EDSM account, and imported a few of my fleet into Coriolis.io without issue.

@Trotsky21: If you could right click the Coriolis icon on the ship you are having trouble importing and use the copy link address option to post on this thread so the team can see the link, they might be able to fix the issue or give more insight.

@Stevax: Which version of Safari is your iPad running? And you might want to post your problem as a separate issue, I've had similar problems when a new release has been pushed, but it usually you just need to do a force refresh or wait for the cached files that your iPad downloads for a site to be obtained again. I'm not sure if there is a forced refresh option for browser tabs on the iPad like there are for other computers/browsers.

**Comment by denisgre** [comment]
I have the same problem after pressing update in the top bar. It is exactly the same screen as Stevax above but my problem is any link to Coriolis from either Firefox (default) or Chrome gives the same end result. From either browser Coriolis is set to the home page. No info is sent via another third party app as far as I know although I do use EDMC. Both browsers have been cleared of cashe. In all cases, pressing CTRL+F5 brings it up as normal, again in all browsers.
![CoriHlp](https://user-images.githubusercontent.com/27203435/55070636-a1abc100-507e-11e9-96ab-56833de118bb.jpg)
Can you Help?

**Comment by felixlinker** [comment]
In #641, it can be seen that a style sheet is not being loaded correctly. This seems to correlate with updates to coriolis. The name of the .css file appears to be random.

Theory for the behaviour: The client is not updated with the correct style sheet to fetch, resulting in a 404. In #641, the client reports that `c74483.css` is missing. Currently, the server only serves `ed20bb.css` which supports my hypothesis.

**Comment by alex-williams** [comment]
This would seem to be an issue with a previous update. I cannot replicate the issue currently.
