### ISSUE TITLE
Uncaught TypeError: When engineering detailed surface scanner

### ISSUE THREAD

**Issue by grandwazir** [EDCD/coriolis#457]
Error: Uncaught TypeError: Cannot read property '1' of undefined.

Browser: Mozilla/5.0 (Linux; Android 9; Pixel 2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.99 Mobile Safari/537.36
Path: /outfit/beluga?code=A0pftsFplCdssnf71717---------3e4ifm051O0tv4C7--2i.Iw18ZJA%3D.Aw18ZJA%3D.H4sIAAAAAAAAA2P%2BJ8XAwPCXFUj8qQAS%2FCq%2F%2Fv8X2sHNwCBSI8rAIHEHKPP%2FPwMAbA6BIicAAAA%3D.EweloBhA2AWEoFMCGBzANokICMF8KERA&bn=Base
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/main.js
line: 53
col: 61516
error: {}

**Comment by SkoidUK** [comment]
I'm getting a similar error when trying to engineer detailed surface scanner:

Uncaught TypeError: Cannot read property '1' of undefined

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Path: /outfit/krait_phantom?code=A0p5tdFflid3ssf5---2l02020h033c1Ov40W43F10l2i.Iw18aQ%3D%3D.Aw1%2BgjOQ.H4sIAAAAAAAAA21QsUoDURAcvUu8mMRnjrszWBjUmFIUUkkglhaCXyDkExQsUggi%2BAXWFpaWFhaWKSz9BBGxsAgpLMRCzK6zwTwI3CummJmdt7OQIoBxgfB7TSi3I6BaEdVatADEV0PV5gtlnZOud14QoqcS4Drfqtmtoz4vmdfPCK75o5qMCKnp9fsQ2DxZoTOQVe%2FsT53xYxlIzlM6J9%2BFsmum0PTeJ%2FWHd1UtyJ4fvSSULHBxpwasW8iGwZZByypoUXpTu%2BuPGDJ4U922nbUirVnp%2BZVsNZddkiNjA2MPvsjefJB10s7xLsua33twzDb7DbZJ5NDvfYr%2Fu8U2ldyNeSGrXLeamkojp3cmQU6qYvb9Aebtt3LNAQAA.EwegLCAMUgzKBGAbCApgQwOYBtUhApETNJEA&bn=DW2%20Kraft%20Phantom
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 53
col: 61516
error: {}

**Comment by Ryuonato** [comment]
Caught this error as well when trying to engineer the discovery scanner on the beta version.

Uncaught TypeError: Cannot read property '1' of undefined

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Path: /outfit/asp?code=A0pjtjFjljdjsof5--1717------044e01--002i.Iw18WQ%3D%3D.Aw18WQ%3D%3D..EweloBhBmVoDhAUwIYHMA2SQgIwQJCmKA%3D%3D%3D
Error: Unknown
Details:
scriptUrl: https://beta.coriolis.io/main.js
line: 53
col: 61516
error: {}

**Comment by willyb321** [comment]
Did you already have a mod on there?
