### ISSUE TITLE
WebApp/Mobile view issues

### ISSUE THREAD

**Issue by DarkSeraphim88** [EDCD/coriolis#46]
Problem with ship menu selector: not all ships listed in menu. Missing overflow rule on div
Fix: Add to stylesheet selector "header .no-wrap" this rule "overflow-x: auto;"

And so it would be more convenient if the menu bar has been bound to the top of the screen.
Fix: Change in stylesheet selector "header" rule "position: relative;" to "position: absolute;" and add to that selector rules "top: 0px; left: 0px; width: 100%;". Then need to add to style attribute of first div in section with id="coriolis" that rule "padding-top: 48px;"

P.S. My apologies for my poor english

**Comment by cmdrmcdonald** [comment]
Thank you for supplying the fixes for these issues.  They have been applied and will be available in the next release.

**Comment by DarkSeraphim88** [comment]
Also for proper view need to add css rule "box-sizing: border-box;" to "header" section and to "#coriolis" section
