### ISSUE TITLE
Krait Phantom PP / PD incorrect (maybe more?)

### ISSUE THREAD

**Issue by brendonlamb** [EDCD/coriolis#460]
![image](https://user-images.githubusercontent.com/1816511/50935951-d6bf5480-143b-11e9-844d-273ff7d861c0.png)

**Comment by felixlinker** [comment]
@willyb321 This might be due to your changes how the standard builds are getting parsed. Shouldn't we maybe just change the way they're written down? I also noticed that a similar bug applies to builds provided by coriolis. They often equip a guardian PD.

**Comment by willyb321** [comment]
Hmm, I suppose yeah.

**Comment by felixlinker** [comment]
Can't reproduce anymore. Must have been fixed at some point.

**Comment by brendonlamb** [comment]
My favorite kinda bug/fix. Cheers.
