### ISSUE TITLE
Module shifts after reload

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#464]
[This build](https://coriolis.io/outfit/federal_corvette?code=A0pvtqFllndAsxf5yJyJ2b0019190802000k----p0fh063d1O0vv41K2dC99q24.Iw18ZlA%3D.Aw18ZlA%3D.H4sIAAAAAAAAA2P4x87AwPCXEUhw9wAJ3g0sDAyCFUCW0AtmBgaVFCDrP%2BM%2Fe5giji9Akp%2Fn3%2F%2F%2FYiCV%2F5n%2BicGk%2BK8ARUVAhChISmICUFD5AtD4%2Fxz%2FQmGKGAT4GBhYQIQQSAqsSPYEyBJOYhTx%2FguBKRJfwM%2FAIAlSpAx2JB9uKf5%2FrnBH6gBJIQF1oKkgn8iDPPn%2FPwMUAACe7S4WDgEAAA%3D%3D.EweloBhBmUEZgA4QFMCGBzANikI4SEhQlA%3D%3D&bn=Tech%20Combat%20Optimized) is broken after a reload. All modules shifted one place; the topmost utility module for example is now in the last hardpoint slot.

**Comment by Ryuonato** [comment]
Also look at one of the medium hardpoints, it has a chaff launcher in it. What did you intend to put in those medium hardpoints?

**Comment by felixlinker** [comment]
It wasn't my build. I got it from someone I can't recall.

**Comment by felixlinker** [comment]
This build just ended up in a horrible place and I do not deem this worth debugging anymore
