### ISSUE TITLE
add experimentals to materials needed for this build list

### ISSUE THREAD

**Issue by willyb321** [EDCD/coriolis#466]

**Comment by Sid127** [comment]
Hi, sorry it took ages to get around to this! This is being worked on, as mentioned in [this comment](https://github.com/EDCD/coriolis/issues/705#issuecomment-1272452146l) on #705

**Comment by Sid127** [comment]
@felixlinker this can be closed

**Comment by felixlinker** [comment]
Very cool! I only now realised that you technically implemented a new feature 👍
