### ISSUE TITLE
Add damage per ammo statistic

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#469]
Another statistic for weapons would be interesting: Damage per full clip and ammo. This would only apply to weapons that use ammunition and would give you a metric for how much damage you can deal before your weapon is completely empty.

**Comment by willyb321** [comment]
Hmm, we could do that.

**Comment by felixlinker** [comment]
Closed in favour of project card: https://github.com/EDCD/coriolis/projects/4#card-53924148
