### ISSUE TITLE
Add button to clear all engineer upgrades

### ISSUE THREAD

**Issue by iPeer** [EDCD/coriolis#47]
Reverting a saved build that has upgrades back to its stock version is a little time consuming. It would be nice if there was a button somewhere that would clear all upgrades when clicked

**Comment by DarkSeraphim88** [comment]
@cmdrmcdonald, @iPeer says, that when you want to remove engineer upgrade from a component of a ship, you need to manually set all parameters to zero. It's good to add a button that clears all engineer data from a component not to revert to stock a whole ship. like a reset button in web 2.0 forms.

**Comment by BlackLightUK** [comment]
@DarkSeraphim88 : Although it's a bit of an annoyance, an easier way to reset a single module to 'stock', unengineered values would be to temporarily replace it with a different grade of module and back again. For example, removing mods from an 0A shield booster, you can swap it to an 0B and back again. Just a thought.

**Comment by cmdrmcdonald** [comment]
This functionality is available in the current release of Coriolis.
