### ISSUE TITLE
Enhanced low power shields incorrectly modify maximum hull mass.

### ISSUE THREAD

**Issue by justjohn2001** [EDCD/coriolis#473]
Add 3A shield generator to Anaconda. Apply Enhanced Low Power level 3 or higher. The site incorrectly reduces the "Maximum Hull Mass" in addition to the "Optimal Hull Mass". This make it think the shield will no longer work. In-game they work fine. Attached is the actual modifications:
![image](https://user-images.githubusercontent.com/27875595/53219528-46755180-362e-11e9-9156-a93fefbe1d4f.png)

**Comment by justjohn2001** [comment]
I believe the error might be in the following code:
```{key:"getMaxMass",value:function(){var e=!(arguments.length>0&&void 0!==arguments[0])||arguments[0],t=0;if(this.maxmass&&(t=this.maxmass)&&e){var n=this.getModValue("optmass")/1e4;n&&(t*=1+n)}return t}},

**Comment by Noobilite** [comment]
I have built 3d shields for an anacondas. I can confirm when using enhanced low power it does not reduce maximum mass. This has been confirmed by game staff in the past as a balance feature to not break installed shields while engineering.

**Comment by VAKazakov** [comment]
If i build shields on coriolis with Enhanced low power blueprint, it drop down opt and max hull mas, instead lowering only opt

**Comment by felixlinker** [comment]
Will be closed by #559
