### ISSUE TITLE
Seismic charge launcher wrong power draw

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#474]
It was reported that 2B (Fixed) Seismic Charge Launcher is listed as having a power draw of 1.01MW, but in-game it appears to be 1.2MW

**Comment by IcyMidnight** [comment]
<img width="299" alt="2019-02-21 23_19_22-elite - dangerous client" src="https://user-images.githubusercontent.com/30482/53237775-687dcc80-364c-11e9-9bb6-3df6e6f04d34.png">

**Comment by felixlinker** [comment]
Thanks for the screenshot!

**Comment by felixlinker** [comment]
Fixed in https://github.com/EDCD/coriolis-data/commit/c21155357c26785d7e4f832e6faa64a5f13b62d4
