### ISSUE TITLE
Export Json Doesn't Include hull

### ISSUE THREAD

**Issue by AweBob** [EDCD/coriolis#478]
This is pretty obvious. Look at the export JSON. Every module contains info on the engineering as part of it. This is that way for every module except for the hull. Which in the JSON file is called "bulkhead" for reference.

Thanks!

**Comment by felixlinker** [comment]
I edited your issue and opened #479 for your other request - this helps us to track things more clearly. I also have a question for that issue so if you could have a look at #479 that'd be great!

**Comment by AweBob** [comment]
Thank you, for moving my suggestion. Here's some more context and an example for this issue.
https://pastebin.com/pv7WkBa0 = https://s.orbis.zone/268_
This build has engineering on the hull and power plant.
If you import this to Coriolis the hull engineering is still there.
However, if you look in the JSON, there is info on the powerplant engineering, but none for the hull.
