### ISSUE TITLE
Unify core internal names with inara

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#479]
A suggestion that is related to JSON File:
Every module in the export has the exact name as Inara has, the exception to this is core internals which has its own confusing naming system. If these were the same as Inara it would make things a lot easier for people like me!

**Comment by felixlinker** [comment]
Could someone explain to me what exactly "inara names" refers to?

**Comment by AweBob** [comment]
(Copy of what I said in EDCD Discord):
Inara names refer to what modules are called on the Inara website. A clear area to see this is at https://inara.cz/galaxy-blueprints/ . All modules except core internals have the same names as this, including capitalization, except for the core internals which are all goofy.

**Comment by felixlinker** [comment]
So, for non-core modules you're referring to the group field that _has_ the value you're looking for, right?

**Comment by AweBob** [comment]
Not entirely sure what you mean, compare side by side Inara names to the names on the JSON output. "All modules except core internals have the same names as this, including capitalization, except for the core internals which are [unique]."

**Comment by alex-williams** [comment]
I don't see the purpose in this issue, we have the ability to search inara for the stations that sell the build with the touch of a button. Closing the issue.
