### ISSUE TITLE
2D beam laser - wrong power draw

### ISSUE THREAD

**Issue by maniac-2k** [EDCD/coriolis#485]
regards v3.0.0

The stats for the 2D beam laser are not correct.

IS: 0.99 MW
SHOULD: 1.00 MW as in game client v 3.3.05

**Comment by felixlinker** [comment]
I consulted edsy as another source which lists the 2D beam laser with a power draw of 1.01. Could someone provide us with an ingame screenshot or a journal export showing the actual number?

**Comment by traveller42** [comment]
2D Beam Laser (gimballed) shows as 1.00MW power draw in the client as I am typing this.

![G 35-15 (20190427-050812)](https://user-images.githubusercontent.com/4277324/56845074-6c66de80-6889-11e9-8f69-9de95af3caa2.png)
