### ISSUE TITLE
Site crashes when using engineering tools

### ISSUE THREAD

**Issue by CoronaryLilim** [EDCD/coriolis#487]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Path: /outfit/diamondback_explorer?code=A2pataFflddfsdf5-------45-----.Iw18UA%3D%3D.Aw18UA%3D%3D..EweloBhBmUBYQFMCGBzANokICMF8hRFA
Error: Unknown
Details:

scriptUrl: https://coriolis.io/main.js
line: 46
col: 157676
error: {}

**Comment by willyb321** [comment]
I have fixed this now.
