### ISSUE TITLE
Problem since last update

### ISSUE THREAD

**Issue by denisgre** [EDCD/coriolis#488]
Going to coriolis.io since the last update just gives me huge blue wireframe coriolis station. Scrolling to the bottom gives a list of ships but does nothing of note. Happens using Firefox or Chrome browsers and going to https://coriolis.io/

Pressing control+f5 works but I have to do this every time. Cashe has been cleared in both browsers, backup file created then app deleted and re-installed and backup imported. Same result on Ffox but Chrome this morning is working but with a stupid pink colour and some joke spelling changes.

Any suggestions?

Denis.

**Comment by blakesplay** [comment]
I had to go to developer mode and go to the storage tab and delete everything I could.  Now it works for me perfectly.

As for the pink color, its an April fools thing.  I hope it gets switched back soon, really sick of the w replacing the r and l letters.

**Comment by denisgre** [comment]
The pink thingy would have been fine for the traditional 12 hours of April 1st!

**Comment by willyb321** [comment]
Australian timezones meant I was asleep by the end of April 1st for America. I have reverted the changes on beta and live now.

**Comment by willyb321** [comment]
Also, try this for the huge logo if ctrl shift r doesn't work: https://willb.dev/image/PzaF
