### ISSUE TITLE
Coriolis suddenly unusable?

### ISSUE THREAD

**Issue by strangealien** [EDCD/coriolis#489]
I understand, that the new colors, the new 'naming' and the silly MS Office hint giver were an April Fool joke. Or not? Hard to imagine that you made your important and well written web tool intentionally unusable.

Yet - unusable it remains until now, April 2nd. Should April Fool jokes last so long? I am missing your site. If it is not fixed soon, I will have to move to the second Shipyard site, but only by force...

So please restore the site as it was ASAP.
Thank you.

**Comment by AweBob** [comment]
But why it's so mwuch easiew to wead. Mwy favowite is the wife suppowt. Pink is awso such a nice cowow. And cwippy pwovides some weawwy hewpfuw tips!!  "twy siwent wunning to dop focus"! OwO

**Comment by willyb321** [comment]
Australian timezones meant I was asleep by the end of April 1st for America. I have reverted the changes on beta and live now.
