### ISSUE TITLE
Adding engineer grade?

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#49]
Not sure if it's an information that can be provided by EDMC but it can certainly be entered manually.

It would be nice to see what grade the upgrade to a given module is. I don't know now how many times I had to visit the outfitting just to check the grade of an upgrade on a module.

**Comment by cmdrmcdonald** [comment]
This information is available by hovering over the engineering icon next to the module name, if it has been provided.

There is a separate request #24  to allow this to be entered manually.

**Comment by nemesyssoft** [comment]
Duh! I missed that all that time! Thanks, Cmdr McDonald!
