### ISSUE TITLE
Detailed Surface Scanner is "1I", not "1C"

### ISSUE THREAD

**Issue by burtonsimmons** [EDCD/coriolis#490]
In Coriolis, the Detailed Surface Scanner is listed as a "1C Detailed Surface Scanner".  In game, however, it's listed as a "1I Detailed Surface Scanner". 

See here: https://imgur.com/a/AfK4kc0

**Comment by felixlinker** [comment]
Thanks for the included screenshot! This is really helpful.

**Comment by felixlinker** [comment]
Fixed in https://github.com/EDCD/coriolis-data/commit/1e8cf4658008f5f36f434315daefc4e4ca561f81
