### ISSUE TITLE
Make module search sticky

### ISSUE THREAD

**Issue by Piedone** [EDCD/coriolis#491]
A little UX suggestion: the search box shown when browsing for a module on the ship building screen is at the top of the scrollable area. So if you're way down in the list of modules then you have to scroll up to do a search (which is a bit inconvenient when you want to change a module that's at the bottom of a long list). It would be great if it could be displayed at the top of the list at all times.

And BTW thank you for the incredible too!

**Comment by felixlinker** [comment]
Good suggestion; I will keep track of this.

**Comment by felixlinker** [comment]
Closed in favour of: https://github.com/EDCD/coriolis/projects/4#card-53924471

**Comment by Piedone** [comment]
I don't think project cards a substitute for issues though.

**Comment by felixlinker** [comment]
It depends on how you look at it. My aim is to separate problems from ideas.
