### ISSUE TITLE
Copy builds and modules

### ISSUE THREAD

**Issue by Piedone** [EDCD/coriolis#492]
I'd like to see a way to copy (or "save as") full ship builds. E.g. I'm starting with a Krait Mk II outfitted for minding with several modules engineered. Then I'd like to see how this would work adapted to combat, but with the engineered modules being the same. So basically I'd like to change an existing build of mine and save it as a new build, instead of starting with a vanilla ship outfit. Possibly this is already there if you export, then import a build, but a more convenient way to do it would be great.

Similarly (though I'm not sure how related this would be technically; I'm including this here, let me know if it should be a separate issue) it would be great to be able to copy engineered modules between builds (or otherwise share them; being able to have a single engineered module shared among multiple builds, that changes everywhere it is used would be even better). The advantage of course is that you don't have to set up the engineering details every time you use that module in a build.

**Comment by felixlinker** [comment]
Thanks for thinking about how coriolis could be improved.

Your first proposal already is implemented. You can just enter a new name for a ship build in the top right corner and save it again. This implements "save as" functionality you talked about.

The second part has already been proposed in #72

**Comment by Piedone** [comment]
Ah nice, I didn't know that. Since this is not straightforward to discover in my experience I'd suggest considering changing it to be easier to discover. UX is not particularly my strong suite so I don't know how, but maybe just info about this into the enabled Save button's tooltip would be a good start? (Like "Save the changes to the current build, or if you change the name then save it as a new build.")

**Comment by felixlinker** [comment]
You can open a new issue for that, if you like!

**Comment by Piedone** [comment]
Sure, added it: https://github.com/EDCD/coriolis/issues/494
