### ISSUE TITLE
Undo functionality

### ISSUE THREAD

**Issue by Piedone** [EDCD/coriolis#493]
It would be great to have an undo (maybe redo) feature, i.e. Ctrl+Z. That wouldn't be the same as the current reload feature that clears out all changes made to a saved build, but rather it would undo the last step you've made (like adding a module, applying an engineering modification).

**Comment by felixlinker** [comment]
It shouldn't be too hard to use the browser to store the sites state; when writing the URL we could opt for using the [history API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) instead of simply writing the URL.

**Comment by felixlinker** [comment]
Closed in favour of project card: https://github.com/EDCD/coriolis/projects/4#card-53924105
