### ISSUE TITLE
Make "save as" functionality better discoverable

### ISSUE THREAD

**Issue by Piedone** [EDCD/coriolis#494]
When you change a saved ship build you can save it under a new name if you also change the name. So there's a "save as" functionality, but it's not easy to discover.

Maybe just adding info about this into the enabled Save button's tooltip would be a good start? Like "Save the changes to the current build, or if you change the name then save it as a new build."

**Comment by felixlinker** [comment]
Just noticed that this has actually been adressed. "Save as" is now called "Rename".

**Comment by Piedone** [comment]
Great!
