### ISSUE TITLE
Damage on Frag cannon Rapid fire Screening Shell incorrect. Forgets round -1.

### ISSUE THREAD

**Issue by Noobilite** [EDCD/coriolis#499]
https://s.orbis.zone/2z5a

The damage on all sized guns is one extra reload in time lowering the dps when considering sustained dps. Unless there is something that does not make the first round fire the moment of reload this is incorrect. **I might be missing something about how it should work.**

Example:
3C Fixed Frag Cannon Rapid Fire, Screening Shell
Current:  341(117.2)<-parenthesis value incorrect. It's using??: `(4*3*3*4.34)\(((1/6.54)*3)+0.88)=116.7088816`?! This isn't even quite correct. But it's close.

Should be: `(4*3*3*4.34)\(((1/6.54)*2)+0.88)=131.7578846`

**Comment by felixlinker** [comment]
Firstly: I took the freedom to edit your post regarding the `*` problem.

Next: I just made some changes to how rof mods work. Could you check the problem on beta? Here is a link to your build for the beta version: [click](https://beta.coriolis.io/outfit/type_10_defender?code=A4pktpFplndusif61t1t1t1t1s1s1s2020xsSn------2d2d2d2d2b2b2929272d2d25.Iw18ZUAxA%3D%3D%3D.Aw18ZXEA.H4sIAAAAAAAAA43SP0tCYRQG8KOp%2Bf%2BqaJlp%2BefW0BDVLNSHaGnzI0RLDg71DaSgqaEPEdQQ4hBuQotbQzREQ4Q0BIW9T%2BcEHcIhzh0eHjm%2F814vvORmiegrzDE54Uh0A0SpoyRR9pBb7jpB5N8EiRBw2yo7HNHbGJHXfAfmLjyeB11R5wccXv8DyBcnQGEcJyruRIga3WcAM66ksi3S%2FwR%2B3pTvFFje8wQhtykoJPPWmOeXj7wadk1dPeaIyWpcoiZRTzpgZX%2BeaHUjy4dEXOuXe%2B0XPqT%2FAKzLf0bU7elJ7Cksq5HdNyCzxT%2FL509A5e6VZcws42aZMMukWabMMm2WnllmzHLBrak8kyt3xTVdLfOVk5aT2%2BRLQ8ksF82ybJaVadlT2VMpDUtmuTwtByoHKqWhapa1aTlUOVQpDXXztzfM0v8jT0WOVI5USgPon%2BcbFMBVx4gEAAA%3D.AwegLCBMKgbBoAuBPADgUwPoEZiYCboBm6AdoQE4gi7Cj0xA&bn=Thargoid%20FCRFSS%202)

**Comment by Noobilite** [comment]
Unless I'm wrong. I think the issue is it must be taking into account some sort of delayed shot. Does the frag cannon fire a milisecond after pushing the button?

https://imgur.com/a/XCzBph5

The data in game doesn't make sense. If it's actually 3 damage and 5 second reload it should be exactly 180 dps. This means that if there is a delayed shot it's 179.1/36=4.975/s effective rof. Pure 5/s dps. That should mean the delay is 1/4.975=0.2010050251-(1/5)=0.0010050251 (assuming no rounding on fdev or further missing rounding from my calculator)

That means the correct Sustained DPS(assuming a shot delay) is: (12*3*3) / (((ROF*2) + (ShotDelay*3))+reload) For a normal un-engineered version.

So, 108/(0.4+0.0030150753+5)=19.98883929

If this is correct then even normal sustained dps is incorrect. Although I'm not sure how it really works in game.

https://elite-dangerous.fandom.com/wiki/Rapid_Fire_Weapon <-Says 66% gain?!
https://elite-dangerous.fandom.com/wiki/Screening_Shell

If I'm correct though Rapid Fire Screening shell would be: 102.6/((0.1204819277*2)+0.0030150753+0.88)=102.6*1.123978931=**91.28284968** sustained dps. 

(Assuming all other info is correct. I haven't checked the actual rapid fire stats yet.)

Have you guys considering displaying the actual bonus next to any effective bonuses so that it's easier to see how it's calculated. It would help find errors. Maybe even a mouse over displaying the exact formula.

I'm still confused on how this weapon is supposed to work. Nothing is adding up completely. I'll try to open up the engineer and look at the final stats.

**Comment by felixlinker** [comment]
First of all: Thanks for the screenshots. Screenshots are the way to go to identify issues. This makes everything much more easy for me.

Numbers in elite are always rounded to the degree that is shown. So 4.975 rof will be rounded to 5.0 as shown ingame. This is no issue and makes the 179.1 dps perfectly explainable. There is no shot delay.

I didn't read through everything you wrote, sorry, don't have time for that right now bit will come back to it if necessary. However, there is one point I need to explain you that might change your mind.

Rof mods are _extremely_ confusing_. When the game tells you that it's modifying the DPS it's actually not doing that. It's modifying the _fire interval_. What's that, you might ask? (I will skip some complexities which don't apply to frag cannons, for burst weapons, there's more to it). The fire interval is the reciprocal of the rate of fire. It is the time between to shots of a weapon.

When the blueprint says to you, that it is modifying the rate of fir by `X%`, it is actually modifying the fire interval by `-X%`.

In your example this means:
* Rate of fire is `4.975` this leads to a fire interval of `1 / 4.975 = 0.2010050251256281`
* Rapid fire G5 changes rof by `44%`, but this will be applied to the fire interval as `-44%`, leading to `fire_interval = 0.2010050251256281 * (1 - 0.44) = 0.1125628140703518` the reciprocal of which gives you the rate of fire which is now `8.883928571428571`
* Multi servos gives you `3%` on the rate of fire which is applied as `-3%` to the fire inveral leading to `fire_interval = 0.1125628140703518 * (1 - 0.03) = 0.1091859296482412` the reciprocal of which gives you the new rate of fire which is `1 / 0.1091859296482412 = 9.158689248895434`

This is not calculated correctly in the current version of coriolis but correct in the beta version. However, I don't see the beta version aligning with my numbers calculated by hand (I might have made a mistake, though). I will have a look into this.

Keep me updated whether my explaining on how rof modding works helped you out.

**Comment by Noobilite** [comment]
The main point was that I think the sustained DPS does not account for the first bullet being in the chamber on reload. I could be wrong. I couldn't make the calculations work. 

I wasn't sure if the game was rounding the ROF from 4.975 or not. But I couldn't make any of the other calculations make sense so I wasn't sure what you were using. But the current sustained DPS all apear to be using the number of rounds directly in sustained calculations and not round-1. I could be wrong though.

Beta now has the wrong ROF. the 2A I showed is 179.1 and it was correct before. That data shows the 4.975 being the correct dps. 

Sustained DPS: (**2A medium** example no engineering)
(pellets x rounds x damage) / (((**Rounds-1**) x (1/rof)) + reload)
(12 x 3 x 3) / (((**3-1**) x (1/4.975)) + 5)
108 / ((**2** x 0.2010050251) + 5)
108 / 5.4020100503 = **19.99255814**

Current is **19.3**

I'm assuming this is from adding an extra round into the rof time.

(pellets x rounds x damage) / (((**Rounds**) x (1/rof)) + reload)
(12 x 3 x 3) / (((**3**) x (1/4.975)) + 5)
108 / ((**3** x 0.2010050251) + 5)
108 / 5.6030150754 = **19.27533632**

**Comment by felixlinker** [comment]
I think I truly came to understand your issue when I stumbled upon the problem myself and opened up a new one for that 😄 You can find that issue here: https://github.com/EDCD/coriolis/issues/504

The PR that holds the fixes for that issue should get merged soon and you can then test the fix on beta.
