### ISSUE TITLE
Missing "Optimal Strength" in engineer shield modifications

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#5]
I have a modification for "Optimal Strength" in the game outfitting screen but I can't find the corresponding attribute in beta.coriolis.edcd.io.

**Comment by cmdrmcdonald** [comment]
Please can you provide an example screenshot showing this modification?

**Comment by cmdrmcdonald** [comment]
Although Elite shows "Optimal Strength" internally it has two values: mass curve and mass curve multiplier.  Without examples of both the API information and the resultant "optimal strength" it's not possible to know how to produce one from the other.

**Comment by nemesyssoft** [comment]
I'll have to play with the 2 properties to see if I can crack it.

**Comment by nemesyssoft** [comment]
I'm adding the engineer mods on my Anaconda. I have a 5A shield generator that has a grade 1 Reinforced Shields. I see the optimal strength at +4.7% but have no mass curve and mass curve modifier. Are these attributes hidden in the outfitting screen or aren't they used to determine the optimal strength?

**Comment by cmdrmcdonald** [comment]
I'm afraid I don't know how they relate.

**Comment by cmdrmcdonald** [comment]
This will be fixed in 2.2.17.
