### ISSUE TITLE
Add option to create your own ship

### ISSUE THREAD

**Issue by VfourA** [EDCD/coriolis#501]
This is just a request, and i wager one which doesn't have too much chance of actually getting made as it's not directly useful within the game itself, at least not outside say, a beta.

However, i hope it's doable in a reasonable amount of time to at least consider :)

Still, it would be incredible if one could create their own ship, by editing all the stats and slots on a ship page, not just the slots themselves. Edit hull mass, base shields/speed (if there's module independant stats), hitpoints, the class of the core internals and the amount, class and type of optional internals, weapon slots and the amount of utility mounts.

A specific use case would be to copy an existing ship and make any changes a beta makes, letting people test out slightly alternate designs. Another use case would be for the coriolis admits, who (depending on how the tools work right now) could make changes much more easily and quickly. 

And well, there's the use case i am thinking of, and that's simply mucking about :)

**Comment by felixlinker** [comment]
I will leave this issue open as an enhancement so someone might pick this up, however, don't expect this to happen soon :)

**Comment by felixlinker** [comment]
I will leave this issue open as an enhancement so someone might pick this up, however, don't expect this to happen soon :)

**Comment by felixlinker** [comment]
It's not really doable in a reasonable amount of time, I'm afraid. There are too many issues with coriolis so we can't really put resources into a feature like this that finds very few applications.

I'm sorry for this harsh rejection but this would require some serious work.

**Comment by Noobilite** [comment]
I think the slot changing and changing which slot for core internals is about all you need besides any potentials in shield calculations. Currently you can change the values of mass in a utility slots(if empty and available) to a negative number or positive number to represent differences in hull mass.

Example: Panther Clipper with 600 hull mass.
https://s.orbis.zone/31fq

**Comment by VfourA** [comment]
@Noobilite That link points to a default Cutter setup, did you try modifying it locally perhaps?

@felixlinker i suspected as much, no biggie. I'll try and get coriolis running locally so i can manually muck about in the ship files for now :)

**Comment by Noobilite** [comment]
@VfourA 

Does it have a 1440t utility and one that weighs -500t?

Either way, It's off the point. That is the current limit. Maybe they could make an invisible utility or other slots and let the game modify it as a shortcuts in the background or something. The variables could be stored in invisible slots.
