### ISSUE TITLE
SDPS calculated incorrectly

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#504]
By a discussion with Rub on discord we found out that coriolis has wrong calculations for SDPS. It seems as if the fire interval of all shots is taken into account whereas this should be the case only for all shots minus one.

**Comment by Noobilite** [comment]
Was it calculated wrong on all weapons or just fragment cannons. I thought some of the others were correct. But I could be remembering it wrong.

**Comment by felixlinker** [comment]
SDPS was wrong on most weapons. Didn't look at all but looked at non-burst and burst weapons and there's not a lot of other variables going into the equation.

Also, thanks for the crossref to heat. Didn't think about heat. As far as I'm concerned, HPS should just be sustained rate of fire multiplied by heat per shot, right?

**Comment by felixlinker** [comment]
SEPS and SHPS now are calculated by `eps / dps * sdps` (or with `hps` respectively). This removes redundancy from the calculations of sustained ratios. It would be great if you could tell me whether this aligns with your expectations.
