### ISSUE TITLE
Frame shift drive integrity is incorrect for A and B rated versions

### ISSUE THREAD

**Issue by robertpateii** [EDCD/coriolis#509]
⚠️ needs verification in game
❌ wrong on Coriolis
🆗 correct on Coriolis

Status | FSD | Actual | Coriolis | EDS 
----|---- | ------- | -------- | -----
⚠️ | 7A |  164 | 144 | 164
⚠️ | 7B | ? | 157 | 197
⚠️ | 7C | ? | 131 | 131
⚠️ | 6A |  ? | 124 | 141
⚠️ | 6B | 170 | 136 | 170
⚠️ | 6C | 113 | 113 | 113
🆗 | 5A | 120 | 120 | 120
❌ | 5B | 144 | 125 | 144
⚠️ | 5C | ? | 96 | 96
⚠️ | 5D | ? | 77 | 77
🆗 | 5E | 86 | 86 | 86
❌ | 4A | 100 | 88 | 100
❌ | 4B | 120 | 96 | 120
⚠️ | 4C | ? | 80 | 80
❌ | 3A | 80 | 70 | 
❌ | 3B | 96 | 77 | 
🆗 | 3C | 64 | 64 | 
🆗 | 3D | 51 | 51 | 
🆗 | 3E | 58 | 58 | 
❌ | 2A | 64 | 56 | 
❌ | 2B | 77 | 61 | 
🆗 | 2C | 51 | 51 | 
🆗 | 2D | 41 | 41 | 
🆗 | 2E | 46 | 46 | 

It's probable that 6A, 6B, 7A, and 7B are also incorrect based on the pattern here, as the 5A is only correct because it was fixed previously in [issue #144 in the main repo](https://github.com/EDCD/coriolis/issues/144). I can't afford a ship that can fit class 6 and 7 FSDs though, so someone else will have to get those numbers. I looked up the unknowns on ed shipyard if they're correct then it confirms that just the As and Bs on Coriolis are wrong. 

I'd be happy to make a PR for this, but I'd want to track down class 6 and 7 first in game. I'll ask some credit rich friends.

**Comment by felixlinker** [comment]
Thanks for the reports so far. There are enough people who can test this (including me but not right now), so let's wait for that!

**Comment by robertpateii** [comment]
@felixlinker cool, thanks for the reply. I updated the table with some numbers from eds to confirm my hypothesis that just A and B are incorrect, and I moved the status on the table to the left for better readability.
