### ISSUE TITLE
Update URL in project description

### ISSUE THREAD

**Issue by tyrope** [EDCD/coriolis#51]
Currently you link to http://coriolis.io , which makes sense given it's parent project, but surely you'd want to point your users to your fork on https://coriolis.edcd.io ?

**Comment by cmdrmcdonald** [comment]
Where do you see this link?

**Comment by tyrope** [comment]
Project description:
![link](https://cloud.githubusercontent.com/assets/516490/22211221/af4700b2-e18c-11e6-8dbd-37232d25c86f.png)

**Comment by cmdrmcdonald** [comment]
@themroc5 please could you take a look at this?

**Comment by themroc5** [comment]
fixed
