### ISSUE TITLE
can't import ship to Coriolis

### ISSUE THREAD

**Issue by JeffKaos** [EDCD/coriolis#513]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAGLC4VwC_8WXbU_jOBDHv8oqr0uUh-ap71gKB6dycBRx0p1OkZu4qYVjR7ZTrov47jd2Sps2bNOyd9q-gDT1_Mb2_GfGfrVueV5TLK3RX6_WeVnyG3ZBSWWNEmew_n7NqwoLa-S5Dry7Ubi0RtaiUmlZU0UyxBhnaUHKGaJpiXNSl9bAumPWSIkaD6x7QbggamWNwHpKuQLrWzPsGom84oQp13ob_DzvnvHeIs8wKimSWPwY19_nZoKUWOopA1qSb9hJM_Aj_V7yI2Grvd1qceWCYJrPOJdqFxycBvY6YXA7UdgJwQIjJQl7pqhm2QJ8q1oIrFIF1NNc-z_P9bC9nbisiMBpxmtBAJrx7Lki6jtAdwOcLkh1sR7bopU6t5DIkCj4DK1yzkXv3C704GukssWBeSFRwlNaCJRjt3d252a0wV2ygjCMBWGFNXq1vtIaV_BF3YzBwIvDyI_CYLB9_xsqMRDu-QsW9xQxlX41MsvB6TsLfr_ClGTg9csVElK_2v6qyb7jmOy9_AciCTnAFKKX8znO9OxkhTMCSVZpH5XxQUmxUC9Y_7U-skonPEOUSJgG7L0SBBSSfxnzFwbDJ3iJqVk-lDYyh-1qitsEzfR76xYSwwyT8kb-wnluxt4JAvNF9AnB0q1RYMN0189DO9Bb925_wxQuzBbvQpwOJI5blNi3gwQ-cZtl9vUCVSg7hucGdrjhuZE9jLw27BpSAvYHAoFZtupdomMPNzB49t7-Hli_17CtRjy287bJN9BBOzq6wAwPF5it9rbKOVJ_YRB29deYpWMizDadrry1KLzvieL4oEZOK6hhYMcOfPxOUMcCvfSGwLcjb8Py7WTo7wS0WchdpUiJ6Aey_UAhXnt2rjvUYfwAeI_FnIsSsQz3M51dZmLrFTtxF6wF-IAU7l23a_tboB0mh6WHm-Br2fnH9rVbRFgzKXms7hK3q7ur6RhqDSseECvw_yK8k6tRYEefLUftOEaB7epyFH1OuVAwgnb1iHY4sG0nqTbYUVgc2m44TBJ_RxaOnbjurjAWK2gMuSDLE8VxJSC60LLnaqyN232WmO4zx7KuKi6aWuc2XK-XOwHDaWO4zzTlMycSetWsVlycNuEmLlvrYyQdDZ0wTLqSnmImwf9EN9c_Ni32s7r-sS7rtsLu2PHnZD1sU_zQjjtdtlnyIxyssJrC8fucFbS_7vltUXoxHAIOVilpnEgTWO9YxTygHIl9rcxrTBViz22N-L2N9gqsHsFqn9ZcDgoMdw50svD0P8dNp9qm_4TuD7qOM0zpbG8xR_r1Wn73tkdmnFft5HxHzhGVh5ihYbqdTaphAZmo4UgJMEi042YYfUzL4SYAWZnxsqr1jQzlS91p8-OgcReaYzjuwuEfLqMqZXxJTNs-rIextvH-E0onBPociBWqKsFRtpA1Uf2k-8ZGrM7XZlNj1iIvOcwIjsLP6RKvM_8w8gnyF9MnbWbp5NS3sM5dyWre69oVrR9zuErAuF8vz9zocv37ujo-Iy6_zChcq-A9lDgzcMJRzmutCaUv8AqV2o3nuMmZE5y5yaPnjAJ_FAz_tN7-BScfcPtREQAA
line: 0
col: 0
error: {}

**Comment by felixlinker** [comment]
Thanks for the quick report. And sorry for not testing properly. Will be fixed by 7a17e18a7602bb0a12be0d9963ca02ace4219a86

**Comment by willyb321** [comment]
This should be fixed and deployed now.
