### ISSUE TITLE
Still can't import a build.

### ISSUE THREAD

**Issue by JeffKaos** [EDCD/coriolis#514]
Worked fine this morning then this afternoon I got a popup saying to refresh to see the update. Did it and it errored out. Submitted a ticket and after a while it worked. But it had the same update popup and when I refreshed got the same error. I'm pretty sure it's just this particular build though because I just bought a sidewinder and it exports fine.

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAG3S4VwC_8WXbW_iOBDHv8oqr2kUJ-SJd93SXnui116petKdTpFJTLDq2JHt0GOrfvcbJxQC6RLo3up40Ybg-c145u-x_WrdiqxiRFmjv16t86IQN_yC0dIaxc5g_f1alCWR1shFDry70aSwRtai1ElRMU1TzLngSU6LGWZJQTJaFdbAuuPWSMuKDKx7SYWkemWNwHrKhAbr23rYNZZZKSjXyHob_H_e3dp7izwjuGBYEfljXG-fm0paEGVCBrSi34iTpOBHeb3kR8pXB7KFOsnaydSCYK0of2a44ukCfOtKSqITDdTTXHdSpRaUsGwmhNK7c_JPA3s_Czxsg0lRUkmSVFSSAjUV6XNJ9XeAaAOcLmh5sR7bohVm5WCZYpmLGV5lQsje2C7M4Gus08WBuLAs4CnJJc4I6o3uvB5d4y55TjkhkvLcGr1aX1lFSviib8Zg4EZB6IWBP9i-_w0XBAj34oXIe4a5Tr7WCc_A6TsLfr8ijKbg9csVlsq82v5qyJ7j1Gvz8h_QHiica8wu53OSmuhUSVIKS6g0PsraB6P5Qr8Q89f6yCqZiBQzqiAMyL2WFDSdfRmLFw7DJ2RJWD19aFx0DulqWtcEz8x76xYkUg9T6kb9IkRWj72TFOLF7AnD1K2Rb0O46-eh7ZvUvdvfcE3yOsW7EKcDiaIWJfJsP4ZP1GbVeb3AJU6P4SHfDjY8FNrD0G3DrmERQ36gEISnq94pOvZwA4Nn9-3vgfV7BWmtxWM7b5sOATpoV8csteHhpbbV3lY5R-ov8IOu_hqzZExlnabTlbcWhfs9URxf1NBpFTXw7ciBj9cp6ljil94SeHboblieHQ-9nYI2E7krNS0w-0C2HyjEbUeH0NCU8QPgPZFzIQvMU9LPdHaZsW1m7ERdsBHgA9akd97I9rZAO4gPS480xTey847t8LeY8iYodazuYtTV3dV0DL2G5w-Y5-SnCO_kbuTb4WfbUbuOoW8j047CzykXGobf7h7hDgfSdpJq_R2FRYGNgmEcezuycOwYoV1hLFawMWSSLk8Ux5WE6sKWPddjY9zeZ2m9-8yJqspSyKbXoYbr9nInYDhtDPeZdfvMqIK9alZpIU8LuKnL1voYSYdDJwjirqSnhCvwPzGb6x-bLfazuv6xXRa1yu7Y0edkPWxTvMCOOrtsM-VHOFgRPYXD9TnPWX_f89qidCM4BBzsUqp2ourCuscq5gFnWO5rZV4RpjF_bmvE691or8DqEaz2ac0xOSdwo8AnC8_8c1AyNTb9dwpv0HWcEsZme5M50q_b8ruXHpUKUbYX5ztyjpk6xAxqJuokqYIJpLKCIyXAYKEdF2H4MS2DmwCsylQUZWXuJjhbmp02Ow4adaEZgeMuHP7hqqkTLpa03rYP62FsbNz_hNIpgTkHEo3LUgqcLlRFdT_pvrGRq_O12bQ2a5GXAiKCo_BzsiTrlX8Y-QTrl7AnY2aZxWluYZ27ktW8N70rXD9mcJWAcb9enqHwcv37ujs-Y6G-zBhcq-A9tLh64ETgTFRGE9pczzUujBvXQfGZ45-h-NF1R447ctGf1tu_A--pXy8RAAA%3D
line: 0
col: 0
error: {}

**Comment by willyb321** [comment]
I just loaded up that URL. Seems to work fine. Can you please try the following:
![image](https://user-images.githubusercontent.com/9222609/57988961-b08b7e80-7ad7-11e9-8e2f-8506f9869459.png)

**Comment by felixlinker** [comment]
@JeffKaos was that able to help you out or are you still unable to use coriolis properly?

**Comment by felixlinker** [comment]
Closed because of inactivity. Should the issue occur again, I'm happy to reopen it.
