### ISSUE TITLE
ReferenceError: Game is not defined

### ISSUE THREAD

**Issue by Br41n88** [EDCD/coriolis#516]
> Jameson, we have a problem..
ReferenceError: Game is not defined
>
> Please note that this site uses Google Analytics to track performance and usage. If you are blocking cookies, for example using Ghostery, please disable blocking for this site and try again.
>
>Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Path: /
Error: Unknown
Details:
>
> scriptUrl: https://coriolis.io/
line: 8
col: 4
error: {}

This happens when i first open the site, whether that is directly via the normal url, or by opening a ship build in a new tab. The problem is that this prohibits me from viewing other builds. I can still create my own builds because selecting a ship from the dropdown works fine.

And yes i have disabled all the blocking from addons and Firefox itself and it still doesn't work.

**Comment by felixlinker** [comment]
Can you try pressing `Ctrl+Shift+R`?

**Comment by Br41n88** [comment]
Yes, doesn't help. I disabled all blocking mechanism, cleared the cache, cleared cookies etc...
When i first visit the site it shows this error. In that tab (and only in that one) i can then choose a ship from the dropdown and start building. But i can't open any links to builds and if i reload the site or open it in another tab it shows the error again.

**Comment by Br41n88** [comment]
Seems to work now, don't know if you guys did something on your end or if something on my end fixed it, but thanks anyway :-)

**Comment by felixlinker** [comment]
Ok, glad to hear that! There was a minor fix with an undefined variable, maybe that solved you problem.
