### ISSUE TITLE
Wrong color in power plant tooltip

### ISSUE THREAD

**Issue by Rob-MFn-Fletcher** [EDCD/coriolis#52]
In the power plant tooltip, when hovering over a power plant with more power generation the text appears red instead of blue. Im pretty sure this is not intended behavior.
![screen shot 2017-01-16 at 1 57 23 pm](https://cloud.githubusercontent.com/assets/7255142/21995641/f2e48784-dbf3-11e6-86c4-3e0ff993c040.png)

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  It should be fixed in the current release of Coriolis.
