### ISSUE TITLE
Guardian defense modules can't be disabled

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#522]
Coriolis currently allows that GSRPs, GMRPs, GHRPs to be disabled and their power priorities changed. This however, is not possible in game. They can malfunction though so it might be desirable to leave the option to disable them untouched.

**Comment by felixlinker** [comment]
@willyb321 What do you think? Should we allow to disable them? I think it's better for people to have the functionality. That way they can check their stats in case of a malfunction or power loss.

So I'd close this issue.

**Comment by willyb321** [comment]
Tbh I'm all for allowing people to do this, coriolis is a theory crafting website after all.
