### ISSUE TITLE
Disabling guardian defence modules does not have any effect

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#523]
GSRPs, GMRPs, GSRPs can be disabled, however, this is not reflected in the stats of the ship.

**Comment by Piedone** [comment]
Isn't the actual issue that those can't be disabled in-game? At least when I tried to disable GSRPs to conserve power it just won't do anything in the game.

**Comment by Piedone** [comment]
Ah sorry you already opened an issue about that: https://github.com/EDCD/coriolis/issues/522
