### ISSUE TITLE
Update on 26th July broke the site

### ISSUE THREAD

**Issue by rurwin** [EDCD/coriolis#529]
Having clicked the "click here to update" banner, the site is unusable. It just shows a set of huge icons.

![image](https://user-images.githubusercontent.com/1812668/61943992-8c936000-af94-11e9-8f3d-f96693171c81.png)

**Comment by bent-mortensen** [comment]
Coriolis.io works fine in incognito mode on chrome.

**Comment by rurwin** [comment]
Clearing cookies fixed it.

**Comment by felixlinker** [comment]
Sorry for coming to this so late. Totally went under the radar. It often helps to hard-reload the site. For this you don't need to clear cookies. Simply press `Shift+Ctrl+R`. Could you try this?
