### ISSUE TITLE
Engineered armour tooltip incorrect

### ISSUE THREAD

**Issue by stefrobb** [EDCD/coriolis#53]
The tooltip says Kinetic Resistance 3 but the mod was actually Lightweight 3 as the values show.

Build details here:
https://coriolis.edcd.io/outfit/anaconda?code=A0putpFklndzsxf57o7l7l7l27272e2e0002030404040404063c055i4afr0s2dC0v62f24.Iw18ZIAwyQ%3D%3D.IzAM4yu0RD4iA%3D%3D%3D.H4sIAAAAAAAAA1VSzUsbcRAdk%2Bxq3Gz2I5tkaROCZmOrIoW2WtKmt5YUIcFLUP%2BBsEc9eO6lBw9Ce%2FTgQQ%2FixQ9oaOm1p%2F4DHjwIUgQb8FY0lNb8pm8OC%2BvlwfzemzdvZpdUioiGSYC5N2R2%2B7fMRgG1s58gCq4AnFAFEWmA%2FFGGqPp%2Bmsj%2FOEpk%2FYTcK%2F1j5qR6EInccxvUpwGzf6ETeUseTDRVF17GjdcNokkjTTQlkD5D%2F4RATYDH1EqUSQuzRPpBhch%2BjrLaRXvq%2Bi9E6ZjoFJn0ZhGiBRG9RIbUNpyKDkpLyVrP0MLjsZ6e9LzIoWdWelp4TC2ix7eQ2N3BbmzE5DdIrH8Q%2BSOR38mIpoz4htI%2FHIE8E5NvmZCf4CC2LF39JbE7kLtP7pDDVKvRKcohPLXf2MheRqnP42ilxjVzdfcPlLbKRJ60CaXbeE1UukREdlTtPtV9DEqVQeXUu4gK%2Bkhq9BSz8wNgbcoxknIMT70REZKT8R3otPAYrAMqsiznYyZPxUQD5XgA%2FxhvXFBvI77yFVHcjSaO%2FQq1fy7yjoiKsSGnMiSUIW0ZsoYvyyXVii6R%2F4ybGwv435w5mARtmCS%2B4Pd6OMDh9DberC5YdyDGFTUTTXcTY0RZE3ZGKP%2BtQCBgNmRP%2Fg%2BEd8nT4wIAAA%3D%3D&bn=The%20Hunk%27o%27Junk
![rep1](https://cloud.githubusercontent.com/assets/246367/22131819/c2a9181c-df1a-11e6-9846-0275ec434a45.jpg)

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  It should be fixed in the current release of Coriolis
