### ISSUE TITLE
Rename "Boost Time" for clarity

### ISSUE THREAD

**Issue by Piedone** [EDCD/coriolis#537]
The wording of "boost time" confused me as initially I thought it's the time (duration) of the boost itself, i.e. how long the boost effect is active. The tooltip does explain that this is not the case, but rather, it's the time between two boosts, so it shows how often you can boost.

I'd suggest renaming the label to remove this confusion (should it be there for others as well; I'm not a native speaker so maybe it's just my problem). "Time Between Boosts" would be suitable for example, though maybe too long. Using the "TBB" is also better IMO, since while nobody would know first what it means without looking at the tooltip it wouldn't give you the false impression that you understand what it means either; thus you're basically forced to check the tooltip first, and now you know exactly what it means.

**Comment by felixlinker** [comment]
I think it's not just you who might get confused by the naming.

Other possibilities for renaming might be: *Boost Frequency* or *Boost Intervall*.

**Comment by Piedone** [comment]
Boost Interval is great, didn't think about that!

**Comment by Piedone** [comment]
Great, thanks @willyb321!
