### ISSUE TITLE
Experimental effect imported wrongly

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#539]
[This build](https://coriolis.io/import?data=H4sIAAAAAAAAA%2B1aXXOkNhb9L9Q%2BeiiExIe8T0lmknjXs3HcruQhleqSQd1NDSBWwMx0pvLf9wrabkBCTbsnH1uJH2w30EdC99yjcy98cvh7XjbOtXMrWCraxrlyVrusggPVvtmJEj6%2FFWmb89q5%2FumTc9PwAs7tqmZdtHmTJawsRbneZsUjy9c5k1uuEHKhILuPOybTSmRlg%2BDEd6Vz3ciWXzl3MhMya%2FbOtXflvCm3Wcm5zMqtc%2F3J%2BTJveQUfmpvXzjXy4zDCgYevjsf%2FwwoO%2BB84q2Bw8Z7LZKfGSmGIW7ih3LkmV873Lcv7Edwo9rv7yDYZl%2F2d3LJHdZ1zJz5w%2BVqyD%2FDdHxiMAEO6HooDmK3MYF4sPxz2XBop%2FLq%2Bqb8RIoULf706Ar1mBdvyOy5XPBFleoTDMH4UUko1RBS7FMOPP4b1dNgjGnFDFAb67Hw3JjaYrG5k9tg2YnKznot9072qg7P3%2BrDjsmC54swIKfZiAxQmFqgvikJ8lWfVKvtlcJexp%2BFQb3p7PwNzPlZAmwIozPI3mw1PFO%2FqiicZ0PHAj7RfwV%2FVqBfw1%2F8j%2BevjP5S%2FYYgo8T8TfwNKfYr%2BJvClBK7avOY5q7l8bGXdrDfZR57aOYwv4TCOovM4jEccjukchWeZR0KX%2BNgziJ2SdBIrFi0mHopcPyQ0IBpa5Eb4JcxDwJdInxxyETqXesiNA2xAsiXsv7Km4XKQpzpzT6b7w756XqJVI%2BH4P%2F4NNABh%2FOfg8PpWJBDHGoJ77RzOO9poo6%2BeR%2FQUlljIJgMmAT3ydCHXC55mbXEke%2F%2F58ziOC9kOEneWYiPPIGIg5DYRm80bSA8viGMv0hGx6xESUSvfJ4kTQBLGHtanh93gRXkD%2B4lRsV8g2HHg6duSEocp1G8htSfod5FhuJB%2BIT5fbf3YDQkhnsGnvoA1IKoB%2Bj8nzV9UbBP11VpZYy7XNdgab50A%2BevgSPUmK%2FcndRafJHpEPKSEckr0mpe1kOsNqxs1j3mRDedYflM2fNtN4xgyrKwnpbrDI7GFkat%2BIe5ZOaQ3Jp7u8OCY5vF0pAdY3Qex6u%2FrWWMR0i0x0jj18zRW9U6F8FGIulkWrDlV8peoUhQjQ7BGU9hx9n6ftt3CH4LmD4KG5gL2FuY8sM%2BuwVhha7IbIh5ArkcQcX0ftEbcuEFjQ%2Fnj%2Brac5xteJvzpblfdKr1VRWeVZ0MpIRFssMAcfQC1j6sfW110kIF7XkNaMxjwCPwKudRMeBtLO9H8nIAgRrmos%2Ff8QshTujbmYbJry3d7TdvOzpe5kul3yhfY4KDE%2Fp2TxqcEUx3qT5U0BJIGIRr%2BnTS%2FfdIkuWjTMwwBucQQeNSfNQS5KLfysBEfkgWNHUHXwFlcd0Fy6AzFVoaa7QChBCl3ERrc8wlX8JZ9%2FKLc5sNORZez07wJtNAOw9R369dMFqKVa1iklONjdPrDM1FBS5QsJIaoHEYzSNjYpwX%2BbPt9rGAhdkPPuBVOiwabanzLWd7sTKqBEdQ4mNBIj5If2IJkFYzQpSgEI6thvlqiRRbp8N0gNNqXlysHDl1iWN5XmPaSElpZBqFfVyqNqpzBv0oKIk0KjhdcQrgojHXCDcbuJWu2Y06j%2BQaMYdNDKHCVBzP0GhGxRa8Tla9YxZJxrUHdmPimZz7YFjtgbgMSnSUZ8HkA57nE1JfW2tJasHi3zl2gQi1QBYNz3QX1Ja2KMDBE6jBwmsmhLIxjhEl8Tv2GPOoiFSRDo9Q%2FGaOx8McuRrp1iCDfLDLTL8V3VZMVLB8LF1SxOhwwx5qoT3B3XG6ELMaZilS5GkWhZ8C17ic9rGLSPWtGYoKIqcWoCespy3AIrepC5QL2mXEDQbFut4evpxI0qGNeoDFvI4ElYD02TXfVReyjRGffpk5NXiE4vxD1TQbzPENNMWhBvwlotLUF0kBbzw11RYGDlgl9vXptZmxI%2Fa4fEpkIpm%2BGp1ihlrwzAhob8mzD67aqhOx3DKLRYXDFi7eMCCNCDQ9Zi6xOYArbXfOBq9%2BzHkXxaAkjsEuNOXkeKcLIRdS4ty%2FdgtNjp9S2EQ8uuyTNImxo02nz2MEKbyT%2Fb3vYvgx5B9UliWY9%2Bo9dh7vWN9QgAOOm%2B5bQ9gTwAHbP%2B2b5qFAOKTY03ELXhtevkmFyOHIxRcbO4gI8fX4BFPIeDg1wtu7iHvxQ8flmd8C7ZHanNEPjj2r4avrR13710MT4R5JDpcPmmL2o3gwjS71p0o2JiYn8aJlwQMZ7gUE5bOpt6s%2BQ55ri5AsGw3B2d%2FSgQtmoGnZSc%2Fo6nO5UNSHatDyHCuPdcJsflJ1Pp%2BdEfSprYOx5w6pKCpbs6jZrBi8yHE7K%2FfT8EmQ1kToRoppxwjX88VB%2Fcq7fN2Vl1zjZ8pJL9iTBB2Dc83iM7lvRF5VEMTYY7ek8JM9KcJPJfGkEzneWsX3D7RterhoJPq%2FZTUqk2DPpiJV49xwmN7aiUOXrIFrbZYTypRTvAEbHimFSGpatUfkGVmq7B8%2FdgY28lZ6cdm9l6QqQ0PUi7BnKttlKe2E7MVKvilBP37wWdRus3QHYZL3QM73Tcr4f7HkJdDxQU9l8rU5o8%2FyZrwpnqCP%2BJIGwPYEm0AkInZAsGUkTmkCS%2FuRCyG3LYLNiJTjd4fODqYwEZ4GmUpTqOXwjRQ6LVbGsR8XmRQh7Bz2339nAE5HnECL12NcyQNSfXDgALAX8UXt48qSBM7ixHXdRpad4aaj0hjPgHytWpkPtQ0tqPmOp5Zsab65veyULiq2b42wmPWLDexU23RxjfQ2mrtzeZkXWDByF%2FgjakKjTrHtst9v9I9t3EfHN4aL9yaU8g405y3lat3LDkudXB9QzgTEu8jrcl7%2BYpV4YIPMvDOjhxy8N%2F3nvd6xW6zvWJLt7lmbtee2DSYQK9bY9k51%2BQZBS0dVthzXsju7UQHMrCGD%2FA0GnP8bULwAA) has distortion fields on the lasers which is technically impossible.

**Comment by alex-williams** [comment]
As the experimental effect has been removed and I can't see evidence this has happened via import, I'm closing this issue.
