### ISSUE TITLE
Chaff Launcher Ammo Capacity BP non-functional

### ISSUE THREAD

**Issue by Taverius** [EDCD/coriolis#54]
Worst/Random/Best, they do nothing.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  This is actually an issue with the list of blueprints, as the only one that exists is the grade 3.  I'll remove the other blueprints from the list.

**Comment by cmdrmcdonald** [comment]
This has now been fixed on the production coriolis site.
