### ISSUE TITLE
Distributor Charge Enhanced: Best/Worst recharge rate inverted

### ISSUE THREAD

**Issue by Taverius** [EDCD/coriolis#55]
Worst has 25% recharge, best has 16%.

Also, all grades of charge enhanced seem to have 16/25 recharge regardless.

**Comment by Taverius** [comment]
Also, engines on G4 go to -16% recharge.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  it has been fixed on the production coriolis site.
