### ISSUE TITLE
s.orbis.zone down

### ISSUE THREAD

**Issue by Seforian** [EDCD/coriolis#552]
Main website is working fine, but if you go any of the links under s.orbis.zone then it is down.
s.orbis.zone has been down over 12h now. 
Also you can not generate short link right now [Error - Bad Request].

**Comment by willyb321** [comment]
Working on it. Having some issues with provider.

**Comment by willyb321** [comment]
And for the record coriolis is down as well but it's cached clientside

**Comment by felixlinker** [comment]
Should work again
