### ISSUE TITLE
Missing Shield Generators

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#558]
Reported by Gazelle on Discord *(data attached)*:
> Coriolis is also missing these three shield generators which are only available at The Brig (engineer Mel Brandon)

[Int_ShieldGenerator_Size1_Class1.zip](https://github.com/EDCD/coriolis/files/3888836/Int_ShieldGenerator_Size1_Class1.zip)
[Int_ShieldGenerator_Size1_Class2.zip](https://github.com/EDCD/coriolis/files/3888835/Int_ShieldGenerator_Size1_Class2.zip)
[Int_ShieldGenerator_Size1_Class3.zip](https://github.com/EDCD/coriolis/files/3888837/Int_ShieldGenerator_Size1_Class3.zip)

**Comment by alex-williams** [comment]
Added 1A, C, D and E Shield Generators to the beta.coriolis.io.
