### ISSUE TITLE
Ship/Module discount "mark-up" support

### ISSUE THREAD

**Issue by AndrielChaoti** [EDCD/coriolis#563]
Currently the discount fields will accept negative numbers happily, but they display very weirdly when reading the label at the top of the shopping list.

![image](https://user-images.githubusercontent.com/3628387/71325446-3e827a00-24aa-11ea-944d-c9b1e3c41e38.png)

**Recreation Steps:**
1) Open the app.
2) Set your module and/or ship discounts to -20% to emulate Colonia's mark-up.
3) Read on Costs tab: Module (Ship --20%) (Modules --20%)

**Suggested Fix:**
Change the label to read: Module (Ship +20%) (Modules +20%)

**Comment by felixlinker** [comment]
Thanks for the report. I have to say, this is very low priority right now but it'll eventually get fixed!
