### ISSUE TITLE
Penetrator Payload Listed Twice as Experimental Effect

### ISSUE THREAD

**Issue by DragonSaphir** [EDCD/coriolis#564]
By the Experimental Effects for the Torpedo Pylons, it gives a fail.

gives twice the option "Penetrator Payload"

![Zwischenablage01](https://user-images.githubusercontent.com/38431006/71772421-fc961100-2f4a-11ea-9159-19c77f974c3b.png)

**Comment by felixlinker** [comment]
What exactly do you mean by "fail"? I see the issue with the double penetrator payload experimental. But for me, both work.

**Comment by DragonSaphir** [comment]
I mean that it is sufficient if the entry is only available once

**Comment by felixlinker** [comment]
That's perfectly right. Thanks for the report!

**Comment by Sid127** [comment]
Hi, sorry it took ages to get around to this! This is being worked on, as mentioned in [this comment](https://github.com/EDCD/coriolis/issues/705#issuecomment-1272452146l) on #705

**Comment by Sid127** [comment]
@felixlinker this can be closed
