### ISSUE TITLE
Entire website is messed up.

### ISSUE THREAD

**Issue by Noobilite** [EDCD/coriolis#567]
On firefox 72.0.1 (64bit) in linux with fedora 30. No idea what this is or the scope. (It says in the browser help screen it's mozilla firefox for fedora. I wonder if that is part of the problem.)

https://imgur.com/a/ZmuddjL

It's great that it's easier to read, but I think it's a little bit too much! ><

**Comment by felixlinker** [comment]
Did you try `Ctrl+Shift+R`?

**Comment by Noobilite** [comment]
That fixed it.

**Comment by felixlinker** [comment]
Cool! I will close this issue. Thanks for coming back to this.
