### ISSUE TITLE
3C Guardian Plasma shows less damage than 2B

### ISSUE THREAD

**Issue by x2611** [EDCD/coriolis#568]
![G-Plasma](https://user-images.githubusercontent.com/60093096/72714735-8232d700-3b6f-11ea-88cb-b3d25ab1fa24.jpg)

Thanks.

**Comment by alex-williams** [comment]
Added a fix for this to https://beta.coriolis.io. Please feel free to test and give feedback. Damage numbers were apparently wrong for most of the Plasma Chargers, this should no longer be the case in beta. The fix will be deployed to live shortly, following some testing.
