### ISSUE TITLE
"class" field in pulse_wave_analyzer is string, should be int

### ISSUE THREAD

**Issue by georgehank** [EDCD/coriolis#569]
Everywhere else "class" is (or at least was last time I ran the JSON) an int.  Makes unnecessary work of converting to int what should be int.

Ah… after typing this I realized that in PHP you don't even notice.  In a proper ;-) language like Python you get an error.

**Comment by felixlinker** [comment]
To not get an error in PHP is a PHP fault in my eyes 😉 Will get fixed!

**Comment by felixlinker** [comment]
Closed in https://github.com/EDCD/coriolis-data/commit/c228adb6c0425fc2c3a606be96114ed7a369f27a
