### ISSUE TITLE
data: alliance_chieftain and alliance_crusader have the same retailCost

### ISSUE THREAD

**Issue by georgehank** [EDCD/coriolis#570]
And it's the price of the chieftain, 19 million.

**Comment by georgehank** [comment]
I see now this is a duplicate of #406.

But it's not just ship prices, for example (which confused me) the 3A PP is 480kCr in game but 507kCr here.

**Comment by felixlinker** [comment]
Thanks for the crossref! I will close this as the other is broader. Your specificity helps, though!
