### ISSUE TITLE
Cytoscramblers have 0 DPS in offence stats tab

### ISSUE THREAD

**Issue by xommified** [EDCD/coriolis#571]
They have a normal DPS value on weapon and total stats: 
![image](https://user-images.githubusercontent.com/1205888/75986381-f6c19b00-5ebb-11ea-8d90-ab85eb6184e9.png)

However in the 'offence' stats tab they have 0 DPS:

![image](https://user-images.githubusercontent.com/1205888/75986289-cc6fdd80-5ebb-11ea-8eda-56728ae96789.png)

![image](https://user-images.githubusercontent.com/1205888/75986245-b5c98680-5ebb-11ea-95fe-5eafd447d7e0.png)

**Comment by alterNERDtive** [comment]
Lower the engagement range or apply long range engineering and it works just fine.

Now, whether weapons actually deal 0 damage right at the edge of their range … no idea.

**Comment by alex-williams** [comment]
Weapons will deal 0 damage at their maximum range, that's the point, falloff is where damage begins to drop, range is where damage stops entirely. At maximum engagement range, the damage is expected to be 0.
