### ISSUE TITLE
Uncaught TypeError: Cannot set property 'textContent' of null

### ISSUE THREAD

**Issue by Bwana-Jim** [EDCD/coriolis#574]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.69 Safari/537.36 Edg/81.0.416.34
Path: /
Error: Unknown
Details:
scriptUrl: https://coriolis.io/
line: 101
col: 28
error: {}

**Comment by SirGouda** [comment]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Path: /outfit/federal_corvette?code=A4putpFklndzsuf57o7o0v0s0s24240j04040404040404B05t5tfm3c1O1K1K1K031JC43x.Iw18WAMmkA%3D%3D.Aw18ZVA%3D.H4sIAAAAAAAAA42TP0jDUBDGr7aJbdM2TeyfVLFqG%2B0mdRQEXVRwEEGEjp0cxKGDYgcFXZwcijg6dHB0cHRwcHB0cHQQcXRQRyla77wL9GFAJYUcH3y%2FXO597wrYDwBfGpfuMRejFQJI7icArB1W9qUB4F71AVAIZxW5xyV6EwMwZ96Jcm2T%2FT7MKX%2BLi%2Bl%2BEGWKn0RZ8Z2LCEC5kWcyjIOKbPZI70uZ3SyTD%2BxQBKd6kNl8Yf%2F2kYg0nFavHnCJJZAofmIBjIkqiRoXNSGKdKz7m1w%2FEU3KzBTFmurED0RkCK02BKCfJ3lSb4hYECiOqwoqctHqHIy%2B%2BUbkzL0SlVvP%2FDkjCJQIAiVxTUFhGSpd4cGk2JKuc8cXOux0mUz9IKP%2Fkiau%2B3IqSERVCYvSOK%2BanIovZ7ar2%2Fy%2BLMDIfYojsIJANi74IKPB92QdxXnBRNEALvr9M507rfACWaK8Tq4oygQms4HJXGAyj8uK3JDDynpbQrreeju4JL7cTfeQS6jNYXo77iVeGWWn3OnwiQuByRKmf%2Fk3EPz5%2Bwb3OyRx2AMAAA%3D%3D.EweloBhBmUEZQFMCGBzANokI4TyKQoA%3D
Error: Unknown
Details:
scriptUrl: https://coriolis.io/outfit/federal_corvette?code=A4putpFklndzsuf57o7o0v0s0s24240j04040404040404B05t5tfm3c1O1K1K1K031JC43x.Iw18WAMmkA%3D%3D.Aw18ZVA%3D.H4sIAAAAAAAAA42TP0jDUBDGr7aJbdM2TeyfVLFqG%2B0mdRQEXVRwEEGEjp0cxKGDYgcFXZwcijg6dHB0cHRwcHB0cHQQcXRQRyla77wL9GFAJYUcH3y%2FXO597wrYDwBfGpfuMRejFQJI7icArB1W9qUB4F71AVAIZxW5xyV6EwMwZ96Jcm2T%2FT7MKX%2BLi%2Bl%2BEGWKn0RZ8Z2LCEC5kWcyjIOKbPZI70uZ3SyTD%2BxQBKd6kNl8Yf%2F2kYg0nFavHnCJJZAofmIBjIkqiRoXNSGKdKz7m1w%2FEU3KzBTFmurED0RkCK02BKCfJ3lSb4hYECiOqwoqctHqHIy%2B%2BUbkzL0SlVvP%2FDkjCJQIAiVxTUFhGSpd4cGk2JKuc8cXOux0mUz9IKP%2Fkiau%2B3IqSERVCYvSOK%2BanIovZ7ar2%2Fy%2BLMDIfYojsIJANi74IKPB92QdxXnBRNEALvr9M507rfACWaK8Tq4oygQms4HJXGAyj8uK3JDDynpbQrreeju4JL7cTfeQS6jNYXo77iVeGWWn3OnwiQuByRKmf%2Fk3EPz5%2Bwb3OyRx2AMAAA%3D%3D.EweloBhBmUEZQFMCGBzANokI4TyKQoA%3D
line: 101
col: 28
error: {}

**Comment by alexudracul** [comment]
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Path: /outfit/{ANY LINK TO OUTFIT - LONG OR SHORT}
Error: Unknown
Details:
scriptUrl: https://coriolis.io/outfit/{ANY LINK TO OUTFIT - LONG OR SHORT}
**line: 101**
**col: 28**
error: {}

**Comment by monkeytail2002** [comment]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Path: /outfit/cobra_mk_iii/02A4D4A3D1D3D4C----0202330o43v62i2f.AwRj4jVEg===.Aw1-kA==
Error: Unknown
Details:
scriptUrl: https://coriolis.io/outfit/cobra_mk_iii/02A4D4A3D1D3D4C----0202330o43v62i2f.AwRj4jVEg===.Aw1-kA==
line: 101
col: 28
error: {}

**Comment by willyb321** [comment]
I've rolled back to an old build that should fix this issue temporarily, until I get a chance to properly fix it. Let me know if it works now. (Make sure to check cache)

**Comment by alexudracul** [comment]
@ willyb321 Yes, it works now
