### ISSUE TITLE
ReferenceError: jQuery is not defined

### ISSUE THREAD

**Issue by danielkim2137** [EDCD/coriolis#575]
> Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0
> Path: /
> Error: Unknown
> Details:
> 
> scriptUrl: https://coriolis.io/
> line: 1
> col: 445
> error: {}

I can't access anything on the site. It seems like the website works on chrome but not firefox. I've tried disabling extensions but none of them seemed to be intervening with the website.

**Comment by felixlinker** [comment]
Did you try force-reload, i.e. `Ctrl+R`?

**Comment by danielkim2137** [comment]
Yes I did, but it still didn't work.

**Comment by felixlinker** [comment]
Sorry for not getting back to this. Completely lost track of it. Can you use coriolis by now?

**Comment by danielkim2137** [comment]
Yes I can!
No worries, it worked out at the end.

**Comment by felixlinker** [comment]
Wonderful to hear that. Thanks for getting back to this so quickly.
