### ISSUE TITLE
Shortlink shortcut uses Command-L on Mac which conflicts with showing the sidebar

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#58]
It'd be nice if we could re-assign the keyboard shortcuts. In Safari under macOS, Command-L is used to show or hide the sidebar.

**Comment by cmdrmcdonald** [comment]
This has been changed to ctrl-o in beta.  I'm not planning on writing a modifiable hotkey setting.

**Comment by cmdrmcdonald** [comment]
Altered in 2.2.12
