### ISSUE TITLE
Power shortage tooltip

### ISSUE THREAD

**Issue by VAKazakov** [EDCD/coriolis#584]
Can you guys add a tooltip [2], explaining why 40% became red on power gauge [1], when power group 1 not fitting to 40% of nominal power plant capacity. Also maybe change  40% red indicator's behavior, to change color when 1 power group of "hardpoints extended" power scheme also can't fit into 40% threshold [2]? 

1: 
![image](https://user-images.githubusercontent.com/47143965/80752626-7b373f80-8b34-11ea-9e68-51b64fbe8d68.png)

2:
![image](https://media.discordapp.net/attachments/517431762402672665/705505352585838663/unknown.png)

**Comment by felixlinker** [comment]
Closed in favour of project-card: https://github.com/EDCD/coriolis/projects/4#card-53924025
