### ISSUE TITLE
There are G5 shielded fuel scoop and refinerie blueprints

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#587]

**Comment by VAKazakov** [comment]
* Fuel scoop and Refinery shielded grade 5 can be build by Marsa Hicks only:
* * Modifiers:
* * * Power Draw +100%
* * * Integrity +300%
* * Cost:
* * * 1 x TUNGSTEN, 1 x COMPOUND SHIELDING, 1 CORE DYNAMICS COMPOSITES.

**Comment by felixlinker** [comment]
Partially addressed by https://github.com/EDCD/coriolis-data/pull/84

**Comment by alex-williams** [comment]
This was fixed by another issue being resolved relating to engineers not matching engineering blueprints.
