### ISSUE TITLE
Shield Cell Banks: displayed Spin Up Time not affected by engineer mods

### ISSUE THREAD

**Issue by Taverius** [EDCD/coriolis#59]
Always says 'Spin Up Time: 5.0s'

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.

This should be fixed on the beta site http://beta.coriolis.edcd.io/ please could you take a look and see if it's now working as expected?

**Comment by Taverius** [comment]
yup, works fine on the beta site.
