### ISSUE TITLE
"Boost Interval" is misspelled.

### ISSUE THREAD

**Issue by crowlute** [EDCD/coriolis#590]
Title.
In the top bar, it's spelled as "Intervall". 
This is my first time using github so I'm sorry if this is in the wrong place or if an issue is too 'urgent' vs messaging the owner, etc. Apologies if there's a better way to address this.

**Comment by felixlinker** [comment]
Your report is perfectly valid and helpful! Thanks for reporting!

**Comment by felixlinker** [comment]
Closed by #594
