### ISSUE TITLE
Failed to import ship

### ISSUE THREAD

**Issue by Smykes2112** [EDCD/coriolis#595]
Hi :)
I had auto updates disabled , so thought I'd check and see if a newer version was available.
EDMC seems to work with EDDB and Inara ...but now I keep getting this "Jameson we have a Problem Failed to Import Ship" message in browser.
I have saved and bookmarked a few of my Coriolis builds that still display correctly in my browser ,  

EDMC buttons  displays correct ship name  but not current system or station.
Was the cmdr name  a button? I can't remember.
 Ship name button doesn't display ship build in Coriolis or  EDSY.  I prefer Coriolis visually ;)

Firefox is up to date, Adblock has always allowed coriolis. I dont use IE or Edge.

Error message Details below. Sorry I dont know what file you would need. Hope it helps. Thank You.  o7

Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIADcaFl8C_-1Z33PaOBD-Vxg_E48s_-atDUmTHly5kGln7ubGo9oCNBjLJ8tJuU7-91sJAjYmsUm56T1cHpLYeD-tdr9vd2W-G2OelCktjMEf341bSVfGwFjkMlqxjGXzlBRURDP2jSbRiiasXBl941NmDKQoad-YCMYFk2tjgPrGNOUSjG_KOb0hIsk5y6RlPPXPAzvWj_37wLgBLEgRkywD3IL9TVEUwyIFbsW9Z9l6hxpUUeNSSkCLebzMmXwByNoBTRcsv9w-W0FZqbwRERMx51_JOuFcvACFd1CX6uEbIuOFRrrK5iyjVEDgjMF3431a0hwu5O0Q1seB59ueY_f3938lKwoo78SKlyK6oeRhPSxhhf4OSblLU5rR3kdKssoHCtJGCFsQoKtvOay5opkk6dVsRmPlWpHTmJE0IhvweFFmS43ceDga8ZikrKAJmA0pzXuTlEi1h74xog80NQZOX9GazRgVG2KPyFd1Hx6f0Symzx_CFlK5GJepZHkK1xqhKG6LD5wnOpmfBIMNkPQzgSAYAz80Q_UDId3esRzPDIIAWZ6K6PM6v8CmJYvvaMEKSWDFVuQLjEykfpwd9IUVmJ7rwa0q9P2CitVJ0AC8d9e0MCziVxEhxCkv2AM9xV17Gwlv764dmI5tQXCe_uwbv5WQI01kEz31D6i_TfJckIRarQLY8K3KfeBilPNHKvKUwL9Kl8FGl24r2kTZTZRdVw24YVMDG7NoyMQh_yeCzyB0XPQmEIFjGsBtGqAbcP5ARcohREkHHQgy7w0FJLHYy8B9SQa3maRzHZi2PFueW2WPg0zsVrmjowmLPx4gWU0kZAZ7IGyiEJht1Xiot_0pl2xF0jEks9U72_aq5MYh-IeOQk6omHGx6sRtC9UU47im47tWEDaBoX7IOyJp--ZNe--liYOgJhFkhgEO9ypR9N5yoAO1K62MsGzjWNGV2-GR-n49HQK3svkdyea0Tu6r9IEJ0hsTIcty2eS25bVxe1Yk0UJ1jnZOKwrAUhmZbyvz67X9CGOaiQhqqUUHdDlFF04VyMam7zt2GL5NG0CASoVGKKjCQDpO0QT2a_R1kGWZfhC6rnXAOT_w65RbrCEdiaohmnZ-V9pdC-ANTCkzqQvQYaFOGdTDMs-5kFXc9glqBIbTjWFHOvt20KTzJg3Q2AT7WkoOgwubL64F_auEUeCgeENz7Q0faZpqxh2SO0DtLPxCSc6z4pLkJO5CJM-qJMsNTNeFplrL_xbxjsYLGN_ay5dnWjvAwMSh16xb3d1zqu5Bz4eCe7Rqd3evqhuorLXZZrougDfn9G6L-HbvXhxldjNIUqHWSbo5JGYXkvugZ9ttknxKMxg5XirbI1i79xGeLPixgcRGZ6quUAYr4fNNxeU6mTd-3qtcyCkcq97Bma09K3aty2OzNoI87_d1CNetlf4gxAFk89XsFtrX4rSidUcS0phVZyVNYa5eaihvA2W3TqrXYHUPVodo-sgnSLysTgftY7T6g6xoqmzOCYmPQ6o9FzHneXXT7aLQkLaG9DpW_cDBRwSxYDRNPsBRVBClzO2x6dzjTKGXiQSdb1ZS_a91sLkmhexd7guSVp59hmHdsmuDK5xMlQBrJfZOeXpkZj0iOnN_yrVNrybj94IvAaYzVlDxKzTxjx2Vm0dPG0acEE6e3o8dlI-cwS3H9O3wAPktB2a3NpSF6hj1evHRxJrv-FutHNEMCNRNSU53Jfm25VpHjrpjVsTRCGYm-YWq382Jabpl8oF6kHOuvoJRrS2_dWa3q90d2oGjco1fz0MieEZjnknB0ygXXAn_OR_uSUXNPS0V-L-ZilqLD35eKmIOQ3osGc_ekApPp8L9PxU_PxV-JRWVBQSdQdDEWiM6JyEGGtE5REx4vIQcx3yVl-odpKrbMKol3UBDDWo3QKkkLKVJUYoZienzFwWSZetOuBbSuFbj5WZKoCuSHAoOiRdFyXSPbXmxubER63dbs6k2qyA_cBbTXE15D3TLjdchPwNzaPpZmRmKEOqriN1bXGNzrXViO9uLBGY
line: 0
col: 0
error: {}

**Comment by Smykes2112** [comment]
update..
EDSY doesnt work now either

**Comment by Athanasius** [comment]
This is an example of a URL 2083 characters in length.  What version of Windows are you using?

Despite using Firefox something about the way EDMC is opening URLs on your setup is still hitting that 2083 character limit.  There's a chance that your setup was always hitting the code path that ends up using Python's `webbrowser.open()`, but with the change to Python 3.7 with EDMC 4.0.0.0 that's now using a 'bad' method to get to Firefox.

**Comment by Smykes2112** [comment]
Sorry for delay in checking/answering..
I'm still on Windows 7 Pro.... dont ask ;) 
Downloaded and installed latest version 4.0.3.0.
ticked " use alternative URL method " in Settings.
everything works now as before..
great work by all your team, 
TY for replying  :) o7

**Comment by NailAlex** [comment]
Hello!

I have the same problem as the author of the topic. 

Windows 10 (2004) and FireFox 79.0

Turning on (and off) an alternative URL in EDMC settings does not help.

With an alternative URL, redirects me and still gets an error.

"Failed to import ship

If you are attempting to import a ship from EDDI or EDMC and are seeing a 'Z_BUF_ERROR' it means that the URL has not been provided correctly. This is a common problem when using Microsoft Internet Explorer or Microsoft Edge, and you should use another browser instead.

Please note that this site uses Google Analytics to track performance and usage. If you are blocking cookies, for example using Ghostery, please disable blocking for this site and try again.

Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAAjIJl8C_-1c3Y7bxhV-FUEokJs1wRn-b69sr9ded7ferAwHbVEII3K0mi5FsvxZWwkCOCkSIEhRX_SuN2mQF3DSbLuIY_sVqDfqGZJrkRQljrR0UbcO4HjF5XwczpzvnO-cOfIn_SPfSVwa9Xd_90n_5nTqH3i3XRb0d7Wd4uM9Pwho2N9FsrzTv-OdMo_SkHmn_d1P-rfchAbwIT7YgxuwqRuKhq2dxfVfkynt7_Y_oiTwveG-bycRdfoLHPjdLea6vYdJ6MGnxS84oCLLMuIPfQITYFPqxcS9Mx5TO4ZhUUBtRtyh69tnw1FIyVk-fune4aFvE5fx5-7207-mF-nL9GL-NH0-_zx9NX_aS1-nr9Kf4dIXvfTH9MX8WW_-WXo5_wx-fZH-PP-6l_4L7v0i_SEb8bw3_xKuv0gv4WGH9Jy62VLBKrIxo2G-jodkxK_3H05oOCXuoU-c7O4oOoju-j5MBO30H4QMXpW4jwgsVn8XI8kAoKtPWDIVQ_t0ZwF2M5z6SXhMPRqHJGa-V4OUlyBhxyR5AYksCWO-pGXUI_KETZPpCfFOaSugolUQdcs0JMWyLBmXIQcTPx4ElDqteKahleCQoeqSqVqWoZfh9siUnNJ94rr-eCw2T_6WJWCYIiwnXFOtT3-_0_8wAXOIZzBQsnRYjP5BTKfwoEkQDwOXRFNCbJu6FFbZD4dj9oQ6Q5eE2XMfeP3dOEzoTv84ZH6Yw-z0B67PbfKQ33WPhE7gg-2jPn-Nd5FTDoOfwgh-Apt2HQFa_R3I8Rnw5iK9zIjyl_lX8PNFTq4X6cW7RxZTMvROuWJYEr9mmR1xRc1eGqtdc8U0JQSc1lCdK4r59riCl7iiL3EFC3FFRepKrhz63unVqpTYApbXGxSTrnNFbePK2A9tOowm1HUFePIdjy2cEBCEXs6_BobAhZdAmKfzZ-mP868FeHJEoqiVIGppSzWp4p6P_cc03AvJ41YQWVKtNyiypOmK1h0dFE7h7aiAZA1J8EfGWokQiirpBkbIuiYhVsy0RgZ4dpUNNvE8MLGcAlPqsGTayoGj7LY1AcOsk0BX2zlgYlmXV3LghATM2WdhjQOH7OPeycxpjBdmKwciZwgPomGYBLEAC765UlwgpwrNtT_YE7D9fDuPaTigtu-1Wwqu-ExLMiyk6w3qohVIq_hIRcIV091jURyyUQI-UJBYWC0RC2mVKZ2QmD4YF1u0flpAyjJBLQ0rlfByQl0Ipw9hK1rnVFmpGjXvszjOLKPtteTybCqUAcJW-eIk09EY3nHKoojxAAIyPicPBBXXHRLnnHh25g3Wk2jAb1_DIVTnkCkUR_Qt4ojv9D7gweQWREZYsA96R_aHCfO8ZU5hvZVT4AlHfFFsEtnEoUPb910qoMV-sRLBg5f4ZVcRBpfVkqRvF2EQ2H7J6hRc49WGdFcMSVYNHS2iFrYkXTFrokuQ81iRlAVNQRBCeKkpwk00KyqvmFGNyZuF0qpi0wxZkUCqNr7kRpEPrQauRj9N1qtkDglzTxOvTOANeYvf8_Y9b_-_eNtcPemAtyXgmmo1rK55q7TzVmmlraFwWbZM2yMW2cN7lMQD5p3dJgGx-Vwq3D0h095DMllmKuJVjoIx6FqMAftexRj-ooUNtJtlWUFyNbSVTEPlnUYg2tarrAksXgSL55LEs8Hoh3EShjQexsybte70Q7hpE2HFfYLIThsrdvr2hIzH7_o2L29QFxuN2jba5mu32OWNtzePv-3h1bAawutgwsuEt3yfR8_hCY0gH2LntSi7xxzWewS5DXjeptAqy22hNcoeMyoeQ8djZjO4UyDh_BsknC_nn8-f8mrk_M-99JJ_5FWYrB7zQ_oyfZVV_EWq-geQ6Z6GuYm2lRLKnJch_eT_bVuMqaR6ejXi_gpWMmZ2vvQ8bxJIHcvVRClbf7wUI7uFhG1y_Qgs49qga7lQtZOIfUzloQ3SLsKbcUJ55zhhTxLvbCZAiG_nf0pfZ8dgP3FqpD8WXCgOxYQKkeI8UM3SJqpYwlydmNtKT1xSnlXZSccUTOpqtvkOHCVuzAKXLdUvmkrhuXktxCPWq_77mjTTQJh2SLE63LXplQFuRy1tM2qpGbUK4HgW0CeQJ9lnAYtX4KCF_pyw4HZxbwlkys-xSWiT8NQfkZnj--EKKPwG6ja_-R6J7Ykg03W1gen5WRPXqeezvaSuXAbUpR7t3aekKZ1sPYojObgwsb_jBIYY91V-xACEftZLv88C38v5M5ESa5VE8FZuPNmARIYlZVGuxFIN7AqyOVW_HpVuLPPzBkQETVX0LiMX5rloB4HrhlKshL6YLiS6SFGRWU_MTAMveJbTodj405A4FLWSIrdB0XilN1hx5oGPXeLFwxysfqZ8j4YENLjHGsKU1WbGAUcPMnTRekj9TBmM-ZKfl3HZ9jp9kT7vrCJS2X216vHFgxzC5UM3bOQtB2g5zJUynNbTC346K6MFqilhrNaKGTxBvlOIYXsmcqpXEpKQj5mrXT6YR3nruL_X1_v7hUkuDErUuWoNXQ75sOEeC-uO9Tj0x_Ciftg7hqk3OVfcZpU0B_fPacjzMiGr5Ce4P3GNlF5mpvii45yhakZI1iR1SUeLqyVwjwv3Y0qqblT9WrYAD4KYTYnbQJaG6alqRTJgXa4S5g3kMQ3HPte1Nt2w-QKpWlZ3lvVlYG7s_IBsw3Qemy1WXpiCgIWXjm8J8_JZRaKeV27wvPuDvWGuVesu9457zsDpHpEwTpKzhuKHLnIyO-HCRNTfpq_Bsi-yfODFlYXzhPkfvGMO3DC_9Hz-Jbjiy_86_1vFMXPiVNJtWOqNjF3WqsYOSobn8NiogQpbJTbKeKZkrbfKCUiB0AlBeGSWqYla5n4IpgU2NY73-GAR6zQUpDblsVll7pCdTuKPKP9_rW0AHt27D3dGfpMHVhbFOfVaNmJWBdp2FmLq5So5yn0MXr8DLoMgkwSBH8blLWivJBzCwEE-UNQ5KNYKWVbqLxjeg03YD-kfkyLY1_qY9h5T123q4kCmkEZzSo8ak0ikuPYtuIWL-dP5F5nveAWfXoH_4GrtJyEnkR_ORcKyqMJJCBWaVa8mFIgn1J4UbV0tiKWagiGZKtKqVbrCyQvPsFr3Q5LVEHTFZ6eUZqdKJq52iwxmkIpPu5pbgXadubWLybKNbRRw62QQ8muqDNxqqM9RD7Tjas92PwHPdhBNpoQ0RF6syR1FPyR34toqFbZaDM1f9SHf0HhgE--md-qKHFeWJ4bX9fPwnY2yh0TZhqqiG3pCHBKWqzgcaZxQF1LsszKU0ppu7MMoyE7PBJ2tqa6s2d6lXtHPWhQSaiGPst7tCU0AetnJYrF67UaHF99kFdrL9J9FSedV0VednWdcpN8X7aSXQl3WG-gppFRqg3lbsGVsl4goUimLldRaE3Sx7IM4BB0eT1rnZpVt02ya2R3Yw9MZ5CAn9JR6AkmxXkqKq9PbvFK1XPkB3YeN-hw3r1M1lMDgWcpSANymXlUNq1Yr37NNO33DlZIjV66UQ0sjAfwlo-GADxSVSKhBIt1LXPeEMi_rxOY0ekul2Ak8J6w85z9XlRULJXrVY6trDkfyuu5Nx2FC345QKoyDNFaSDdW0rkcTmGFmuQsnA3JCt3TtmiwRw92GI2uQqwVdrCtKLZVbsh6BdAJVyYIzsmjvydIBWcxqewXukCsV5aRjVVIg07zu6QfKQ4pZ6S1RlGuHFDHcbciyBnl90aORKepGTFEypqh1adkMjTeCVjNo_J6EnTejmt1xEFXilaJZoOmAg_i6h_mZRVulSrWEdL3W07PN8aMI7nbH-yuRt-DgZkTRNiKKbpiNpfHse0UOs7nGhBUg3lKV_Lbv-h51e7dCFvX26NlZY_lLFShFbtKNpeBywlDNGGDaB4tpizXxGtVv7Gmr8faJDct4yKZZs8QGoj47ZVm_7-PIKS8433Qkmsxnm65nm47Kjnfkj0YuHcahH0xmQ9ufjkh7l8etbJCsNACB6XMfAEgwDhyWKJbWIZbRgBUwuGVKXCoIguQyiEPt0jn5bDhLYCdDf9oKtscHomWox4z3tQiNxg0TSabBWXaqKjC-skv5SZqdRLE_ZVG-vAHzzlqhcsZyNot3MiDjfzq6Kp1JXKtW6O1S4moY9LMO8VXrWOIakmnqpq50rHCbYDsRuG-Aq8mgjnSjU4l7xACahDMZvVeh71PB96lgK09wPRHMukVpF9CV2BcQAP-DPxrmPXzT4qbhORuFvIFqRl3Xf9zeOsVh7vuj-qx5FxaNSRCEPrEnUcLidq1xnI8JZzeLYYNsWAmZf70QkGP-r1iwgDlDx09Anri8H2bkEvtMqCX3YE9-G6CoGTQIiQ2kIa6MN4Djjk_uGrAyw3Of2TTgX948p8Upy3qUR8Ab6j7iw8o4j7MT7C1EVH70fSWigFx8mldNpf2dYlV5LqAWHxx-CrXbv3vzBkKouKOIEHdPHhw9uPXgN3AV_Gx2G__KpJ9w_R6D3wb6Tzk6lrF8QzZvyPghUndldVfTf9v_9N8z6H7GXUwAAA%3D%3D
line: 0
col: 0
error: {}
"

**Comment by Athanasius** [comment]
The `AAA%3D%3D` on the end tells us this isn't a URL length issue.

What will help is if we can get the `Loadout` event from when you login to the game with the same ship as in the above URL.  That will be from the latest `Journal.YYMMDDHHMMSS.XX.log` file in `shell:SavedGames\Frontier Development\Elite Dangerous\`.

The line we need will start something like:

```json
{ "timestamp":"2020-08-02T18:58:22Z", "event":"Loadout", "Ship":"python", "ShipID":6, "ShipName":"Dobbin", "ShipIdent":"CH-WHS", "HullValue":48191570,
```

Then we can see how the data in the URL above compares to that.  EDMC *does* do some internal munging of the data before reconstructing the Loadout event for the URLs.

**Comment by Smykes2112** [comment]
Hi :) 
I am sorry to hear other users are having this issue.
If it is any help, here is my latest JournalLog for comparison.
I am still using Windows 7 Pro .. Firefox 79.0
Maybe it's some quirk that Windows 7 has that Windows 10 doesnt.
I am not a coder, nevertheless I find it interesting how problems can arise and are solved by teams who provide 
3rd-party game tools.
All the best, 
Smykes

[Journal.200804113245.01.log](https://github.com/EDCD/coriolis/files/5022135/Journal.200804113245.01.log)

**Comment by felixlinker** [comment]
Closing in favour of #597. Thanks for all the detailed reports!

**Comment by felixlinker** [comment]
Nevermind, might be a different issue 🤷‍♂️

**Comment by felixlinker** [comment]
Issue of @Smykes2112 is related to #597 but issue of @NailAlex is not. Will investigate that!

**Comment by felixlinker** [comment]
@NailAlex The problem you experienced is due to #600. I will close this issue in favour of that one to keep things clearer!
