### ISSUE TITLE
Inform users about Windows 2083 URL length limit

### ISSUE THREAD

**Issue by Athanasius** [EDCD/coriolis#597]
To aid those users who fail to import a build from EDMC and the like due to hitting the Windows 2083 character limit on URLs under some circumstances I propose.

1. If the base64 decode step fails
1. then if the full URL length (including the `https://coriolis.io/...` part) is exactly 2083 characters
1. then inform the user about the Windows 2083 URL length limit.

NB: As per comment on #595 I've now realised that *perhaps*, under some circumstances, EDMC 4.0.x.0 might have an extra issue with this that older, Python 2.7 based, EDMC didn't.  *I* can still open 'long' URLs with Firefox 78.0.2 on Windows 10 without issue though.  Either way we'll want to come up with a good set of instructions on how to avoid the issue.

**Comment by Athanasius** [comment]
EDMC 4.0.3 is now out with a workaround for this situation.  So if you enhance coriolis to add this the message could direct users to https://github.com/EDCD/EDMarketConnector/wiki/Troubleshooting#import-failed-no-ship-loadout-found if they're using EDMC.

**Comment by CMDR-DrDigital** [comment]
Hello. I am seeing this issue for the first time today. By the way, my EDMC is version 4.0.4


Browser: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAEN3MV8C_7WZXXPaOBSG_wrjm95QjyV_c5eGpslu2NKQ6c7szo5HsQVoY1teWU7Kdvrf90iGYAPBJmV7UzDWo6_3vDpH-W5MeFKltDRGf343PuYLllMqWL4wRt-ND2lFC_gib8bGCOHA823bd4bb57-RjBoj43dKCp5Htzxf3JF8QY3hCwl-_SA4H9wT8U_F8sYvimlblmVb8OxbAZ1mNJck_Tif01hCu7KgMSNpVCxJCQOKSvpPRfNY0_feh85jkrKSJtByWrcYzLYtbukTTY2RO1TzZXNGRT3jW_KgnhsTUpb6tbK8KT9xDhg0ND4LBoMl6VcCMzZGjgljXX92TfxjuG0_5c9UjAV57oRYZhi8UJCJsN_kjElGFnRKxYzGPE92aNYezTN9Nwyw-0L0TCuwA8feh3aykOnjxshcJ2hCJuQby6pss8HHUWpjm4sV-rbpwbMw2B_XFUlTPp_3A7uvcv8aGl8qkIBc6TV2vR9D40bSDPpZFjIqqrSkKSmpeKhEKSNZCUFllNGEVRl0-zk3RlJUdGhMBeOixgyNWcqVFif6tWsikoKD7pGhpnGRZfwmv0xZYYxCeLf-fs2LQukeeYE17BFRjpLDaRF1z5PBu_slHXyACUkq3g0m8ReIrgPhhb2u8Iq5ELxkTzQqlzRNu6PrctNgMFs3WAeXc8bgst4aXNtIgM_emwXstAXso8A1URj6VitaZ0suZwWl3XGKvBYPBz7M1w8D22nylILWw-wkYtQiKrm1V-0N0YVfn_VOeAXIbcdXVqWSxSTPQbY_FVtYx1aTzHKIHh260Zx9o8kbwXY3uMyIFvRx7ky9teMFZ8fuLUO5ZDRNHjhXER-V7F9qRTH0Urqd5HuWr454F8J73gU6sNr2CT1lRAMSOleH6maXJcBPGwHeH8H-AFq9x0syn6ekyuMlzP30Huut7_ZiP8T7XjzTC_9hvfB3tGSlBPdrW_ItZYPLJa0AvefBCHd5cHtvH6ExxFK3E19xEatDgMePWxe2X3Phm1zShV6mTvMLGibgOCby3ubGyGzmE3b77K9VtBlqvcgTZSJFCt97WJWpRGo52x4CM1BPwmY3v9ZrWe8a2eSCx8AtU8Wm74fwr4mEg1dkb0eietyt7BH2OdVH6k9DmzaN1Hnwf1iI0_QmuSpoCFlE_Fgw-QoHbU1uyYrL9bsNSKaKECJiIhb8gawSzkXnkC7Vy9dExsv94RCR8UpEgpJ4HavHh3Wh3-_rEl647xI6KqYpyWVUW0XSNohrKghUQTk7UAKp5LGrQOkfvQg3U6nQPpBLXZKCxH1YGMocJSz0wrNtM_RDz2-FxDUlEvyJxQxietUjS3OaWdpOboE9HG51CyscFWrMhV5bJVrvuGi3u7rdk54767kHdrZuFo2Z0AvW2NOp4HOYKBeDKYz-UPbd6fy0hvMnKlJOklo1x10frHcxGAuQdWmcVTeO07I-bDp7RtXf-0MTNcwfdhXwLcvTE_9cSAZpz4EC4VDC67U8Lwh3Et4XJJTPcy6yXja6k0WrNfARatepNViJ_I5I2uPYs7eJvomD3drU35H3WgNK2n5fP54QltfDKvtqOzxwc3M1G79WZH5MnxhY1oQIWVWPB7KazspyXibRkpKnVbemlQCgqxwKFnG225rWTQFua-WUsECtk1Yb1E6WcUqB6jcr1MDDbhME-3FKSKCgXVX6vm3a4M14R3F2s1pTklvCKSkSoav-bkfdyu5KgG7gDJ9LbUDNg1dhUwZ-WBUFF7VTuzUXd3JvoeGsbrjLXFSQdjCS60MggexIsIdK8jp_8TrJ9dZsm_WJFt-xkO0eqARoDmb_WsB0lgBnuSZBbQ9sq7oe4D0kRlTOoBi_gDq0z2VdU0PYbCmy38WB5-PWuCwbvDoIPSdwdqToIdyWYqnHXOrtdPrq8I4kROwqZV7RFHLnx6ak7c4k4QpaQV72uEvTuaggcY0LahzqTnDhP8uKZqrNOZGoD9I_CYk10j-O9E5C2hrpHUe6JyEdjXSPI52TkK5GOof0U8acF6dpUSO9w8hE8Fx
line: 0
col: 0
error: {}

**Comment by alex-williams** [comment]
Updated the error system to work out whether or not, in the event of an error, the URL is equal to or greater than 2083 characters in length. If it is, it presents this screen, instead of the normal error screen.

![image](https://github.com/user-attachments/assets/3c0e9780-8281-4cda-83f4-adefd4c43578)
