### ISSUE TITLE
Jameson, we have a problem...

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#60]
I did backup my ships from coriolis.edcd.io and imported them back in beta.coriolis.edcd.io. For some reason, I have a couple of ships that will display this error when I select them from the Builds menu:

Jameson, we have a problem..

TypeError: r.getTime is not a function. (In 'r.getTime()', 'r.getTime' is undefined)

Please note that this site uses Google Analytics to track performance and usage. If you are blocking cookies, for example using Ghostery, please disable blocking for this site and try again.
Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12
Path: /outfit/anaconda?code=0pptkFklndusxf57o1f1f1f2m2m19190303040800040404060505p1CbCbf5321vP42f.Iw18ZlA%3D.AwRm4yu0Tc4KA%3D%3D%3D.H4sIAAAAAAAAA02QsU4CQRCGh0OBuOhycHdcoLjCrYSS2EpjbKCiIzE8Ay9ASWUPkcqX0MSOllBSmFjwBHSGhBh3%2FP%2FiEpovczvf%2FrM34ssi8ncB1N%2BMyHXtRsRERZFwVxBxc0AL%2FoESSknuAxErXrWyADTwSd6KX3HrdoC8tINv%2B4Wz6BdSvcuQom%2FRvOSkRQ39j6Nqegc9eonQb%2FinPCk9YYjZoAwJR9gGpmU9ZGh8Zq5pvtMkHGH3mJltqzCTM3MMmBFNwhF2xswlHqNN%2F5ib2e6Ky8jQ7%2FNiCYfmGVVIOELbfpivLZ5U0J%2FiHeEBcN%2F4w%2BDzR7W9RnpphqWkK97Rf2XNwYhsAQAA&bn=Mining%20Anaconda
Error: Unknown
Details:
scriptUrl: http://beta.coriolis.edcd.io/app.410067.js
line: 421
col: 3901
error: {"line":421,"column":3901,"sourceURL":"http://beta.coriolis.edcd.io/app.410067.js"}

**Comment by cmdrmcdonald** [comment]
This was due to an issue with limpet controllers.  Please try it again in beta and see if it's working now.

**Comment by cmdrmcdonald** [comment]
Fixed in 2.2.12.
