### ISSUE TITLE
Add advanced weapons

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#600]
The advanced multi-cannon and the advanced missile-racks are missing from coriolis-data.

**Comment by big-malibu** [comment]
true. and Coriolis stack if try import ship.
please fix that, I am forced to use EDSY when I have advanced weapons.
thanks for your work!

**Comment by alex-williams** [comment]
Advanced MCs are now in the https://beta.coriolis.io website, just advanced missile racks to add.

**Comment by alex-williams** [comment]
Advanced Missile Racks are there too, however they do not appear clearly in the search feature. I am creating a PR to resolve that, which will also make other 'special' Hardpoints easier to see in the search (Nanite Torps, Grom Missiles, Packhound Missiles, Enforcer MC's, etc.)

**Comment by alex-williams** [comment]
Fix deployed to live site
