### ISSUE TITLE
Experimental Effects Tooltip

### ISSUE THREAD

**Issue by jpwalsh1** [EDCD/coriolis#602]
I'm never going to memorize them all. Other than the 'change' in the categories, can we get the flavor text of what they actually do so I don't have to flip between it, the game/wiki?

**Comment by felixlinker** [comment]
This is a very valid suggestion and has been on my internal list for a long time, I hope, I will come to it at some point!

**Comment by felixlinker** [comment]
Closed because will be tracked in project: https://github.com/EDCD/coriolis/projects/4#card-53923883
