### ISSUE TITLE
3D SHIELD GENERATOR with G5 Enhanced Low Power wrong value

### ISSUE THREAD

**Issue by DemonBDC** [EDCD/coriolis#603]
there's a mismatch in the Ship Builder with the Maximum Hull Mass for the 3D Shield Generator engineered with G5 Enhanced, Low Power. The maximum hull mass is listed wrong as 388T instead of the correct 413T value.

**Comment by felixlinker** [comment]
But it is correct without modifications?

**Comment by DemonBDC** [comment]
Yes, the value is correct without modifications

**Comment by felixlinker** [comment]
Duplicate of #473
