### ISSUE TITLE
Shield recovery time different on (ostensibly) same build

### ISSUE THREAD

**Issue by spacek531** [EDCD/coriolis#604]
This ship is reported to take 10:40 to regenerate its shields:
https://s.orbis.zone/8eR-

This ship is reported to take 5:25 to regenerate its shields:
https://s.orbis.zone/93nI

I cannot for the life of me figure out why. The first one originated from EDMC and the second one originated from Coriolis.

**Comment by onspiene** [comment]
Pips are set up differently, hence the difference.
(The second one has all the pips on SYS so regeneration is quicker.)
