### ISSUE TITLE
Export to ED Engineer misses bulkhead and life support blueprints

### ISSUE THREAD

**Issue by alterNERDtive** [EDCD/coriolis#607]
No idea if other stuff that I haven’t actually been using is missing, too. Also no idea if the issue is on Coriolis’ or ED Engineer’s end.

**Comment by Sid127** [comment]
Hi, sorry it took ages to get around to this! This is being worked on, as mentioned in [this comment](https://github.com/EDCD/coriolis/issues/705#issuecomment-1272452146l) on #705

**Comment by Sid127** [comment]
@felixlinker this can be closed
