### ISSUE TITLE
orbis.zone site webserver seems down with Error 521

### ISSUE THREAD

**Issue by fruitcakegsi** [EDCD/coriolis#608]

**Comment by felixlinker** [comment]
Duplicate of https://github.com/EDCD/Orbis/issues/17

**Comment by dudeisbrendan03** [comment]
> Duplicate of [EDCD/Orbis#17](https://github.com/EDCD/Orbis/issues/17)

Do you mind responding to it, it's over a year old

**Comment by felixlinker** [comment]
Hey @dudeisbrendan03, I will take this to the duplicate issue.
