### ISSUE TITLE
Mismatch between coriolis defense summary and what the game says

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#61]
When looking at my Federal Corvette loadout (https://eddp.co/u/RHJ2YDT2), I see damage from explosive at 127.8%, damage from kinetic at 111.8% and damage from thermal at 93.2%.

However, when I'm in the game and check the new ship defense tab from the system panel, I see shield kinetic resistance of 53.7%, shield thermal resistance of 6.6% and shield explosive resistance of 61.3%.

Attaching a screenshot.
![ship defence](https://cloud.githubusercontent.com/assets/2309889/22391497/a6a68622-e4bf-11e6-9238-a69458ce78d1.jpg)

**Comment by nemesyssoft** [comment]
Same thing with the Imperial Cutter (https://eddp.co/u/k23ocVae). coriolis reports 51.0% resistance against kinetic while the game reports 49.0%, 100.5% thermal resistance against the game reported -0.5% and 42.5% explosive resistance against the game reporting 57.5%.

Attaching screenshot.
![cutter ship defence](https://cloud.githubusercontent.com/assets/2309889/22394586/947580c4-e4f2-11e6-9c6f-9681e137cc7c.jpg)

**Comment by cmdrmcdonald** [comment]
Coriolis shows the damage taken from different sources, not the resistances.  This is because it's easy to understand taking 105% damage from a given damage type compared to having -5% resistance to a given damage type.
