### ISSUE TITLE
Uncaught exception on mobile

### ISSUE THREAD

**Issue by Emereoth** [EDCD/coriolis#614]
Got the current error several time sin a row while on my phone. When reloading the page, got maybe 10/15 seconds before it crashes again.

Uncaught TypeError: Cannot read property 'disconnect' of null

Browser: Mozilla/5.0 [Linux: Android 10:RedmiNote 9 Pro] AppleWebKit/537.36 [KHTML, like Gecko] Chrome/77.0.3865.92Mobile Safari/537.36

Path: /outfit/krait_phantom?code=A2pptkFfljdystf5--1717----4j040404---00-.lw18WQ%3D%3D.Aw18WQ%3D%3D..EweloBhBmUE4AclCmBDA5gG2SEBGCQkKEoA%3D

Error: Unknown

Details: 
    scriptUrl: https://coriolis.iooutfit/krait_phantom?code=A2pptkFfljdystf5--1717----4j040404---00-.lw18WQ%3D%3D.Aw18WQ%3D%3D..EweloBhBmUE4AclCmBDA5gG2SEBGCQkKEoA%3D
    line: 1
    col: 825
    error: {}

**Comment by felixlinker** [comment]
It looks like something about your build went wrong. Does it only happen for this build?

**Comment by Emereoth** [comment]
I don't know, I didn't try it again on mobile since. And it was not a
personal build or anything like that, juste me on my phone.

**Comment by felixlinker** [comment]
So you played around with the build manually?

**Comment by Emereoth** [comment]
Oh right, you mean build as in spaceship build? I thought you were about
the app build, my bad.

Yeah I was trying out a new loadout.

**Comment by felixlinker** [comment]
Can you explain to me what you tried to do? I.e. which steps did you take? Did this ever happen again?

**Comment by felixlinker** [comment]
Closing because dormant
