### ISSUE TITLE
Setting PIPs not working as ingame

### ISSUE THREAD

**Issue by xamidi** [EDCD/coriolis#616]
I noticed that setting PIPs does not work the same on coriolis.io as it does ingame.
For example, using ᐁ ᐊ ᐃ ᐃ ᐃ results in (2, 4, 0) ingame, but in (1.5, 4, 0.5) on coriolis.

**Comment by alex-williams** [comment]
Closing as a duplicate of #655 as the pips function needs a re-write and this will be covered under that rewrite.
