### ISSUE TITLE
Broken on firefox 83

### ISSUE THREAD

**Issue by devdave** [EDCD/coriolis#618]
Using latest version of Firefox version 83.0 on Windows 10 professional

In the developer console the only error is a 404, unable to load `GET https://coriolis.io/72f0cd.css`

Looks like that 404 might be the culprit as the browser window is filled with huge/oversized images,

If I go straight to https://coriolis.io/ I get the same oversized image filled document as well.   

https://coriolis.io/import?data=H4sIAKd5xV8C_-2ZXW_bNhSG_4qhm964Ainq03dN0iwZktaNgw7YMAi0RNtcJVGlpGRekf--Q8mJKcuplMbGgG25SayQjw55Xp4P-ptxLeIqYYUx-e2b8S5NxWV2mvDcmPhovPl8IfKcSWNiIQuevc-WPGNM8mxpTL4ZJ0nFcvhQXp4ZE2z5rkccRMbb5x9oyoyJ8QujucjCj3dMRisqlyw2tiz4_62IR29uV2x0ktCiZPLN6Dr6VPEs04apVxCELBfMuGJ3LDEm9lgtgC84k80SruhcPTfOaEqXbMrkjEUiUy-7YkVxWfwkRGxMAPBRcqDS5DMFS2FxxLSCwHUBuHlCXBO7PnL9h_EutpdGTNt9Ajkm8VDgtDm8KCWfV6WQZ5Le7wBxB4iA8QREpu1jnQb7JlOaXAkaDyA5WCM5HrZ0lHK5EsCM_9W_zACZ6Inlw4eH38fGp4omvFzXcIs8jI3LkqVAXuVlmFZJySOaZSCFJU_nNAlXVb2fHzNjUsqKjY2p5EI2gLExS0QJcy9g0AWVcS5AUdhQBv-vVV2rjukR2w2cA2gVuS6y_ntaJcQ7glatWqs9OvRIgAL8rA7fLxY84iwr2yo8kUKMbqn8CsrrCg8Rpf8_4TDwFKbSBCgsUvYVOYs4LOa-ocePKukODq9EBPtTgP4nhjoNBWx047Va0M5zgp6KezZMK7jtYd-ybber4eFHA9sm2aoZ-yaxkRPg18iZ6CZiMyCe7_2woh0Tb2GWiWx7R4aBF7RlOGc0hTDDZFhWUrIyTFRE6lXhlRq1EzL_KRkeTi6wP0QPCBYI5jVy8U1_y8NKfwiQr1GLBUWDphbL8x1k_6haQHqaefDBcZzdFEsI6RFMymJepb2Kua6H_eslQwKCvENqxnN97LsH1AyBjbX9Q2nGBSdZO6KxkX8UzTTZ7nvcApaR9GJnatSOEg9N7dgaqeRXqIQPYJXpUBjBWwqnF3zLs_Xz1hYrzpJ4LoQqFV8Bto4FJscC28cCO8cCu8cCe8cC-zp4wWImackh9EZC3rGyZPBH9CXn5TNUvD0dK56fbsZqyFRdD1AZQTkh5nQdCyGfQVlPqFM1-IKW0arPOCpTUclwKWnMrF4T39Wjh-Ql6Ow81-vmpTptTBOaleFJvfU7nd01rFSMPt23U9ZjL4e2iYk8l5gus5Ita8N7S1XX0ToSbCPTarVvta2nNKfREBpxNZhtmyo5B4HOu2C0fEzI0XpA3rT1Js7drTswtrc5BHY4zJW9eb23Ss7-9-W89erWJwM96zpB17PNtPCMy3qzNJ9OpVjASoUcTcH6fT26NaDgeIFfYfc1v1oWpFv4sTq-HVQbBOBJvdqwAK-TmrV8zEsO2e0aNrz_9gC7eiuMfdUZ70VCTbQQUHhkUX97jVELSgKopYPA97pgpcMbWrIBvSHRWyW_0yk5XluBrNGAUp83NJheU541dhVD5RfYXfmdz86gW86WNzRrmumt_s5ZwtURHp1TWahHHQFiNECAe3zb3TJbd4Jjtf36Eglj3ZkYnOmAhN0fkzCUyI7e47vtOAdb9xL5Yr-lNMtDrmlDqPM7jZHbVsdqnTMZS37XKMQdqpBzCS6G7Lgoz9RkPaUpbMIhulR5LmQT95yGa_V36DBx1kwcmtJI8ExK0zqO8IIvV-eSfa02YV6_uFyx0dk9S5K9KvQHqLBp7IrBacmzNF-5_p5QuCHesOaqtZ9otuKhbdnY7QaZ4Rbavp44HdMJAiWmLnGwhbbpb5dsBnbQjtizNdQd6SEN3BBfZWAntrp7snusyWxAjkftHK-JdPcQFSyDBF28DHpDY9ohLSqWlDT7op9F0luDnMOsW5i1S6vLXkmjL3pSwf21NPxCOFT30t4hkdZ-ZNNLLFmm6uuNawYnwBpM9oPVZhaREPnLImaNdGqku4tcVtC5cJotilbzMxDq1lCnYyeEPCBBf6K7HQ9jevuZsRSZuhAqpUigYYGYGdW9i3oBedFOBPUL7M4LoNmCWB-JNK_UNtD4TlVa8SAoRjWUdKRQQZKLZMULBgbCgRtGa7TaurpoiqmoKkqR8qLp2_IKCnzWq9UmYJ6K5LFb07NwlSSS8QwKy4ipLxuGJM0t-ppDiKJyjfAuuG5UWRdtvxjdumjJoT4s_xDzcF_7mlQpz0RVhCKD5ytG4xD1H-WpQv4s5rsrUL0TK2meS0GjVVHxsn-rp80cuX63mTarp2nkO8Ejlqt4A5EHkkAv8jPkDpZ8VtN0TvN1UVsP96shNjYZ_lEOkGjUVcP-CwGj-aeqSCy8-TtWzThUrx_eouAcBkCFUj9Qt6GiUgIv1cVdSVMFVV_8vsX4LUG3FpkgNHGcX42HvwGKWwes5yAAAA%3D%3D

Screen looks like 
![image](https://user-images.githubusercontent.com/281946/100676958-2e645300-3327-11eb-8c7a-76ef8c8a7c61.png)

**Comment by devdave** [comment]
Seems to be working today (Dec 1st 2020)

**Comment by felixlinker** [comment]
Hey dave, thanks for reporting! If this happens again, pressing `Ctrl+Shift+R` should fix it :)
