### ISSUE TITLE
Pacifiers miss falloff

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#622]
Here are the correct stats: 
![image](https://user-images.githubusercontent.com/9728715/101941178-e88d7180-3be7-11eb-9cd3-b78853d20248.png)

**Comment by felixlinker** [comment]
Falloff has been adjusted, however, the falloff was set to begin with.  This must be a bug in the code.

**Comment by alex-williams** [comment]
The code to generate the slot value of 'falloff' requires the 'range' value to be set. Adding the range value to the Pacifier data in coriolis-data, causes both range and falloff values, to be displayed.
