### ISSUE TITLE
Thermal Spread on Thrusters should be 10% heat reduction (currently 4%)

### ISSUE THREAD

**Issue by tabasc** [EDCD/coriolis#624]
4A Thrusters with Clean Grade 5 showing 4% heat reduction for Thermal Spread instead of 10%.

Sorry if this is duplicate, I searched but could not find issue listed.

Thank you for this indispensable tool.

**Comment by felixlinker** [comment]
Thanks for the report. This is not a duplicate issue.

**Comment by felixlinker** [comment]
@tabasc Could you maybe give me the overall thermal load for your thrusters?

**Comment by alex-williams** [comment]
Resolved, thermal load needed to be 'additive', not 'multiplicative', it now shows correctly in the tooltips.
