### ISSUE TITLE
Reservoir Fuel Tanks Not Always Accurate

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#625]
- Reservoir fuel tanks were added by https://github.com/EDCD/coriolis-data/pull/79/files
- They are sometimes off, e.g. Adder (compare with the attached list)

[ReservoirTank.txt](https://github.com/EDCD/coriolis/files/5726854/ReservoirTank.txt)

**Comment by jeneg** [comment]
Hey, I've updated data with provided list, please check if it solves issue.
