### ISSUE TITLE
Add tooltip for lesser known properties

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#629]
I decided to only show true modifiers in the blueprint tooltip. Some players might be confused by this. Tooltips could help with this, but at the same time, the properties are already shown in a tooltip.

**Comment by alex-williams** [comment]
I don't see any reason for this, so closing the issue. I have a redesign in mind for certain tooltips and 'pop-outs' to change the UI a little, but this is far down the line, after a react upgrade and other bugs and issues are resolved.
