### ISSUE TITLE
Import missing engineering information

### ISSUE THREAD

**Issue by lwt-pressy** [EDCD/coriolis#631]
When exporting data from Inara to Coriolis no engineering is shown on coriolis. Speaking to Artie from Inara, he says the problem is on coriolis side.

Here an example of an ship export:
`[{"header":{"appName":"Inara","appVersion":"1.0","appURL":"https:\/\/inara.cz\/cmdr-fleet\/292951\/2510292\/","appCustomProperties":{"inaraCommanderID":292951,"inaraShipID":2510292}},"data":{"Ship":"krait_light","ShipID":4,"ShipName":"New Frontier","ShipIdent":"LWT303","HullValue":30438198,"ModulesValue":22590193,"Rebuy":2651421,"Modules":[{"Slot":"tinyhardpoint1","Item":"hpt_plasmapointdefence_turret_tiny","On":false,"Priority":2},{"Slot":"tinyhardpoint2","Item":"hpt_plasmapointdefence_turret_tiny","On":false,"Priority":2},{"Slot":"tinyhardpoint3","Item":"hpt_heatsinklauncher_turret_tiny","On":true,"Priority":1},{"Slot":"tinyhardpoint4","Item":"hpt_cloudscanner_size0_class2","On":true,"Priority":2},{"Slot":"slot01_size6","Item":"int_cargorack_size6_class1","On":true,"Priority":1},{"Slot":"slot02_size5","Item":"int_fuelscoop_size5_class5","On":true,"Priority":2},{"Slot":"slot03_size5","Item":"int_cargorack_size5_class1","On":true,"Priority":1},{"Slot":"slot04_size5","Item":"int_guardianfsdbooster_size5","On":true,"Priority":2},{"Slot":"slot05_size3","Item":"int_shieldgenerator_size3_class3_fast","On":true,"Engineering":{"BlueprintName":"shieldgenerator_optimised","Level":3,"Quality":1,"ExperimentalEffect":"special_shield_health"}},{"Slot":"slot06_size3","Item":"int_cargorack_size3_class1","On":true,"Priority":1},{"Slot":"slot07_size3","Item":"int_dronecontrol_collection_size3_class4","On":true,"Priority":2},{"Slot":"slot08_size2","Item":"int_buggybay_size2_class2","On":true,"Priority":3},{"Slot":"slot09_size1","Item":"int_detailedsurfacescanner_tiny","On":true,"Engineering":{"BlueprintName":"sensor_expanded","Level":5,"Quality":1}},{"Slot":"powerplant","Item":"int_powerplant_size3_class5","On":true,"Priority":1,"Engineering":{"BlueprintName":"powerplant_armoured","Level":5,"Quality":1,"ExperimentalEffect":"special_powerplant_highcharge"}},{"Slot":"mainengines","Item":"int_engine_size4_class5","On":true,"Engineering":{"BlueprintName":"engine_tuned","Level":2,"Quality":1,"ExperimentalEffect":"special_engine_overloaded"}},{"Slot":"frameshiftdrive","Item":"int_hyperdrive_size5_class5","On":true,"Engineering":{"BlueprintName":"fsd_longrange","Level":4,"Quality":0.817}},{"Slot":"lifesupport","Item":"int_lifesupport_size4_class2","On":true,"Priority":1},{"Slot":"powerdistributor","Item":"int_powerdistributor_size4_class5","On":true,"Engineering":{"BlueprintName":"powerdistributor_highfrequency","Level":3,"Quality":1,"ExperimentalEffect":"special_powerdistributor_capacity"}},{"Slot":"radar","Item":"int_sensors_size6_class2","On":true,"Engineering":{"BlueprintName":"sensor_lightweight","Level":3,"Quality":1}},{"Slot":"fueltank","Item":"int_fueltank_size5_class3","On":true,"Priority":1},{"Slot":"armour","Item":"krait_light_armour_grade1","On":true,"Priority":1,"Engineering":{"BlueprintName":"armour_heavyduty","Level":1,"Quality":1}}]}}]`

**Comment by felixlinker** [comment]
Can you also provide me with the link inara generates for you?

**Comment by lwt-pressy** [comment]
Here ist the link: https://coriolis.io/import?data=H4sIAAAAAAAAA9WX227bOBCGX2Wha29sSZYT%2B7IHoAHSbre7272oC4OWRhZRimSHlFO3yLvvkFRqyYfGMVpsGwSQPRp%2B%2Bv8hOaLffYkqYAVgNPsSMa1fsRqiWXQtGbJo4CJvAQ1XkoLxxSiE%2FnlzQ18ra7WZzYfzIXfZF%2Fnn%2BTCvC%2Fy9FAB2PkymyTSL6TqJp6NJOh%2BGwU8bY1X9GpUGtByMe7AHPFV1zSRJuX4WzcLgQbjzV8W1DwbS3d0gKphlbqS7RVrsRsMn4t9nXoaPrZtXcPvbM3Yr7xMKkJbCN%2F%2F%2BnY4yCr5ohHjLREO58dVklKZZNoheqqIRYNr41eQyndLfIHoDy2YTzbJkchlfpl%2Fzotk7UiOUAwuGK6gYFlpxaWN6wrWF2pVM20XdCMtzJqWSixWvl0wsfD5l%2FUFVttjAIHouV1wCIJcr5%2FIJadD0xbaGboFpGq7WgHnlBhc0%2BgbWIKLZeBD92TDBLYkcXVxlCdE%2BUa15Ta6ZeF6WkDuRRkPO6eGssWohlF8DVNkjJpL%2F08Q0nZ5pooaCN%2FWxqVgCqwUzgPceQvoZJoSSK2TSF6C1EHcsxA%2FItxVgTde1W5hd%2FYai4mT5PvunVZ%2F80urTX0y95XJzbOGYioMolkoZSwYM%2FwyjRU5uTNYxcIyVfEfWTlGpDZSlYI3MydXCZZ7AGPcZ9DazhssPW0yDCPYbNEOXUeylT7YsIrfeViABmVXB3SS4SxclM%2FYx870LQ%2BCyVJh32176iJkPPMK0SL6G%2FvJ1thKvOTtkKwchlkx%2BCBn7c3aioS0m6OKma6i3lPfUpf7Z4766sgFhcqV0uPnNxeQpY5%2BY9Cm1fyt%2FrbGrYUgLvKRn9DVyha3GHXj2I%2BETPyo%2BDR6fDq85VZzhZrSDruicsw8enwFOfhQ4%2Fc5grW4BtWDS9sHbeHdXZ6dIZbQp%2FM4wfWQIHsc9sJ3a4QVHu9luoOQRHaEluAOVPwoVvX5QIj2H9mxpC3S9ol9nOj%2Bjj5%2FdDkpTHHqZZY8w4BDUv9eb%2FkGUl2AarRXuzGHnRld1crhX%2BBkvuLHIl3RaxAProXP37GncA1V8VZUIHxuQ%2Bea8uuwxc6ZZ7oZ264SsYDuuDEij0BzbNN3VQV3XUhvf78X2%2Fh3RAtIT9gjDWjUdLf7n2SJE6Y3FchtW4EHOgyVuOX6lFE13t8T9nw3Z3d17%2Bv8P7EduN%2BQOAAA%3D

**Comment by felixlinker** [comment]
Thanks!

And another [link](https://coriolis.io/import?data=H4sIAAAAAAAAA82Y227bOBCGX2Whaze2DpYPl22zqIF2t9tie1MvBIYcWUQoUstD0rTou3d0iCM5luU6RhvAsOIh%2BWs%2B8ueIyudvXgaEgfaW3zxSFH%2BRHLylt5JEE29URj6BNlxJDPoXkzr074e3%2BDOztjDL9Xg95mXvC%2Fp1PaY50y9SAWDXY38Sx8FkPQ6ihR9G8XpcD37ljFX5e60K0JaDKW9cCbxSeU4kprJ67S3rwaO65WPGizLYKH3%2FPvIYsaQcWTZhLiloBoJICniT%2B%2B7hpP67YXpXdbAZ%2FLFare67MZAW2z6%2BeTFZ%2FInBN06IT0Q4HBCF0XQ29Wcj751iToC5j%2FtxvJiH%2Fsj7AFfuDgPBNA5nwbaft%2FyMiQlVCmduAxnRrFBcWh9vsLKQl%2FHCJoUgJieEUhCgiVU6SfkXYEk5Bnv%2BjXNutYORdyk3XAJoLjcl80tMo8AftgG7BVIomUCacspLnpH3Fm5AeMvpyPvHEcEtZon5Xn7BOec5diHiMk2BlhmaAignIsGJ0TleqZLMcevhLG8pcmDc5X0cmnCxcbLJvu7byf%2B95kpvkzgKRii50URWE7EHZnIx9xcDQCkAuyL0OqHEULQ4kikB7BBYcNwC7UE8yxIhVTw9kF74u9Mrt8OB%2FKJn4IvZZDbgC%2BOwMSlAgq1nbY8vLJd3fXY3GQfBrpQyFnUM%2FwqThOJSmGkPXDAI15XEgnxzxxwOPWkjd8Vo5uT1XT9c8LzgJheLaHZewvDZEU796KyE0S8m1GC4sfymZxOed%2FmmJ8H9FE%2F16OP0V9DEXRr0ijVcXgviJM3KVJzWYJNyzMmlMueGbpUpKQjlbTP6bbh2ogYvE7%2Ba09ako27DuMGSWVfMqsthTw2nuSuqgctUaYqluGfjxPMwPGo1Wg59BBhV2QddwAyPfdv7l9J1pxoxOBnxsexgcZgFi2CA8bHqHtdVrNMKwz%2BG1f8NrAs%2FOh9rvI81NQwv%2BHLA6b1vB0Cjlm6hbkHjKas6ELVUH%2BKVYvzUndDSIzpXTvdtgc52zQlqVsKmm14d7N%2BkA9k0wxnXB1w6n8cDK9fIqBvQQuHxu3vASjXeDDdrapmuHyRth96hbhWvIKKnPr3QBcMHx0U4dHAsZVIHYltS20CCp4Any0LpHbO0Gto0wc8sSVXRBd9k9hbK7weGsM8dlacYFkHNrxx6f4%2BDW639Pj7Gum2hDPNLNfzvQNITD7CPNFNiuu%2BjmjCyQ2RAGqXNyVNcj98%2FyTvvaFEYdqyMlrBEXu9UniZaJRTWCYV9FaKlVheAB62H%2F2w0tSFBG7Oqzp1WbBqVJ75kNCrbYvwffn4AahS0IUwSAAA%3D)

**Comment by L1S9D7M3T** [comment]
> When exporting data from Inara to Coriolis no engineering is shown on coriolis. Speaking to Artie from Inara, he says the problem is on coriolis side.

i do not believe that this is true and the reason is because if i export my build to Coriolis from the EDSM site - all my engineering shows up correctly. if i export my build from Inara - it does not. so that tells me that the problem is on the Inara side of things.

**Comment by felixlinker** [comment]
> i do not believe that this is true and the reason is because if i export my build to Coriolis from the EDSM site - all my engineering shows up correctly. if i export my build from Inara - it does not. so that tells me that the problem is on the Inara side of things.

I can confirm that the problem is on coriolis's side. There might be problems with other apps, but we get the engineering data correctly.

**Comment by mikeshome1** [comment]
**Hi I'm new here, a question, what happened to my fleet, I use to be able to click on the MY FLEET tab and see all my ships, and I am signed in, now when I do that it's empty what happened, I have 7 ships.**
![d9adb0bbc207a0c9425be9636d94cb62](https://user-images.githubusercontent.com/82956799/115574073-4ebd8b80-a28f-11eb-8a1d-183e39286332.png)
.

**Comment by felixlinker** [comment]
Hey @mikeshome1, I'm sorry to see that you're having issues, but this repository is about coriolis. Your problem seems to be on inara's side. Best to get in contact with the developers on this Discord server: https://discord.gg/0uwCh6R62aPRjk9w

**Comment by javicv** [comment]
Links generated by Inara and EDSM are different, more data is sent by EDSM. Inara and EDSM show the right information and engineering, but when exported to Coriolis, EDSM works fine but Inara doesn't.

Here you can find links for the same ship
[Inara](https://coriolis.io/import?data=H4sIAAAAAAAAA52WWW%2FbOBDHv4ue3cSSLF%2BPmwZoFtndHmhfmoVBkyOJMEUSPNK4Rb57h5LTULJcNwEMHzPkj%2F85OPLXH0kNhIFJ1j8SovW%2FpIFkndxIYkgyCZYvYCxXEo3pxbQzff54iz9r57Rd313eXfKw%2BoJ%2Bv7ukDTNvSgHg7i7zWV5MU%2FxMZ9lyiV%2B6zVfeOtW8N0qDcRxsOLgFXKmmIRKl3LxN1t3mSef5VHPdGjvS4%2BMkYcSRsDO4UAvjpFGSbQndPQg852nHovt6iOqW33NZ4fESntYwkA49f1%2B9eXudovGdF%2BILER6Xp%2FO0mM9Wk%2BQfxbwAezCvlqtpnqH5I2z9PlkXiyKfTn%2BtStZfUZVQgeq43NfEMK24dIF%2B46AJmdNuQ4XyzFIiJZiN5d9hiiZibYHL%2FsNsO%2BNhklzLiksAg7JDtH%2BhAo0%2F3CEgC9IqsxFKVobIKkR1C%2FcgUNUk%2BeCJ4A4VTi%2Fm80XI2riwWV8YtoOzXO4E8ZLWKM55Y8Btwp5IW0Sz%2BDFN2yAiFpI3pQdhqVK6cx5HOKRkYxRKTKUMljampL08vTdcmTbYdIjM213575D5C5GzMaStOQhWAdaTOGVicPaimg44SjvecAvsubh5r7irYr54HEos2vOzvsStr6r9luw737G2IWQ%2BBumnLnth6hbtrrSPZOAIF8CsNyWh8HQrBh33p7cBHnQYI%2BzUZViu0qN0LUdlKbrDo6hqtHeoh7B7ImkLHos1i6BafQOjBcHh0kM%2B2%2BP%2BKE5l72zIEW%2BrlHVx1FkUdS%2FihiCy5dq%2Bus4Y37IT3VEaPB4btXTM8HvoU%2Bo9TvbW3pKKV8y10rJzQy3k5gEP4g1OcCKuyxJoW04NlBOxCYgwfijRhIYdcQYEL8F6rZUZ1CdynLrAwyozbp3hW493daTWkffVE%2BEIpA8d8lzEE4MhO5OkI%2FJotgxhZBBbd9Xs64fc4cHFq9p9g%2FB%2BosqxjlBOR%2BTu%2BBkTrHGz5X8wjohplI%2FC6v2F2HTeDXYgg5PD7WyYB0o0OEYn0qrIzxTqAKK1l7tQnP%2Fx9RMI9E0SuwkAAA%3D%3D)
[EDSM](https://coriolis.io/import?data=H4sIAAAAAAAAA6VYXXOjNhT9Lzx7GRDffmub7DZt0k3jnfahk%2FHIIBtNADGSSOLN5L%2F3CsgaI4G9iR8SW4jDlc65517xYpFHUklraV0znLFGWgtrldMaBjKKS1ZlG5w%2BPBcwfMOypiDCWv73Yl1JUsKUvJbrtGBNJlJcVYSvBf1OHBjCQgQKqWAKWtJqn2Oe1YxW0oXxr5W1lLwhC%2BuWU8ap3FtLZ2FdVjtaEcJptbOWL9avRUNq%2BCGvLqyli%2BLId5wkXBzG%2F8IlAXhBKsH4umDVjuNqR%2BAB17CqwloGC%2BvvBhcdvh2Gkdsug24p4d1CrvFGTbRu2RPhFxw%2Fwc3%2FYHiAtfTtGCLlFGLCRT%2Fm2UiBC3ElvjCWQViviwPIqtuFuz6I%2Fp7Yjx0bQvcSV8ODYecY0BkC3uDnX6pdMQBzHTvQUNxgjHH%2FqmAGLOUES0GrhwI3VZoDU7LhnMi1omaCKH%2BKqAH0kUbWmJes4WtgISPuAbUbnkBzT9IeRl7o%2BTrt%2FdNw9oirlGRTrCeBN0X6BdkSuPXt4u8EFzK%2FaQpJ6wJ%2BDym0Q10MUWIn6oNmGPwTViZpekcEFVLFeQD9FNhOCPzrfH5Cju2ojz%2BD%2FA1YLM3ILrJ9HwLTQ54T2%2BVzXTBBH4kxWITsIIKQkB6t1%2B9DqKlwoUCB2BIsBheX2y1JlSBETVKKf%2BglzZvqYW8NJQssr2uVknWB4auyFU%2BzlcOEj2grCg2WMnj2hjEhh%2FJCA3lN%2BslVJcmujeLHFoaerqA5PlpL%2Bg3XOD2CcX0bxUCEbibunBBB3BIIoCkFyQ%2FgwJp8XSa2P7a5%2BzE9pN3Zlhq%2FowYdqCkxXGsniDNcRMHlexBKxkF%2BLWSgsb3lQI3I6Va2s95dRZSdJAY72YrsVAmZZPsGQj1sKQq1DUXOTNkwaMU15Jk7BtHVclzAHDtCvu4uUAhngvm8uvhaS1ri4nhRbogiU%2BlxghMF7HNDilvC%2F2jK%2BoAWGKD0InbCPhRjW0BP33JkLNGCbolo6prxIwsZ6HQw40ydts6QgT9yumkk4xPA42kfkWvkowmHGsZR96CHtOsV7I3KIZpS8b8E16wSBsuJ7DCB%2FiXR6Y9nyO%2Fx7kgKPcWwI3KhXoSmLLHdufrULUwPD7m2kwQ%2BMqhzroD2eKbwUOTGBluci261hypRmjbPs6MgMaTzXGw9mh6bY8eJq9d1LbJTuaPJZzKJuu5aTOgcWj38fnFDRw%2F6nu7o6S6XT0T9nezuIEHOc2XVg%2BuUzrXzBl9GRuOa1UW7lG%2BKRanOB6N%2BXrVV%2BilDs1St%2BirfgxbtYVgsvUGx7C9PNUZjU4NOh0hc15zhNBcNlWTYV795WjeL748mnvkIFZFIGauHHcOgvAv457jdxTOtOIVNZRyOHkNIdwSJZiHHUR5DemZIr7t4JiS0LKTIdgQOhni6XrTA%2FizwWbUiRpEhnUYhMFXgqRg2teMicW5WubaHAt2PfjKtPGSj9gihp8JcgTH0PFAKnCRCBods%2B9zpo3u7RV9IZW5%2Bgtj2VHyGmhBqfYsJdiU5FGaZHzCTCMzLMx2oktPpv2l2u%2F0G71vBILOagu7iu5IJmZUfzkKOlZ%2BBWdCCZKLhW5ySt3dEx68cWtyoxf3QmyFXufBEHSHPNa6y6VcEcfIz74WcU6fqI2FdrFbrWyzT%2FA5ntBmeEhI7inXy9SZfIz9j6QNsRMrKupGEG5y63dR4dlPRALRUb%2FYwbyUAospY26%2F2WO1orlYwiXT%2F%2Bj%2BlIXZYRxQAAA%3D%3D)

From my point of view, Inara isn't sending all data to Coriolis in the "data" parameter.

**Comment by dartharnold** [comment]
The big difference I see on a SLEF from INARA and EDSY is capitalization and that EDSY sends more data.  I don't believe the extra data is the issue.  EDSY  export on Left and INARA export on Right

![2021-07-23_09h43_39](https://user-images.githubusercontent.com/10802089/126799101-9d23fb5f-fee8-43f2-a3c9-531654a78499.png)

**Comment by alexeygorb** [comment]
@felixlinker thanks a lot for the quick merge and deploy... 
I noticed there are some inconsistencies, even though the added logic is better than not having the engineered modules exported from Inara at all :)

I'm looking for the cause of the issue rn and I will come up with a new PR once I find a solution.

**Comment by felixlinker** [comment]
Thanks @alexeygorb for handling this!
