### ISSUE TITLE
Cannot find 'Planetary Approach Suite' in build options

### ISSUE THREAD

**Issue by psdevil** [EDCD/coriolis#635]
Maybe I'm doing something wrong, but I've been unable to find this option in any drop down.

**Comment by felixlinker** [comment]
This is intended behaviour. The approach suite can only be installed on a single slot, and that slot only fits the approach suite. It doesn't consume power, and it has no mass.

Therefore, we decided not to include it as it would be nothing more than a dead slot that shows you the suite.
