### ISSUE TITLE
s.orbis.zone is down

### ISSUE THREAD

**Issue by AlexandrosG** [EDCD/coriolis#636]
Again...

**Comment by BCLV4** [comment]
Any idea on fixing delay / date ?

**Comment by felixlinker** [comment]
Thanks for letting me know!

We're currently transitioning the project such that I become the core maintainer of coriolis. I am currently figuring out new hosting setup under my control.

I hope, I get it done this week, but I don't want to make any promises.

**Comment by felixlinker** [comment]
Should be back up again

**Comment by mwebber92** [comment]
@felixlinker im still having issues with it. some links return forbidden message (https://s.orbis.zone/c6m3) and i still cant export my builds in shortlink 
![image](https://user-images.githubusercontent.com/6996948/105693010-df423500-5f07-11eb-957b-93db17212529.png)

**Comment by felixlinker** [comment]
Do you know when this link was generated? There is a small gap of links we were not able to export.

The other part of not being able to generate links is known and I'm fiddling around with things. It's expressed in #638

**Comment by mwebber92** [comment]
i think a year ago was that link, but i noticed that reddit and site links are returning to normal, thanks

**Comment by felixlinker** [comment]
No worries. I inspected the database manually and didn't find a reference for the short link you provided. I can't tell you where it is, but it's gone, sorry.

**Comment by DeepstarOne** [comment]
Hi,
all ship build links e.g. on this site are not working anymore.
Error message: "403 Forbidden"
Best regards

**Comment by DeepstarOne** [comment]
https://www.youtube.com/watch?v=fRHncYWjGuE
