### ISSUE TITLE
short links blocked by browser's anti-cross-site-scripting CORS

### ISSUE THREAD

**Issue by moginheden** [EDCD/coriolis#638]
When I try to get a short link for my build I'm getting "Error - Bad Request"  When I bring up the developer tools on my Chrome browser I get the following error log:

Access to XMLHttpRequest at 'https://s.orbis.zone/api.php' from origin 'https://coriolis.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Error: Request has been terminated
Possible causes: the network is offline, Origin is not allowed by Access-Control-Allow-Origin, the page is being unloaded, etc.
at y.crossDomainError (client.js:621)
    at XMLHttpRequest.t.onreadystatechange (client.js:703)
  | console.<computed> | @ | console-breadcrumbs.js:23
-- | -- | -- | --
  | (anonymous) | @ | ShortenUrl.js:93
  | y.callback | @ | client.js:611
  | y.crossDomainError | @ | client.js:628
  | t.onreadystatechange | @ | client.js:703
  | XMLHttpRequest.send (async) |   |  
  | y._end | @ | client.js:772
  | y.end | @ | client.js:676
  | (anonymous) | @ | ShortenUrl.js:91
  | t.default | @ | ShortenUrl.js:20
  | value | @ | ModalPermalink.jsx:31
  | performInitialMount | @ | ReactCompositeComponent.js:348
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | mountChildren | @ | ReactMultiChild.js:234
  | _createInitialChildren | @ | ReactDOMComponent.js:701
  | mountComponent | @ | ReactDOMComponent.js:520
  | mountComponent | @ | ReactReconciler.js:43
  | updateChildren | @ | ReactChildReconciler.js:119
  | _reconcilerUpdateChildren | @ | ReactMultiChild.js:209
  | _updateChildren | @ | ReactMultiChild.js:308
  | updateChildren | @ | ReactMultiChild.js:295
  | _updateDOMChildren | @ | ReactDOMComponent.js:944
  | updateComponent | @ | ReactDOMComponent.js:758
  | receiveComponent | @ | ReactDOMComponent.js:720
  | receiveComponent | @ | ReactReconciler.js:122
  | _updateRenderedComponent | @ | ReactCompositeComponent.js:751
  | _performComponentUpdate | @ | ReactCompositeComponent.js:721
  | updateComponent | @ | ReactCompositeComponent.js:642
  | performUpdateIfNecessary | @ | ReactCompositeComponent.js:558
  | performUpdateIfNecessary | @ | ReactReconciler.js:154
  | _ | @ | ReactUpdates.js:148
  | perform | @ | Transaction.js:141
  | perform | @ | Transaction.js:141
  | perform | @ | ReactUpdates.js:87
  | w | @ | ReactUpdates.js:170
  | closeAll | @ | Transaction.js:207
  | perform | @ | Transaction.js:154
  | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:60
  | batchedUpdates | @ | ReactUpdates.js:95
  | dispatchEvent | @ | ReactEventListener.js:145

Failed to load resource: net::ERR_FAILED   s.orbis.zone/api.php:1

**Comment by felixlinker** [comment]
Thanks for the report - it's a good pointer. No idea how to fix this, though.

**Comment by moginheden** [comment]
Well the error has changed.  It's now reporting "500 Internal Server Error" instead and the Access-Control-Allow-Origin seems to be in the response now.

**Comment by felixlinker** [comment]
Yes, I made progress ;)

**Comment by DeepstarOne** [comment]
Links like the ship builds on this site https://www.youtube.com/watch?v=fRHncYWjGuE result in a "403 Forbidden" error.

**Comment by felixlinker** [comment]
Thanks for the report. This is a very interesting case. Only the first short-link in the video's description does not work anymore. I find a database entry without the underscore that points towards [this build](https://coriolis.io/outfit/federal_corvette?code=A2putpFklndzsxf57o7o7l272a29290404040404040404B05s5s5n5nfr1K1K1K1P326j25.Iw18eAMWcQ%3D%3D.CwBj5AmachGBilzEgzBkQ%3D%3D%3D.H4sIAAAAAAAAA42TP0hbURTGT5KXNMlL8vKe%2BfOS%2BK%2FJswEHsWNA6FQqpYUsYlbByclBwUEhHbp1KqWTQwZHB0eHjB07dBEcSuYO3SpFWntOv%2FNoLnVQ7xs%2BPvh%2B991zz7mX%2BBER%2FUlDbt5D3HGSqDgsEPkDuODcJYquEkSS4GeGPIJkP%2BWIvLWfIrWRhzzJNZPvQbzol0hl%2FrdIVfPwzCHq7NZBprhpyIMpGe9UOayC%2FIpEHH46hbyD78g%2FT0QkzT2z9A0kV2CR%2FAef6LG6troldU%2FUSYa3pnhQ7hKtrF%2BJNF7NIcrywPwJpyVHi0gPWkSZ0yIqjYvI2UD5%2F6DUXZDLGwbKQkjLcVQC7Un4BWOYC29wxAJvGnIbstynf3OIG9PQNVK0gUo2kMfPDXSszdYoWN0HpANeuCwBKttAvg0U2EAzvH4LcncxUV8lepdHXnkgr%2FKL2%2FlJBjv1cRV9dfFOkTqpWZN1fm3IHUhSh5XRS%2B32MHV%2FAqlq9dEYo5SQXyruKP4Wkhj%2BEPFWr0Xif3a%2FAe%2BM8HikYU02rcmWNdnm2SlZ0PsQ6ltt6quWDi%2BbE3%2FU3lzAlhbB%2B%2BoCJSN1InTf9xek2MUhYwQAAA%3D%3D.EweloBhBmSQUwIYHMA28QgIwVyKBQA%3D%3D&bn=PvE%20Vette) which looks right. I wonder how this came to be. Especially, if you access https://s.orbis.zone/8sQ you get an anaconda?

**Comment by felixlinker** [comment]
> Links like the ship builds on this site https://www.youtube.com/watch?v=fRHncYWjGuE result in a "403 Forbidden" error.

Was able to fix this specific error.

**Comment by DeepstarOne** [comment]
Perfect! Thank you! 👍

**Comment by felixlinker** [comment]
Should be fixed now
