### ISSUE TITLE
Some shortened links are not working

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#640]
They result in a 502. Here are some that don't work:
https://s.orbis.zone/7Yc0 https://s.orbis.zone/7YbV https://s.orbis.zone/7YbT https://s.orbis.zone/7YbR https://s.orbis.zone/7YbN https://s.orbis.zone/7g75 https://s.orbis.zone/7YbH https://s.orbis.zone/7YbF https://s.orbis.zone/7YbD https://s.orbis.zone/7Ybw https://s.orbis.zone/7Ybu https://s.orbis.zone/7Ybs

**Comment by felixlinker** [comment]
This is part of the error log:
```
2021/01/27 18:04:47 [error] 279099#279099: *92 upstream sent too big header while reading response header from upstream, client: 51.154.195.178, server: s.orbis.zone, request: "GET /7Yc0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "s.orbis.zone", referrer: "https://github.com/EDCD/coriolis/issues/640"
```

**Comment by felixlinker** [comment]
This is part of the error log:
```
2021/01/27 18:04:47 [error] 279099#279099: *92 upstream sent too big header while reading response header from upstream, client: {IP_ADDRESS}, server: s.orbis.zone, request: "GET /7Yc0 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.4-fpm.sock:", host: "s.orbis.zone", referrer: "https://github.com/EDCD/coriolis/issues/640"
```

**Comment by srguglielmo** [comment]
Based on that error, I'd suggest increasing the values of Nginx's `fastcgi_buffer_size` and/or `fastcgi_buffers`. Docs at: https://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_buffer_size

Thanks!

**Comment by felixlinker** [comment]
Great! Thanks for the hint @srguglielmo ! I was fiddling with the proxy pass buffers which didn't help. Great pointer, fixed it :)
