### ISSUE TITLE
Orbis is dead for some time now, yet coriolis still has an upload icon - which suggests that coriolis may be out of date

### ISSUE THREAD

**Issue by feczo** [EDCD/coriolis#643]
Orbis is dead for some time now, yet coriolis still has an upload icon - which suggests that coriolis may be out of date.

Checking 
3.0.0 - 2021-01-27
Commits Since Last Release (2021-01-27

this is not the case .. so Im confused why Orbis.zone is still linked...

Could it be removed? Or does orbis.zone has any relation to this project?

**Comment by felixlinker** [comment]
A very valid point! Coincidentally, I removed the icon a few days ago. The commit is not yet live, but soo will be!

https://github.com/EDCD/coriolis/commit/888f807a7b418981566f79f8fc3d0eeb143b0d9a
