### ISSUE TITLE
Incorrect Jump range

### ISSUE THREAD

**Issue by nomakewan** [EDCD/coriolis#646]
Hey there. I had a build on Coriolis for a jump-focused Diamondback Explorer, but when I went back to it I found the shortlink was broken (sorry, I don't have the broken shortlink anymore) so I remade the build from scratch by logging into the game and copying everything down module by module. But the jump range numbers don't match what's displayed ingame. I remembered I still had a JSON for the build handy so I checked that too, but when I copied that in the jump range numbers still didn't match.

Here is the JSON from my build, showing the correct numbers: https://pastebin.com/A8tA7xx5

Thank you!

**Comment by alex-williams** [comment]
This is a known issue in Coriolis, where the FSD Jump Range may appear slightly off, due to rounding and/or incorrect mass per ship, skewing the calculation. It should be addressed properly, by checking the maths involved and the mass of the ship, vs what's in game.

**Comment by alex-williams** [comment]
There is a rewrite of some of the calculations required, for several features in Coriolis, not least, Heat Generation, Pips affect on yaw/thrust/speed as well as affect on shield regen and weapon drain... this will also encompass the calculation of jump ranges, so closing this as a separate issue, which will be covered by that rewrite.
