### ISSUE TITLE
Wrong integrity on shielded+double braced FSD

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#648]
![image](https://user-images.githubusercontent.com/9728715/110866646-bf9f7a00-82c5-11eb-869d-5c22bd13e8d7.png)

Is a 4A shield generator; coriolis says [it's 259](https://coriolis.io/outfit/cobra_mk_iii?code=A0peteFaledesef4--------------.Iw18cQ%3D%3D.Aw18cQ%3D%3D.H4sIAAAAAAAAA2P%2BJ83AwPCXFUj8qQQS%2FFcMGBiELrAzMIjcAQoqe3z5DwQMADJJ5vsnAAAA.EweloBhBGA2EoFMCGBzANokMK4fiIA%3D%3D).

**Comment by alex-williams** [comment]
Fixed and deployed. The modifier for the Double Braced 'Special' was set to 0.15 instead of 0.25 which is what it should have been. Coriolis now shows the appropriate Integrity of 281 for a G5 Shielded + Double Braced 4A FSD.
