### ISSUE TITLE
KeelBack (and others) missing slot#1 for "Planetary Approach Suite"

### ISSUE THREAD

**Issue by incryptx** [EDCD/coriolis#65]
Was this intentional, to leave the "Planetary Approach Suite" off the charts for all ships?

It is a "slot" which can be used in "Elite Dangerous", but only "Horizons" needs to have it assigned by default. It is not in ED, but the slot is still available. It does have a cost and value to the ship, and the value of the ship would not be properly calculated without it, as well as the insurance costs.

If it was left out intentionally, then it is not a bug. If it was overlooked, then someone should add the slot and the equipment for the slot. I guess the slot could be used for another device, other than the Planetary Approach Suite, but I cannot think of a reason to do so, unless it was to save on space and use a Fuel Scoop in it's place?

**Comment by Athanasius** [comment]
No, you can't use that slot for anything else.  You can sell the module, but then not buy another on that same ship.  You're quite right about it slightly affecting insurance rebuy and purchase values though, that at least needs double-checking.

**Comment by cmdrmcdonald** [comment]
We don't receive any information at all about the planetary approach suite in any of the APIs so it's impossible to say if one is installed or not.  I believe that the cost is minimal, and it doesn't affect anything else due to having no weight or power usage, so it's not something on the list to add.
