### ISSUE TITLE
Add Engineered FSD V1 to list of FSD for Grade 5+ slots

### ISSUE THREAD

**Issue by mdgarrison** [EDCD/coriolis#650]
For ships capable of installing a Grade-5 FSD, the newly-introduced "Engineered FSD V1" (available from Human Technology Brokers) doesn't show up as an option.  (Manually adjusting the stats on an engineered FSD doesn't reflect the new increase in jump range equivalent to the Engineered FSD V1.)

**Comment by BCLV4** [comment]
Lot of new V1 modules granted in CG, or with Tech Broker.

**Comment by devdave** [comment]
Looking at the problem.   This is a multi-step problem, the data @ https://github.com/EDCD/coriolis-data/blob/master/modules/standard/frame_shift_drive.json needs to be updated and at the same time the module/logic that reads that data will also need to be modified.   I've started trying to understand how Coriolis works but I am not sure if I can cleanly hack dual modded modules in.

**Comment by alex-williams** [comment]
Exactly as devdave said, the way coriolis works is to have all the base modules, then engineering is applied at runtime to generate the new values that the engineering has given the module. This either needs a special module to be created with metrics applied at base and the ability to change the engineering blueprint then denied in the main coriolis code (except experimentals) or it needs another module that is identical to its base module, but with new ID's, then the coriolis code needs to apply all of the applicable engineering to it at runtime, which will require the engineering code to be updated to run two separate blueprints on one module, while preventing that from happening on normal modules, which can only have one blueprint applied to them... neither option is simple.

**Comment by alex-williams** [comment]
I'm in the process of adding the pre-engineered modules to Coriolis, so this manual editing will no longer be necessary once they're added in. I'm therefore going to close this issue, so as to reduce the number of open issues, as I'm trying to get through those, before any major feature upgrades.
