### ISSUE TITLE
Engineering a point-defence doesn't give one the option to set some stats

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#651]
One cannot set the stats of a CG point defense manually:
![image](https://user-images.githubusercontent.com/9728715/111869165-46b3b880-897e-11eb-8dfa-88e7e44f704a.png)

The only options editable are integrity, mass, ammunition maximum, power draw, and reload.

**Comment by alex-williams** [comment]
I think this issue pertains to the fact that the pre-engineered modules don't currently exist in Coriolis and the particular Module achieved from a CG was something that couldn't be replicated. I'm in the process of working on adding the pre-engineered modules, so I'm going to delete this issue for now, as the need to manually edit pre-engineered modules, should no longer be necessary once they're added.
