### ISSUE TITLE
npm install fails without legacy dependency resolution switch

### ISSUE THREAD

**Issue by SamClayton** [EDCD/coriolis#653]
npm 7.6.3
node 15.12.0

`Could not resolve dependency: peer react@">= 16.0.0 < 17" from react-testutils-additions@16.0.2 node_modules/react-testutils-additions dev react-testutils-additions@"^16.0.0" from the root project`

Essentially, it appears that the primary dependency is `"react": "^15.5.4"` while react-testutils-additions@16.0.2 requires `react@">= 16.0.0 < 17"`. There are multiple other package versions specified in the package.json that will cause these. I attempted to downgrade two of them before falling back to legacy dep resolution.

In the interim, perhaps add `npm --legacy-peer-deps install` to the development page in the wiki, since that's what resolved this immediate symptom for me? I suspect the project was previously built with an older version of npm that used this deprecated package tree resolution algorithm.

**Comment by felixlinker** [comment]
This would be adressed by #654, right?

**Comment by SamClayton** [comment]
> This would be adressed by #654, right?

No, that PR still includes some old React UI-related packages for which there is no updated version. I may fork them, since it seems the only problem is that they require a React version <16 despite working with >16.
