### ISSUE TITLE
Wrong modules and engineer recipe exported to EDEngineer

### ISSUE THREAD

**Issue by eronaile** [EDCD/coriolis#656]
Trying to use 'Materials needed for this build' and then 'Send to EDEngineer' so I do not have to put everything manually on the shopping list. 

[Link to the Coriolis build I try to export](https://coriolis.io/outfit/federal_corvette?code=A0putpFklndzsxf50x0x0v2a2a292904040404040304044k5t5t1Ofm1K1K1K1K322b29C5.Iw18WAMmkA%3D%3D.Aw18ZVA%3D.H4sIAAAAAAAAA43TPUvDUBQG4NOv2Da2MbEfqYPYGrV0EN0LjoroqmtdHEVErIMOgjg7FFwc%2BgP8AY4O%2FgAHRwcncXBwECnSnuN7Ar2DINwMLwfOk9ybk5sErxHRKIMYniOyjzkir%2F0tUul7RJLkivZT2j9GeGdDkVIwEik380ThHDrzsUzxjJGnYxk8TRCV7gqQl%2BhImlfHyNv4Qv%2F2TUQy3Da3XiByemteo67ReGaRBV1k8d7FQxzeG%2FPgsEq0vDIQqfV8tLK8a540i2g1Fekm4vVryiVng%2FI2yOUdg%2FYRjg7O63zixa7fRULdmEzaoIINKtogj9cNukG4W2kM%2BxVz9LUKX%2FCtI61kylr61jKwltPWsmwtK9ayyttGHiCSIZCjp9ktJIn8E0R8wqMP5SFvGn6FSPR18tEPhq5HYin%2BDQY6%2Fpq1rHPLyJ5u9ghl8SHA6loFHfyJkVbS%2BCu7RnaN1EqE%2Frt%2BATEZ99npAwAA.EweloBhBmSQMwKYBNECcCGAbA%2BgYwHs0A3RAFzMRBAHYaoGQIg%3D%3D&bn=corvette%20beam3%20rail4
)

Several exported modules and engineer recipes are totally wrong. For example, none of the shield boosters got exported, instead I find stuff like Long Range Cannon or Lightweight Electronic Countermeasure in the shopping list which are nowhere in the build.

This is too bad because having automatic correct material list is one of THE greatest things you can expect from a build tool.

Thanks for having a look.

**Comment by eronaile** [comment]
Any feedback? Is this known already?

**Comment by BraINstinct0** [comment]
Confirmed this behavior still happens

**Comment by Sid127** [comment]
Hi, sorry it took ages to get around to this! This is being worked on, as mentioned in [this comment](https://github.com/EDCD/coriolis/issues/705#issuecomment-1272452146l) on #705

**Comment by Sid127** [comment]
@felixlinker this can be closed
