### ISSUE TITLE
Multicannon Experimental Effect Auto-Loader not showing in Modifications

### ISSUE THREAD

**Issue by ArghArgh200** [EDCD/coriolis#66]
`special_auto_loader` might be the name of this modification:

[Modifications panel in Coriolis as it appears now](
https://arghlex.net/u/WEQC9IdlDnAP.png)

[In-game information from Outfitting](https://arghlex.net/u/c8MjJivxCqIP.png)

**Comment by cmdrmcdonald** [comment]
It appears that the names is something other than what we would expect.  Please could you import this ship and immediately copy the URL (should start with /import) here?  Thank you.

**Comment by ArghArgh200** [comment]
[Link to craft with Auto Loader Multicannons](https://coriolis.edcd.io/outfit/federal_corvette?code=A2putsFklkdzsxf57n7n7l2727e0e004040404040402024k5s5s5nfm2d2dm9m92b2b6g.AwRj4yuqg%3D%3D%3D.CwRgDGJWBMfw%2BUYGY0qpkwg%3D.H4sIAAAAAAAAA12TT2gTQRTGp2myTbLZbHeTJkuspO2OORTpQfDgSSFqe1D0KGgPHgTBYj1oC4XSHqWIoAd78GirICKoYBHtVfDvQVEoetAiLfXeVmsyz%2B87bFn2kI%2Bdeb%2F53nszL8p0KaXaGYh%2FzVHKcVyl7O8ppbwRiG53KCUd5jAhfKpKA7wbtESyq4hLylQY6oT0nEAo%2FO0pFaxg7Z6ClOdA%2Bo8QlU5T2820VUC88Vck%2BGkBuoDEpQ0Ews9MlzGHIjI%2FgdAApUHJje%2BI9FeNyL7sP0EN5kxEtvBTmQqyW5NoIT20LVJl2ZJLQs9LgMa7ARlC8%2BgjnEIdko%2BR7CgzQ7tvkHTzj4h7GdX5txGozuArXAYjdtKdxtYTlnBxC%2B4HAIW8ZPcW8vhdbLCQPLPGPB%2BLOFNjnofAxUlC72l83gd0HcbhlTZu9hlwKSbJ%2ByS3yyAX0KDbYtnveBWuORaR9ZtHsWtdRWFfsA6OIKd9g1C3GYkgPZvD7g4yeb8g9cd8t3na3SPpxexOH8fu01nEl2g3yoO4U%2BVRNEX8GL7QBN6aBj5BfD0LvEmcoilSMsMRHrxGYvttGnGKprgf0Ht9iENYjpGrnN81kusk%2BeUuYWqkak5GUE8f7VY45JfwPPorykud3RTZcxfjai2CkV4zuDuun%2FAyxc0AZ15g7VE0RfbGoDuERsvsgxBFnyPUZ%2FZHkLeBIdYHMbr2S0jxFavvj5lM5WHyAM9nj6Ewj6IpToM3MmB6o%2F9h4QecgkWEam9Qs8h%2FdllEWskDAAA%3D&bn=The%20Arghlexvette)

**Comment by cmdrmcdonald** [comment]
That isn't an /import URL.  How are you importing this ship?

**Comment by ArghArgh200** [comment]
Ah, hold on, I messed up. [Here's a freshly-imported one with Auto-Loader Multicannons](https://coriolis.edcd.io/import?data=H4sIAJb2kFgC_-Vc23LbRhL9Fz4rrpnuufottuLLrrObslxJbaVSLIiEJGxIgguCjrUu__ueAUiZuBEgRDtOrfwi0ESjZ-Z09-kL9HEyi7LbdPL0I35ZR7Mkv588FZ8uJjdZHE-e3kSLTYyLbbwIX1lGyar6VSZ8N4s3cfY-rv6PfCL5E_4zmU-eerqYLNP5dhFvwpe-z5bpNisEFh-G3yrPC_dIckJ5tuWtyU0SZ8XN8eo2WcVx9voSTxeCpNh9X1hZ-eqvHyeraAmh4cPpMtpsJheT_H6NT_DF99Fii9_EE1ZKkyKjmLXhTxeVu-bxTbyaxXup07s4WuR30-V2kbcKI6uJHXtlobjqEXa7SK-jxfRuu1h0SfxOPBHKWdaOWDmC-B6Z8Yf1It0k7-OqRKpIFFAxyBLKOu_61pzfxdkymR0VSNg7yHTKeO_p02_7434X3YaTIPotoGSWrONwbDhaY9kodTHZLNL89Woef5g8VVBkr8eLeB5nUZ6kq-nzFNDK83haomb6MovmMUORFFDMsy3gss6SNCtBt3_Mm_h9gKzeX_-jlLuT8SqO3t9fbnHHxWS7WqTRKgaCxMOapGLrjWERAPwsvb5exEL249UyaUkPiyhvnF7lDwtJ0kWymf6SZHG3_m36HOpB2M_fHq64cqUqV7pyZSpXtnLlKlf-8EqK8uoynkWLgXtA-mEPitumPy2i-zh7maXb9fT7ObxAOMxoHo3YhUIgfSN68J-vxw-FO3yeLgqPGk7qRYZHXd0lN_lllpReucfNGiXJHnezUuzcrDLsxrlZzU5Yx8JJUfdipVtt93_Salij8GRxo63duMbjgrNbp3_EWetzpTXCWmGs0ySodvvNZj5N13myTDbxUd3Jk3Des5eyrkLlrqpbxKZZab2X2leWnAcXVjw8BNbpGk7239vluvgEW9HmZUMcMIWLlcYI4RouVpo2F-urLlYfuNjXq3z6Ck_J5gEl06vkv7GZPl9gNboDhqLHub64upy-SVe3b6PVbdzlWRkR0uAgoMgLLP5dtPp9EEJZi4rq-5sLxXWpOJ9mP8Cil0GRV9vb-FWUzddpssrlIF6itOvhJeYzL7H2iMX8EUdrRId5tIyKXWvCTynShrQDnpypk4rd7dEsP24HioTx2moJKKoOIbNFsp5usJ_tlkhYt7HKB-LQIaG2iip-yTttDStYheeGOewk3OEcVvFm83DdZQ_SaOsUkQLQ3aFhb9YAJZxstM3TKU59frAj_BmITQu6cC0mhLVWTEiazyb0ap1PfwQrSp5HqxV0fZF8gBsJaOoAIvVY0C_lmv_5Ps5m2Ihb4LXDjIQQ3ogGeOn84HXuUeBl53BE3gmBAEAjwcteAzreeWgjzDjwwoAIBBX8FCg-Hb2MKOSNN9IQwkD7_Q_YXWOvZsnqtl2UMMxSwpo1QgOb_1_ovgnfO9XxGjkQu1ob80i_C9IgPHJDKY0f63e1lQh6koNiehR0JaxHO8RyA8yYhuMMBKTOoKrQLRgDRMD3s3604xUeG8vOC2TN2toW-M7SLCuT0M1dvFicEcLkuiH8MlmGdLoA1ZcGsfLS2II7vElu4qvtep1m-TCmbajCYw7uP6Qy-jQqI0lJBjWFQj9GyapMCjaDFBKBIw6k_lIdMajythKOs222K0Ek60XSRc1xwpawkcaRqZvGTloFhVW7cmDVUnlnYRgnpwXCO6WN57B8EJOh-UiwJl_-BPfN7Up_3oKOkg5yEjyYWHutAqRPtWiFY2FlNBwDgcIOVaKWnTAEWOkZ_FSbpkHatoRC22pCQdWEogReAWRbApkGJhNcM8WdpMsk667SICPDCgrQx_Nkuzw5lIjBocSZR7IghDyHSAAaRGYsC7IucG_DyAa6KEgvhSciCSaGvXM9WXiFbIP4aI9ABP5FI6g_KJNnoywolP56hIdFb7QogfPFwwWcjWjBKZ0dp_aRlAdZomGpnMRh6bGUR4QaBdACkKlxlIcU2JsVxFYrSY-mLMhcgziF3JXZnu5v4fYke7IIN9byV8NviEvfGH6TRZJH2f2QargxTiszvHujR5UVLfyKY6EB3IHNm2g-bxUV8gUyoVjHjSLfuNaNVEY5Cxu2ob10unYVDGpyGnzBEhJYKxsY3ok7EPPw0U7Zjv5NgLewQjrLUrNSzdIiiRasgjhUmYCtlRaxNW_jZHWTZlhkvKqwWxrZvmkK7evksCMtqtCl80OXx0BXifJHgxo0GOyp2CXJQIXQWrBw5wEvBCKrMN4br80JRW-QFAmrZM2gTefoLcLCBTwQg7QoMxKd5htH50_I2vK_pdeDGkp80FDa3zhta5n-nFxnEfT4F7Lw9I8R3aWfFvg4WM3363WWRrO7q22SD2gpGUtwopUtL0VV5ZykkCJdqBR4x2WyybPkGlE3G5Tkkuzrb7l9kgvUHrHmgvXMPz99b0zY-bhzvMAQUlygWDby1A5pZTTusEvQEBgWaRWCQZ_Azf0mj5d1gRXvb4XXBOYoyLJqxpUDYbvMshTWK7pwBhbUn4KHhBXbJg3ybbbLVdtVvmq7dQAUput6yyZHTbch81Vye_cii_-zhbsK1lt---fdprUDFJA3MsxT7FEaID-sKiTM8P6rsn34XIfnHuuJCq-Q9wspNRGf0ovdhSzwYCFbsVc-urNqAyCEDrDXkpBSm24JVeWrbMUwk3HkjZWupW7Rxqyt0dV4IFswVT55BJpkG5qKw58-S1NYSWctnB0Ao6UKkHkbzaOB3kyrivZX8WqTZptD1enE-qFyxKYopVxhl4QsSzjDtPE9I1qS9ump8OIIdjd3SbyYn1BABCNmb8GMLXh2vSCyk9ZGfmskXTs4aastEoAOIddZ-nu8mmbxbbzqSFjBlUAZlSfhvWuXskqzZQgV3VKABwvDUBas0Kl2KfEqzm7vi6GBLklhUch1vUG-AIph2wUd3-eKyUmvVAiiSoYa8Amrq6UZiF1gk44lUcsEg24xXFcLBvWC41Xx8JdhU6J9LLDHrbcvK66LfKB0ndlxqONaUNO99dAJ1gNf1rKg5yBsz_bTDT3r4Y7pBkBS8meT5m9RKVXOnQxTimyfUmaUUszOAZcPSumhSlnAmWV1LAW8IY-zZ9H9oULyNIWkdi40mfcKmTI7GZIbBJUqCv1Y3DAm12ndKgse5x4Us9-qYq4QpQZm-mpwpu9Hzb6BrUjEKREqtfZxib4iw1LCiSJenSnRF85qkHR4sGCcZsQEdHW6gUM7KQw9gqNJfdZCFXIesA0NXxDi7MhSgB9SClBfuxQQxpnKGmsBYP-lAHysVFU_698hJK9XZyrYYW3A6ZQzYTRMjyn2VFgLwT5MUQ_Tyo-bdK_KA9PwwtqQ3vI5JuchUUjk8kIGZvLIii48AkuhTInSgWimaovAiD8FzX8vkTEIy1IUOvAQLBtLNDgRrn311_pob7LKQzFkFkjcTRTmsaaLZJm0Y4W1JvaC2XgAesQ8AZOD5_Oh7aVsc874UJlsNyDb7owBCxIsjJQNPY7KqXph7ck5AZ9uSKkmtlRbc99Wk2RTmxZ-cXX5-uDpxaEeJ1yqJ1GGxMP1_PBhHeHRXTzbKGuVKIM8Uo3FKe1-YyUrPXTqkR_XROUQ6dlIzUbw2CaqFcoqS6HaQjSyiUpKWnBJR94fn1_r6Jx-V_Q-dRh-DwOQpjFr0t0HkGFgjZwKpUp_ppb_hRrUNZV9Y44FeqZXeZYWI5pfdtxROimbkKUzQ5bk4yArwohuGNKwSPZHQnZkq1_isZqFNeG9ua5Wf6n7UVUq_g9OD75CWUmK3YiZSS2gDZgDmDsL_qrwpW8Svu-S1f1JDhe8lHtaqGIfy1ladQIv3RewOt_CRI7ASBKslrLxpkJHlkZPkKER7mMljdXDBwKl8szYJKxZNihhP3Eg5cLrHUiY4Kr1oNur_lmDRBotNJyFFH3Z276GOIjrqjCpbiUYPnDapBDcRk9d7Z3O2sh5WbMpi-IlgxDnKNbtBfYlWcTOlcS0Amc6M5zJHR3D6jiUnvSoCOgsw4sQzlky7lFHXeGuWiJOO6tw2tybxe3k9uSGQSp7GyzQhVawHSb1WOoPWwYv9uH1AT9iZFYYBDhGYMBRDkWz951vKH8FNL8rAXEalvnsrpnEGV0z7xqIMhRweKhrdh4u2UhLsjl-etQ1m3COThtB-vRXR5EPwh5AfaXxDXPrYL6hR0qiCDwOT-dhFbrj6C-mYIQJxWaHzNoXCeo4d8x_BXeszg7hUAI8H7twzhAyotDMahCFTghbT2QRF4xhkidAmMPLP2E4A4R2BLvAM40Pk1Ns7GAES1CgolcXChpnQzDOjMI0F6wpbME4ANNfAcD6_D74WKmrHwaI6w7EIbBh28jhTzjR2iASaSdVGD2UjR7z0SkSBx4DTol_7OixxABhBLkjqfAqUWNtQwg0eHPoLxqpCeR_KDOo4VJ9VVy-jTfJJqTAp-HSnB-X6nG4ZFckLyJUi-hcuBQ2vFkltQ-lr1NwyZoVwr13wb0_ggbXQzfMw5G1CtHbUPP1g8o-Ta93Z3y8GVZkfsU4loZU4e1I3Oq_Am7toNdktPSVtcB551fJ6vc30XY1uwt8eptlcT4Nok9rLlOI83Wl3DeiVFnK2f8BmAHTw9J9Vml383aTp8tkU04PPwviTx0VPvqnmyYP3_w4Cc3oMOGgwQWscAd_F0whK4Dpkqs85NOn_wGeeh6Ho0wAAA%3D%3D)

**Comment by cmdrmcdonald** [comment]
Thank you.  Please could you supply a couple of outfitting screenshots for your auto loaders, showing the modifications (i.e. after clicking on the 'Modifications' option for the module)?

**Comment by cmdrmcdonald** [comment]
Fixed in release 2.2.13
