### ISSUE TITLE
Manually edited Optimal Mass on FSD size-5 apears to be capped below FSDv1

### ISSUE THREAD

**Issue by NecroBones** [EDCD/coriolis#661]
It used to be possible to manually edit the FSD's optimal mass to reflect a v1 pre-engineered size-5 FSD with mass manager experimental (1856.4, specifically), but now it appears to be capped at 1827. Thus it can't currently reflect the actual jump range enhancement of the FSDv1 with a mass manager experimental added.

**Comment by felixlinker** [comment]
Should be fixed now!

**Comment by NecroBones** [comment]
Thanks!
