### ISSUE TITLE
Incorrect calculation of the 'Mass Manager Effect'

### ISSUE THREAD

**Issue by MoonSeeker2020** [EDCD/coriolis#662]
The value of 4% of the Mass Manager effect is applied on the base value of the optimal mass, instead it should be calculated on the value already optimized by the previous engineering.

**Comment by felixlinker** [comment]
Thanks for the report! And kudos that you found out, what the issue is 😉

This is already known, though!

Duplicate of #660

**Comment by felixlinker** [comment]
Should be fixed now!
