### ISSUE TITLE
Shield resistance tooltip not showing when mouseover

### ISSUE THREAD

**Issue by BraINstinct0** [EDCD/coriolis#664]
Environment: latest stable Chrome, Windows 10 x64
---
![image](https://user-images.githubusercontent.com/29201475/118902913-8e8c9700-b951-11eb-94ab-101f1cb1f7a4.png)
Armor
---
![image](https://user-images.githubusercontent.com/29201475/118902919-92b8b480-b951-11eb-9a50-0deedcc098db.png)
Shield
---

**Comment by felixlinker** [comment]
This is intended behavior. Feel free to make proposals if you think, a tooltip is needed!

**Comment by BraINstinct0** [comment]
Ah, that was my mistake.
