### ISSUE TITLE
Unused phrases

### ISSUE THREAD

**Issue by BraINstinct0** [EDCD/coriolis#665]
"PHRASE_BLUEPRINT_EXTREME": "Best beneficial and worst detrimental primary values for this blueprint"
"extreme": "Extreme"
These two phrases don't seem to show up.
Also, the actual option for this is the 'best'.(Used in blueprint rolls)

**Comment by alex-williams** [comment]
Closing this for now, as there will be some effort put into trimming unused phrases and translations in a later update, as the UI is developed further.

**Comment by BraINstinct0** [comment]
Noted.
