### ISSUE TITLE
Applying and resetting FSD modifications results in continually decreasing range estimates

### ISSUE THREAD

**Issue by brianpmack** [EDCD/coriolis#67]
I noticed my estimated range numbers kept going down with successive modifications to various ships.  I performed this test with an Adder.  Behavior also confirmed on a handful of other ships including Hauler, T9 and Vulture.  

1. Start with base Adder and upgrade only the FSD to 3A
2. Max Range: 21.54
3. G5 Increased Range, Best: 31.87
4. Reset Range: 21.25
5. G5 Increased Range, Best: 31.44
6. Reset Range: 20.96
7. G5 Increased Range, Best: 31.02
8. Reset Range: 20.68
9. G5 Increased Range, Best: 30.61

**Comment by cmdrmcdonald** [comment]
This should now be fixed at http://beta.coriolis.edcd.io/ and will move to production in the next release.

**Comment by cmdrmcdonald** [comment]
Fixed in release 2.2.13
