### ISSUE TITLE
Data JSON files missing from coriolis.io

### ISSUE THREAD

**Issue by Jessidhia** [EDCD/coriolis#670]
According to the documentation in https://github.com/EDCD/coriolis-data#hosted-versions, it should be possible to download a compiled version of the JSON data from https://coriolis.io/data/, but it seems that is no longer a hosted folder and instead loads the web app with a 404 error.

This causes a warning in https://github.com/eyeonus/Trade-Dangerous when updating data, and makes it more difficult for scripts to have access to good data. The EDDB dumps help, but they're missing important information like mass from many modules for example.

**Comment by felixlinker** [comment]
Sorry that this took so long but the file is deployed now! I hope the format is correct. Please reopen, should it not work.
