### ISSUE TITLE
Experimental effects materials don't show up in required materials list

### ISSUE THREAD

**Issue by WonkieNJ** [EDCD/coriolis#677]
Always end up forgetting this and being short in a few things and going back out shopping when I thought I was done. In the end I have to manually get a list for what I need on every module anyway.

**Comment by Cmdr10Th** [comment]
This.

**Comment by Sid127** [comment]
Hi, sorry it took ages to get around to this! This is being worked on, as mentioned in [this comment](https://github.com/EDCD/coriolis/issues/705#issuecomment-1272452146l) on #705

**Comment by Sid127** [comment]
@felixlinker this can be closed
