### ISSUE TITLE
All multicannon falloff is 2km not 1.8km as shown on coriolis

### ISSUE THREAD

**Issue by robertpateii** [EDCD/coriolis#678]
Pretty simple. Falloff is 2km.
![image](https://user-images.githubusercontent.com/494069/129293402-36a89562-b923-4461-a0a2-eed41b7a5f22.png)

**Comment by alex-williams** [comment]
Fall off in missiles shows in Coriolis as 1.8km correctly, suspect this can now be closed.

**Comment by felixlinker** [comment]
@alex-williams This is on multicannon falloff.

**Comment by alex-williams** [comment]
> @alex-williams This is on multicannon falloff.

indeed, sorry, head was in the last issue with missiles... also, it seems some in Coriolis have 1.8 and some have 2.0, will confirm in game and come back to this.

**Comment by alex-williams** [comment]
Fix deployed to live site
