### ISSUE TITLE
Missing module: Shield Generator 1D

### ISSUE THREAD

**Issue by Seforian** [EDCD/coriolis#679]
Not many people know that one of the engineers is selling Shield Generator class 1D

You can only buy it in: 
System: LUCHTAINE
Station: The Brig 

Same station where Mel Brandon is located. 
This has been reported since 2020 yet still hasn't been added into Coriolis. All the other outfitting 3rd party tools has it listed, some reason Coriolis is only one what is missing it.

**Comment by alex-williams** [comment]
The elusive 'Explorers Shield' which you have to travel to Coriolis to get... I remember a Squad Mate picking one up a few years ago. It needs to be added as a module to coriolis-data.

**Comment by alex-williams** [comment]
> Not many people know that one of the engineers is selling Shield Generator class 1D
> 
> You can only buy it in: System: LUCHTAINE Station: The Brig
> 
> Same station where Mel Brandon is located. This has been reported since 2020 yet still hasn't been added into Coriolis. All the other outfitting 3rd party tools has it listed, some reason Coriolis is only one what is missing it.

This has now been added via #558 Please feel free to test the implementation on the https://beta.coriolis.io site and give me any feedback on the results. It will be added to the live site in due time.
