### ISSUE TITLE
Wrong DPS reported for the Corvette

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#68]
Happening in various browsers. Basically, the overcharged grade 3 to one of my multi-cannon is reported as with 15679087.09% damage. That screws up the overall DPS reported. This is happening in Chrome for Windows, Safari for macOS and Safari on iOS. See attached picture. And yes, I'm using version 2.2.13 in all browsers.
![img_0113](https://cloud.githubusercontent.com/assets/2309889/22601253/11a139da-ea0c-11e6-9541-c70fa29d8412.jpg)
![img_0114](https://cloud.githubusercontent.com/assets/2309889/22601256/15a0ec38-ea0c-11e6-9b68-5e5a51548581.jpg)
![screen shot 2017-02-03 at 12 23 12](https://cloud.githubusercontent.com/assets/2309889/22601257/18836dae-ea0c-11e6-9e40-324937f1fa41.JPG)

Interestingly, this is not happening on the 2..2.13b beta for some reason.

**Comment by cmdrmcdonald** [comment]
Is this with a stored build?  The bug in 2.2.12 with incendiary multicannons meant that the URL was corrupt, and you'd need to re-import the build to 2.2.13

**Comment by nemesyssoft** [comment]
I imported it and then saved the bookmark which was then automatically synchronized on all my devices. I will try to re-import it to see.
