### ISSUE TITLE
Change Optimal Mass to Optimized Mass for FSD´s

### ISSUE THREAD

**Issue by Schmusoe** [EDCD/coriolis#680]
Hey I´m new to ED and confused about the mass things. After researching a bit i learned that the modules have unique "optimal mass" and that for the FSD its called "Optimized Mass" ingame. So in my opinion it would really help, when the name would be "Optimized Mass" so that you know that those are different stats to beginn with.

**Comment by alex-williams** [comment]
Optimal Mass is still Optimal Mass for the module, Optimised Mass relates to the way the FSD manipulates mass during a jump. No change required.
