### ISSUE TITLE
Error When Trying to Import from Inara to Coriolis

### ISSUE THREAD

**Issue by rbradh53** [EDCD/coriolis#681]
Tried 3 different browsers. Getting same error.

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAAA9VY227cNhD9lUIvfdnYou7atzYNkABpmiZtXuJiQYujFWGKVEnKjhP43zuUdh1JliwnaAIHMLxeXs45cyE54%2FefvAooA%2B1tP3m0aV7RGryt90JSTb2NG3kH2nAlcZCc%2BP3Q329e4tfK2sZsz07PTrlbfVJ8PDstaqaflALAnp2SLEkj%2F%2Bw08IMoC5Kz037z09ZYVb%2FWqgFtORhH3AE8VXVNJUp58Zu37Tdv%2Bpm3FW%2Fc4AHp5mbjMWqp2%2BmmUAuVtFCSOcnHxSTv%2Fz5Y9FdF9V5x9rP56RXfV7amGo6rGUiLS94%2Bf%2BJnv%2BDg81aId1S0uI8EUZ6ncRhuvN8VawWYw0SYBySLAkI23hs4b69RXZzFuZ8Htyu97XsUKJTDrto9oALWKC4tQY4XFmo33tjdvsUJTuXOuBUFlVLJXck%2FANsJFO1k%2FoH%2Bt7qFjXerKwvCML7Z3DJ0S78nRfDtKcJvQVED42295CnW1ucl11BzY7gATYuLA0W%2Fb0fZJZUFsDmygPh5jBnxTO65BNBc7l2S%2FoqTDX6xh1y8Atqg8grzsKANLbi9RrSXcAnC20Yb78%2BWCje2JTfLuoMfRbepqRBf7u5u2%2F2qMbLx%2FyfaP0Ef5MvKH%2BzwByofEFkur5c89AGkMi7XQe%2FOqeHFzq2eQw0DP%2FfJEuxEPpWWt%2FJCqitpqtYy%2FFwEjuMgC5dwJ2cUXxNruLwQtJVFhZptqzXYZdF%2BGqzGEH1c3CLfjSJZSr2R0OhHERqPhZqKg2DnShmLKg3%2FCP6uENSYeDa1oiROs1WhY1BUfHnN2qHU%2BEFSk8cm1T%2FJsjhd1Js%2BBr2LN%2BVIavaopRr88EmnY%2BBTRD4I3QPeV9SqXmp6kLozViuUMqM4jX3ih0E65Qg6gGTMcSwEei4NXJZKF1CD48flcc8XzBFlaRj5wZQm%2FD400RxND1%2BAEOdUXvQr7olt6GNJSu44Ku4ljaErrGQfqPu15kr3gf5MlUdZuv7E3mX5kgulU5%2FMqS9cyd49rAPVZFV1nua%2BPyVI5wgYZiNg44BZKXYaGsr1kGrW%2FQm%2B3VE0hc%2B6fdF8%2FtRdP3A3DtE9%2BRMm4UyQ8zmakRWFEgIKix1btzS8x5I0zkgyYSD%2BKoMGo1o0w%2FCm%2BlqW%2FrgF94U7eGi4gyyenjPSnzNyjxWs%2B4vW2GDeOovMUR7jQeJ8WIxzzGSqr33yaA9cuHTgGnUFuhFYAY61fx7vRGdzQZ0TTbAtx3Y4zFd1Dxj6R4ct3A%2BI9KFBGGcbFc%2FKElPaxbaBglMxVFooJRBm1ChR1NAJMWMD%2B8HRizQX6ij2%2FYTkyao5BzzG9eJFt2LIAUFdghaKsokhpUYefB1KyzS%2FhEmmXSNuN776YpCIuP9hrMenNNhJ4wOtqey66a%2BwyEGULYjb4ndokOAlmLZplJ6k3mBi9WVN8pSE03RmHEsLft5ixTGT1IPZ5dQ%2BXid475IwWu%2BG7yC7FrPU8G8LsvjKfLiDWVJjRy7UlNGJiQakUdoMLZt1HIlDrLDW07rHw5jsK3sF7vcDXnEXc4vly1jacXQY1HD1QsEKPh1etlTX%2BOJ8Rj7%2Bt2%2FXT%2BwwXxmswxKS%2BElOgmjVAwfctSpmJZgHlKLCPtudg3%2Fw5z%2BYbeaXcBUAAA%3D%3D
line: 0
col: 0
error: {}

**Comment by gopstr** [comment]
Same as https://github.com/EDCD/coriolis/issues/684#issuecomment-980177786
but tries to find hpt_dumbfiremissilerack_fixed_medium_advanced here

**Comment by jamesk29485** [comment]
Same with me.
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.39
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAAA9WY23LbNhCG34XXisXzQZdNMlO3aZumk9xEHQ5ELkWMQYAFQNtKxu%2Fe5UEyKYmB4rppOuOxxAX47344LBb6%2BNkqgeQgrdVni9T1r6QCa2VdcyKJtWgtH0AqKjganSu7N71%2F9wYfS61rtVov10va9r7KPq2XWZXLFwUD0OulG%2Fu2766XXuS5YWCvl%2F3LLxulRfVWihqkpqBax53AS1FVhGMo16%2BsVf%2Fyom%2F5o6R1axyUHh4WVk40ad9smzCWG0moTqsbStHJobvffx%2BY9i05cI2PP71%2FYSc%2Fo%2FHHhrEPhDXYx%2FdsP4rtaGH9IvKGgRrsTmLHfhD4KPgONs0OLU4Q23HgHnpaq48YDROtNCNyCyWReS0o1w76uNZQtUNW6xQjZduGpwW9hzytIKdNhT1%2BwxHWsoGFtffpeLEThQ%2BLGVn335H1prJVwzTNCOeCp1tabQhLu%2F7npIPQS6JwYb3mW8oBJOXbdop%2BwMYaH%2FQwD3dAalQr6bbMSE0yqneo9gZugaHGwvq9Iay1rRyUusdVQiucMcJeFwVkbcCqhoxiIJmQUih6C6kqgTHrYQTVD8DcHNQNU8CIArlppNLGQXNd3w0uBWOCbyXh3RgNVP6Iyr4Kw8BANijlpCIo8wUu97%2FlCiZcbuQ9mUtTvpubLVVSYPlGCKVBpop%2BAjvNkFIFZ5kiXIVmqKmoBEWVxqU0x5Y4ngluqpiVDb%2FZzTO63x9jHDwzo%2FfNGfEsu93lzVxGwXl0n5XQ%2F94ITTnTiKfww3a62MNHOIxmeHULHCTRoscLezwvLYjSZxnDJElC50LIR3EJlBdCZpD%2F4x3ZDhnT5SmlO0%2BZ4XmyIfxmDHl2Dj0vjqPEfOgdy%2FYRUjXm8796Hlu9FJNyjq%2Bd8nld9MGUr8Rq5zC4rXjfqUd0J4hvJRVyH82hQoqjwDbinnox7kzfDiMD9Knq3AL2%2F1%2FonnEpX44edFT%2BJej%2BpehY%2FzoXFApPQA%2F7DPg86GFH5U3Rq64%2BP4X3LoWPkd4%2BdhV9O1dxp%2BFe5sq91JUXOKeukk7DmboqVI4fIHOa7dO%2BM82IBcGy86Cc%2BFFkm%2FfJkSzc1%2B3lbzbdu9F4umtxB7JmhOtprI%2F2Ls7oXOY%2BOxoxHlJJe2E0RD1yQGQlGjkXsSmBj4QyIRjKTMp8gkF0kagpYG80HktOEGGu8j0jz6CXU%2FmFPWrKy4OIuAXJBMmPWAqJrvC8KnQu%2B%2BpznJh2qNvZx8n4LJOPV%2FPIvWhhme4qpslpJbrUNQFhtADV1LWQR6tu1DCfVw9FXxial1lFVYay21LfQft%2FtmR3vJNtkWOVL%2BmmwV11ZnOMWue3yH4nR75vJ%2Bbi7US4vdsXEv5qgGdPLFRPNA%2B%2FFYyBsfQhR5QKuBJSPV%2Fl1umdnwx3DDRZ8w0wjYXeUSYdrOOl7hlzUxJ4zjhT93nnUfnxt68hJWHxTLLhomc41%2B3AjXFfJcZRGJSN53lgKmQGocMR%2Fif%2B%2FQ30X147hRQAAA%3D%3D
line: 0
col: 0
error: {}

**Comment by shambaloid** [comment]
For some reason, Coriolis stopped working correctly for me - when I clicked the "Exproduce in Coriolis" button, the ship's equipment. Everything worked correctly before. Has this feature been removed now? I tried different browsers - the same result.
He's writing:
"Jameson, we have a problem..
Failed to import ship"
I'm playing Odyssey

**Comment by alex-williams** [comment]
Both of the import links given here as evidence, now work, seems like this was just related to missing modules? Suspect can also be closed.
