### ISSUE TITLE
Focused pulse laser does not retain falloff on reload

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#686]
[Example buid](https://coriolis.io/outfit/federal_corvette?code=A4putpFklkdzsuf57r7r1e1b1b24240404040404040404p006Cj3cv21O2d2dm9m76lm53w.Iw18ZVA%3D.MwRhAZPAmW9sinGAFnakxyp0A%3D%3D%3D.H4sIAAAAAAAAA42Tq04DYRCFp%2FRCL9tud%2Bll27SF0gUSRNMHaHAEBCEIeABegCAgmAqwKIIAi0ChcCCQPAASgeAhGgSUGeY09A8I2H%2FFyWTPt%2FNfzizxNBF9JlVG5yq5sxhR%2Ftgh8o608u9zROHDFJHEeMWQA5X01oeI%2B9olqtwmlHzSRjLFFQMdqLjhu0ippWT5yiUKQHb2q0rGuT4hx9B4pdKgrNCLvpQk902nE5UMoCykDZl3WGQBnRZ7nuIp3p3gfnGJqLs%2BFKltNNVK87bpdKpSxZ5rgDpDPaJkIvxshJ%2BL8J0IP887xk%2BrEKwExMf5AlxsMxiJSOEHGf%2BXdHnNkJeI9Tql94zEPFTBY0ZjRSVFa9KzJn1rcsaaLFmTZV79RbqYJ793%2BA3NPhcUqthAVd400B4gzLCHNcPxDNfYgx%2BDhTj8G00l6GN8m7xsPr3Adu%2B0LMw19HtUPjqFqKRlTba5AVJ%2FIXIQegCr3n%2FTvIX%2BfL4AEX5MBuIDAAA%3D.CwegjOIAwgzATCA7BApgQwOYBtUhPABwCsh05UQA&bn=Temperature%20Critical) with the issue occuring.

**Comment by felixlinker** [comment]
I am confused. Focused doesn't increase falloff. I wonder, if reporter on Discord meant: user set falloff.

**Comment by felixlinker** [comment]
I am confused. Focused doesn't increase falloff. I wonder, if reporter on Discord meant: user set falloff.

**Comment by alex-williams** [comment]
Cannot replicate an issue with reload of the page. Closing the issue as not reproducable.
