### ISSUE TITLE
Sending to ED Engineer throws exceptions

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#692]
Sending the materials of [this build](https://coriolis.io/outfit/mamba?code=A4pktfFalfdpsff30w2b2b292904040404000kp22b2927m3m1.AwRj4yvI.CwBj5AmboZgRkfBxixMIA%3D%3D%3D.H4sIAAAAAAAAA42Svy8DYRjHn1Zb%2FXnXu17rKhTtIWmiqdHEIgwiTQxWFjF0MBAdRNiMjSAGEoM%2FwGgQk3QyGA0iBoMBk0Go5%2FE8Te%2BNCMnd8M03eT7P%2B33e517ATgD4CrI0d1lidR9AYisOYKyzM89jAM6FH4B8OC5kQMhNlvANd%2Brld6LMI%2BPkx4w6aZVFdz6IrNwnUfpEB7DPuLOw0sVkB3YrsuaSrSRrI83kHVcogKMupNeeuX59T0RBHFOt2yyROBJF9wyAAXF5cYPihsRRCBdd3EwOA5Sm34iyM71cCuO8OinHUqxA%2B7qt%2FKzgFME5BR2zBBciAKHqK5E98UJUqD%2FxTFEvUOxH3NJ%2FcXEvUAKnFHQof%2Bw0xCuq8J4NcfYVpzviSPNM6jipyCPZuMSZ5bU21HerMZT0Apm47EL2Tsrd%2BEOJSymcVf1V6ZdnYcg4TutZWFhU9QMZ95Kt1t%2FDkDhTcEccpX%2BTDUU2FCmOMjiiyH0h800iTQY3xDk1Jongr%2B8bhaeVDhoDAAA%3D.IwOgrA9KkMwQDBAHAiBbAhmgRhiAVACwFMACAJQwC8B7AJ1wGMBrUgBQDc2p5fVF4QA%3D&bn=la%20mAmba%20%235) to ED Engineer raises `Uncaught Error: .field(name, val) val can not be empty`.

**Comment by Sid127** [comment]
This is being addressed with #705

**Comment by Sid127** [comment]
@felixlinker this can be closed
