### ISSUE TITLE
Railgun has charge and reload intervals, but currently used reload only.

### ISSUE THREAD

**Issue by DarthVan** [EDCD/coriolis#699]
Please, add charge interval for railguns, EDSY calculates rails correctly.

**Comment by alex-williams** [comment]
Now resolved. Rail Gun stats for RoF and DPS now match (aside from rounding differences, as Coriolis rounds to 1 decimal place, edsy rounds to 2) EDSY 
![image](https://github.com/user-attachments/assets/a18ab96f-f807-4ab9-a059-527bf9dc00e5)
![image](https://github.com/user-attachments/assets/1c4eae64-9d7d-4f0d-a2e7-f6e8a6da4353)
