### ISSUE TITLE
1C Detailed Surface Scanner power calculations

### ISSUE THREAD

**Issue by wysiwyg67** [EDCD/coriolis#70]
This module should report a power draw of 0.6MW but it doesn't show up in the calcs when I fit one in any of the option slots on the Asp Explorer. Haven't tried it on any other ships.

(Great job with the updates to the engineering stuff - keep up the excellent work!)

**Comment by cmdrmcdonald** [comment]
This is a Frontier bug, where the detailed surface scanner shows as taking power in outfitting but doesn't actually take power as shown in the relevant right-hand side panel.  Please raise this discrepancy with them.

**Comment by wysiwyg67** [comment]
Good to know. Thanks for the feedback :)

**Comment by cmdrmcdonald** [comment]
Fixed in 2.3.0
