### ISSUE TITLE
Incorrect Powerplant price list

### ISSUE THREAD

**Issue by GLWine** [EDCD/coriolis#700]
Good evening, I noticed that the prices indicated on the site are incorrect, this concerns both the price of the ships and of the individual modules.
I don't know if he is the first to see it, if not, are you thinking of correcting the price list?

**Comment by GLWine** [comment]
I have checked all the internal modules the only one that has a big price alteration (> 1000Cr) is the Power Plant. Honestly, it took me a long time to check them ... for the other modules I don't know if there are any other errors.
What caught the eye is that the Power Plant and Thrusters on Coriolis are priced exactly the same. This makes me think that the mistake is prior to that ... I think the price of the Power Plant points to that of the Thrusters
![Power plant](https://user-images.githubusercontent.com/54741923/175563532-01df4645-a544-4a2d-9b91-824fb5a0c0da.png)
![Power Plant VS Thruster](https://user-images.githubusercontent.com/54741923/175563534-967bc7be-ad59-4525-8585-3d9677f92623.png)

**Comment by GLWine** [comment]
The problem seems not to have been solved, I admit that it is not that fundamentally important. However, I want to bring up the problem again, after the time that has passed.

**Comment by alex-williams** [comment]
Power Supplies are not the only module that is incorrectly priced. I have begun an investigation into all of the modules that are incorrectly priced and adjusting those prices.

**Comment by alex-williams** [comment]
PR Submitted to rectify the module pricing issue https://github.com/EDCD/coriolis-data/pull/109

**Comment by GLWine** [comment]
@alex-williams To avoid dirtying the PR, I'm writing to you here.
What changes between a single elite and a triple elite?

I was intrigued that you mentioned In the PR

**Comment by alex-williams** [comment]
> @alex-williams To avoid dirtying the PR, I'm writing to you here. What changes between a single elite and a triple elite?
> 
> I was intrigued that you mentioned In the PR

Just that you get access to Jamesons in Shin at Single Elite, whereas with Triple Elite you get a universal 2.5% discount on modules everywhere, at Jamesons you get 10%. I was merely highlighting that this CMDR had neither status, so the only other possible discount, could be being in LYR Space, which that CMDR is not.

**Comment by alex-williams** [comment]
> > > @alex-williamsPer evitare di sporcare il PR vi scrivo qui. Cosa cambia tra un’unica élite e una tripla élite?
> > > Mi ha incuriosito il fatto che tu abbia menzionato nel PR
> > 
> > 
> > Solo che ai Jamesons di Shin hai accesso da Single Elite, mentre con Triple Elite ottieni uno sconto universale del 2,5% sui moduli ovunque, da Jamesons ottieni il 10%. Stavo semplicemente evidenziando che questo CMDR non aveva nessuno status, quindi l'unico altro sconto possibile potrebbe essere essere in LYR Space, cosa che quel CMDR non è.
> 
> So I have to correct you, I'm a single elite and the 2.5% discount is already active... so the triple elite doesn't seem to do much differently for now.

Indeed, I've just been and verified that, I had always believed you needed triple Elite for that discount, but you're correct. Either way, the prices are now set (following PR Approval) to the base prices a non Elite CMDR would see in-game.

**Comment by alex-williams** [comment]
Fix deployed to Live site, along with other updated module values.
