### ISSUE TITLE
Components ignored by 'Stations that sell this build'

### ISSUE THREAD

**Issue by PBonnema** [EDCD/coriolis#701]
Coriolis has a button that allows you to find systems that sell complete builds. However, I noticed on 2 occasions it left out 1 or 2 components from the list. Today, I saw it with the 3B Operations Multi Limpet Controller.

Example:

- Create this build:
![image](https://user-images.githubusercontent.com/3737630/188333052-c22d1bc3-6ba8-42cf-9827-25b14cbdd63b.png)
- Click on 
![image](https://user-images.githubusercontent.com/3737630/188332558-f6a9379b-c676-4086-a8ca-829ba7d005d5.png)
- Check that the list of modules doesn't contain the operations multi limpet controller:
![image](https://user-images.githubusercontent.com/3737630/188333066-1af8f9de-d0bd-40f4-a7a0-3d3418ee8a8e.png)

**Comment by Sid127** [comment]
@felixlinker this can be closed
