### ISSUE TITLE
Maintaining coriolis

### ISSUE THREAD

**Issue by Athanasius** [EDCD/coriolis#702]
OK, I brainfarted and did this on the *first* github link in the EDCD #coriolis channel title, rather than here, see https://github.com/EDCD/ed-forge/issues/36

I'd already tried pinging @felixlinker on the EDCD Discord.

EDCD Council is wondering if it would help to actively try finding an additional maintainer for this project. To aid in that it would be good to know any pertinent information about the current state of both this project and that nascent "write a library that has better code quality/API" project.

Users have been reporting a few newer items, and some bugs: e.g. [discord.com/channels/164411426939600896/164411501166198784/1000063397854990366](https://discord.com/channels/164411426939600896/164411501166198784/1000063397854990366) [discord.com/channels/164411426939600896/164411501166198784/1016084611622780989](https://discord.com/channels/164411426939600896/164411501166198784/1016084611622780989)

**Comment by felixlinker** [comment]
Hi Athanasius,

I give the high-level summary here:
- I unfortunately have very little time and motivation to work on coriolis, but would very much like to get the migration towards ed-forge done. I believe it could increase coriolis's maintainability.
- To that end, the [ed-forge](https://github.com/EDCD/coriolis/tree/ed-forge) branch contains a working version of coriolis (potentially with many bugs). The biggest and open problem is translation.
- I would appreciate if other maintainers jumped on board and would love to help them get a grib on the project.

Maybe a "project manager" type of role who does not coriolis's codebase necessarily, but knows all the stakeholders and knows what is to do where would be a good next step.

**Comment by felixlinker** [comment]
@Sid127 volunteered to help out for now. Many thanks!

**Comment by alex-williams** [comment]
Now actively maintained by myself and @Rixxan
