### ISSUE TITLE
EDOMH Integration

### ISSUE THREAD

**Issue by jixxed** [EDCD/coriolis#703]
Request for integration with the odyssey materials helper
https://github.com/jixxed/ed-odyssey-materials-helper

recently implemented in EDSY: https://github.com/taleden/EDSY/commit/2dd2981873f9859a6d8c0ed04b515517e34c554e

works by creating a url that contains compressed json base64 encoded in the format:
edomh://coriolis/?<compressed json base64 encoded>

json follows the format:
{
    "version":1,
    "name":"ship build name",
    "items": [
        {
            "item": "Hpt_BeamLaser_Fixed_Small",
            "blueprint": "Weapon_Efficient",
            "grade": 5,
            "highestGradePercentage":0.8
        },
        {
            "item": "Hpt_BeamLaser_Fixed_Small",
            "blueprint": "special_weapon_damage"
        }
    ]
}

experimental effect do not require the grade and highestGradePercentage fields.
only blueprints and experimental effects need to included in the json, no modules. 

the url can then be embedded  on the site and contains all the information to construct a wishlist in the app.

**Comment by Sid127** [comment]
hi! I looked at the schema you have, and was wondering if it'll be compatible with SLEF

**Comment by jixxed** [comment]
Not sure what SLEF is, but the json is limited to blueprints only. Adding more data can result in urls that exceed the 2KB limit. I can make customizations to the format. To include rolls per grade for example, as long as they are limited to integers. Or to leave out highestGradePercentage if it is unused in coriolis.

**Comment by jixxed** [comment]
Currently there are discrepancies in the data that is sent over. 1 example is LifeSupport_LightWeight which should be Misc_LightWeight
![image](https://user-images.githubusercontent.com/14129491/215457207-90bec1a0-edac-41a2-8042-77f11014c4c0.png)

there may be other discrepancies. 
Also the armor is not properly sent over and is missing mandatory fields:
![image](https://user-images.githubusercontent.com/14129491/215457607-6309f657-43fb-4551-b13c-f86553cb6606.png)

**Comment by jixxed** [comment]
tested on beta:
button stays disabled, can't export.
![image](https://user-images.githubusercontent.com/14129491/222271741-0beb131f-4edb-4c08-b3d6-580061f43ea8.png)

**Comment by shanel262** [comment]
Trying to do this myself and the "Send to EDOMH" button is available if EDEngineer API is running but the request fails. Maybe this isn't yet implemented in EDOMH?

**Comment by jixxed** [comment]
Support for it has been disabled in EDOMH since issues mentioned were never fixed.

**Comment by alex-williams** [comment]
> Support for it has been disabled in EDOMH since issues mentioned were never fixed.



> Support for it has been disabled in EDOMH since issues mentioned were never fixed.

Quite happy to pick this up if you wish to continue the integration?

**Comment by alex-williams** [comment]
Now in testing with @jixxed to confirm duplicate blueprints are resolved, misnamed blueprints are resolved and mat miscalculation is resolved. There is still an issue with the fact that Coriolis cannot currently export to EDOMH with an accurate percentage for the grade of the blueprint, as that data doesn't seem to be gathered properly (or is not easily identifiable) in the process of building the 'ship' data ready for the export... I will address this separately, as most people will simply build to 100% of a grade when 'planning' a build.

**Comment by alex-williams** [comment]
Fixes and improvements deployed to live site
