### ISSUE TITLE
Getting 'Uncaught Error: .field(name, val) val can not be empty' issue when trying to export build to EDEngineer

### ISSUE THREAD

**Issue by Upecle** [EDCD/coriolis#705]
![image](https://user-images.githubusercontent.com/74144208/193396216-5493ac17-2b6a-48bb-a60b-ee3d7057dcd7.png)
trying to export this build https://s.orbis.zone/kh-o
trought trial and error i found out that Plasma Accelerator(PA) modification 'Plasma slug' somehow causes that everywhere 
even with a stock Corvette(https://s.orbis.zone/kh-p) changing only PA to 'Plasma slug' modification
![image](https://user-images.githubusercontent.com/74144208/193396478-47238f72-7e9b-4da3-8a6b-3f4dc08f74b6.png)

**Comment by Sid127** [comment]
This will be investigated, thank you for the report!

**Comment by Sid127** [comment]
Update: the json file in coriolis-data is more lacking than I thought, and this will take a little longer to fix, but it _will_ happen. I'm gonna have to rewrite more than 3/4ths of the file, and while doing so, I'll also be making provisions for getting the materials required for experimental effects.

**Comment by Sid127** [comment]
@felixlinker this can be closed
