### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'components')

### ISSUE THREAD

**Issue by actiiiscene1** [EDCD/coriolis#713]
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Path: /outfit/anaconda?code=A20GtpFkln3Gsxf52c0o0o0o1g1g2e2e04040j0202000301B05n2Lfm1O371K2Cm76l2b0d3w.Iw18ZXEA.Aw4FlSu6GYaA.H4sIAAAAAAAAA42Sq08DQRDGp%2FT6OPq43vXaLqUtj5Y0GAIJEoEjJAgMCYakDgsJghAkAhAIBApRgUAgkMgKJII%2FgBA0QaAIgXaGmUtuU5Jt2hNfNvP9bnZ2ZgDjANCLsXQvWVLLSYBMGoncZALAO3knarywTWNY1OQBi9P4IfJrv0SFtgOg7i2A%2Bl6JySiWNXkUkt5DCsA%2FLjAZpLNwKYScww%2F2n16JKI6t%2F9HOG9HCyhdbSdzVWS9YYtuTAPG7DN8aJLT7%2FJrBHx%2Fip4b46T7%2F3OBnhvhZ3NI%2BdxYg1wSwRDzpmnrmYFV1%2BaXOyGQO1zR5LdO74Wk6mzwTV07q0QZoyInckUkPbcNg8jgn0YiUc5rnSqScipzIH2wVjLmKxmjJGFW4oeveF0t2wRPfv%2B3x6klrVeuTyQlcF9IS8owlIk9KtBlvSsOmA6iKtRByOjv86%2BoUlzmDlTCaluKVLHQ52LpZnNf3X7FkF7%2F5fslKdYwachEM%2Fv4Ao0C32G0DAAA%3D.EweloBhBmSQQwHbwMYHtEBN4hARgE4iQpSg%3D&bn=Ganohali-dohi
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 65
col: 247497
error: {}

**Comment by felixlinker** [comment]
Closing in favor of #718 

Thanks for reporting!
