### ISSUE TITLE
Engineering not possible

### ISSUE THREAD

**Issue by norohind** [EDCD/coriolis#718]
When pressing to modifications button (with wrench icon) on any weapon in this [build](https://coriolis.io/outfit/fer_de_lance?code=A3pktfFalfdpsff32c1g1g2a2a040404040402p25d2J2G2525.Iw18WQ%3D%3D.Aw18WQ%3D%3D.H4sIAAAAAAAAA42RL08DQRDF51raUq69ZY%2FSHoK%2FXcAQgiUhQRGCIXwENBgEJBUIMCgEogmVCASyshLBB0AiEEgEQRFEaWeYV8KGCpI78fJu3%2B9mZueIC0TUz6n0rlTC9wxR%2BaxEZA%2BzRHEnJHJdDSTgTU%2Beqow%2BFInMxqdI9cZonuGqz49VjOuKVGa%2BRCaRJ%2B0RovpRTcksT3myoRLcv4j84M96WH%2FUkSTH6x46VymWWGSsaYnm4RbgFuGW4CTP%2B7%2B4abyJxKi5iumkzFu%2B0jVyNInXTnQmXGH2KdLvoz9Q6z%2FIpKk0zttDUHibV3JP92DhBqSDE5uanOBdTx6gMTZqQbrBRiu8gzxAfoGNvuq%2FK9z1RZY%2F9HAu6ekearziizTRblpPI1zBXmo5h1dJ0kBCw8837%2BtUb0UCAAA%3D.IwegLCqgHCAMICmBDA5gG0SSdf33EA%3D%3D) it shows an error:
```
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Path: /outfit/fer_de_lance?code=A3pktfFalfdpsff32c1g1g2a2a040404040402p25d2J2G2525.Iw18WQ%3D%3D.Aw18WQ%3D%3D.H4sIAAAAAAAAA42RL08DQRDF51raUq69ZY%2FSHoK%2FXcAQgiUhQRGCIXwENBgEJBUIMCgEogmVCASyshLBB0AiEEgEQRFEaWeYV8KGCpI78fJu3%2B9mZueIC0TUz6n0rlTC9wxR%2BaxEZA%2BzRHEnJHJdDSTgTU%2Beqow%2BFInMxqdI9cZonuGqz49VjOuKVGa%2BRCaRJ%2B0RovpRTcksT3myoRLcv4j84M96WH%2FUkSTH6x46VymWWGSsaYnm4RbgFuGW4CTP%2B7%2B4abyJxKi5iumkzFu%2B0jVyNInXTnQmXGH2KdLvoz9Q6z%2FIpKk0zttDUHibV3JP92DhBqSDE5uanOBdTx6gMTZqQbrBRiu8gzxAfoGNvuq%2FK9z1RZY%2F9HAu6ekearziizTRblpPI1zBXmo5h1dJ0kBCw8837%2BtUb0UCAAA%3D.IwegLCqgHCAMICmBDA5gG0SSdf33EA%3D%3D
Error: Unknown
Details:

scriptUrl: https://coriolis.io/main.js
line: 46
col: 84892
error: {}
```
![the error](https://user-images.githubusercontent.com/60548839/198876439-ebc1c2e1-bcf0-44ec-86f9-49f8a344cba0.png)

UPD: it appears that attempt to engineer any ship weapon leads to this error
So reproduce steps should be:
1. Open any build.
2. Press modifications button.
3. See the error.

**Comment by felixlinker** [comment]
There seem to be a lot of related issues. I closed all of them.

@Sid127 Should you find time to look into this, please make sure to check the already closed issues (the error messages are not exactly the same, we need to make sure all is fixed).

For now, I downgraded coriolis to a prior version. I hope this resolves the issue for now.
