### ISSUE TITLE
Add possibility to save and recall an engineered module

### ISSUE THREAD

**Issue by s7urmi** [EDCD/coriolis#72]
It would be awesome if someone could save the values(the roll) of an engineered part under an name and call that on other ships. Would be much easier to see how an already owned component would fit onto another ship without having to "reenter" all the values of the engineered parts.

**Comment by felixlinker** [comment]
I altered the title because I was constantly searching for "module" in order to find this issue.

**Comment by Piedone** [comment]
I'd imagine being able to give a name to an engineered module when configuring it. Then under other ship builds when browsing for modules there would be a category for engineered ones (or a section for engineered ones under their respective categories, like module reinforcements) where you could select them. I.e. share them across ship builds.

**Comment by felixlinker** [comment]
Closed in favour of https://github.com/EDCD/coriolis/projects/4#card-53925515
