### ISSUE TITLE
Engineering still broken...

### ISSUE THREAD

**Issue by MurkyDregs** [EDCD/coriolis#724]
Plasma Accelerator:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Path: /outfit/krait_phantom?code=A4pptkFflfdussf52b2b1717040406065oB2372d29m529v62i.Iw18WQ%3D%3D.Aw18WQ%3D%3D.H4sIAAAAAAAAA42RO0sDURCFJ8nmnexm12yM4iPq6oJgULBJYydEUPAnKGhjlUIhhRaCdjZCsLLIT7DTwlJSWVhaSLAWCwux0DjjnCIXTKO3OBw43x3O3EucIKLvuErvXCV7ZRHlcyzi7qrzTl5EguUUkUR4xZBHKqnNLxHnuUpUwh3vIalQlEsG2ldxgk%2BR4oSSftshKoOcaQwrGeNRQzb7pHeTJSoe%2Bko%2BaSIWL%2FUhp%2Fmq%2BX1XROJcM1ePVdKom2m5RFNw03CzcHNwkuDtPu4VQqJq%2FV1kZH1coxzXzaRLbN%2FA4pDgLKN5%2Fo%2Fc5tVfuYPW3uKB9r9LE00%2B2go5%2F4EKvAbIAnSqEkGUbH%2BIhHjYytabLu7yhpm0pxIt90QSeNNsLUbkdlV8jAtu8RlDPG%2FwC7S%2FVmtXxpSE8%2FAjAZwUB8mOITuGhJMSLxiyBTLUCjY2cuGCHSVFaOD8AInleh5mAgAA.EweloBhBmSQUwIYHMA28QgIwVyKBQA%3D%3D
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 46
col: 84922
error: {}
Modifications

**Comment by felixlinker** [comment]
Hi @MurkyDregs,

What is your issue specifically? I tried loading your build and could apply engineering.

We downgraded coriolis today to a version that worked previously. Did you apply that update? To make sure you did, you can try hard-reloading the website (`Ctrl+Shift+R`).

I hope that helps!

**Comment by MurkyDregs** [comment]
Hey Felix!

Seems to work fine now. I refreshed all my links. Thanks for reaching out.


________________________________
