### ISSUE TITLE
Experimental Weapon Stabilazier ? Where is it ? When will it be added ?

### ISSUE THREAD

**Issue by delaware1999** [EDCD/coriolis#736]
Coriolis can't pass the AX-builds exactly. Firstly, there are no Mbooni weapons in Coriolis and secondly, there are no stabilizers in Coriolis.

**Comment by robbyxp1** [comment]
Use EDSY - Coriolis is not being updated at present.

**Comment by PhoenixWhitebrow** [comment]
EDSY is way less comfortable to use, I personally prefer Coriolis instead. Is it officially dead? Very sad indeed if it's so.

**Comment by alex-williams** [comment]
> EDSY is way less comfortable to use, I personally prefer Coriolis instead. Is it officially dead? Very sad indeed if it's so.

Nope, it is now being actively maintained again.

**Comment by alex-williams** [comment]
As per #744 

Currenttly EWS logic isn't supported. Add following logic:

EWS unique module
If EWS size 3 is installed 5 experimental weapons could be installed
if EWS size 5 is installed 6 expiremental weapons could be installed

**Comment by alex-williams** [comment]
EWS is in fact supported in Coriolis live site. Closing.
