### ISSUE TITLE
Failed to import  : AX Type 10 with the Cat 5 stabiliser and other recent modules equiped.

### ISSUE THREAD

**Issue by TonyFlury** [EDCD/coriolis#737]
This is the data block on the error page : 

scriptUrl: /import?data=H4sIAAAAAAAEAO1a32%2FbNhD%2BX%2FScCvotOW9p0jXd0jWLg%2FZhKARaOttcKFKgKKdZ0f99R8mJZVOyFacYMCx5iCGK%2BnQ8fvfxeNR3C1bAlXVqXQmSi1pZJ9Z0SUtsuH0oYZJ%2BpIwqIh%2Bw%2FaPIawaVdfrnd%2BuDggL7qKZPse6TnslC1DJdSJKDq5GY0NBtM15%2F4tapkjWcWNeSCknVg3Xq%2Fjh5giv0G4jMiFyIGXnIhZAblHPdeklUthxA8jpIH7hKl2iczCVdQVrRvyFOM0aqyt8g%2FiJJATjaubrQvQZgnRPrHV9QDiApX1in3623rIYSL9SHC7TfS6LYjybeyab9d8TV%2BNOL9ErwxQ3hC41%2Bhb5m1ql%2FYv1RE9aO3nYax9I5Bdm69orMdC%2FrIxqLD30miGqdTiLd85OkaAlh68bE0Y1XUFUfqvdC5K3x2g2PIOgHWDTjeEJy3YntORP8M%2FBc390FnBNWbSFei3uQF5LcbxAdOwoDAwxb99uG7vlUKloQtj1UL%2FCdnsG6iWMMt7Xu64%2BdmZ%2FXwBThd828R%2Ba84%2B1bvD2CkRqN0TlUdVkKqRrAsAXsEPwKe0zbHiO5CQ2jurzswH0klLeUq17EySg0Odk%2Blt7WHPINJd1xlGwf7p00N3BdpJXjxL45c0EwMHMnPdjXIOdCFoRn0IF3EtvRf4mJPkQLA%2FwSiLohqgtrOyZxXdvvIa5BspIRDoqUpRQkW1Y1VZCSfKXtzjdzed32kg9n645T3XEk80odazmtlKSzWgnZ5UvQeUcTkptuQ6TpQ9ejaGmdGHHS4OoBDLF6194KeCVk1cAFBq1vSE4GbTtI6DhwotgxCT1t3ple0cVSfQH9f0Nr7xiljeywh2NHCG0Y25GmrGfAxd5BxrbDusU1D9Q0I%2FyML1iHuF7co5D%2BGH3cWbIzkd2VVG1mSa%2F%2B50%2BNo2a9xnU2kzWtAB2JNOyA4Y%2FrpVPkgztSGaslBZZnwNhsWMH1j%2BM2uMlItre4C%2BAgyWMoRQZHG%2BDW4Pgl2pv4cQ9VGxPeP5lwA5Sj1GVdJR6ZHDxBTZXEtUQtu1Lp2InmnSnEZr5g8O6tFHfAbwAdtS2VgR1PYgMxtH3%2FoPaCXDygqjegW1lDYKr5wazhN%2FS8otkNaKZtLxJBZHuT3sTGn9jNjeiArbdLkEU%2F%2BJvYNpeKN57TLkvBISd8K5moMMnsgw5D2zM1J3xOtlNlQpTd7CTc4bTfcDoaGSxNBi5Jdjcg5Q1k2EAGI1ViG9Lrh4wbSH8E5ErQDEoNt4K17K6BPqPHgH3W90ealkvBIRNcScFSiai0lQe315VuqzveSFfmqKWoE5koylqB7EkRmpEne0feBb0scWuDmUxF%2BR0jNc%2BQs6mqpQSVKso7nrjFq0si81KgBg3p70%2BAHuMKDd1K8EyISjtCe9gxPLwFPOiOMRIc923JWt18uzahDcZ26%2Fc8%2Fe1Z7oPAdiMjioPkmB0VpqA9ia7tHS2NmJw7%2FbnI4SVhjyi%2BBHavJD4beEsVjyLbkJC9ku2VbD%2BdbOEr2V7J9m%2BR7UU7mVey%2Fa%2FJRriiNb%2Fj4p5Xy1rl%2BLsvFRzajXd3%2BTlkhKWYEM%2BISoG15bA12IW%2BN5Squs8BGUpKnwUyZifSlnKzulKioBVRVPC0rGXJOmBtmJ0LNu4cBHcgXP0lZulOsWZFZ1KX6x6AMXHfKdTp%2Fr%2BK2QhojgFcMtzZr4eNG8P75dbAdQFIh7nzU9HGzOk9kFLw%2FZ780vQZ7UlN4W%2FARZURzlGqZqSi2T4Cj90hL2vG5GP9pgC%2BdTTgdWr567lzBh0wSoTdiSnCl2jCzZYJl0BWDxd1I6drIQ6PKYF6Xk%2Btw40O1UAvYA4oP49vQGuYWp7lOdUz2Smwxo4dTyaTxNRmf3JY8PbJc2y7XoDIBjAOSNd%2Fkhdo9Eux9wv1UehGKejZrByjkjqGZkAKxNiUAwrIaV10EJvrw9WGw3V%2B5EDSw%2FY28NN38znNKPBOlX9krtF7cBk7UV8NctJ3AtRlOinIAq5BTnXdKO8WX20v8EzIxE4O1Uk7Bzi7WUxkrt9ekyXts7HhMmH6XL%2BLlYR%2BT7HRt8ODh17H8GCwNPTKg%2F80D4gqaoYqjKsqTsaaC0yfVqWrjs5c6ZZnlyCPAh9bhDwKfGxd9ijwwcLT7jcD38qi%2FQRHkRkKeLXe%2FYX9x2NBU1EeKjTsCjxReV3M5lQCpl4VZZDO6TfI1%2FG9Zf1OiI%2F1TdczLXaFtGR9BXHd%2FhOWEkycQqfnyHgtIZ9WILOlnornfwkxHPjN9tKI%2BsgN%2FSQ8FPkNaDdIg9DcCruYKRwrIZhdRebpmG49QkPwsYlnHgnq5v1oZ0UhzhktNT83cJO%2BI%2B3BjzsMRTqWXsO68fXHP9GvX%2F0eJwAA&bn=Nightmare
line: 0
col: 0
error: {}

**Comment by alex-williams** [comment]
Marking as duplicate and referencing single issue for future import failures relating to missing modules #754 the content of this issue, will appear there, by virtue of that reference.
