### ISSUE TITLE
DPS summary does not account for engineer special effects.

### ISSUE THREAD

**Issue by WEKarnesky** [EDCD/coriolis#74]
For example, modifying a cannon to have High Yield Shells does not add explosive damage into the summary.

**Comment by cmdrmcdonald** [comment]
In general special effect information is updated as expected.  We have no data for high-yield shells as to how it changes the split between kinetic and explosive damage; if you have this information we can add it in to the effects list.

**Comment by felixlinker** [comment]
@cmdrmaligno posted this helpful issue in the wrong repository: https://github.com/cmmcleod/coriolis/issues/219

I link it here because it's of obvious relevance to this issue.
