### ISSUE TITLE
Failed to import ship from EDDiscovery

### ISSUE THREAD

**Issue by colinquek** [EDCD/coriolis#741]
From EDDiscovery, to Firefox, hit the below error. Not sure how to report an "Unknown" error, but here are the details.

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAAAAAAAEAO1aXXObOBT9LzynDOLT5C1bN5tsk202zrQPOx1GBtnWWiBWiKTZTv%2F7XoETYxCG2Jmdzk7yEA8fPrpI5557rvB3g9yTTBqnxhXHCS%2BlcWLMVjSHEx8FpjK6Xl9ewrlrnpSMFMbpn9%2BNS0lSuL6urqdrSqMzkfJSREuBE%2BIoBMYVZH0ajj9lxqkUJTkxbgTlgspH4xSdGB%2ByJc0IETRbGqffjV9YSXI4kJdTuGxP%2FMDxXfdke%2F53nJJn2OiC4PvHaQlYJ8YVPAUzTr0T448SsxrftKqw6YISUQd%2BhefqLuMaFwV86TMGYON0EphWCH8TiFNQiAizzRU%2FUBhXpCgui185T%2BqH%2BHGyRZqSBcli8jQMhMTk6rpkkuYMjreDOOHEDH3Lsu3OKLZntYdZYFbsjPMR5knS%2BJYUtJAYRtwiv0OB6SKI3%2B0gv7MBWf25A%2FB3KyJSPbxtIg8QvA74cNAfvuWMF%2FSeaMN2fDOcwKz73bCd0FQLEvq6Ab6eKGAgTQq8xezDYkFiRbYiJzHFLMI1O%2BJVma0fjR8qoA1hU8VhLGIslnyOHxPOxZar79XZCyzjVQ9frQZSQmIYKebpHMsowdmSCF4WW7Cpuo76iN8BSomM5oI8EBFzkXOBJeVZtOQsaUHaoyEHYnNGAJEqO%2BOykDylRR1TTrP1FqrO3%2Fec7cnyBuBlJqPVIyxdIoAUUUH%2FIV4UM0hGb4t5LiDJQYEWcqruOko8Qo14nM%2Bm0RXPlrdqZvTKYZlh4I%2FTDttXWdBO6E5qtGUDZoIsqyd5Rgodc%2BLWqdqCQ128TqrdcCDPVOCHLaBl%2BqEmaf39kcH0fMolTTHbfVDkTyApgxDZ3XxFVp%2BCDeXqokiilZLxnTxVPFmUhIFirJssaVSWc7h8hysujmEdowtSlDmklqwA3Q7truCOWX1HX%2F4PUi5wkKuj3DUt4uiKLlfyC1H%2Ft6xzd1lnuyNZZ3qBbhkOoJ0XmL6qEN2yFPo9a9peqlonqnn1O%2FN6jWlWT1tx8LyqVPbC7rzWX4umVBzgATRzATw2Xf1kINs9JAcnpusHXbTA9AbSsH40fSbavqURHeS6IyryE%2BwNEQsu0t2SjFzP9FTdRRpujQUHCyRvsdxxEPak662Q6WimYEgwNlzj90Qw8Ksk2RGOHMgm%2F%2BLzqGFNUxKvcAb2I7LsLS1v1J2%2F8flI%2FcgZBv%2BF81xwHK%2BKkkoS4eReTV%2BjRN%2FUd4nHs82NM3Xj2CEUexKIU9B5Kbmo8ino5FNNsu1txyRV4GiSqj1AdAGSdS7I3yUY3Zen2ReCc54V73GO413h8Uzf6aaGjwZ5toG8VQsrlg2ihSYKNUzzTTSKuZogncB0QqRrDdzhODeo3ThBWDVPPiwws8cC%2BPLaYW5QjwxzKHE79F7gQnaqfnWXSja5j%2F4qz%2Fqq9ChjGPiaKr2F3rSzVWof01h6tjlR5cTpTuIhpdpBfoWHNGLqjixPGu54ph2A5ncbPGdY8pXYw1LTmG7E4dlmOl6XOpbpHiD5DU6sQIo2LG0zpyBZwUXRdCENub%2FFCT58HyJwLeT4XcbMqjGHuonRdHFsXVnvuLA2U%2Boo7tSsyFmMs7NsyZrVF2lQRyzt0xM9aavr6VyH5%2FYZgx2b2KjHMY%2FXOZXbtVG7Te%2BfTw6VyntOYwIcXkdgAWoib3A%2BQwiEfVbXR%2BA8VEVkX3Nbl5kXNbeJ4NAw80wKziIBYdK6jDsdQqoPK4hm6uKI%2FYaLXKo%2BSRYQIcNlFq%2BIiGQpBJGRpFljFu7g6AKLJOfAU%2FdQdxBa4DIDp6eVUVk%2Fg0gaYrLhPRrH%2B7M05df4G03LdMswV9dJD9OUKB94B%2BLR8LHgr8d2R51uZmcNY84YqJEiR2MdvdY6%2Bi9axznBKaDAAi5pOgeBY5uy%2B9SJqsPnJezdRBpT5xydwat5%2FWqqhSpVb032ZEi0NL0SMieavY%2Bh%2FYoNjVpqpVpareyNaGOmOMVLco4Z44vFOFy%2FVwQHaptU%2B67wWW3B%2FxgiSkoSWmXMU29dHT9TpXdz8GehCjiNYTs5iilIk99DQP9TpijNSqHrVFE8rkrGBKEZ9PYxUUiVbCF9%2BQkr2RqzS63GqMsZqQuaXSO6LcRJhdjHQ6uFqA%2FW0wfrVNDeUa4faSh%2BAUHc7gTxWq%2BVbFsjjMN2TvtG6SxJqKpCDX4Flqlsu6bfdcKj3idB9US2q2sm4YE278kOfZl0NPbeV0qHoX9t626MwRXS%2BIVeqy%2BPRm0b%2B76mvXgdr9XqMXScNIP9lNTatUDXDRxm1zxd3zPCrh3oinv16c0V904zdN%2B0zNYZf8iKVSkT%2BKymOLq3e2Z5jB3urwKuvgp4VRXoa2t%2BxiqAkMb0DNrjsUXAdk0HLIXbfRnkjGjx9xUByEmwhGGgUYvw2CJwLPb%2BInAQ%2BpD96rJU8%2FuCF5sa983U7PAZHsecTLS%2FNjnW1HjqTZxndd9svYKpORZ7iM8HoL8an6sfywi139bYWUUtHqOKx%2F7Yn4C8JEXs%2FdBvKfKWIv99inz98S%2FHwTzNNykAAA%3D%3D&bn=vengence
line: 0
col: 0
error: {}

**Comment by MartindForlon** [comment]
Seem this issue may be linked with new modules. Below is my import of Imperial Clipper which also ends with import failure.

https://coriolis.io/import?data=H4sIAFeJhGQC_-2aXW_bOhKG_4qh60TQByXLuUvj5CQ98WmOHbTALg4EWqJtrilSS1FJvUX_-w4lJ6b8JTlJcfZic9HGAvlwqHk5MxznhzUSaclIYV3884d1mWXijl8xmlsXruOcrR_cijwn0rrwqmd3imTWhbXIVYxVVjJFE8y54PGcZlPMYoblnFhn1hduXShZkjPrQVIhqVoB4cyaMKFg-r0edYtlmgvKlWv9PPsbl_c-bvmMpLTMWtcfVcN-xf7fZsCeN7C9fP_MuuZzygmRlM-tix_WJ1aSHD6ouyGM96K-74ZheLZ5_gfOiF6LFkl8S7CaUL68wjlOtDEbHAwZ46z3iBfGQ830Hcd1Yc_35ImwyiRQK51RImu93uOpfm6NcFFYelhR3BW_CZFWY79ICijMvmKwB57YsIP1776N9H5f5uuNjvB3mlUvzsQ4O5jAdl4xfdsxMWPCBE4faUbajXEMjAvMn3-dWX-WmFVucjXX9HSCywIcXcD7Y7jkyYLIWJVSEhUrylet3n6EQVtiM-jfCReFVhGR2dKLp7igyTGus5_bQUOoTUMDx_XCvn-6hiq5DPRPu1xOcbdn-Al9kLv7dnDc3QvY54m-dvf7xP-_T_7nfILM80eynEoSK4lTYCYiWeZUtfImC5pfrccasEznciwTSG5iilepEPIAyn9FXenBt1gli4rUEuJBByFCu1K4lJkopRbD02pYbkf3CWGEk95ngvluhPd0hL_-DloEr3GF2fVsRhJtWpGThEJKwzU8WZR8WZF3Bsf3IgHHFQQ8bQ0JyXsPDCu9h1flBe9KHqEpln7UFN2QzAhPyAseXgJTi5FOzTmDz-16Dky6PwhshFCIXHON3-GVQQYYk4IWCsNqrdRzD6j6B72iz0HmIfJQ1DfRj6Dm7CR04-TYgxCFTmASwUFMFPSJnGKuP7CrWBFuzPX7tocGQYAaR9OxIxdtDmfzBK21Mtef_NZzVMu2o_D7_T3CfxDPRILYuIonqnJ8U_q3RGKobDjdFb4zaBN-ruF5BV_Q-SJZrGvblgMwErxQRMLvH6R-z3S4F9pIy8ozPV69BiMFtAne9jTC3UA9Gw2gvm1oXqcW2B5NKByvVauVjr1RumO7yPPDLd0M9Jl60Q340HzBBf0PCeOEwfsIWnWz8XrXoBkMdrVTT4uHVG4HzAcpZrBXIXsPYPy-oOm1aYfUcPFEpE6JlRjaAqfE895QwrktOijnjisyl13c7XrIDBhOcEhAYMBzq5shU29CRGSjsN8A1S_qS65ohtkede8xD6FGQPN0sN-LfCByJmTWKZ6BmE0oCuxARzd3F6xlPsaqQ8Vi-5sDY3tRdLhi0eJeK-AkYY8w5bVVRVdlD_ZExZvJEJTF52PM64C1kfY1e6IQEkdYqrJc7rnwhc4viloNn56iXpMTbRWc3XXr2KERnsKBSfkkhDq9aPWapsBLP0n2TtCsgKNgh9dZml7frGC8lwN-VJ-LFUSjVIebSqNBV43eSBAZVMAzVcWqLjrt-y6klwM3mHtIreob0f82pXoPS_c-w8hC7AvB_kd1JhoCc903C9UNGmHWP3al0Q5gFJJMmedCqi4eMLpnMHFST-xaO_mDA7XTEApESaelEnB9AB_cSPLvcp3vDV9AkdobPhPGqnp6O2ZEnSqp1FhqhgvVnhFhk0T2rgRPS6q6JMVvBOdQfXWuhBpH8CVHRKb_18Qxea3-2vpTntGfipALyN2c091C3xSVD9X-nmzb3TrfsA7ZkReEJm2ygro1-yjb1rT32Hb0-OxoqkOm9ZolpCH-TmEMOVDt7B6kCeFQKx4JZIT2rhakrO7D22fH24Qx9HFhrP_mKOaEBib07XCnVqy3-6idqiYJ5pd8zjq4t5E60bGWq_ZuUS1SnBYYxzjF0uzIaNKsJAzuwMsKhWpU-9X0BmbBvXG5Tata_qkUnCSCKylYXHLIgrKAKKcX6B-3ddP40f85bjzRc7YXqTpIEidLc_tue1tKI70KGe7YXX3PJAnlUEInRIdc84V43eB-BUdds467J-vcloyNG2a8uWv1IWVq1Eja9iD0Ii9sbS9dpilVtKpLWmTf0H3g9O2BH_gD9L7mklv3aqKN5ZHtBgj54fs6S7vcEK57g2bD6i3tpcPgZotgu0YFsbxXs8jQrIGelxiyB-b7l_CPL-E0lwiqJfxfuUS4fwlJckwlqZOfd1Ls6VdEb5s4Lefz1RSvTOIhG1GTGO0nHgo97kluHFTwxpdnUzGdMri9cPE8Y3hJWkGfqgmOvweSLCRoOYOyVJLOoMgEpQQK1xjqiRxwBATdjhnqKe4upFiCYqJu070D0_vdpjfeRd2ySMpCiYwWWAe4OC9lztq3UsfnK8FeGrprJMiTq3-JaVz3iV--aMGM0bnE-WIVOx36fRryWUy3laVbh0ThPJcCJ4sCLgkkxumTjkhpO7SeLFeX6_kTPd9cgkPGgiUAWixoTtM4FSW4nem2zvOii4P1F0V3Q-dXQN3DX2Np8JIqF85yBhcovxPxd6o-VcM7cItcUHYCeFKP70BWmDLUFfsIgzswn6FC6VI91dBvevQBh-lzVUAR1N1PuuhxPpTW8PuToAlkACgUoQSty_vjlK-QpQn7qqeZnOfqlts8-MmqKryO8-rr8cuxh1yuzdx2hXW21qz-Wwtn_SGFNKBrtJtzhNYD1hXib-Pr0f3dH_AQ6rtq0L3AcEr0rUrRjEDJkek1PMfzz53w3HUeXQT3z4vA_Yf187-M45zsUyUAAA%3D%3D

**Comment by genen** [comment]
Here is one of the error ships (I think it's the engineered heat sink) 
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.54
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAEAO1a23LbOBL9Fz57WATv9JsTJWPv2Buv5UoetlIsiIQkrEiCBYJOtKn8%2BzZIOaIEUKQpZ2Z2d%2FIQFy86aKBPH3Q3%2BM0gT6QQxqVxy3DKamFcGPM1LeHG%2FVasWQHXdyytM1IZl%2F%2F8ZtwIksOzsnkWX%2FGc1TxecZwSR%2F4yYxKqvQ3XHwrjUvCaXBj3nDJOxda4RBfGu2JFC0I4LVbG5TfjTVaTEi7EzQwe26EfOL7rXuzv%2Fx3n5AdsfE3w03ZWA9aFcQvWZ8ald2H8o8ZZg2%2BZUdTYTJeU8NbqW7yQrxl3uKrgVx8xIBuXfmiGEfyDoT5wCibhbPfEc0xLglfVTfUrY2k7i%2B8Xe6QZWZIiIc%2FDgE2ZWN%2FVmaBlBtf7QZwoNCPfsmxbGcX2rONhljirDsb5DRZK0OSBVLQSGEbcI%2F%2BCAtN1bMfzFeRfbECW%2F9wB%2BMc14bke3jaRE%2FlyLY%2FAh41%2B97XMWEWfiNZsJwDbXBepVjuRKf0R%2BTr8zxcSF0iTA19x9m65JIkkW1WShOIsxi07knVdbLbGd2nPjqy55C%2FmCeYrtsDblDG%2B5%2Bpbefcai2Tdw1e7g3RTiHi9BSNSDrOLK%2Fpv4sVJBqzy9ojvOdAVYmgpZvKtHlhrVBhEmjB4P5%2FFt6xYPeBiRfQxgKSLxoSA7cs3j3mpePiY%2FbAOZNXM4wdS5Jih2zLuCA6peApj7tkXwmccf9kDWqav455%2F2jJYnA%2BloDnODieK%2FMg2PeBWoEYLsvoCcYhzyyqN11KODvgmWbKsSQbE33Q50lHI9%2FD4ER73aeQRWkaXpKrLknHRALoK6W7hjXn7Rg%2Bmc4RJGvY1cL4Cd4dp0dKzOou%2FXqjyt%2F1ZPKO8K%2BHuoYQ7yO1jsIZ8yIpMoJllORr2uVPYF5oOUpkSmN4A%2F9rJ6SloR7poQ647QlGfYe8JXzKeH0oqcoDbKIpCNWCQNRYctjDxgEUX1ow8FdB0NCvw%2BZj%2FZYZh48JlyRlO1lVNBYlx%2BiTtTvc0u2%2Ff4tur3Ytz%2BeLIoCil11LYXzhd1ILxhsqBQuXWufvXetDdMXwOPI0eHw8QP4N%2BIrhkRdWbpqDePGX3y7e4xMmhygYmqFUYqdT00aCfd6gPJFnDpke6ZA8Cx1ITFN9Eo6ijMdRxzdCDgFRB3WFDd6iqoY6pbi%2FD4T3fVsCa1zZyh6ozMhxrpBo2kksydsQpNsuw6ZP5Uel14Hs9PG6g4zeMweTSPXPRuORCJ82Ob4aWXprdkdKs8ZzTbOaRutLOsN5JpYOtnCYUUvhtN%2BNwVSZYpjtG7ypSVIxXPdvpA05xn%2FAMb6SBa4HPVIfNmzHjW7pai09E%2Ft8nNZ5lB%2BMSQgS6JPM4NTtXd6kRWaFv63a8EVtyO7dHGVlinuDiqlhl3eIENrzRrj9w1q5yTViyKanYu0gWvW9%2F3Bzaf54YTQiQchM%2Fkd2MdzgfYXiSfZTPR%2B5juawaU84KkrBCcJbFX0nBGiY5SuIo%2F1hhPJcP%2BwjVnS3kceJfbBHvpr3EiaCsQLGFOpoiX%2FobW4ywdwdTwWJtqEDxos4hPbYPl%2FE3Kt409ycAViWjGeGOgjhvH0yAFJhmSMF7hLsTwL5AjFaqdZ%2Fk7ZH%2B5kAcykmbr9iKVjQejhoP29MlA7JXXe59R6skBptJlnbl3Zku775nIqnEgdpEiaYk3hDYtqrqyJSzGZbhdZ1lnNACcuSEyKKtW3%2FZR4vsNIvsn7WRyhzueJGvwYiHAyMGW1aB6zgjK3ZbkwMhf1K%2F6ipNqZSDjl77lomQayF1DCc6q1sFJjqBa7tqiQIT2m3lU1tVZ2OfbFhNQz%2BPmvZrUFMT%2F6OoeViKh47tjaQmAu7IBfmJ%2FAwCqFUCNTs5l522iTwvRD%2BFnedin2bnJPShxpZKVk1f9cWsRn8ewY0cf2RG%2FHMFN3A804rAg2p5dC6lPdMOQk9T0rwCpc%2FFPk3pSeivQunrUsRYNBk5FB0FZH4rmi%2Fg19muxn9ut8rLa8xTyEoLgabmaZFlh16g0em2VRN%2FgOqibS%2BkeiKfSNY0uRXos67A9XUVbpfKOMcrck%2F4XFYo6cHOGCDL1nUJZVaIUKA9yVGgu9kfFJ%2BBigdZYSi3oWHC4kweZA7O2damk0NHTLVgcQbwUIecz5rJ2f1frPmfYc0yw5uccYF5LGrOiYhzktI675zENNfDUjOGjgPY%2Fy2EhJzUUp1tme7A2Uw%2FIy0oOq1AU%2FREpue7MLkXEhKZbmBr0mDTcaIpdIQCUUdH9MeLWG8T6k%2FGmb9E7OeJ2JpgUdFik%2BG6SMCQZykTtOg0Rh%2Fh6jUyJmRrm%2BFNZ0t29udgSefA4GUHGFd5zu7wV5o3Mtk9vFG8MpSaPxC5XI%2BwoB2PBJq2NdI31j8fL7PsClcyNMHVGzte4Iomp9bYHblVTHDfGTvF%2F6X7FmyxyEgsOCvXW%2FgDYbRf2TfNQ6svJI7bx6savEBx0XzVREbX3l5Te3sjOJGSBAK%2BMTImsOTE6nSnZ%2FLhGFNbFHAZKaD0KsRBT79B6SPRaRT7CKVvA%2BqiFMCxMsOCNH18msaLDCebwyb%2Bzcx6EVJJOfyxkA5LcnoMmnTnwcFPwrKMNCc0jStR60r30JXIalw5WULl4YBna9ooTQxqTxOPOoLy84MxrZMmrVKb%2BUrwjThItMP2FFlzLhmOOPWTOpfguoLc5oVSNznBac5gfP8sqbPMyLfHrbXu0whkBqcXWquXgUYvvWl66elOf0fo5Ys7i%2B5Jdftd%2B%2BVRMLqz%2BDv0y23gBXKjQPOhxJntRddEDgpcXXif3V48F%2Ft0e3ESusLPhHEOY7Ci5Iwtm4%2BLufwgoPN9Jjpiqd%2BwtC8vO94ZquaYdkUg38PPn7ftPgjw4gr2C6DyIX4w8F3A5%2B%2F%2FAbZ%2B2L%2FvLwAA&bn=Manta
line: 0
col: 0
error: {}

**Comment by tbayart** [comment]
Hi there, i faced the same issue so i avoid creating another issue and contribute to this one.
I export [my ship from Inara](https://inara.cz/elite/cmdr-fleet-ship/378394/3843844/)
And i result to a [**Failed to import ship** error](https://coriolis.io/import?data=H4sIAAAAAAAAA%2BVYbW%2FbNhD%2BL%2FrsNqLeLOXjugIt0G1di%2FVLMxi0dLKIUKRGUk7cIv99R0mOJVma3K4F0i0wIpuknrvn3njkx89OATQD5Vx%2FdmhV%2FUpLcK6d14Iq6qzsyAdQmkmBg%2BS52w798e4N%2FiyMqfT1zdXNFbOrn6efbq6AMwM3V2mZqWc5BzDPdMGqmyt%2FHftJgM84wA9%2BaYFe1NrI8q2SFSjDQFslGrAXsiypQLVe%2F%2Bxcty%2Bv2pn3iNcMtkgPDysno4baN%2B0U6kUFTaXIrPrHxSRqv3fsPoCgRip2f1ySgTA4%2Fv7Vs72xg69qzj9QXuNiQmI39D0P5f8is5qD7iZ83yNk7YbJynkH2%2FrgXHte6MYhSR5XOtcfUSsuLXZR76CgKqskE4agjNcGSjtemc2uxglGxabiVJeU01qkBahNzu4h25SQsbrEN35DJxhVw8PqEZVTNQ9LTVlzw1IqhBSbHSu3lG%2BaNy4B874lmP%2FvwFoTfHvzjXC9b4VrV%2FM5dbdASwREoI54s7oHtHK6EIvC0MXIfSl2TAAoJnY2zH%2FCuQp%2FmC6a74BWaEUuxU5R0ZjwDeyBY4iunN9riimJwUkQ5x7TjJUY65S%2FzHNIG1UrSBkqYZAZ6rHZ21R4mOXi%2FdBcDBOHObfcg5DaRiSSodmeihSdbF%2BYYrN2Ayw%2Fc8jj1BGG1eJWyDuhi9pk%2BJwFDkMv9udwx1k0g7vZe9NhOQALhmApxVrMUs3E7WOgm1opMLO6BvE6dBddWjKdbnCPMRY6pRVNrQ8f%2FUr6fp31VfgjKRuNlOWyzo6RpdkncHGIah1MqelHYZTEi3pqEFpiJaLaWOSTht5FGq6fnjnd50kYziocPz2FB9bV%2BHBJ492ebRF3kykpAPsRoyTfKKgoa4Ng3QZBOFkrSUDcJBrje82L0RC%2FwFZFARO5VCnYetgsClt0b4D%2BVjFseroCejSLf5FdzqWgkfaHrO5bJ%2FyCEn0O2BRtljpnZvWnaGNbCTzbAeaUbeXaJf9gUhKRdRL6ZDmzRsCPSmYnosEXEG3xEKaDZHs4pxh8B89iy4yufQqeTQvcpQ7nrMOW0H80nudYR9%2BB9dP39XqKNdxXZXtSMnTLONPdBtnx9pd5h8TFv7GwuEEJhsJSqZS0J9lKSZmneNiQiqa37dJWIFkUmJBkfSYumRLXlvqOUDBVmaYdSYIkSEYSiDslYVvvdoctPfQleFO1Lw68YKw0aauqN4RsvXEeiORS%2B9gwHEtqixsZbYtgKOOQ6VrlNIVje3S2e1%2FWB2Eg2duCbCaK%2B9FYYpwZqg4u%2Bf%2FUnUregcJDLJ6GBpxP4w3Z%2BNIoTaJ1EJP18mbaE0BVKWs1t4ti97fEtIdVsF2RFs11wcC1FHVpFNKjOtMMTrVdOeW61yOGrhuRZPmY2gFmTPX9NiQU%2B16yQKmDKWjN6YhLrlAS9g65yZRtGYaxekDQZny%2B7zn5zT81QQGWr9BPFvnlOmvOFlspzdfFpUVoQnvAirMcdF1VUo0isTfRz7vpVs6NEy9cX9bLcwwVcwf2%2F8xdwlmiZEwbxbY1dn8T6dKbnU%2BaTlMPyznxgwvzpI9sIzxX8FcNIv3KynCGCXnOUja%2BElE0oyOebVHVfXpzBTA4eSX0Xd9bTp2uYk%2F6ZVQR%2FGA9SIkauKHidqjscfTLGoeYuKR%2FzdJWpxPy8Q65K1ubHZoJlmEJidwoIfayeMEMHe5S9X94%2BBM%2FfwMV4HPWpRcAAA%3D%3D) with the following details

> Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAAA%2BVYbW%2FbNhD%2BL%2FrsNqLeLOXjugIt0G1di%2FVLMxi0dLKIUKRGUk7cIv99R0mOJVma3K4F0i0wIpuknrvn3njkx89OATQD5Vx%2FdmhV%2FUpLcK6d14Iq6qzsyAdQmkmBg%2BS52w798e4N%2FiyMqfT1zdXNFbOrn6efbq6AMwM3V2mZqWc5BzDPdMGqmyt%2FHftJgM84wA9%2BaYFe1NrI8q2SFSjDQFslGrAXsiypQLVe%2F%2Bxcty%2Bv2pn3iNcMtkgPDysno4baN%2B0U6kUFTaXIrPrHxSRqv3fsPoCgRip2f1ySgTA4%2Fv7Vs72xg69qzj9QXuNiQmI39D0P5f8is5qD7iZ83yNk7YbJynkH2%2FrgXHte6MYhSR5XOtcfUSsuLXZR76CgKqskE4agjNcGSjtemc2uxglGxabiVJeU01qkBahNzu4h25SQsbrEN35DJxhVw8PqEZVTNQ9LTVlzw1IqhBSbHSu3lG%2BaNy4B874lmP%2FvwFoTfHvzjXC9b4VrV%2FM5dbdASwREoI54s7oHtHK6EIvC0MXIfSl2TAAoJnY2zH%2FCuQp%2FmC6a74BWaEUuxU5R0ZjwDeyBY4iunN9riimJwUkQ5x7TjJUY65S%2FzHNIG1UrSBkqYZAZ6rHZ21R4mOXi%2FdBcDBOHObfcg5DaRiSSodmeihSdbF%2BYYrN2Ayw%2Fc8jj1BGG1eJWyDuhi9pk%2BJwFDkMv9udwx1k0g7vZe9NhOQALhmApxVrMUs3E7WOgm1opMLO6BvE6dBddWjKdbnCPMRY6pRVNrQ8f%2FUr6fp31VfgjKRuNlOWyzo6RpdkncHGIah1MqelHYZTEi3pqEFpiJaLaWOSTht5FGq6fnjnd50kYziocPz2FB9bV%2BHBJ492ebRF3kykpAPsRoyTfKKgoa4Ng3QZBOFkrSUDcJBrje82L0RC%2FwFZFARO5VCnYetgsClt0b4D%2BVjFseroCejSLf5FdzqWgkfaHrO5bJ%2FyCEn0O2BRtljpnZvWnaGNbCTzbAeaUbeXaJf9gUhKRdRL6ZDmzRsCPSmYnosEXEG3xEKaDZHs4pxh8B89iy4yufQqeTQvcpQ7nrMOW0H80nudYR9%2BB9dP39XqKNdxXZXtSMnTLONPdBtnx9pd5h8TFv7GwuEEJhsJSqZS0J9lKSZmneNiQiqa37dJWIFkUmJBkfSYumRLXlvqOUDBVmaYdSYIkSEYSiDslYVvvdoctPfQleFO1Lw68YKw0aauqN4RsvXEeiORS%2B9gwHEtqixsZbYtgKOOQ6VrlNIVje3S2e1%2FWB2Eg2duCbCaK%2B9FYYpwZqg4u%2Bf%2FUnUregcJDLJ6GBpxP4w3Z%2BNIoTaJ1EJP18mbaE0BVKWs1t4ti97fEtIdVsF2RFs11wcC1FHVpFNKjOtMMTrVdOeW61yOGrhuRZPmY2gFmTPX9NiQU%2B16yQKmDKWjN6YhLrlAS9g65yZRtGYaxekDQZny%2B7zn5zT81QQGWr9BPFvnlOmvOFlspzdfFpUVoQnvAirMcdF1VUo0isTfRz7vpVs6NEy9cX9bLcwwVcwf2%2F8xdwlmiZEwbxbY1dn8T6dKbnU%2BaTlMPyznxgwvzpI9sIzxX8FcNIv3KynCGCXnOUja%2BElE0oyOebVHVfXpzBTA4eSX0Xd9bTp2uYk%2F6ZVQR%2FGA9SIkauKHidqjscfTLGoeYuKR%2FzdJWpxPy8Q65K1ubHZoJlmEJidwoIfayeMEMHe5S9X94%2BBM%2FfwMV4HPWpRcAAA%3D%3D
line: 0
col: 0
error: {}

**Comment by alex-williams** [comment]
Marking as duplicate and referencing single issue for future import failures relating to missing modules #754 the content of this issue, will appear there, by virtue of that reference.
