### ISSUE TITLE
Error loading data from EDMC

### ISSUE THREAD

**Issue by sb-jones** [EDCD/coriolis#75]
Hi 

I get an error trying to load ship data from E:D Market Connector to either Coriolis or ED Shipyard sites. I see this using Chrome and IE, error messages states to raise a bug on here and copy the data below: 

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393
Path: 
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAGNwn1gC_81abW_bOBL-L_6cK_j-0m95adreZRdFnbtgsSgExqZtXWVRR0vZ-Ir89xtKtmPZsk25u9fCQBBL4sxD8plnZkR_G4yMn7rB22_wT2FGabkcvBXs5WIw8dYO3k5MtrDwpbJZeGZu0rz9LCXwrLcL659s-w56I-gL3EzHg7ccXwzmblxldhEeuvRzV_naYH0x_NfyF8ZgohDTFImLQW7mcG9wuSiSZmjy3puxpYOLgQM8pa9gTOFT52vP4KzKM2dyC2bQxeDJZBWM51pzRFXAdOUeHzOL8GkIQhIp2AZCMzC5t8_ltfG27IcAbfkmcb6x7vL9-Xy_NM4vIV1-_3m-XxY5X97l99fz_fI4v6hzvpfn-xWR69zJrYfz_cofNF8VOV_R5fe38_3qyBhGXX7fPY8yMz_bOUY_QkBu7MhkMdKlsKR447keltyki9Lk5YPz2XhxrnPyI53TH-T8XT5Nc3vtsjp1_f7lYnDrwf5wlk7KG5826e9EPhMMB2GFp9JJan2dDG1t1_qPN5BNEcIINc8ThIhuPfv7t_WM4GIyN4swjXJZ2Br4GusbKoIjohglTPCXi9aomTVZOesY9zf0hmCuEaUYayHV7sAC3MEkk8L9YX2nX0IZlhwRmCSM3xk-WYwTV5TpPF3YI9iZ0hgrQbngjG1DKEPCr62EWiQprE_-Xc2L-grMqdxYI1vWEKGYw4oKsKp1PKKWDcQoVYoKoiXVRL18WZcy92YaNgWLL6ECGqWFDVtYhzwVGkJ-kbnyYz62z7CxoaRaOf-Yl8kH8OPHgTXJMP2v5cl1BgD4YVo2Du7sUyjE-Pr7r43F2-FNcufy6WeTT-2gm8NhFlTgwORbWMF7k3-NIizlqIV8PXgbd1QhpijSr3DqbwHMXTqxw6oonC_jAoizFp6t8TUk1kAiByCh7tUhisq6Wv0FKtwm0hdRcJCSx-OZkHU8c0aPhHMzrOZhMqqgmk7mVVamRZYeCDcsFeJYSYZgTUSfMGdKYCI1JlorsjNwBaMVUq3RHAZyKUGmJKeqe_TrJLptIC0YaDRBClMq-wsNC-qgGSFcS30KQtc6tgKcCQLbz4mmQZ33NKeFZ22-PTnSmhznksIfpSlWXXohu_RC6LZe8LZeNJSM0Qp0QitWlu6rEAHre_9aLcaBxgkjqnkTHnacVvMPxo8Ll-YljurhQHo2k_lQlMmVNfM7Ay1j8j6dP0JqbqzGRCxHSKAtZPXXDmAkrrlUogXsUwUPnInsFRTlrMH0CbSk_Lt7PI0FqhXG5QbLemASOt6H1NtJqDQS6Ff7ly2fMrhcGr-8LArvzGg2rNLSRtWtFMsWCRtTbTsRgBjhr1mI8BpUiKVQkPn0sSqdj1N-fUpq16UTVogckdo6ksev3pNp5sJme1PabsGBvhQKAMUwaCbd1asD1kYz46eHBFAKIRin0N5jqvFx8W6JFceUcNBvCgqKaJR0tscrGVQ3fKA83Bcn3SFO8GmLk2qL0-5ubufhWJmiOzK1Z_NDOp3devufyuajZaRwUSkU0RvCBf7GFRmIk2iqYXyKakXweyyfSaUZU0xD3a37ZHIqpJRQloaym-kuXjauD2RzMMAF1ohDAmSK0EgD7WyngYyKKQ6NA8f72bPOw8cIDe0xl0SL0DbI3WrkcFXOMNMwEoIIYkHu81h18Vioo0X5p9cJn1GUsy4G15RLrpxblNHpdqtS_2zGJk4cCdWtuQxtvnB-sT2RniWxBE6yAAI63OIfaXkF7ZZddb6rS0PItdnOtYc0r3cgXIGlRriGIOJ6DUZbk7gO76Y_m1HTbIhmGj2TIOg21_Vi1nBIsyJxa6pO9epiXdtTckwFFrPUZuM-tT2Tsu6jQa7VblyurK3STLB0IMkoDs08hVpZCGiqu608evfV5om3U5sfaBcQhLaC2BZcI9ltJXd-HhLoYSuIQznMMMJQZQPBu83Y3Prpsm7uD5kCS1SqUP0zCQkUnarXjyxWW8egWEfQUkGXpmDje0yzbYaBFYhFxjh0Z3xfl3iHLqmd_Mp2iv
line: 0
col: 0
error: {"errno":-5,"code":"Z_BUF_ERROR"}

Thanks
CMDR Jones.

**Comment by cmdrmcdonald** [comment]
That URL is missing some data off the end.  This usually happens if you either use a Microsoft browser or copy/paste the URL, as either can cause truncation.

Please try this again with Chrome set as your default browser.  If that still doesn't work you'll need to raise a bug with EDMC.

**Comment by sb-jones** [comment]
Thanks CMDR McDonald, I did try Chrome but I cut and paste the URL from IE which was my default browser! Never considered the URL would be wrong as seemed to work for some ships.  Changed now as suggested and it works perfectly opening directly in Chrome. Will be a big time saver, thank you.
