### ISSUE TITLE
Transfer Problem

### ISSUE THREAD

**Issue by djsarnold** [EDCD/coriolis#750]
Trying to transfer ships from EDMC to Coriolis and getting this message " Jameson we have a problem" and I am using Google Chrome

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAN4XQmYC_-1ca2-jSBb9KxZaab6kEcWb7Kd03Jmkx5nOxFZa2tXKqkDZrg2mmAKS8bb6v-8tIHFhE1N-zKp3RBTlgasORdU59966XPim3bKoiEmmnf_zm3axXLKb5DKmqXbueWf1_9csTQnXzk1kGGfap2ROE0I4Teba-TftY1yQFP7Jb4baOTJ917Mcwz5bH_8VL4l2rn0lOGXJ9Msz4eEC8zmJtDUWfD5h0eCnyYIMPsY4ywn_aXAb_lbQJJGaiVNYhmG6Yhh_wJjokiQ5jj_NZiTMASRLSUhxPKVJSJKIYr6aclYkUaa1dZiOWIhjmsFQzrWbty6D-9cuI_JMYu3cOROTRGeU8GqaRvhRHNeGeInn5I7wMQlZEpU9suwm-5kxgIRBfuEURo7jBwyzARNo6WYQuC5MT33E8nTX9AP3-9kmaieYpdvuG46j-77ZAKFZzuljkTM-5PhlAw1toRm65b2hGbodBI4MBwvDlzgeMRwpQDnoDQrpntOEusc5-TK7olzlEi3XMwxrPV06CnzXsWQ8wVHB2DH9TzdiYOjGG5rn6cb2xE9WqcAp24xzQc2_lVdPw79LhxvcqWdH-_6vM-23Ag7nK3HlAK7d5GQJLRZpPl0WcU5DnCQggzldPgJPF0W50F8S7TznBTnT7jhlvOp-po1jJkh9DY2uMY9SBmpCmhhxr9Nep71Of2SdmqVOOzToWYHhu_tr8CNnbDDB_HfQ3bbsDKtLdnk1D9Nn-LhbcfWsDR6q1icXmyHEBl9r9ti6Y8AB_xihOLrjrxmkO5Z1qE5A-mud-KAT5Owm0CPBSzCOhL_SJxZr2MmfkWi1Yeh_UAK9VPhkNqMhVSLRVcxeBpcsyTmLFUh0x16I2jojyVAYerBtJ9SZiEzdMd_ATKSbvg1e7BgWgvFfOxFbd237UBY6urUem6sj5O9JwiWJaLHsZOFt2aynYU_DH4mG5lbYi3xjM-61TbW41_aDd7l6TeeLS5ziUIznzwt8a-ZGryFkB22FgjKImyIFzt7iLOtcRlOiKwS7MhvUOb8Zi7queQzvXd234MuWvLZvGpZ3QMxtQE9pZL5tuweGtr5uNQcV6KYTwPdpQltgcTO2FVC3-A-6LDXSETnBPk_CEvQHsH1j2wykH3fqcSxa7diFtsjRstz_FzmGjHOW0WcyzRaknI0OQV6-dhiM6w4_riybxv4Eqiz5b_31BSUI_D8SlNJ2EbTiBS0pm_GCkjj6yJjQwfSeZBAdADWbehnSiA4eYJ3A1beJxDC6RJKVp3msTxMuiuRp1a2UcQEfD2oNM66SrrlJcjLnleJ3L5jtN-yfblqb28Z9IjhTyoY0UiFDMiNJSF5HW833rVj5NIb_Vba45QSvSW-6TZb-AksBPKrWDsO5FFycRHqIyrYjutPBwRLHpbU7CnCnjprkErGOMQ3BsmdOp5ImNFntt1_phdQLqRfSbiH1HqkXUi-kEwjJ6oXUC6kX0vFCsnsh9ULqhXS8kJxeSL2QeiEdLyS3F1IvpF5IxwvJ64XUC6kX0vFC8ksh1cAzEhGOc8oScYPzmeQ5gT_Cp5Tm3benFjS9rNtKkEvxsADmIeZz9ohXEWP8HSjzDepSNL7GebhQVLnrtKj8gi9Zwaf10jbFPSYxScjgM8Ftd39Rl7JxBa0q6SEh6eAuhomFK1Coh2yq55rgOF_sox5H5pLp-aWYLHScfkxHJqil2z6AouNE9MEK9LKS092NfIieUA0t13R6yBTI7wqrjf_1WnOCw9pJ7NZBRTtV9-S2ELc0wUCXJJ9WYJtVcNcwyMEEJ7TFKwVd3E0Felqih4zFFbZaPe84hVk4WUWRL7M02LDv6i4NuTIxLddqApWTKRWEdNSlu7J_NHSrUVEBSsw_1aWD4UqhrMKWqios5O6ofIPVl1dG2HNf1Z6v-aJsLlvqZ6pu0yHlm4Uzd5zN4EIZH9zB0NsMptlFOlKBs2fCY4YjFdJBDDIfDDlI7rQhELJt2ZCZpm4L83hg6UygIykKMnQTNYtnqpn6kuYUBNQii7aSErdZnhJs1Ke8Qd4RPmMiOlWxho06FWQ7uiOMI9oGFiQX1TkK8d_68Q2IJP0OdtcUEMz2djPbWNd0YppUo8pUqd0W71-Nh0CtZH6Pk_lGlH9FYiosw-AK84yUznWD3Kgzzp9l0XRB8LNCJCAYMLjFCZ7XfvwEdtSWV9YxD7ajtlyRjASXXfCWwaElZZ4j11O6ZmODACuylyaMZpmVadq7yqwE3RYrWIhImI_S6lTV5CX7XFX2XXGgD4S1s7w0Q2p17chuY-AtzcLpiM4X-VcifjZJOIJTDz5Dy4y1WVdR1V4zxT6uWLDBlIOJgmSH6wZdKxFT8B5FmjJe-TVHdf5H0HFcdVQNp6zgnXBKqn8vS0SvOPm9qL24XCO6IIPhC4njVkvgK8VWkXSqGc5y5S0_S6KC5irerqp1zZTDGk8uE4V4yXXtjQi7RrwnlVC6EfWG2_Mdz912JeoDbOYlLN3zwD15LYjKA7R1OfA3Lb_hlscr2DYvTzm-GvGY8XUHhzK1FEJEoxkiShpQsmW2gayWZ3TGJIFY8D2Hqm7LjvN6bjOK85vWrBrjRKxEPg5xcpHMY4WnUhv7ZtSEfL3W3RCgg0agZRi-0WUgs3KwmbyiZueK3uMIcznRIpBmBYlhd_wk21mrc_9wBb1gN_mkaGR9-92U6s8kEftn9k7WZUTo4HJBijILsmlcTbV0KmzE59VZ6oxtx-NbYIDhnG-SPNkuwmpES76li0xq0DAy92KkLaF0mzGwZb_cMKUfOXsCGGUs1BiYqbvOcXmf7RSN6eoBEkeOTP5sZ3nhXEawmZE-JPnTyIDZ4oGBDgmW3Jq_0VfapVivTrwj_Qm_DDQVzx94ipGiK56mb40UKzVtpn3UTSs6AcEdTzaGDtLFkjd93j7bgcCTbhYgt8PbCUOWhYylKvtFs7kIpvoiiJARtYSM10Uc3xOawPY6JMK2TK_F_m5YbKZGjswjL-A8vHGePymlrORSkZz8EnmRHbd0qqT0RRRRkS1VMCKN1zNYnu6LJO-RpskUb7OQM7ywM7Fdzzk2La2Ge4hd2oG8eze7RRTJw5tqxsnqddHrotfFli7sUhdur4teF70uJF04vS56XfS62NKFW-rC6XXR66LXhaQLT9KFBF0WgJFtcHsvcL8Et7cSnlkEv0RiPHxN29iqZRMlbiDh9mLe565z41aiezopm24zd4f0QBRtWcdJGVXCCKQSCN01DLuZ0Npfymq4B9WvvY98gJStfdSGjFIVlupdorY8Zn2XCK4cJ9G-BWyne8ua0XjLWvOloOPx9E4Umd7jiBaZUlHyOlPdeVcnIjmmMYmygs9wSDLxyhfCp6DBldoiVMlkJJu8iITlC9Hy6SMnMAUh4ymrCxbnLI46gYcCoAWSCILWQGRJs-xRXKUSmnlSNEtGq0qGwiLLGaBUeC8LmndjVaS6ZPEepZi9be8Dtb96oHZLARfzlYFUw7T9oRsGIcUA_m_2OG1_tEDoc07YtCpx7ihzFVCf2ePmyEXFLNjaNOUMh4usoKJoO3oWy6AAWnXmq4u6_1j0l0-RgCWAU-TiTW80pZGiBRKPQ9wMjZMhoa7nNATmE83R9LFYgsWwlXB_ofnHsrkyepYy8GrcVIUfV-2V8YXTtFTBJ9BYGfkFLGSmPC1fRev21Uu5eBQATLCB9lhC4VGMUwM2WPHMaEhSHD5Nn0l9j3c3ygOYKBI_iG4yTvWq0abbVfLgVRHZq9cFOyaG2b4s2lnN6-r2rfgzEu_jPdcuRqPx5L7-vHbDk6vxYPTp4eZicn3xK3xEnqu24gW0rBA353PwkGB6l-J0pmHaHwznA7ImyDq3fPj-h_b9v_Y5Ad64ZAAA
line: 0
col: 0
error: {}

**Comment by felixlinker** [comment]
Import works for me. Please try Ctrl+Shift+R reload of the website.
