### ISSUE TITLE
Bugged Class 2A SCO FSD, 

### ISSUE THREAD

**Issue by aaaaettvgrr** [EDCD/coriolis#757]
On the hauler and sidewinder, when the grade A SCO is selected, the entire website freezes, class E-B  SCOs work normally, 

Only effects ships with a max FSD class of 2c,

**Comment by chennin** [comment]
This has been discussed on Discord and a fix is on the way.  Can you confirm it looks good on https://beta.coriolis.io/ ?

(no clue on deploy time)

**Comment by alex-williams** [comment]
This was deployed in beta coriolis a few days ago. It will move to Prod when people confirm the issue has gone away. Please confirm here.

**Comment by chennin** [comment]
I can confirm it's no longer freezing for me (Firefox 125, Linux)

**Comment by aaaaettvgrr** [comment]
I checked, and it does work on the beta website, thank you,

**Comment by alex-williams** [comment]
Fix deployed to live site.
