### ISSUE TITLE
Nanite Torpedos and Enhanced AX Missile Racks

### ISSUE THREAD

**Issue by chennin** [EDCD/coriolis#758]
This build - https://s.orbis.zone/n_7d - only imports the beam laser for weapons. Please add the [nanite torpedoes](https://www.elitedangerous.com/en-US/news/galnet/guardian-nanite-torpedoes-enter-production) and [enhanced AX missile racks](https://elite-dangerous.fandom.com/wiki/Enhanced_AX_Missile_Rack). Here is the Loadout info, please let me know if more information is needed.

```json
    {
      "Slot": "MediumHardpoint2",
      "Item": "hpt_atventdisruptorpylon_fixed_medium",
      "On": true,
      "Priority": 0,
      "AmmoInClip": 1,
      "AmmoInHopper": 64,
      "Health": 1.000000,
      "Value": 698778
    },
```
3B:
```json
    {
      "Slot": "LargeHardpoint3",
      "Item": "hpt_atdumbfiremissile_fixed_large_v2",
      "On": true,
      "Priority": 0,
      "AmmoInClip": 12,
      "AmmoInHopper": 128,
      "Health": 1.000000,
      "Value": 1412054
    },
```

**Comment by alex-williams** [comment]
The following PR's will address this issue, by adding the following weapons:
AX Missile Racks (Enhanced)
AX Multi-Cannons (Enhanced)
Nanite Torpedos
Advanced Multi-Cannons

https://github.com/EDCD/coriolis/pull/760
https://github.com/EDCD/coriolis-data/pull/107

**Comment by alex-williams** [comment]
@chennin this has now been pushed to https://beta.coriolis.io and all weapons should be available. After some time in beta, it should make its way to the live site.

**Comment by alex-williams** [comment]
Fix deployed to live site
