### ISSUE TITLE
TTD with 2Pips to WEAP

### ISSUE THREAD

**Issue by s7urmi** [EDCD/coriolis#77]
As far as i'm aware the TTD(Time to drain WEP capacitor) currently shows the value for 4 Pips to WEP. Many PvP players tend to build they'r ships that way that they can fire with 2 Pips to WEP for having 4 Pips in ENG or SYS. Would be nice to see how long you could shoot with that setup with only 2 Pips to WEP.

Maybe even build an little Control that you can enable and divert the Pips like you wanted to see how the stats(shield strength, boost frequency, TTD) would be affected and if that build would fit your playstyle.

**Comment by cmdrmcdonald** [comment]
Thanks for the suggestion.  Coriolis has become a little busy with all of the data it's showing on the outfitting page.  I'd like to make this and various other features part of a new page that allows users to set this type of information.

**Comment by cmdrmcdonald** [comment]
Fixed in 2.3.0
