### ISSUE TITLE
4c Fsd (sco) incorrect price

### ISSUE THREAD

**Issue by PleaseNoLag** [EDCD/coriolis#775]
Price in Coriolis is $182.475 real price is $547.428 (this is both with a 15% discount)

**Comment by chennin** [comment]
As a corroborating datapoint, the price was adjusted after release in  18.04

https://www.elitedangerous.com/update-notes/4-0-18-04

**Comment by alex-williams** [comment]
4C SCO price is currently correct and matches the in-game price, with no discount, it must have been corrected by another issue being resolved, probably the one relating to general pricing.
![image](https://github.com/user-attachments/assets/58c34d37-a7c7-492b-913f-3b2b5bad085a)
![image](https://github.com/user-attachments/assets/6f3ecce0-80b5-4f46-9132-e55cb4cbdce0)
