### ISSUE TITLE
Multi cannons do not show correctly the Overcharged engineered modification when imported from other sources (Inara, EDMC)

### ISSUE THREAD

**Issue by phlnx** [EDCD/coriolis#776]
Example link: https://s.orbis.zone/qv43

Expected modification: G5 Overcharged
See attachments.

![2024-08-05 00_30_28-Viper Mk IV – Mozilla Firefox](https://github.com/user-attachments/assets/e69efc37-3899-481c-9ad0-3ac3064f8dfd)
![2024-08-05 00_32_06-• Discord _ #coriolis _ EDCD_ Community Developers – Mozilla Firefox](https://github.com/user-attachments/assets/20658db8-fc75-4612-bf6f-a9385b0ae471)

**Comment by alex-williams** [comment]
This is now fixed in coriolis, although the live site will take time to update because of the caching, the beta site is confirmed fixed.
