### ISSUE TITLE
Incorrect stats for 2A Guardian Power Distributor

### ISSUE THREAD

**Issue by chennin** [EDCD/coriolis#782]
For the 2A Guardian Power Distributor Coriolis has W 10/2.5, S 10/0.8, E 9/0.8, integrity 56,  but the actual stats are W 13/3.1, S 11/1, E 11/1, integrity 45.

mass and power draw are correct.

https://coriolis.io/outfit/federal_assault_ship?code=A0potoFjlo0Usjf4--1717----4e0302--02---4F.Iw18eQ%3D%3D.Aw18eQ%3D%3D..EweloBhBGA2EDMoCmBDA5gG2SGF8hRFA

![2024-08-25_13-20](https://github.com/user-attachments/assets/49c15ce7-7c7c-4dd7-b66e-796f63094914)

**Comment by alex-williams** [comment]
Should now be fixed in beta.coriolis.io. If you confirm, I'll push it to live straight away. 
![image](https://github.com/user-attachments/assets/0085dc49-09e0-438d-8dc4-8fa5870be0b8)

**Comment by chennin** [comment]
Looks good! Thank you!

**Comment by alex-williams** [comment]
pushed to live, closing the issue
