### ISSUE TITLE
"Power and Costs" tab permits editing power priorities of modules that cannot be prioritized in game

### ISSUE THREAD

**Issue by StreamyDenny** [EDCD/coriolis#796]
Certain modules in game do not allow for a personalized power priority, such as Guardian Shield Reinforcement Packages or Discovery Scanners, yet the Coriolis website believes they can be prioritized in the power management window under the "Power and Costs" tab.
![image](https://github.com/user-attachments/assets/e56f0d64-5aae-428b-8e18-52ab882a22fa)
![image](https://github.com/user-attachments/assets/8d31435d-6b56-47a0-83eb-903e7bf40882)

**Comment by alex-williams** [comment]
This is now resolved and deployed. The live site may take time to update due to caching, but beta.coriolis.io has the fix active already.
