### ISSUE TITLE
Advanced Missile Rack appears twice in the hardpoint selection list

### ISSUE THREAD

**Issue by phlnx** [EDCD/coriolis#804]
![2024-12-13 22_59_27-• Discord _ #coriolis _ EDCD_ Community Developers – Mozilla Firefox](https://github.com/user-attachments/assets/4be7a56f-4e4f-4e50-9871-054fd973b2af)
![2024-12-13 22_59_41-• Discord _ #coriolis _ EDCD_ Community Developers – Mozilla Firefox](https://github.com/user-attachments/assets/f6976eff-9086-4d42-806f-19837b50ead2)

**Comment by alex-williams** [comment]
Fixed, was a duplicate entry, it existed in both the missile rack subcategory and in the advanced missile rack subcategory
