### ISSUE TITLE
https://coriolis.edcd.io/ initial page is black on firefox

### ISSUE THREAD

**Issue by Clockwork-Sphinx** [EDCD/coriolis#82]
Are there any known issues with "https://coriolis.edcd.io/" specifically and firefox? That page is a black screen if directly navigated to but reaching it via a ship build and then the coriolis station icon functions as normal. Opera and internet explorer function normally. Firefox add-ons were disabled for that page and issue still persisted.

edit: debug error message "18:35:38.855 Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. 1 jquery-min.js:3:6335"

**Comment by cmdrmcdonald** [comment]
I haven't been able to reproduce this issue, but others have seen it in the past.  A comment suggested that the following would fix it:

    Firefox Options -> Advanced -> Network:
    Offline Data Menu at bottom: remove https://coriolis.edcd.io/ from the list.
    The checkbox above should be ticked.

Please let me know if this fixes your problem.
