### ISSUE TITLE
Ipad mini issue

### ISSUE THREAD

**Issue by Deadmaxx** [EDCD/coriolis#85]
I've noticed now that when I have coriolis open on my Ipad mini and I scroll up and down on the ship information the top static task bar gets lost or partly erased.  It will come back when you refresh the screen.

**Comment by nemesyssoft** [comment]
I see the same thing happening on my iPhone 7 Plus.

**Comment by cmdrmcdonald** [comment]
The beta site http://beta.coriolis.edcd.io/ should no longer pin the top bar.  Please give it a try and let us know if it is working now.

**Comment by cmdrmcdonald** [comment]
Fixed in 2.3.0
