### ISSUE TITLE
Shield booster kinetic resist recipe extreme preset inverts benefit

### ISSUE THREAD

**Issue by sporebat** [EDCD/coriolis#86]
[this build](https://coriolis.edcd.io/outfit/vulture?code=A2patfFeledksjf30v0v04040003B2-022o26m0.Iw1%2FkA%3D%3D.Aw1%2FkA%3D%3D.H4sIAAAAAAAAA2P8Z8%2FAwPCXGUhw7OBmYOD3%2BPL%2Fv1gCJwPDf6Z%2FYiApFiDBv%2BDb%2F%2F8iAb%2F%2F%2Fxc9ApSSuMPKwKB8Rw6oiPWfJUwRJ0ieC2SIIoilBGKpglhqINZ%2Frn8eMJXcPP%2F%2B%2FxcEESoX2IFS3P%2FcUKUMfgClQKz%2FfP%2F8YFKMQMH%2F%2FGt4GRgg8gv4gVr%2FAwB3zXv8wQAAAA%3D%3D&bn=Engineered) shows -20% kinetic, not +20% kinetic, on best and extreme. Worst is +17%.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this, there was an incorrect sign for the kinetic resistance that has been fixed.

You should see the change in beta now at http://beta.coriolis.edcd.io/ and it will go in to live with the next release.

**Comment by sporebat** [comment]
Title typo: how embarrassment. Thanks for the quick fix of the bug itself!
