### ISSUE TITLE
Display hardpoint location on hull instead of "empty"

### ISSUE THREAD

**Issue by sf302** [EDCD/coriolis#87]
Would be nice to know which weapon/utility is going where without having to look for ship images to figure it out.

Mockup using best-recollection Anaconda hardpoint locations:

![Mockup](https://i.imgur.com/6FDBqMZ.png)

Probably needs work done in the Slot classes and the ship data, but I'll try to figure out how to work it into the code if nobody else is willing to.

**Comment by cmdrmcdonald** [comment]
The relevant data is in the coriolis-data repository.  For example, under ships/anaconda.json we currently have:

    "slots": {
      "standard": [8, 7, 6, 5, 8, 8, 5],
      "hardpoints": [4, 3, 3, 3, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
      "internal": [
        7, 6, 6, 6, 5, 5, 5,
        { "class": 5, "name": "Military", "eligible": { "hr": 1, "scb": 1, "mrp": 1 } },
        4, 4, 4, 2
      ]
    },

You would need to change the hardpoint information to contain in addition the FD name and your location for each item, so for example:

    "slots": {
      "standard": [8, 7, 6, 5, 8, 8, 5],
      "hardpoints": [
        { "class": 4, "location": "ventral", "fdname": "HugeHardpoint1" },
        { "class": 3, "location": "ventral fore", "fdname": LargeHardpoint1" },
        { "class": 3, "location": "dorsal port", "fdname": LargeHardpoint2" },
        { "class": 3, "location": "dorsal starboard", "fdname": LargeHardpoint3" },
        ...
      ],
      "internal": [
        7, 6, 6, 6, 5, 5, 5,
        { "class": 5, "name": "Military", "eligible": { "hr": 1, "scb": 1, "mrp": 1 } },
        4, 4, 4, 2
      ]
    },

You'd need to do a fair bit of work to map FD's names to the locations, putting appropriate weapons in each slot then dumping the companion API dump (via EDDI or EDMC) to work out which hardpoint name maps to which physical slot.  Ditto for utility mounts.

This would have to be done for each ship, of course.  It's a fair chunk of work.  Altering coriolis itself to use the data isn't too hard once the information is available.

**Comment by strideynet** [comment]
Too much effort.
