### ISSUE TITLE
Module dropdowns unwieldy

### ISSUE THREAD

**Issue by Xjph** [EDCD/coriolis#89]
The module dropdowns, especially for large optional internals, are somewhat awkward to nagivate.  The addition of category headers has improved this, but it's still a bit unwieldy.

Could the categories be made collapsible to remove much of the clutter when navigating?  If they defaulted to collapsed, with perhaps the category for the currently installed part expanded I believe it would be much less cluttered and faster to find desired parts.

**Comment by cmdrmcdonald** [comment]
Thank you for your suggestion.  Adding more clicks to the module dropdown isn't something that we are looking to do at this time.
