### ISSUE TITLE
Inconsistency at HPS and EPS of Fragment Cannon.

### ISSUE THREAD

**Issue by fabioascoelho** [EDCD/coriolis#92]
Hi,
I've noticed that the Heat per second, and the sustained HPS, and also the Energy per second, and the sustained, have a much higher value showed on Coriolis than the values showed in game and at Edshipyard.
I tested two G5 double shot 2A Fragment Cannon with incendiary rounds that supposed to generate 45.2 sustained heat per second and consume 8 MW of sustained energy per second but that doesn't seen to be the case in game.
My Federal Assault Ship with only 7.2 MW wep charge distributor could maintain the full consumption of both weapons with only 2 amd a half pips, also there was almost no heat being generated with a 0.4 efficient power plant.

With a weapon stats like that showed on Corolla I thought it would be impossible to utilize.

So, is this a bug or am I missing something?

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  I took a look at the data for the fragment cannon and some of it was incorrect.  I've updated this on the beta site http://beta.coriolis.edcd.io/ with the latest data from the live game and the numbers look more realistic.  Feel free to take a look at this site with the new numbers.

These changes will be released to live with 2.3.

**Comment by cmdrmcdonald** [comment]
Fixed in 2.3.0
