### ISSUE TITLE
Command Center: Effective Shield Breakdown

### ISSUE THREAD

**Issue by BeckyYork** [EDCD/coriolis#93]
When the beta changes go live please add a mouse over to Defence Effective Shield MJ.
This should have a breakdown of where the MJ comes from:
- RAW MJ from Shield Generator
- RAW MJ from Booster Shield Boost
- RAW MJ from Shield Cell Banks
- MJ Gained/Lost from Shield Generator Resists
- Effective MJ gained from Boosters Resists
- Effective MJ added by PIPS

**Comment by cmdrmcdonald** [comment]
Fixed in 2.3.0
