### ISSUE TITLE
Ammo count for size 2 mine launchers is incorrect

### ISSUE THREAD

**Issue by faybs** [EDCD/coriolis#94]
Size 2 mine launchers show ammo as 3/36, but it should be 3/72. Since this is probably a cut'n'paste error, it may be worthwhile to double check all stats for the mine launcher.

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  I've checked through the mine launcher data and updated it where appropriate.  The updated information is visible at http://beta.coriolis.edcd.io/ and will make it to live in the next release.

**Comment by faybs** [comment]
Fix verified in the beta. Thanks for the quick fix! As usual, I'll close it when it goes to main.

**Comment by cmdrmcdonald** [comment]
Fixed in 2.3.0
