### ISSUE TITLE
Different Engineer mods on the same module stack instead of clearing the old mod

### ISSUE THREAD

**Issue by rokxx** [EDCD/coriolis#95]
Happens with any type of module that can be engineered.

For example, take a 0A Shield Boosters

If you apply Resistance Augmented Grade 5 and roll the "best" preset to one of the Shield Boosters, it ends with 20% shield boost and 12.5% Kinetic, Explosive and Thermal resistance, and if you then apply Heavy Duty Grade 5 to the same module, both modifications stack and you end with a 56% shield boost and 12.5% resistance of all damage types.

![Modules example](https://cloud.githubusercontent.com/assets/12429120/24462713/0e9af732-147b-11e7-82d0-1d4e6446c2db.png)

**Comment by cmdrmcdonald** [comment]
Thank you for reporting this.  This has already been addressed on the beta site http://beta.coriolis.edcd.io/ and will be in the next release.
