### ISSUE TITLE
Allow Cargo hatch to be imported

### ISSUE THREAD

**Issue by robbyxp1** [EDCD/coriolis#97]
In companionapiutils.js, you hard code the cargo hatch to off/p4.

Now with the companion api you don't get the cargo hatch, so thats okay.. but..

The journal loadout message does have the cargo hatch info.  And my addition to EDDiscovery allows import into coriolis of the ship details without using the companion API.  It synthesises the correct JSON for import from the data we have accumulated thru the journal entries.

So would it please be possible to allow import of the cargo hatch.  If its not in the JSON supplied, then the current behaviour is used, else its imported with the enable state and the priority.

Many thanks

Cmdr Robby, ED Discovery.

**Comment by cmdrmcdonald** [comment]
This is present in the beta version of Coriolis at http://beta.coriolis.edcd.io  The module should be named 'CargoHatch' in the JSON.  Please try importing against this site and let me know how it goes.

**Comment by cmdrmcdonald** [comment]
Fixed in 2.3.0
