### ISSUE TITLE
Shipyard

### ISSUE THREAD

**Issue by Tony2438** [EDCD/coriolis#99]
Shipyard only displaying on the first ship 
![capture png 4](https://cloud.githubusercontent.com/assets/27761597/25167449/77237e84-24d7-11e7-8e1d-d0d90678e7d6.PNG)

**Comment by cmdrmcdonald** [comment]
Frontier have altered their API to not provide details of ships other than the current active ship.  Until/unless this is restored you will only be able to export that ship.
